apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template: 
    metadata:
      name: ${project.artifactId}
      labels:
        name: ${project.artifactId}
      annotations:
        date: ${timestamp}
    spec:
      containers:
        - name: ${project.artifactId}
          image: ${docker.registry.name}/${project.artifactId}
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
         - name: tz-config
           hostPath:
             path: /usr/share/zoneinfo/America/Bogota
  replicas: 2

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.artifactId}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.artifactId}
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
