DECLARE @DBNAME VARCHAR(255),
		@sql NVARCHAR(4000),
		@fechaInicio DATE = '20190601',
		@fechaFin DATE = '20190901'
--DROP TABLE #PersonasModificacionDatosBasicos
--DROP TABLE #FechasNovedadesSolicituNovedad
CREATE TABLE #PersonasModificacionDatosBasicos(perId BIGINT, actualNumeroId VARCHAR(16) , actualTipoId VARCHAR(20), anteriorNumeroId VARCHAR(16), anteriorTipoId VARCHAR(20), sl VARCHAR(500) )
CREATE TABLE #FechasNovedadesSolicituNovedad(snoId BIGINT, fechaRegistroNovedadCerrada DATE, sl VARCHAR(500))

SET @sql = '
SELECT sno.snoId, CAST(CONVERT(VARCHAR(10), dateadd(second, revTimeStamp / 1000, ''19700101'') AT TIME ZONE ''UTC'' AT TIME ZONE ''SA Pacific Standard Time'' ) AS DATE) AS fechaRegistroNovedadCerrada
FROM SolicitudNovedad_aud sno 
INNER JOIN Revision rev ON (sno.REV = rev.revId)
INNER JOIN(
	SELECT sno1.snoId, sno1.REV  
	FROM  SolicitudNovedad_aud sno1 
	WHERE sno1.snoEstadoSolicitud = ''APROBADA''
	GROUP BY sno1.snoId,sno1.REV 
) aux ON aux.snoId = sno.snoId AND aux.REV < sno.REV
WHERE sno.snoEstadoSolicitud = ''CERRADA''
GROUP BY sno.snoId, revTimeStamp'

INSERT INTO #FechasNovedadesSolicituNovedad(snoId, fechaRegistroNovedadCerrada, sl)
EXEC sp_execute_remote CoreAudReferenceData, @sql	

SET @sql = '
 SELECT DISTINCT perA.perid, perA.perNumeroIdentificacion actualNumeroId, perA.perTipoIdentificacion actualTipoId,
 	    aux.perNumeroIdentificacion anteriorNumeroId, aux.perTipoIdentificacion anterioTipoId 
 FROM Persona_aud perA
 INNER JOIN ( 
	 SELECT per.perId,per.REV,per.perNumeroIdentificacion, per.perTipoIdentificacion
	 FROM Persona_aud per 
	 inner JOIN Persona_aud perAux ON perAux.perId = per.perId AND perAux.perNumeroIdentificacion <> per.perNumeroIdentificacion
	 GROUP BY per.perNumeroIdentificacion, per.perTipoIdentificacion,per.REV,per.perId 
 ) aux ON aux.perId = perA.perId AND aux.perNumeroIdentificacion <> perA.pernumeroidentificacion AND aux.Rev < perA.REV
 UNION
 SELECT DISTINCT perB.perid, perB.perNumeroIdentificacion actualNumeroId, perB.perTipoIdentificacion actualTipoId,
 	    tablaAux.perNumeroIdentificacion anteriorNumeroId, tablaAux.perTipoIdentificacion anterioTipoId  
 FROM Persona_aud perB
 INNER JOIN(
 	 SELECT  per.perId, per.REV, per.perNumeroIdentificacion, per.perTipoIdentificacion
	 FROM Persona_aud per 
	 INNER JOIN dbo.Persona_aud perAux ON perAux.perId = per.perId AND perAux.perTipoIdentificacion <> per.perTipoIdentificacion
	 GROUP BY per.perNumeroIdentificacion, per.perTipoIdentificacion,per.REV,per.perId 
 ) tablaAux ON tablaAux.perId = perB.perId AND tablaAux.perTipoIdentificacion <> perB.perTipoIdentificacion  AND tablaAux.Rev < perB.REV '
 

INSERT INTO #PersonasModificacionDatosBasicos (perId , actualNumeroId, actualTipoId, anteriorNumeroId, anteriorTipoId, sl)
EXEC sp_execute_remote CoreAudReferenceData, @sql	

SELECT
			2 AS tipoRegistro,
			(SELECT cnsValor FROM dbo.Constante WHERE cnsNombre = 'CAJA_COMPENSACION_CODIGO') AS codigoCCF,
			CASE perAfiCore.perTipoIdentificacion 
			    WHEN 'CEDULA_CIUDADANIA' THEN 'CC'
			    WHEN 'TARJETA_IDENTIDAD' THEN 'TI'
			    WHEN 'CEDULA_EXTRANJERIA' THEN 'CE'
			    WHEN 'PASAPORTE' THEN 'PA'
			    WHEN 'CARNE_DIPLOMATICO' THEN 'CD' 
			END AS tipoIdAfiliado,
			perAfiCore.perNumeroIdentificacion AS numeroIdAfiliado,
			CASE perDetAfiCore.pedGenero
				WHEN 'MASCULINO' THEN 'M'
				ELSE 'F'
			END AS codigoGeneroAfiliado,
			perDetAfiCore.pedFechaNacimiento AS fechaNacimientoAfiliado,
			SUBSTRING(perAfiCore.perPrimerApellido,0,60) AS primerApellidoAfiliado,
			SUBSTRING(perAfiCore.perSegundoApellido,0,60) AS segundoApellidoAfiliado,
			SUBSTRING(perAfiCore.perPrimerNombre,0,60) AS primerNombreAfiliado,
			SUBSTRING(perAfiCore.perSegundoNombre,0,60) AS segundoNombreAfiliado,
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR')
				     THEN 'C01'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB')
					THEN 'C02'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')
					THEN 'C03'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
					-- ('RETIRO_TRABAJADOR_DEPENDIENTE','RETIRO_TRABAJADOR_INDEPENDIENTE')
					THEN 'C04'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('REPORTE_INVALIDEZ_PERSONAS','REPORTE_INVALIDEZ_PERSONAS_DEPWEB','REPORTE_INVALIDEZ_PERSONAS_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_WEB')
			     	 THEN 'C07'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')
						--('RETIRO_TRABAJADOR_DEPENDIENTE','RETIRO_TRABAJADOR_INDEPENDIENTE','RETIRO_PENSIONADO_25ANIOS','RETIRO_PENSIONADO_MAYOR_1_5SM_0_6','RETIRO_PENSIONADO_MAYOR_1_5SM_2','RETIRO_PENSIONADO_MENOR_1_5SM_0','RETIRO_PENSIONADO_MENOR_1_5SM_0_6','RETIRO_PENSIONADO_MENOR_1_5SM_2','RETIRO_PENSIONADO_PENSION_FAMILIAR','RETIRO_CONYUGE','RETIRO_HJO_BIOLOGICO','RETIRO_HIJASTRO','RETIRO_HERMANO_HUERFANO','RETIRO_HIJO_ADOPTIVO','RETIRO_BENEFICIARIO_CUSTODIA','RETIRO_PADRE','RETIRO_MADRE','RETIRAR_BENEFICIARIO_EDAD_MAYOR_IGUAL_18_NO_TIENE_CEDULA','RETIRAR_AUTOMATICAMENTE_BENEFICIARIO_X_EDAD','RETIRO_AUTOMATICO_POR_MORA')
 					--AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					 THEN 'C08'
			   --WHEN ( SELECT CASE WHEN EXISTS (SELECT abono.casId FROM dbo.CuentaAdministradorSubsidio abono WHERE abono.casId = cuenta.casId AND abono.casEstadoLiquidacionSubsidio = 'COBRADO' AND abono.casIdCuentaAdmonSubsidioRelacionado IN ( SELECT CuentaAdministradorSubsidio.casId FROM CuentaAdministradorSubsidio WHERE CuentaAdministradorSubsidio.casTipoTransaccionSubsidio = 'RETIRO' AND CuentaAdministradorSubsidio.casFechaHoraCreacionRegistro BETWEEN @fechaInicio AND @fechaFin) UNION SELECT detalleAux.dsaCuentaAdministradorSubsidio FROM dbo.DetalleSubsidioAsignado detalleAux WHERE detalle.dsaId = detalleAux.dsaId AND detalleAux.dsaOrigenRegistroSubsidio IN('LIQUIDACION_SUBSIDIO_MONETARIO', 'DERECHO_ASIGNADO_RETENIDO') AND detalleAux.dsaFechaHoraCreacion BETWEEN @fechaInicio AND @fechaFin ) THEN 1 ELSE 0 END ) = 1

			   	--	THEN 'C09' Las novedades de subsidio de pasan al siguiente union all
			END AS codigoNovedad,
			--==== INICIA NOVEDAD C02 =====
			CASE  
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB') AND -- CODIGO NOVEDAD C02
			    	 perAfiCore.perTipoIdentificacion = 'CEDULA_CIUDADANIA' THEN 'CC'
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB') AND -- CODIGO NOVEDAD C02
			    	 perAfiCore.perTipoIdentificacion = 'TARJETA_IDENTIDAD' THEN 'TI'
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB') AND -- CODIGO NOVEDAD C02
			    	 perAfiCore.perTipoIdentificacion = 'CEDULA_EXTRANJERIA' THEN 'CE'
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB') AND -- CODIGO NOVEDAD C02
			    	 perAfiCore.perTipoIdentificacion = 'PASAPORTE' THEN 'PA'
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB') AND -- CODIGO NOVEDAD C02
			    	 perAfiCore.perTipoIdentificacion = 'CARNE_DIPLOMATICO' THEN 'CD' 
			    ELSE NULL
			END AS tipoIdAfiliado2, -- VARIABLE 1
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB')  -- CODIGO NOVEDAD C02
				THEN perAfiCore.perNumeroIdentificacion
				ELSE NULL
			END AS numeroIdAfiliado2, -- VARIABLE 2
			--========= FIN NOVEDAD C02 ========
			--========= INICIA NOVEDAD C01 =====
			CASE 
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01 
					 AND perDetAfiCore.pedGenero = 'FEMENINO' THEN 'F'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01
					 AND perDetAfiCore.pedGenero = 'MASCULINO' THEN 'M'
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01
					 AND perDetAfiCore.pedGenero ='INDEFINIDO' THEN 'I'
				ELSE NULL
			END AS codigoGeneroAfiliado2, -- VARIABLE 3
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR')--codigo noveddad c01
				THEN perDetAfiCore.pedFechaNacimiento
				ELSE NULL
			END AS fechaNacimientoAfiliado2, -- VARIABLE 4
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR')--codigo noveddad c01
				THEN SUBSTRING(perAfiCore.perPrimerApellido,0,60)
				ELSE NULL
			END AS primerApellidoAfiliado2, -- VARIABLE 5
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR')--codigo noveddad c01
				THEN perAfiCore.perSegundoApellido
				ELSE NULL
			END AS segundoApellidoAfiliado2, -- VARIABLE 6
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01
				THEN perAfiCore.perPrimerNombre
				ELSE NULL
			END AS primerNombreAfiliado2, -- VARIABLE 7
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01
				THEN perAfiCore.perSegundoNombre
				ELSE NULL
			END AS segundoNombreAfiliado2, -- VARIABLE 8
			CASE 
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR')
				THEN depAfiCore.depCodigo
				ELSE NULL
			END AS departamentoAfiliado, -- VARIABLE 9
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB','CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','CAMBIO_GENERO_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB','CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL','CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB','CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB','ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR') --codigo noveddad c01
				THEN munAfiCore.munCodigo
				ELSE NULL
			END AS municipioAfiliado, -- VARIABLE 10
			--========= FIN NOVEDAD C01 ================
			--====== INICIA NOVEDAD C03 Y C07 ============
			CASE WHEN --dbo.ParametrizacionNovedad.novTipoTransaccion IN ('AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO', --CODIGO NOVEDAD C03
					 --'AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_WEB_REINTEGRO')
					 dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_RAZON_SOCIAL_NOMBRE')
				THEN aporteGenAfiCore.empFechaCambioEstadoAfiliacion
			    --WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO')
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','REPORTE_INVALIDEZ_PERSONAS','REPORTE_INVALIDEZ_PERSONAS_DEPWEB','REPORTE_INVALIDEZ_PERSONAS_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_WEB')
			     AND snp.snpBeneficiario IS NULL THEN rolAfiCore.roaFechaIngreso
			    WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','REPORTE_INVALIDEZ_PERSONAS','REPORTE_INVALIDEZ_PERSONAS_DEPWEB','REPORTE_INVALIDEZ_PERSONAS_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_WEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_DEPWEB','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_PRESENCIAL','ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_WEB')
			     AND snp.snpBeneficiario IS NOT NULL THEN benCore.benFechaAfiliacion
				ELSE NULL
			END AS fechaAfiliacion, -- VARIABLE 11
			--====== FIN NOVEDAD C07 ============
			---===== INICIA NOVEDAD C03 ========
			CASE
				--WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO','AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_WEB_REINTEGRO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'))	  
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE') -- NOVEDAD C03
				AND rolAfiCore.roaTipoAfiliado = 'TRABAJADOR_DEPENDIENTE' THEN 1
				--WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO','AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_WEB_REINTEGRO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'))	  
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE') -- NOVEDAD C03
					AND	 rolAfiCore.roaTipoAfiliado = 'TRABAJADOR_INDEPENDIENTE' THEN 2 --2 - Trabajador afiliado facultativo
				--WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO','AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION','AFILIACION_EMPLEADORES_WEB_REINTEGRO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION','AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'))	  
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE') -- NOVEDAD C03
					 AND rolAfiCore.roaTipoAfiliado = 'PENSIONADO' THEN 3
				ELSE NULL
			END AS codigoTipoAfiliado, -- VARIABLE 13
			---===== INICIA NOVEDAD C04, CONTINUA C03 ========
			CASE
				WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perAportanteAfiCore.perTipoIdentificacion = 'CEDULA_CIUDADANIA' THEN 'CC'
				WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perAportanteAfiCore.perTipoIdentificacion = 'TARJETA_IDENTIDAD' THEN 'TI'
			    WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perAportanteAfiCore.perTipoIdentificacion = 'CEDULA_EXTRANJERIA' THEN 'CE'
				WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perAportanteAfiCore.perTipoIdentificacion = 'PASAPORTE' THEN 'PA'
			    WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perAportanteAfiCore.perTipoIdentificacion = 'CARNE_DIPLOMATICO' THEN 'CD'
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perEmpAportanteAfiCore.perTipoIdentificacion = 'CEDULA_CIUDADANIA' THEN 'CC'
			    WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perEmpAportanteAfiCore.perTipoIdentificacion ='TARJETA_IDENTIDAD' THEN 'TI'
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perEmpAportanteAfiCore.perTipoIdentificacion ='CEDULA_EXTRANJERIA' THEN 'CE'
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perEmpAportanteAfiCore.perTipoIdentificacion ='PASAPORTE' THEN 'PA'
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 AND perEmpAportanteAfiCore.perTipoIdentificacion ='CARNE_DIPLOMATICO' THEN 'CD'
				ELSE NULL
			END AS tipoIdAportante, -- VARIABLE 14
			CASE 
				WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 THEN perAportanteAfiCore.perNumeroIdentificacion 
				WHEN (aporteGenAfiCore.apgPersona IS NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 THEN perEmpAportanteAfiCore.perNumeroIdentificacion 
				ELSE NULL
			END AS numeroIdAportante, -- VARIABLE 15
			CASE 
				WHEN (aporteGenAfiCore.apgPersona IS NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --NOVEDAD C04
					 OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')) --NOVEDAD C03
					 THEN perEmpAportanteAfiCore.perDigitoVerificacion
				ELSE NULL
			END AS digitoVerificacionAportante, -- VARIABLE 16
			--======== FIN NOVEDAD C04 =========
			--==================================
			CASE 
				WHEN (aporteGenAfiCore.apgPersona IS NOT NULL AND  dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE'))--NOVEDAD C03
				THEN CONCAT(perAportanteAfiCore.perPrimerNombre,' ',perAportanteAfiCore.perSegundoNombre, ' ', perAportanteAfiCore.perPrimerApellido, ' ',perAportanteAfiCore.perSegundoApellido)
				WHEN (aporteGenAfiCore.apgPersona IS NULL AND dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE'))--NOVEDAD C03
				THEN perEmpAportanteAfiCore.perRazonSocial
				ELSE NULL
			END AS razonSocialAportante,-- VARIABLE 17
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')-- NOVEDAD C03
				THEN aporteGenAfiCore.roaFechaAfiliacion 
				ELSE NULL
			END AS fechaVinculacionAportante,--VARIABLE 18
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')-- NOVEDAD C03
				THEN depEmpAportanteAfiCore.depCodigo 
				ELSE NULL
			END AS departamentoUbicacion,--VARIABLE 19
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')-- NOVEDAD C03
				THEN munEmpAportanteAfiCore.munCodigo 
				ELSE NULL
			END AS municipioUbicacion,--VARIABLE 20
			--========================= FIN NOVEDAD C03 ==================
			--============================================================
			--ESTADO AFILIACIÓN 21: NO SE MUESTRA EN NINGUNA DE LAS 'NOVEDADES'
			--AL DIA (1- AL DIA O 2- EN MORA) 22: NO SE MUESTRA EN NINGUNA DE LAS 'NOVEDADES'
			--- ================= INICIO NOVEDAD 'C07' ================-----
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')-- NOVEDAD C03
			     	 AND snp.snpBeneficiario IS NULL THEN 1
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL','CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB','CAMBIO_RAZON_SOCIAL_NOMBRE')-- NOVEDAD C03
			     	 AND snp.snpBeneficiario IS NOT NULL THEN 2
				ELSE NULL
			END AS codigoTipoMiembroPoblacionCubierta, -- VARIABLE 23
			---==== FIN ULTIMO CAMPO NOVEDAD C03 ============
			--- === NOVEDADES 'C07' Y 'C08' =================
			CASE
				WHEN (snp.snpBeneficiario IS NULL) OR ( dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB') -- NOVEDAD C08
				 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )  AND rolAfiCore.roaFechaRetiro IS NOT NULL)
				THEN perAfiCore.perTipoIdentificacion
				WHEN (snp.snpBeneficiario IS NOT NULL) OR (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB') -- NOVEDAD C08
				AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL ) AND  benCore.benFechaRetiro IS NOT NULL)
				THEN perBenCore.perTipoIdentificacion
			END AS tipoIdMiembroPoblacionCubierta, -- VARIABLE 24
			CASE
				WHEN (snp.snpBeneficiario IS NOT NULL OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) -- NOVEDAD C08
				AND  benCore.benFechaRetiro IS NOT NULL
				THEN perBenCore.perNumeroIdentificacion
				ELSE NULL
			END AS numeroIdMiembroPoblacionCubierta, -- VARIABLE 25
			--- ==== FIN NOVEDAD 'C08' ========

			CASE
				WHEN benCore.benGradoAcademico IS NOT NULL AND benDetCore.bedCertificadoEscolaridad = 1 THEN 'E' --ESTUDIANTE
				WHEN benCore.benGradoAcademico IS NULL AND benDetCore.bedCertificadoEscolaridad = 0 THEN 'D' --DISCAPACITADO
				ELSE NULL
			END AS codigoCondicionBeneficiario, -- VARIABLE 26
			CASE
				WHEN benCore.benTipoBeneficiario = 'CONYUGE' THEN 1
				WHEN benCore.benTipoBeneficiario IN ('HIJO_BIOLOGICO','HIJO_ADOPTIVO','HIJASTRO','BENEFICIARIO_EN_CUSTODIA') THEN 2
				WHEN benCore.benTipoBeneficiario IN ('PADRE','MADRE') THEN 3
				WHEN benCore.benTipoBeneficiario IN ('HERMANO_HUERFANO_DE_PADRES','HERMANO_HOGAR') THEN 4
				ELSE NULL
			END AS codigoTipoRelacionConAfiliadoBen, -- VARIABLE 27
			--- ================= FIN NOVEDAD 'C07' =====================-----
			--- ================= INICIO NOVEDAD 'C09' ====================----
			NULL AS fechaAsignacionSubsidio, -- VARIABLE 28
			NULL AS valorSubsidio, -- VARIABLE 29
			NULL AS codigoTipoSubsidio, -- VARIABLE 30
			NULL AS estadoSubsidio, -- VARIABLE 31 				--codigoNovedad = 'C09'
			NULL AS departamentoSubsidio, -- VARIABLE 32
			NULL AS municipioSubsidio,   -- VARIABLE 33
			NULL AS fechaEntregaUltimoSubsidio, -- VARIABLE 34
			--- ================= FIN NOVEDAD 'C09' =====================
			--===================================================
			--================== INICIO NOVEDAD C04 ===========================
			CASE
				WHEN  dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE') --codigoNovedad = 'C04'
				THEN aporteGenAfiCore.roaFechaRetiro
				ELSE NULL
			END AS fechaDesvinculacionAportante, -- VARIABLE 35
			 ---== NOVEDADES C04 Y C08 ====---
			CASE
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN('RETIRO_TRABAJADOR_DEPENDIENTE') --codigoNovedad = 'C04'
					 AND rolAfiCore.roaFechaRetiro IS NOT NULL
				THEN rolAfiCore.roaFechaRetiro
				WHEN dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB') -- NOVEDAD C08
				AND benCore.benFechaRetiro IS NOT NULL
				THEN benCore.benFechaRetiro
				ELSE NULL
			END AS fechaRetiroAfiliado, -- VARIABLE 36
			CASE
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN('RETIRO_TRABAJADOR_DEPENDIENTE') --codigoNovedad = 'C04'
					  AND perDetAfiCore.pedFechaFallecido IS NOT NULL)
					 THEN perDetAfiCore.pedFechaFallecido
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB') --codigoNovedad = C08
					  AND perDetBenCore.pedFechaFallecido IS NOT NULL) THEN perDetBenCore.pedFechaFallecido
				ELSE NULL
			END AS fechaFallecimiento, -- VARIABLE 37
			--============= FIN NOVEDAD C04  ===========
			--- ================= INICIO NOVEDAD 'C09' ====================----
			NULL AS tipoIdbeneficiario, -- VARIABLE 38 codigoNovedad = 'C09'
			NULL AS numeroIdBeneficiario, -- VARIABLE 39
			NULL AS VARIABLE40,
			NULL AS VARIABLE41,
			NULL AS VARIABLE42,
			NULL AS VARIABLE43,
			NULL AS VARIABLE44,
			NULL AS VARIABLE45,
			NULL AS VARIABLE46,
			NULL AS VARIABLE47,
			NULL AS VARIABLE48,
			NULL AS VARIABLE49,
			NULL AS VARIABLE50,
			NULL AS VARIABLE51,
			NULL AS VARIABLE52,
			NULL AS VARIABLE53,
			NULL AS VARIABLE54,
			--- ================= FIN NOVEDAD 'C09' =====================
			/*CASE perDetBenFovis.pedGenero   --TODO: DEL CAMPO 40 AL 54 NO SE USAN
				WHEN 'MASCULINO' THEN 'M'
				ELSE 'F'
			END AS codigoGeneroBeneficiario,
			perDetBenFovis.pedFechaExpedicionDocumento AS fechaNacimientoBeneficiario,
			perBenFovis.perPrimerApellido AS primerApellidoBeneficiario,
			perBenFovis.perSegundoApellido AS segundoApellidoBeneficiario,
			perBenFovis.perPrimerNombre  AS primerNombreBeneficiario,
			perBenFovis.perSegundoNombre AS segundoNombreBeneficiario,
			CASE perEmpAportanteAfi.perTipoIdentificacion--perEmpresaFovis.perTipoIdentificacion
			    WHEN 'CEDULA_CIUDADANIA' THEN 1
				WHEN 'NIT' THEN 2
			END AS tipoIdEmpresaRecibeSubsidio,
			--perEmpresaFovis.perNumeroIdentificacion
			perEmpAportanteAfi.perNumeroIdentificacion AS numeroIdEmpresaRecibeSubsidio,
			--perEmpresaFovis.perDigitoVerificacion 
			perEmpAportanteAfi.perDigitoVerificacion AS digitoVerificacionIdEmpresaSubsidio,
			--perEmpresaFovis.perRazonSocial 
			perEmpAportanteAfi.perRazonSocial AS razonSocialEmpresaSubsidio,
			1 AS aQuienSeOtorgoSubsidio, 
			':fechaInicio' AS fechaInicialPeriodoInformacion,
			':fechaFin' AS fechaFinalPeriodoInformacion,
			0 AS totalRegistroRelacionadosArchivo,
			':nombreReporte' AS nombreDelArchivo,*/ 
			NULL AS identificadorUnicoSubsidio, -- VARIABLE 55
			NULL AS nuevoTipoIdMiembrePoblacionCubierta,  --VARIABLE 56
			NULL AS nuevoNumeroIdMiembroPoblacionCubierta, -- VARIABLE 57
			CASE
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
						OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
					 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					 AND rolAfiCore.roaFechaRetiro IS NOT NULL AND rolAfiCore.roaMotivoDesafiliacion = 'DESAFILIACION_EMPLEADOR'
					 THEN 1
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
						OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
					 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					  AND ((rolAfiCore.roaFechaRetiro IS NOT NULL AND rolAfiCore.roaMotivoDesafiliacion = 'FALLECIMIENTO') OR
					 (benCore.benFechaRetiro IS NOT NULL AND benCore.benMotivoDesafiliacion = 'FALLECIMIENTO')) THEN 2
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
						OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
					 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					 AND (rolAfiCore.roaMotivoDesafiliacion = 'RETIRO_POR_CAMBIO_DE_CAJA_COMPENSACION' OR
					 aporteGenAfiCore.empMotivoDesafiliacion = 'RETIRO_POR_TRASLADO_OTRA_CCF' OR benCore.benMotivoDesafiliacion = 'RETIRO_POR_CAMBIO_DE_CAJA_COMPENSACION' )
					 THEN 3
			    WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
						OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
						AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
			    	  AND dbo.ParametrizacionNovedad.novTipoTransaccion = 'SUSTITUCION_PATRONAL' THEN 6
			    WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
						OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
					 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					 AND aporteGenAfiCore.empMotivoDesafiliacion = 'FUSION_ADQUISICION'
					  AND rolAfiCore.roaMotivoDesafiliacion = 'DESAFILIACION_EMPLEADOR' THEN 7
			 	--TODO: FALTAN LAS CAUSAS DE RETIRO DE LA 4 A LA 12
				WHEN (dbo.ParametrizacionNovedad.novTipoTransaccion IN ('RETIRO_TRABAJADOR_DEPENDIENTE')
					OR dbo.ParametrizacionNovedad.novTipoTransaccion IN ('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB','INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL','INACTIVAR_BENEFICIARIO_CONYUGE_WEB','INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJASTRO_WEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB','INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL','INACTIVAR_BENEFICIARIO_HUERFANO_WEB')) --codigoNovedad = C08
					 AND (benCore.benFechaRetiro IS NOT NULL OR rolAfiCore.roaFechaRetiro IS NOT NULL )
					 AND benCore.benFechaRetiro IS NOT NULL AND benCore.benMotivoDesafiliacion = 'OTROS' THEN 30
				ELSE NULL
			END AS causaRetiro
			FROM dbo.Afiliado AS afiCore
			INNER JOIN dbo.RolAfiliado AS rolAfiCore ON rolAfiCore.roaAfiliado = afiCore.afiId
			INNER JOIN dbo.Persona AS perAfiCore ON afiCore.afiPersona = perAfiCore.perId
			LEFT JOIN dbo.Ubicacion AS ubiAfiCore ON ubiAfiCore.ubiId = perAfiCore.perUbicacionPrincipal
			LEFT JOIN dbo.Municipio AS munAfiCore ON munAfiCore.munId = ubiAfiCore.ubiMunicipio
			LEFT JOIN dbo.Departamento AS depAfiCore ON depAfiCore.depId = munAfiCore.munDepartamento
			INNER JOIN dbo.PersonaDetalle AS perDetAfiCore ON perAfiCore.perId = perDetAfiCore.pedPersona
			-- Novedades Persona
			LEFT JOIN dbo.SolicitudNovedadPersona AS snp ON snp.snpPersona = afiCore.afiPersona
			-- Fechas de las novedades persona
			LEFT JOIN dbo.SolicitudNovedad AS sno ON snp.snpSolicitudNovedad = sno.snoId
			LEFT JOIN dbo.ParametrizacionNovedad ON sno.snoNovedad = dbo.ParametrizacionNovedad.novId
			LEFT JOIN #FechasNovedadesSolicituNovedad AS novedadesAprobadas ON novedadesAprobadas.snoId = sno.snoId
			LEFT JOIN (
						SELECT CASE WHEN afiRol.roaEmpleador IS NOT NULL THEN NULL ELSE afi.afiPersona END apgPersona, 
								empleadorAporte.empEmpresa apgEmpresa,
							   	afiRol.roaFechaAfiliacion,
							   	afiRol.roaFechaRetiro,
							   	afiRol.roaId,
							   	empleadorAporte.empMotivoDesafiliacion,
							   	empleadorAporte.empFechaCambioEstadoAfiliacion
						FROM dbo.RolAfiliado AS afiRol
						LEFT JOIN dbo.Empleador AS empleadorAporte ON empleadorAporte.empId = afiRol.roaEmpleador
						LEFT JOIN dbo.Afiliado afi ON afi.afiId = afiRol.roaAfiliado
			) AS aporteGenAfiCore ON aporteGenAfiCore.roaId = rolAfiCore.roaId
			LEFT JOIN dbo.Persona AS perAportanteAfiCore ON perAportanteAfiCore.perId = aporteGenAfiCore.apgPersona
			LEFT JOIN dbo.Empresa AS empAportanteAfiCore ON empAportanteAfiCore.empId = aporteGenAfiCore.apgEmpresa
			LEFT JOIN dbo.Persona AS perEmpAportanteAfiCore ON perEmpAportanteAfiCore.perId = empAportanteAfiCore.empPersona
			LEFT JOIN dbo.UbicacionEmpresa ube ON ube.ubeEmpresa = empAportanteAfiCore.empId AND ube.ubeTipoUbicacion='UBICACION_PRINCIPAL'
			LEFT JOIN dbo.Ubicacion AS ubiEmpAportanteAfiCore ON ubiEmpAportanteAfiCore.ubiId = ube.ubeUbicacion
			LEFT JOIN dbo.Municipio AS munEmpAportanteAfiCore ON munEmpAportanteAfiCore.munId = ubiEmpAportanteAfiCore.ubiMunicipio
			LEFT JOIN dbo.Departamento AS depEmpAportanteAfiCore ON depEmpAportanteAfiCore.depId = munEmpAportanteAfiCore.munDepartamento
			INNER JOIN dbo.Beneficiario AS benCore ON afiCore.afiId = benCore.benAfiliado AND snp.snpBeneficiario = benCore.benId
			INNER JOIN dbo.BeneficiarioDetalle AS benDetCore ON benDetCore.bedId = benCore.benBeneficiarioDetalle
			INNER JOIN dbo.Persona AS perBenCore ON perBenCore.perId = benCore.benPersona
			INNER JOIN dbo.PersonaDetalle AS perDetBenCore ON perDetBenCore.pedPersona = perBenCore.perId
			WHERE rolAfiCore.roaEstadoAfiliado = 'ACTIVO' AND
			dbo.ParametrizacionNovedad.novTipoTransaccion IN ('CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB',
			'CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL',
			'CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB',
			'CAMBIO_GENERO_PERSONAS',
			'CAMBIO_NOMBRE_APELLIDOS_PERSONAS',
			'CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB',
			'CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB',
			'CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_DEPWEB',
			'CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_PRESENCIAL',
			'CAMBIO_DATOS_CORRESPONDENCIA_GRUPO_FAMILIAR_WEB',
			'CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS',
			'CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_DEPWEB',
			'CAMBIO_DATOS_CORRESPONDENCIA_PERSONAS_WEB',
			'ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR',
			'ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB',
			'ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL',
			'ACTUALIZAR_DOCUMENTO_IDENTIDAD_PERSONA_WEB',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_0_6_WEB',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MAYOR_1_5SM_2_WEB',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_6_WEB',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_PRESENCIAL',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_0_WEB',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL',
			'CAMBIO_TIPO_PENSIONADO_PENSIONADO_MENOR_1_5SM_2_WEB',
			'CAMBIO_RAZON_SOCIAL_NOMBRE',
			'ACTUALIZACION_MUNICIPIO_DESEMPEÑO_LABORES',
			'RETIRO_TRABAJADOR_DEPENDIENTE',
			'REPORTE_INVALIDEZ_PERSONAS',
			'REPORTE_INVALIDEZ_PERSONAS_DEPWEB',
			'REPORTE_INVALIDEZ_PERSONAS_WEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL',
			'ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_DEPWEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_WEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_DEPWEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_PRESENCIAL',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_WEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_DEPWEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_PRESENCIAL',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_WEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_DEPWEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_PRESENCIAL',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_WEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_DEPWEB',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_PRESENCIAL',
			'ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_WEB',
			'INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB',
			'INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL',
			'INACTIVAR_BENEFICIARIO_CONYUGE_WEB',
			'INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB',
			'INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL',
			'INACTIVAR_BENEFICIARIO_HIJASTRO_WEB',
			'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB',
			'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL',
			'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB',
			'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB',
			'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL',
			'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB',
			'INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB',
			'INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL',
			'INACTIVAR_BENEFICIARIO_HUERFANO_WEB')
			AND  novedadesAprobadas.fechaRegistroNovedadCerrada BETWEEN @fechaInicio AND @fechaFin