
CREATE OR ALTER PROCEDURE [sap].[LIMPIAR_INFO_INTEGRACIONES_6_MESES]
AS

DELETE SAP.Contactos_E2G WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Contactos_G2E WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Empresas_E2G WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Empresas_G2E WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE D FROM SAP.IC_Aportes_Det D INNER JOIN SAP.IC_Aportes_Enc E ON E.consecutivo =D.consecutivo  WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.IC_Aportes_Enc WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE D FROM SAP.IC_CM_Det D INNER JOIN SAP.IC_CM_Enc E ON E.consecutivo =D.consecutivo  WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.IC_CM_Enc WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE D FROM SAP.IC_FOVIS_Det D INNER JOIN SAP.IC_FOVIS_Enc E ON E.consecutivo =D.consecutivo  WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.IC_FOVIS_Enc WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Personas_E2G WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Personas_G2E WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6
DELETE SAP.Relaciones_G2E WHERE DATEDIFF(MONTH,fecing,GETDATE()) > 6