-- ====================================================================================================
-- Author: VILLAMARIN JULIAN
-- Create date: MAYO 10 DE 2021
-- Description: Llama el SP [SAP].[USP_GetEmpresas_DocumentoId] el cual realiza el ingreso de registros 
-- por numero y tipo de identificacion cuando se presenta una novedad o una afiliacion a la tabla de
-- integracion.
-- =====================================================================================================
CREATE OR ALTER PROCEDURE [sap].[USP_GetEmpresas_Insert] AS
BEGIN
SET NOCOUNT ON;
 
DECLARE	@perNumeroIdentificacion VARCHAR(20), @perTipoIdentificacion VARCHAR(20), @solNumeroRadicacion VARCHAR(30), @tipo VARCHAR(10)

CREATE TABLE #tmp_filaEmpresas (perNumeroIdentificacion VARCHAR(16),
                                perTipoIdentificacion VARCHAR(20),
								solNumeroRadicacion VARCHAR(30),
								tipo VARCHAR(30))

-- Registro en bitacora de registros a ser integrados y que no hayan sido integrados previamente en registro de la tabla EmpresasCtrl.
-- Selecciono las novedades y las afiliaciones realizadas

    INSERT INTO #tmp_filaEmpresas
	SELECT per.perNumeroIdentificacion, per.perTipoIdentificacion, sol.solNumeroRadicacion, 'NOVEDAD' AS tipo
	FROM Persona per WITH (NOLOCK)
	INNER JOIN Empresa emp WITH (NOLOCK) ON per.perId = emp.empPersona
	INNER JOIN Empleador eml WITH (NOLOCK) ON emp.empId = eml.empempresa
	INNER JOIN SolicitudNovedadEmpleador sne WITH (NOLOCK) ON  eml.empId = sne.sneIdEmpleador
	INNER JOIN SolicitudNovedad sno WITH (NOLOCK) ON sne.sneIdSolicitudNovedad = sno.snoId
	INNER JOIN Solicitud sol WITH (NOLOCK) ON  sno.snoSolicitudGlobal = sol.solid AND sol.solUsuarioRadicacion <> 'Integracion'
	LEFT JOIN  sap.EmpresasCtrl ctr WITH (NOLOCK) ON  ctr.solNumeroRadicacion = sol.solNumeroRadicacion
	WHERE solusuarioradicacion <>'Integracion' --CAMBIO OLGA VEGA 20220131
	AND sno.snoEstadoSolicitud = 'CERRADA'  
	AND sol.solResultadoProceso = 'APROBADA'
	AND sol.solFechaRadicacion >= '2024-03-20'
	AND sol.solTipoTransaccion IN (
		'DESAFILIACION_AUTOMATICA_POR_MORA',
		'DESAFILIAR_AUTOMATICAMENTE_EMPLEADORES_CERO_TRABAJADORES',
		'DESAFILIAR_AUTOMATICAMENTE_EMPLEADORES_SOLICITUD_RECHAZADA',
		'INACTIVAR_AUTOMATICAMENTE_CUENTA_WEB_EMPLEADOR',
		'INACTIVAR_AUTOMATICAMENTE_BENEFICIOS_LEY_590_2000',
		'INACTIVAR_AUTOMATICAMENTE_BENEFICIO_LEY_1429_2010',
		'DESAFILIACION',
		'SUSTITUCION_PATRONAL',
		'TRASLADO_TRABAJADORES_ENTRE_SUCURSALES',
		'INACTIVAR_BENEFICIOS_LEY_590_2000_WEB',
		'INACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL',
		'ACTIVAR_BENEFICIOS_LEY_590_2000_WEB',
		'ACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL',
		'INACTIVAR_BENEFICIOS_LEY_1429_2010_WEB',
		'INACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL',
		'ACTIVAR_BENEFICIOS_LEY_1429_2010_WEB',
		'ACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL',
		'CAMBIO_RESPONSABLE_CONTACTOS_CFF',
		'CAMBIOS_ROLES_CONTACTO_WEB',
		'CAMBIOS_ROLES_CONTACTO_PRESENCIAL',
		'INACTIVAR_SUCURSAL',
		'AGREGAR_SUCURSAL',
		'ACTIVAR_INACTIVAR_CODIGO_SUCURSAL_DEBE_COINCIDIR_CON_PILA',
		'CAMBIO_MEDIO_PAGO_SUCURSAL_WEB',
		'CAMBIO_MEDIO_PAGO_SUCURSAL_PRESENCIAL',
		'CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_WEB',
		'CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_PRESENCIAL',
		'CAMBIO_DATOS_SUCURSAL_WEB',
		'CAMBIO_DATOS_SUCURSAL_PRESENCIAL',
		'CAMBIO_CODIGO_NOMBRE_SUCURSAL_WEB',
		'CAMBIO_CODIGO_NOMBRE_SUCURSAL',
		'CAMBIO_MEDIO_PAGO_EMPLEADOR_WEB',
		'CAMBIO_MEDIO_PAGO_EMPLEADOR_PRESENCIAL',
		'CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_WEB',
		'CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_PRESENCIAL',
		'ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_WEB',
		'ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_PRESENCIAL',
		'ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_WEB',
		'ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_PRESENCIAL',
		'ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_WEB',
		'ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_PRESENCIAL',
		'CAMBIOS_OTROS_DATOS_IDENTIFICACION_EMPLEADOR',
		'CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_WEB',
		'CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_PRESENCIAL',
		'CAMBIO_NATURALEZA_JURIDICA',
		'CAMBIO_RAZON_SOCIAL_NOMBRE',
		'CAMBIO_TIPO_NUMERO_DOCUMENTO',
		'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO',
		'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION',
		'AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',
		'AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',
		'AFILIACION_EMPLEADORES_WEB_REINTEGRO',
		'AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION',
		'AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO',
		'AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'
	)
	AND ctr.solNumeroRadicacion IS NULL

	--CAMBIO OLGA VEGA 20220310 no enviaria nada porque lo hizo con los datos del erp 
--UNION

INSERT INTO #tmp_filaEmpresas
SELECT perNumeroIdentificacion, perTipoIdentificacion, sol.solNumeroRadicacion, 'AFILIACION' AS tipo
	FROM Persona per WITH (NOLOCK)
	INNER JOIN Empresa emp WITH (NOLOCK) ON per.perId = emp.empPersona
	INNER JOIN Empleador eml WITH (NOLOCK) ON emp.empId = eml.empempresa
	INNER JOIN SolicitudAfiliaciEmpleador sae WITH (NOLOCK) ON  eml.empId = sae.saeEmpleador
	INNER JOIN Solicitud sol WITH (NOLOCK) ON  sae.saeSolicitudGlobal = sol.solid
	WHERE sae.saeEstadoSolicitud = 'CERRADA'
	AND sol.solResultadoProceso = 'APROBADA'
	AND sol.solFechaRadicacion >= '2024-03-20'
	AND solusuarioradicacion <>'Integracion' 
	AND sol.solTipoTransaccion IN (
		'DESAFILIACION_AUTOMATICA_POR_MORA',
		'DESAFILIAR_AUTOMATICAMENTE_EMPLEADORES_CERO_TRABAJADORES',
		'DESAFILIAR_AUTOMATICAMENTE_EMPLEADORES_SOLICITUD_RECHAZADA',
		'INACTIVAR_AUTOMATICAMENTE_CUENTA_WEB_EMPLEADOR',
		'INACTIVAR_AUTOMATICAMENTE_BENEFICIOS_LEY_590_2000',
		'INACTIVAR_AUTOMATICAMENTE_BENEFICIO_LEY_1429_2010',
		'DESAFILIACION',
		'SUSTITUCION_PATRONAL',
		'TRASLADO_TRABAJADORES_ENTRE_SUCURSALES',
		'INACTIVAR_BENEFICIOS_LEY_590_2000_WEB',
		'INACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL',
		'ACTIVAR_BENEFICIOS_LEY_590_2000_WEB',
		'ACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL',
		'INACTIVAR_BENEFICIOS_LEY_1429_2010_WEB',
		'INACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL',
		'ACTIVAR_BENEFICIOS_LEY_1429_2010_WEB',
		'ACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL',
		'CAMBIO_RESPONSABLE_CONTACTOS_CFF',
		'CAMBIOS_ROLES_CONTACTO_WEB',
		'CAMBIOS_ROLES_CONTACTO_PRESENCIAL',
		'INACTIVAR_SUCURSAL',
		'AGREGAR_SUCURSAL',
		'ACTIVAR_INACTIVAR_CODIGO_SUCURSAL_DEBE_COINCIDIR_CON_PILA',
		'CAMBIO_MEDIO_PAGO_SUCURSAL_WEB',
		'CAMBIO_MEDIO_PAGO_SUCURSAL_PRESENCIAL',
		'CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_WEB',
		'CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_PRESENCIAL',
		'CAMBIO_DATOS_SUCURSAL_WEB',
		'CAMBIO_DATOS_SUCURSAL_PRESENCIAL',
		'CAMBIO_CODIGO_NOMBRE_SUCURSAL_WEB',
		'CAMBIO_CODIGO_NOMBRE_SUCURSAL',
		'CAMBIO_MEDIO_PAGO_EMPLEADOR_WEB',
		'CAMBIO_MEDIO_PAGO_EMPLEADOR_PRESENCIAL',
		--'CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_WEB',
		--'CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_PRESENCIAL',
		--'ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_WEB',
		--'ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_PRESENCIAL',
		--'ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_WEB',
		--'ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_PRESENCIAL',
		--'ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_WEB',
		--'ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_PRESENCIAL',
		'CAMBIOS_OTROS_DATOS_IDENTIFICACION_EMPLEADOR',
		'CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_WEB',
		'CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_PRESENCIAL',
		'CAMBIO_NATURALEZA_JURIDICA',
		'CAMBIO_RAZON_SOCIAL_NOMBRE',
		'CAMBIO_TIPO_NUMERO_DOCUMENTO',
		'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO',
		'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION',
		'AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',
		'AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',
		'AFILIACION_EMPLEADORES_WEB_REINTEGRO',
		'AFILIACION_EMPLEADORES_WEB_NUEVA_AFILIACION',
		'AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO',
		'AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'
	)
	   	AND NOT EXISTS (SELECT  solNumeroRadicacion 
			FROM sap.EmpresasCtrl Emp WITH (NOLOCK) WHERE emp.solNumeroRadicacion = sol.solNumeroRadicacion)



	DECLARE cursor_documentoId CURSOR FOR 
	SELECT * FROM #tmp_filaEmpresas WITH(NOLOCK)



OPEN cursor_documentoId 
FETCH NEXT FROM cursor_documentoId INTO @perNumeroIdentificacion, @perTipoIdentificacion, @solNumeroRadicacion, @tipo 
WHILE @@FETCH_STATUS = 0 
BEGIN

BEGIN TRANSACTION 
	BEGIN TRY

	  	EXEC [SAP].[USP_GetEmpresas_documentoId] @perNumeroIdentificacion, @perTipoIdentificacion, @solNumeroRadicacion;

		-- Marca los registros como ya integrados (se debe cambiar por el consecutivo)
		INSERT INTO sap.EmpresasCtrl
		SELECT @solNumeroRadicacion, 1, @perNumeroIdentificacion, @perTipoIdentificacion

COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	  SELECT
		ERROR_NUMBER() AS ErrorNumber,
		ERROR_STATE() AS ErrorState,
		ERROR_SEVERITY() AS ErrorSeverity,
		ERROR_PROCEDURE() AS ErrorProcedure,
		ERROR_LINE() AS ErrorLine,
		ERROR_MESSAGE() AS ErrorMessage;
	END CATCH;

    FETCH NEXT FROM cursor_documentoId INTO @perNumeroIdentificacion, @perTipoIdentificacion, @solNumeroRadicacion, @tipo 
END 
 
CLOSE cursor_documentoId 
DEALLOCATE cursor_documentoId 

DROP TABLE #tmp_filaEmpresas;

END