--liquibase formatted sql

--changeset clamarin:01
--comment: Insercion en la tabla VariableComunicado

--Comunicado N°48: Notificación de resultados de solicitud de novedad empleador
--Inserción Variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${resultadoNovedad}','Resultado novedad','Resultado de novedad "Aprobado" o "Rechazado"',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') ) ;
 --Inserción Constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')) ;

--Comunicado N°50: Notificación de radicación de solicitud de novedad de empleador
--Inserción Variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
-- Falta un insert de Resultado Novedad No se encuentra en la Plantilla Mensajes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ) ;
--Inserción Constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')) ;

--Comunicado N°51: Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable
--Inserción Variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
--Falta un insert Producto no conforme no subsanado No se encuentra en Plantillas Mensajes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') ) ;
--Inserción Constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')) ;

--Comunicado N°53: Solicitud de confirmación retiro de aportante
--Inserción Variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAportes}','Responsable  Aportes','Persona responsable de Aportes',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') ) ;
--Falta un insert Nombre y Apellidos Representante Legal No se encuentra en la Plantilla Mensajes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') ) ;
--Inserción Constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante')) ;

--Comunicado N°54: Desistimiento novedad de retiro de aportante
--Inserción Variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
--Falta insert de NovedadEmpleador No se encuentra el insert en plantillas mensajes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') ) ;
--Inserción Constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')) ;

--changeset clamarin:02
--comment: Insercion en la tabla PlantillaComunicado
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de resultados de solicitud de novedad empleador',null,null,null,null,'Notificación de resultados de solicitud de novedad empleador',null,'NTF_NVD_EMP')
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación de solicitud de novedad de empleador',null,null,null,null,'Notificación de radicación de solicitud de novedad de empleador',null,'NTF_RAD_NVD_EMP')
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Desistimiento novedad de retiro de aportante',null,null,null,null,'Desistimiento novedad de retiro de aportante',null,'DSTMTO_NVD_RET_APRT')
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable',null,null,null,null,'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable',null,'RCHZ_NVD_EMP_PROD_NSUBLE')
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Solicitud de confirmación retiro de aportante',null,null,null,null,'Solicitud de confirmación retiro de aportante',null,'CNFR_RET_APRT')

--changeset flopez:03
--comment: Se actualizan tablas para Novedades 28 y 29 HU:[496]
--Novedad 28 Inactivar automáticamente beneficios de Ley 1429 de 2010
INSERT INTO ParametrizacionEjecucionProgramada (pepProceso, pepHoras, pepMinutos, pepMes, pepDiaMes, pepFrecuencia) VALUES('INACTIVAR_AUTOMATICAMENTE_BENEFICIO_LEY_1429_2010', '00','00', '01', '01', 'ANUAL')
UPDATE Novedad SET novPuntoResolucion = 'SISTEMA_AUTOMATICO', novRutaCualificada='com.asopagos.novedades.convertidores.empleador.ActualizarInactivarBeneficiosLey1429', novTipoNovedad = 'GENERAL' WHERE novTipoTransaccion = 'INACTIVAR_AUTOMATICAMENTE_BENEFICIO_LEY_1429_2010'
--Novedad 29 Inactivar automáticamente beneficios de Ley 590 de 2000
INSERT INTO ParametrizacionEjecucionProgramada (pepProceso, pepHoras, pepMinutos, pepDiaMes, pepFrecuencia) VALUES('INACTIVAR_AUTOMATICAMENTE_BENEFICIOS_LEY_590_2000', '00','00', '01', 'MENSUAL')
UPDATE Novedad SET novPuntoResolucion = 'SISTEMA_AUTOMATICO', novRutaCualificada='com.asopagos.novedades.convertidores.empleador.ActualizarInactivarBeneficiosLey590', novTipoNovedad = 'GENERAL' WHERE novTipoTransaccion = 'INACTIVAR_AUTOMATICAMENTE_BENEFICIOS_LEY_590_2000'

