--liquibase formatted sql

--changeset clmarin:01
--comment: Insercion de las VariableComunicado 54
-----Inserción plantilla comunicado Desistimiento novedad de retiro de aportante
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Desistimiento novedad de retiro de aportante',null,null,null,null,'Desistimiento novedad de retiro de aportante',null,'DSTMTO_NVD_RET_APRT')

--changeset clmarin:02
--comment: Insercion de las VariableComunicado
---Inserción 48 Notificación de resultados de solicitud de novedad empleador (Variables,Constantes)
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')  , 'VARIABLE')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${resultadoNovedad}','Resultado novedad','Resultado de novedad "Aprobado" o "Rechazado"', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'USUARIO') 

------Inserción 50 Notificación de radicación de solicitud de novedad de empleador
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${resultadoNovedad}','Resultado novedad','Resultado de novedad "Aprobado" o "Rechazado"', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ,'USUARIO') 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'USUARIO')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'USUARIO') 


---- Insercion N°51: Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${productoNoConformeNoSubsanado}','Producto no conforme no subsanado','Producto no conforme no subsanado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO') 

----Insercion N°53: Solicitud de confirmación retiro de aportante
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAportes}','Responsable  Aportes','Persona responsable de Aportes', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'USUARIO') 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'USUARIO') 


-----Inserción N°54: Desistimiento novedad de retiro de aportante
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${novedadEmpleador}','Novedad Empleador','Tipo transacción', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = ' Desistimiento novedad de retiro de aportante') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'USUARIO' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'USUARIO' )

--changeset halzate:03
--comment: Insercion de las VariableComunicado 4
-- variables comunicado 4 Carta de bienvenida para empleador
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadSede}','Ciudad sede','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${direccionRepresentanteLegal}','Dirección  Representante Legal','Dirección capturada en Información de ubicación y correspondencia', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${telefonoRepresentanteLegal}','Teléfono Representante Legal','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${ciudadRepresentanteLegal}','Ciudad  Representante Legal','Municipio capturado en Información de ubicación y correspondencia', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador') ) ;

--Constantes comunicado 4 Carta de bienvenida para empleador
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de Ubicación de la Caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de Ubicación de la Caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la Caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Número telefónico de la Caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo documento de la Caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de documento de la Caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Dirección del sitio web de la Caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logotipo de la Superintendencia de Servicios','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Imagen de la firma del responsable del envío del comunicado en la caja','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Nombre del responsable del envío del comunicado en la caja','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo del responsable del envío del comunicado en la caja','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Carta de bienvenida para empleador')) ;

--changeset clmarin:04
--comment: Insercion de las VariableComunicado 54
-----Inserción plantilla comunicado Desistimiento novedad de retiro de aportante
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Desistimiento novedad de retiro de aportante',null,null,null,null,'Desistimiento novedad de retiro de aportante',null,'DSTMTO_NVD_RET_APRT')

---Inserción 48 Notificación de resultados de solicitud de novedad empleador (Variables,Constantes)
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')  , 'VARIABLE')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${resultadoNovedad}','Resultado novedad','Resultado de novedad "Aprobado" o "Rechazado"', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de resultados de solicitud de novedad empleador'), 'USUARIO') 

------Inserción 50 Notificación de radicación de solicitud de novedad de empleador
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${resultadoNovedad}','Resultado novedad','Resultado de novedad "Aprobado" o "Rechazado"', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') ,'USUARIO') 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'USUARIO')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Notificación de radicación de solicitud de novedad de empleador') , 'USUARIO') 


---- Insercion N°51: Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${productoNoConformeNoSubsanado}','Producto no conforme no subsanado','Producto no conforme no subsanado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable') , 'USUARIO') 

----Insercion N°53: Solicitud de confirmación retiro de aportante
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAportes}','Responsable  Aportes','Persona responsable de Aportes', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante') , 'USUARIO') 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'USUARIO') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Solicitud de confirmación retiro de aportante'), 'USUARIO') 


-----Inserción N°54: Desistimiento novedad de retiro de aportante
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreYApellidosRepresentanteLegal}','Nombre y Apellidos Representante Legal','Nombre del representante legal del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${razonSocial/Nombre}','Razón social / Nombre','Nombre del empleador que realizó la solicitud', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante')  , 'VARIABLE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE' )
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${novedadEmpleador}','Novedad Empleador','Tipo transacción', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'VARIABLE')
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableAfiliacionCcf}','Responsable  Afiliacion CCF','Persona responsable del proceso de afiliación', (SELECT pcoId FROM PlantillaComunicado where pcoNombre = ' Desistimiento novedad de retiro de aportante') , 'USUARIO' ) 

INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${tipoIdCcf}','Tipo ID CCF','Tipo de la caja de Compensación','TIPO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${numeroIdCcf}','Número ID CCF','Número de la caja de Compensación','NUMERO_ID_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'CONSTANTE') 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'USUARIO' ) 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoPlantillaComunicado,vcoTipoVariableComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF',(SELECT pcoId FROM PlantillaComunicado where pcoNombre = 'Desistimiento novedad de retiro de aportante') , 'USUARIO' )




