--liquibase formatted sql

--changeset alquintero:01
--comment:Insercion de registros en las tablas DestinatarioComunicado y PrioridadDestinatario
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('POSTULACION_FOVIS_PRESENCIAL','NTF_INT_POS_FOVIS');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='POSTULACION_FOVIS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_POS_FOVIS'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1);
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('POSTULACION_FOVIS_PRESENCIAL','NTF_RAD_POS_FOVIS_PRE');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='POSTULACION_FOVIS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_RAD_POS_FOVIS_PRE'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1);
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('POSTULACION_FOVIS_PRESENCIAL','RCHZ_SOL_POS_FOVIS_ESCA');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='POSTULACION_FOVIS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_SOL_POS_FOVIS_ESCA'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1);
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('POSTULACION_FOVIS_PRESENCIAL','RCHZ_SOL_POS_FOVIS');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='POSTULACION_FOVIS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_SOL_POS_FOVIS'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1);
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('POSTULACION_FOVIS_PRESENCIAL','NTF_SBC_POS_FOVIS_EXT');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='POSTULACION_FOVIS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_SBC_POS_FOVIS_EXT'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1);
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','NTF_RAD_SOL_LEG_DES');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='NTF_RAD_SOL_LEG_DES'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','NTF_INT_LEG_DES');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='NTF_INT_LEG_DES'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','DES_FOVIS_AUTO');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='DES_FOVIS_AUTO'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','NTF_DES_FOVIS_EXT');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='NTF_DES_FOVIS_EXT'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','DES_FOVIS_NAUTO');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='DES_FOVIS_NAUTO'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','RCHZ_SOL_LEG_DES_FOVIS_ESCA');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='RCHZ_SOL_LEG_DES_FOVIS_ESCA'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
INSERT DestinatarioComunicado(dcoProceso,dcoEtiquetaPlantilla) VALUES ('LEGALIZACION_DESEMBOLSO_FOVIS','RCHZ_SOL_LEG_DES_FOVIS_SBC_NEXT');
INSERT PrioridadDestinatario(prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='LEGALIZACION_DESEMBOLSO_FOVIS' AND des.dcoEtiquetaPlantilla='RCHZ_SOL_LEG_DES_FOVIS_SBC_NEXT'),(SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'),1); 
