--liquibase formatted sql

--changeset dasanchez:01 
--comment:Eliminacion de registros en las tablas parametros y constantes
DELETE FROM Parametro;
DELETE FROM Constante;

--changeset dasanchez:02 context:integracion runOnChange:true
--comment: Configuracion del ambiente integración COMFABOY
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','COMFABOY',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','TUNJA',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','BOYACA',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Carrera 10 # 16-81',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','18000918778',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','891800213-8',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','d528dcd6-ed22-4d7e-9cca-e0a33cecc507_1.0',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.dianis.com.co',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','pruebaLogoSuperServicios',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','pruebaFirmaResponsableEnvioComunicadoCaja',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','15',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','asopagos-proyecto@heinsohn.com.co',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','zDgxdoNnBaLbivLqKjtnww==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.office365.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','587',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','5m',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','5m',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','91de0193-281a-4d14-a592-f105efe82eea_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','44662d2b-90df-4f44-9202-abcf9e6144fd_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS','/subsidios/integracion',0,'FTP_ARCHIVOS_DESCUENTO','Ruta de los archivos de descuento en el servidor FTP');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','CONFAHBT','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF10','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.77.187.42/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.77.187.38:8282/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','Admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','Asdf1234$','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://50.23.54.143:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://50.23.54.143:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_SERVIDOR','localhost','Host donde están desplegados los servicios en JBOSS EAP');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_PUERTO','80','Puerto donde escuchan los servicios en JBOSS EAP');

--changeset dasanchez:03 context:pruebas runOnChange:true
--comment: Configuracion del ambiente pruebas HBT COMFACAUCA 
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','COMFACAUCA',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','POPAYAN',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','CAUCA',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Calle 2N No. 6A-54',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','(2) 8231868',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','891500182-0',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','9560bfc8-d503-49fb-8733-eeafc66d94ce_1.0',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.ccfcaldas.com',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','pruebaLogoSuperServicios',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','pruebaFirmaResponsableEnvioComunicadoCaja',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','juan.oviedo',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','juan.oviedo',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','30m',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','19',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','asopagos-proyecto@heinsohn.com.co',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','zDgxdoNnBaLbivLqKjtnww==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.office365.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','587',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','86400000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','51d2e66c-564b-4aa3-ba70-b7e8c6420f1f_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','44662d2b-90df-4f44-9202-abcf9e6144fd_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS','/subsidios/pruebas',0,'FTP_ARCHIVOS_DESCUENTO','Ruta de los archivos de descuento en el servidor FTP');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','CONFA','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF14','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.77.187.51/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.77.187.38:8282/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','Admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','Asdf1234$','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://50.23.54.143:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://50.23.54.143:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_SERVIDOR','10.77.187.51','Host donde están desplegados los servicios en JBOSS EAP');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_PUERTO','8181','Puerto donde escuchan los servicios en JBOSS EAP');

--changeset dasanchez:04 context:asopagosSubsidio runOnChange:true
--comment: Configuracion del ambiente ASOPAGOSSUBSIDIO
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','ASOPAGOSSUBSIDIO',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','TUNJA',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','BOYACA',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Carrera 10 # 16-81',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','18000918778',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','891800213-8',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','d528dcd6-ed22-4d7e-9cca-e0a33cecc507_1.0',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.dianis.com.co',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','pruebaLogoSuperServicios',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','pruebaFirmaResponsableEnvioComunicadoCaja',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','15',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','asopagos-proyecto@heinsohn.com.co',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','zDgxdoNnBaLbivLqKjtnww==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.office365.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','587',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','91de0193-281a-4d14-a592-f105efe82eea_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','44662d2b-90df-4f44-9202-abcf9e6144fd_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS','/subsidios/ambSubsidio/carga',0,'FTP_ARCHIVOS_DESCUENTO','Ruta de los archivos de descuento en el servidor FTP');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','asopagos-subsidio','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF10','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://172.20.0.135/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.77.187.38:8282/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','Admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','Asdf1234$','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://172.20.0.135:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://172.20.0.135:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_SERVIDOR','localhost','Host donde están desplegados los servicios en JBOSS EAP');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_PUERTO','8181','Puerto donde escuchan los servicios en JBOSS EAP');

--changeset dasanchez:05 context:integracion-asopagos runAlways:true runOnChange:true
--comment: Configuracion del ambiente integracion asopagos integracionasopagos
DELETE FROM Parametro WHERE prmNombre IN('NOMBRE_CCF','CIUDAD_CCF','DEPARTAMENTO_CCF','DIRECCION_CCF','TELEFONO_CCF','TIPO_ID_CCF','NUMERO_ID_CCF','LOGO_DE_LA_CCF','WEB_CCF','LOGO_SUPERSERVICIOS','FIRMA_RESPONSABLE_CCF','RESPONSABLE_CCF','RESPONSABLE_NOVEDADES_CCF','TIEMPO_EXPIRACION_ENLACE','CAJA_COMPENSACION_MUNI_ID','CAJA_COMPENSACION_DEPTO_ID','mail.smtp.user','mail.smtp.password','mail.smtp.host','mail.smtp.port','112_IMPRIMIR_FORMULARIO_TIMER','112_CORREGIR_INFORMACION_TIMER','122_CORREGIR_INFORMACION_TIMER','123_ABRIR_LINK_TIMER','123_DILIGENCIAR_FORMULARIO_TIMER','TIEMPO_INACTIVAR_CUENTA','ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS','FTP_ARCHIVOS_DESCUENTO_URL_RESULTADOS');
DELETE FROM Constante WHERE cnsNombre IN('CAJA_COMPENSACION_SITE','CAJA_COMPENSACION_ID','CAJA_COMPENSACION_CODIGO','BPMS_BUSINESS_CENTRAL_ENDPOINT','ECM_HOST','ECM_USERNAME','ECM_PASSWORD','KEYCLOAK_ENDPOINT','IDM_SERVER_URL','SERVICIOS_SERVIDOR','SERVICIOS_PUERTO');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','COMFABOY',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','MANIZALES',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','CALDAS',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Cra 25 Calle 50',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','57(6)8783111',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','890806490-5',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','fc360d0a-165b-435b-940c-e3593c2d94dd',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.asopagos.com',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','c4562d89-1f8a-414f-bbe7-e2bf90ed4cf0',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','839e030f-d8f2-464a-8a95-0ff6e8c00b03',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','17',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','soporte.ti@asopagos.com',0,'MAIL_SMTP','Usuario que se autentica en el servidor de correo SMTP.Debe tener permiso de envío de correos en el servidor configurado');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','RWU4DjifCrlC4vGGxj+FWw==',0,'MAIL_SMTP','Constraseña del usuario que se autentica en el servidor de correo SMTP y que tiene permisos de envío de correo en dicho servidor. Propiedad cifrada ');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.gmail.com',0,'MAIL_SMTP','URL del servidor que provee el servicio SMTP a través del cuál se enviarán los correos electrónicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','25',0,'MAIL_SMTP','Puerto por el que atiende el servidor de correo SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','91de0193-281a-4d14-a592-f105efe82eea_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','44662d2b-90df-4f44-9202-abcf9e6144fd_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS','/subsidios/espejo',0,'FTP_ARCHIVOS_DESCUENTO','Ruta de los archivos de descuento en el servidor FTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubCategoriaParametro,prmDescripcion) VALUES ('FTP_ARCHIVOS_DESCUENTO_URL_RESULTADOS','/subsidios/resultadosdescuentos/espejo/',0,'FTP_ARCHIVOS_DESCUENTO','Ruta de los archivos de descuento generados');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','integracionasopagos','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF11','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.77.187.13/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.77.187.38:8282/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','Admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','Asdf1234$','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://genesys.heinsohn.com.co:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://genesys.heinsohn.com.co:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_SERVIDOR','10.77.187.13','Host donde están desplegados los servicios en JBOSS EAP');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('SERVICIOS_PUERTO','8181','Puerto donde escuchan los servicios en JBOSS EAP');

--changeset dasanchez:06 context:asopagos_confa runOnChange:true
--comment: Configuracion del ambiente asopagos_confa
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','CONFA',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','MANIZALES',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','CALDAS',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Cra 25 Calle 50',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','57(6)8783111',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','890806490-5',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','fc360d0a-165b-435b-940c-e3593c2d94dd',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.asopagos.com',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','a25863d9-9d6e-414c-926e-7934cbd7e0b4',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','814d2376-5847-44da-a3ea-32c4751fe559',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','17',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','soporte.ti@asopagos.com',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','RWU4DjifCrlC4vGGxj+FWw==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.gmail.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','25',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','5m',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','5m',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','48886d02-b8ea-46b0-a5c9-281c80029158_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','0c67fc05-63a2-4ce9-8fb6-686e477fd05c_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','FUNCIONALES','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF11','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.0.1.4/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.0.1.5:8080/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','SK-[:gq{1S','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://pruebasconfa.eastus2.cloudapp.azure.com:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://pruebasconfa.eastus2.cloudapp.azure.com:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');

--changeset dasanchez:07 context:asopagos_funcional runOnChange:true
--comment: Configuracion del ambiente asopagos_funcional
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','CONFA',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','MANIZALES',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','CALDAS',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Cra 25 Calle 50',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','57(6)8783111',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','890806490-5',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','fc360d0a-165b-435b-940c-e3593c2d94dd',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.asopagos.com',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','a25863d9-9d6e-414c-926e-7934cbd7e0b4',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','814d2376-5847-44da-a3ea-32c4751fe559',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','17',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','soporte.ti@asopagos.com',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','RWU4DjifCrlC4vGGxj+FWw==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.gmail.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','25',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','48886d02-b8ea-46b0-a5c9-281c80029158_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','0c67fc05-63a2-4ce9-8fb6-686e477fd05c_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','FUNCIONALES','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF11','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.0.1.8/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.0.1.5:8080/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','SK-[:gq{1S','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://comfa.eastus2.cloudapp.azure.com:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://comfa.eastus2.cloudapp.azure.com:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');

--changeset dasanchez:08 context:asopagos_subsidio runOnChange:true
--comment: Configuracion del ambiente asopagos_subsidio
DELETE FROM Parametro;
DELETE FROM Constante;
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NOMBRE_CCF','CONFA',0,'CAJA_COMPENSACION','Corresponde  al nombre de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CIUDAD_CCF','MANIZALES',0,'CAJA_COMPENSACION','Corresponde a la ciudad de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DEPARTAMENTO_CCF','CALDAS',0,'CAJA_COMPENSACION','Corresponde al departamento de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('DIRECCION_CCF','Cra 25 Calle 50',0,'CAJA_COMPENSACION','Corresponde a la dirección de la caja de compensación actual. Utilizadoen los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TELEFONO_CCF','57(6)8783111',0,'CAJA_COMPENSACION','Corresponde al teléfono de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIPO_ID_CCF','NIT',0,'CAJA_COMPENSACION','Corresponde al tipo de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('NUMERO_ID_CCF','890806490-5',0,'CAJA_COMPENSACION','Corresponde al número de identificación de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_DE_LA_CCF','fc360d0a-165b-435b-940c-e3593c2d94dd',0,'CAJA_COMPENSACION','Corresponde al id en el ECM del logo de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('WEB_CCF','www.asopagos.com',0,'CAJA_COMPENSACION','Corresponde al sitio web de la caja de la caja de compensación actual. Utilizado en los comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('LOGO_SUPERSERVICIOS','a25863d9-9d6e-414c-926e-7934cbd7e0b4',0,'VALOR_GLOBAL_NEGOCIO','Corresponde al id en el ECM del logo de la superintendencia de servicios');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('FIRMA_RESPONSABLE_CCF','814d2376-5847-44da-a3ea-32c4751fe559',0,'CAJA_COMPENSACION','Corresponde al id en el ECM de la firma del responsable de la caja de compensación actual. Utilizado en comunicados');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al cargo que tiene el representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('RESPONSABLE_NOVEDADES_CCF','libardo_ramirez',0,'CAJA_COMPENSACION','Corresponde al username del representante legal de la caja');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_EXPIRACION_ENLACE','1d',0,'VALOR_GLOBAL_TECNICO','Corresponde al tiempo de expiración del enlace web');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_MUNI_ID','001',0,'CAJA_COMPENSACION','Código DANE del municipio de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('CAJA_COMPENSACION_DEPTO_ID','17',0,'CAJA_COMPENSACION','Código DANE del departamento de la CCF');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.user','soporte.ti@asopagos.com',0,'MAIL_SMTP','Cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.password','RWU4DjifCrlC4vGGxj+FWw==',0,'MAIL_SMTP','Contraseña de la cuenta de correo desde la cual se envian las notificaciones');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.host','smtp.gmail.com',0,'MAIL_SMTP','Nombre del servidor SMTP usado para enviar los correos electronicos');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('mail.smtp.port','25',0,'MAIL_SMTP','Puerto de conexión al servidor SMTP');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_IMPRIMIR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('112_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los empleadores que se afilian vía web para llenar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('122_CORREGIR_INFORMACION_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores dependientes para corregir la información de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_ABRIR_LINK_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para diligenciar el formulario de afiliación');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('123_DILIGENCIAR_FORMULARIO_TIMER','1d',0,'EJECUCION_TIMER','Tiempo limite que tienen los trabajadores independientes para usar el token de acceso');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('TIEMPO_INACTIVAR_CUENTA','2592000000',0,'EJECUCION_TIMER','Corresponde al tiempo limite para inactivar una cuenta de usuario despues de la desafiliación de un empleador');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EXCEL_CARGUE_MASIVO_122','48886d02-b8ea-46b0-a5c9-281c80029158_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de Excel para el cargue múltiple del proceso de afiliación masiva 1.2.2');
INSERT Parametro (prmNombre,prmValor,prmCargaInicio,prmSubcategoriaParametro,prmDescripcion) VALUES ('ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122','0c67fc05-63a2-4ce9-8fb6-686e477fd05c_1.0',0,'VALOR_GLOBAL_NEGOCIO','Identificador de la plantilla de ejemplo para el Excel de cargue múltiple del proceso de afiliación masiva 1.2.2');

INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_SITE','FUNCIONALES','Nombre del SITE en el ECM para la caja de compensación');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_ID','1','Es el id en la solución genesys para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('CAJA_COMPENSACION_CODIGO','CCF11','Es el código en pila para la caja de compensación actual');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('BPMS_BUSINESS_CENTRAL_ENDPOINT','http://10.0.1.10/business-central','Endpoint donde se encuentran disponibles los servicios del bpms');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_HOST','http://10.0.1.5:8080/alfresco','Endpoint donde se encuentran disponibles los servicios del gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_USERNAME','admin','Nombre de usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('ECM_PASSWORD','SK-[:gq{1S','Contraseña del usuario usado para conectarse con el gestor documental');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('KEYCLOAK_ENDPOINT','http://10.0.1.10:8082/auth/realms/{realm}','Endpoint donde se encuentran disponibles los servicios de keycloak');
INSERT Constante (cnsNombre,cnsValor,cnsDescripcion) VALUES ('IDM_SERVER_URL','http://10.0.1.10:8082/auth/','Endpoint donde se encuentran disponibles los servicios de keycloak');
