--liquibase formatted sql

--changeset atoro:01
--comment: Insercion en la tabla Novedad
--Novedades
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarPersonaNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','GENERAL','com.asopagos.convertidores.persona.ActualizarBeneficiarioNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','GENERAL','com.asopagos.convertidores.persona.ActualizarBeneficiarioNovedadPersona');
INSERT Novedad (novPuntoResolucion,novTipoTransaccion,novTipoNovedad,novRutaCualificada) VALUES ('BACK','DESACTIVAR_ACTIVAR_GRUPO_FAMILIAR_INEMBARGABLE_GRUPO_FAMILIAR','GENERAL','com.asopagos.convertidores.persona .ActualizarGrupoFamiliarNovedadPersona');

--changeset atoro:02
--comment: Insercion en la tabla ValidacionProceso
--PARA HABILITADORES
-- Novedad 97. Activación/Desactivación de condición cabeza de hogar - Pensionado pensión familiar
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FAMILIAR_PRESENCIAL','VALIDACION_ESTADO_AFILIADO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_SOLTERO_VIUDO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FAMILIAR_WEB','VALIDACION_ESTADO_AFILIADO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FAMILIAR_WEB','VALIDACION_AFILIADO_SOLTERO_VIUDO','PENSION_FAMILIAR',1,'ACTIVO');

-- Novedad 98. Cambio de estado civil - Trabajador dependiente
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');

-- Novedad 99. Cambio de estado civil - Independiente
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');

-- Novedad 100. Cambio de estado civil - Pensionado fidelidad 25 años
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_AFILIADO_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');

-- Novedad 101. Cambio de estado civil - Pensionado más de 1,5 SM y 0,6%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');

-- Novedad 102. Cambio de estado civil - Pensionado más de 1,5 SM y 2%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');

-- Novedad 103. Cambio de estado civil - Pensionado menos de 1,5 SM y 0%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');

-- Novedad 104. Cambio de estado civil - Pensionado menos de 1,5 SM y 0,6%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');

-- Novedad 105. Cambio de estado civil - Pensionado menos de 1,5 SM y 2%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');

-- Novedad 106. Cambio de estado civil - Pensionado pensión familiar
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_AFILIADO_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');

-- Novedad 107. Cambio de estado civil - Beneficiario Cónyuge 
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NOVEDAD_CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','NOVEDAD_CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_AFILIADO_ACTIVO','CONYUGE',1,'ACTIVO');

--PARA VALIDACIONES DE REGLAS DE NEGOCIO 
-- Novedad 98. Cambio de estado civil - Trabajador dependiente
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_PENSIONADO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_EXISTENCIA_PERSONA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_EMPLEADOR','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_ESTADO_CONYUGE','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_PENSIONADO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_DEPENDIENTE',1,'ACTIVO');

-- Novedad 99. Cambio de estado civil - Independiente
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_PENSIONADO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_EXISTENCIA_PERSONA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_EMPLEADOR','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_ESTADO_CONYUGE','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_PENSIONADO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_AFILIADO_ACTIVO','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_INDEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA','TRABAJADOR_INDEPENDIENTE',1,'ACTIVO');

-- Novedad 100. Cambio de estado civil - Pensionado fidelidad 25 años
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_25_ANIOS_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_EXISTENCIA_PERSONA','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_FALLECIDA','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_EMPLEADOR','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_ESTADO_CONYUGE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_AFILIADO_ACTIVO','FIDELIDAD_25_ANIOS',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_25_ANIOS_WEB','VALIDACION_PERSONA_FALLECIDA','FIDELIDAD_25_ANIOS',1,'ACTIVO');

-- Novedad 101. Cambio de estado civil - Pensionado más de 1,5 SM y 0,6%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_EXISTENCIA_PERSONA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_EMPLEADOR','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_ESTADO_CONYUGE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_6_WEB','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');

-- Novedad 102. Cambio de estado civil - Pensionado más de 1,5 SM y 2%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_EXISTENCIA_PERSONA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_EMPLEADOR','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_ESTADO_CONYUGE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_APORTES_3_PERIODOS','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_OTRO_PARENTESCO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_PRESENCIAL ','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_EXISTENCIA_PERSONA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_EMPLEADOR','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_ESTADO_CONYUGE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_AFILIADO_ACTIVO','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MAS_1_5SM_0_2_WEB','VALIDACION_PERSONA_FALLECIDA','MAS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');

-- Novedad 103. Cambio de estado civil - Pensionado menos de 1,5 SM y 0%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_POR_CIENTO',1,'ACTIVO');

-- Novedad 104. Cambio de estado civil - Pensionado menos de 1,5 SM y 0,6%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_0_6_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_0_6_POR_CIENTO',1,'ACTIVO');

-- Novedad 105. Cambio de estado civil - Pensionado menos de 1,5 SM y 2%
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_EXISTENCIA_PERSONA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_EMPLEADOR','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_ESTADO_CONYUGE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_AFILIADO_ACTIVO','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_MENOS_1_5SM_2_WEB','VALIDACION_PERSONA_FALLECIDA','MENOS_1_5_SM_2_POR_CIENTO',1,'ACTIVO');

-- Novedad 106. Cambio de estado civil - Pensionado pensión familiar
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_EXISTENCIA_PERSONA','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_FALLECIDA','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_EMPLEADOR','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_ESTADO_CONYUGE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_AFILIADO_ACTIVO','PENSION_FAMILIAR',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_PENSION_FAMILIAR_WEB','VALIDACION_PERSONA_FALLECIDA','PENSION_FAMILIAR',1,'ACTIVO');

-- Novedad 107. Cambio de estado civil - Beneficiario Cónyuge 
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_EXISTENCIA_PERSONA','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_EMPLEADOR','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_ESTADO_CONYUGE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_PENSIONADO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_APORTES_3_PERIODOS','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_OTRO_PARENTESCO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_AFILIADO_ACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CAMBIO_ESTADO_CIVIL_CONYUGE_PRESENCIAL','VALIDACION_PERSONA_FALLECIDA','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_EXISTENCIA_PERSONA','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_FALLECIDA','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_EMPLEADOR','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_ESTADO_CONYUGE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_PENSIONADO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_AFILIADO_TRABAJADOR_DEPENDIENTE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_AFILIADO_TRABAJADOR_INDEPENDIENTE','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_OTRO_PARENTESCO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_CONYUGE_EMPLEADOR','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_AFILIADO_CON_CONYUGE_ACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_AFILIADO_ACTIVO','CONYUGE',1,'ACTIVO');
INSERT ValidacionProceso (vapProceso,vapBloque,vapValidacion,vapObjetoValidacion,vapOrden,vapEstadoProceso) VALUES ('NOVEDADES_PERSONAS_WEB','CAMBIO_ESTADO_CIVIL_CONYUGE_WEB','VALIDACION_PERSONA_FALLECIDA','CONYUGE',1,'ACTIVO');

--changeset jocampo-jzambrano:03
--comment: Script generado para el reporte de de entidades pagadores para las altas y retiros
INSERT FILEDEFINITIONTYPE (ID,DESCRIPTION,NAME) VALUES ('1','Estructura de los registros está dada para el convenio de la caja de compensación Confa y Colpensiones.','Estructura Solicitud de Alta');
INSERT FILEDEFINITION (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,COMPRESSALL,COMPRESSEACHFILE,ENCRYPTEDFILEEXTENSION,ENCRYPTERCLASS,FINALCONDITIONSCLASS,NEXTLINESEPARATOR,SIGNEDFILEEXTENSION,SIGNERCLASS,FILEDEFINITIONTYPE_ID,FILELOCATION_ID) VALUES ('1',',',null,null,'.','0','0',null,null,null,'\r\n',null,null,'1',null);

INSERT LINECATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,PAGINATED,QUERY,QUERYTYPE) VALUES ('1','com.asopagos.entidades.pagadoras.dto.EstructuraSolicitudAltaRetiroDataLine','Estructura Solicitud de Alta','Estructura Solicitud de Alta',null,'0',null,null);
INSERT LINEDEFINITION (ID,GENERATELINEFOOTER,GENERATERHEADERLINE,LINEORDER,NUMBERGROUP,REQUIRED,FILEDEFINITION_ID,LINECATALOG_ID) VALUES ('1','0','0','1',null,'1','1','1');

INSERT FIELDCATALOG (ID,DATATYPE,DESCRIPTION,MAXDECIMALSIZE,MINDECIMALSIZE,NAME,PAGINATED,QUERY,ROUNDMODE,IDLINECATALOG) VALUES ('1','STRING','No. Afiliación',null,null,'numeroAfiliacion',null,null,null,'1');
INSERT FIELDCATALOG (ID,DATATYPE,DESCRIPTION,MAXDECIMALSIZE,MINDECIMALSIZE,NAME,PAGINATED,QUERY,ROUNDMODE,IDLINECATALOG) VALUES ('2','STRING','No. de Documento',null,null,'nroDocumento',null,null,null,'1');
INSERT FIELDCATALOG (ID,DATATYPE,DESCRIPTION,MAXDECIMALSIZE,MINDECIMALSIZE,NAME,PAGINATED,QUERY,ROUNDMODE,IDLINECATALOG) VALUES ('3','STRING','NIT. de Entidad',null,null,'nitDeEntidad',null,null,null,'1');
INSERT FIELDCATALOG (ID,DATATYPE,DESCRIPTION,MAXDECIMALSIZE,MINDECIMALSIZE,NAME,PAGINATED,QUERY,ROUNDMODE,IDLINECATALOG) VALUES ('4','STRING','Tipo Novedad',null,null,'tipoNovedad',null,null,null,'1');

INSERT FIELDDEFINITION (ID,INITIALPOSITION,FINALPOSITION,LABEL,FIELDORDER,FORMATDATE,FOOTEROPERATION,GENERATEEVIDENCE,FIELDCATALOG_ID,LINEDEFINITION_ID) VALUES ('1',1,13,'No. Afiliación','1',null,'NONE','0','1','1');
INSERT FIELDDEFINITION (ID,INITIALPOSITION,FINALPOSITION,LABEL,FIELDORDER,FORMATDATE,FOOTEROPERATION,GENERATEEVIDENCE,FIELDCATALOG_ID,LINEDEFINITION_ID) VALUES ('2',13,25,'No. de Documento','2',null,'NONE','0','2','1');
INSERT FIELDDEFINITION (ID,INITIALPOSITION,FINALPOSITION,LABEL,FIELDORDER,FORMATDATE,FOOTEROPERATION,GENERATEEVIDENCE,FIELDCATALOG_ID,LINEDEFINITION_ID) VALUES ('3',25,34,'NIT. de Entidad','3',null,'NONE','0','3','1');
INSERT FIELDDEFINITION (ID,INITIALPOSITION,FINALPOSITION,LABEL,FIELDORDER,FORMATDATE,FOOTEROPERATION,GENERATEEVIDENCE,FIELDCATALOG_ID,LINEDEFINITION_ID) VALUES ('4',34,35,'Tipo Novedad','4',null,'NONE','0','4','1');






