data:
  wildfly-swarm-messaging.yaml: |-
    servicelocator.type: KUBERNETES
    gestor-cache: SERVICIO
    swarm:
      undertow:
        servers:
          default-server:
            http-listeners:
              default:
                max-post-size: 104857600
      transactions:
        socket-binding: txn-recovery-environment
        status-socket-binding: txn-status-manager
        default-timeout: 7200
      datasources:
        data-sources:
          asopagosDS:
            driver-name: sqlserver
            connection-url: ${url.core}
            user-name: ${user.core}
            password: ${password.core}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter

          asopagosAudDS:
            driver-name: sqlserver
            connection-url: ${url.aud}
            user-name: ${user.aud}
            password: ${password.aud}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
          asopagosSecurityDS:
            driver-name: sqlserver
            connection-url: ${url.security}
            user-name: ${user.security}
            password: ${password.security}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
          pilaDS:
            driver-name: sqlserver
            connection-url: ${url.pila}
            user-name: ${user.pila}
            password: ${password.pila}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
          subsidioDS:
            driver-name: sqlserver
            connection-url: ${url.subsidio}
            user-name: ${user.subsidio}
            password: ${password.subsidio}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
          reportesDS:
            driver-name: sqlserver
            connection-url: ${url.reportes}
            user-name: ${user.reportes}
            password: ${password.reportes}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
          bpmsDS:
            driver-name: sqlserver
            connection-url: ${url.bpms}
            user-name: ${user.bpms}
            password: ${password.bpms}
            pool-prefill: true
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 10000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            stale-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.novendor.AlwaysStaleConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter                
      deployment:
        org.apache.activemq:activemq-rar.rar:

      resource-adapters:
        resource-adapters:
          activemq-rar:
            # This is not the physical jar name, but the maven coordinates (without version!)
            archive: activemq-rar.rar
            transaction-support: LocalTransaction
            config-properties:
              ServerUrl:
                value: failover:tcp://activemq:61616
              UserName:
                value: admin
              Password:
                value: admin
              UseInboundSession:
                value: false

            connection-definitions:
                ConnectionFactory:
                    jndi-name: ConnectionFactory
                    class-name: org.apache.activemq.ra.ActiveMQManagedConnectionFactory
                    enabled: true
                    min-pool-size: 1
                    max-pool-size: 100
                    pool-prefill: false
                    same-rm-override: false
                    use-java-context: true

            admin-objects:
                GestorDocumentalExternoQueue:
                    class-name: org.apache.activemq.command.ActiveMQQueue
                    jndi-name: jms/queue/GestorDocumentalExternoQueue
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: GestorDocumentalExternoQueue
                        
      ejb3:
        default-resource-adapter-name: activemq-rar.rar
        default-mdb-instance-pool: mdb-strict-max-pool

      ee:
        annotation-property-replacement: true
        default-bindings:
          jms-connection-factory: java:/ConnectionFactory

      messaging-activemq:
        servers:
          default:
            active: false
            connection-factories:
              InVmConnectionFactory:
                block-on-acknowledge: true
                entries:
                - "java:/ArtemisConnectionFactory"

      jca:
        archive-validation:
          enabled: false

      logging:
        loggers:
          com.asopagos:
            level: DEBUG