--liquibase formatted sql

--changeset Heinsohn:1 stripComments:true

-- Creación de Códigos CIUU

INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0111','Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0112','Cultivo de arroz.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0113','Cultivo de hortalizas, raíces y tubérculos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0114','Cultivo de tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0115','Cultivo de plantas textiles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0119','Otros cultivos transitorios n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0121','Cultivo de frutas tropicales y subtropicales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0122','Cultivo de plátano y banano.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0123','Cultivo de café.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0124','Cultivo de caña de azúcar.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0125','Cultivo de flor de corte.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0126','Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0127','Cultivo de plantas con las que se preparan bebidas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0128','Cultivo de especias y de plantas aromáticas y medicinales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0129','Otros cultivos permanentes n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0130','Propagación de plantas (actividades de los viveros, excepto viveros forestales).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0141','Cría de ganado bovino y bufalino.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0142','Cría de caballos y otros equinos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0143','Cría de ovejas y cabras.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0144','Cría de ganado porcino.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0145','Cría de aves de corral.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0149','Cría de otros animales n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0150','Explotación mixta (agrícola y pecuaria).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0161','Actividades de apoyo a la agricultura.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0162','Actividades de apoyo a la ganadería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0163','Actividades posteriores a la cosecha.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0164','Tratamiento de semillas para propagación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0170','Caza ordinaria y mediante trampas y actividades de servicios conexas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0210','Silvicultura y otras actividades forestales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0220','Extracción de madera.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0230','Recolección de productos forestales diferentes a la madera.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0240','Servicios de apoyo a la silvicultura.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0311','Pesca marítima.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0312','Pesca de agua dulce.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0321','Acuicultura marítima.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0322','Acuicultura de agua dulce.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0510','Extracción de hulla (carbón de piedra).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0520','Extracción de carbón lignito.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0610','Extracción de petróleo crudo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0620','Extracción de gas natural.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0710','Extracción de minerales de hierro.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0721','Extracción de minerales de uranio y de torio.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0722','Extracción de oro y otros metales preciosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0723','Extracción de minerales de níquel.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0729','Extracción de otros minerales metalíferos no ferrosos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0811','Extracción de piedra, arena, arcillas comunes, yeso y anhidrita.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0812','Extracción de arcillas de uso industrial, caliza, caolín y bentonitas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0820','Extracción de esmeraldas, piedras preciosas y semipreciosas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0891','Extracción de minerales para la fabricación de abonos y productos químicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0892','Extracción de halita (sal).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0899','Extracción de otros minerales no metálicos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0910','Actividades de apoyo para la extracción de petróleo y de gas natural.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0990','Actividades de apoyo para otras actividades de explotación de minas y canteras.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1011','Procesamiento y conservación de carne y productos cárnicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1012','Procesamiento y conservación de pescados, crustáceos y moluscos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1020','Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1030','Elaboración de aceites y grasas de origen vegetal y animal.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1040','Elaboración de productos lácteos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1051','Elaboración de productos de molinería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1052','Elaboración de almidones y productos derivados del almidón.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1061','Trilla de café.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1062','Descafeinado, tostión y molienda del café.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1063','Otros derivados del café.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1071','Elaboración y refinación de azúcar.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1072','Elaboración de panela.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1081','Elaboración de productos de panadería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1082','Elaboración de cacao, chocolate y productos de confitería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1083','Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1084','Elaboración de comidas y platos preparados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1089','Elaboración de otros productos alimenticios n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1090','Elaboración de alimentos preparados para animales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1101','Destilación, rectificación y mezcla de bebidas alcohólicas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1102','Elaboración de bebidas fermentadas no destiladas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1103','Producción de malta, elaboración de cervezas y otras bebidas malteadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1104','Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1200','Elaboración de productos de tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1311','Preparación e hilatura de fibras textiles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1312','Tejeduría de productos textiles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1313','Acabado de productos textiles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1391','Fabricación de tejidos de punto y ganchillo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1392','Confección de artículos con materiales textiles, excepto prendas de vestir.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1393','Fabricación de tapetes y alfombras para pisos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1394','Fabricación de cuerdas, cordeles, cables, bramantes y redes.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1399','Fabricación de otros artículos textiles n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1410','Confección de prendas de vestir, excepto prendas de piel.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1420','Fabricación de artículos de piel.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1430','Fabricación de artículos de punto y ganchillo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1511','Curtido y recurtido de cueros; recurtido y teñido de pieles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1512','Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1513','Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1521','Fabricación de calzado de cuero y piel, con cualquier tipo de suela.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1522','Fabricación de otros tipos de calzado, excepto calzado de cuero y piel.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1523','Fabricación de partes del calzado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1610','Aserrado, acepillado e impregnación de la madera.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1620','Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1630','Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1640','Fabricación de recipientes de madera.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1690','Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1701','Fabricación de pulpas (pastas) celulósicas; papel y cartón.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1702','Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1709','Fabricación de otros artículos de papel y cartón.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1811','Actividades de impresión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1812','Actividades de servicios relacionados con la impresión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1820','Producción de copias a partir de grabaciones originales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1910','Fabricación de productos de hornos de coque.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1921','Fabricación de productos de la refinación del petróleo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('1922','Actividad de mezcla de combustibles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2011','Fabricación de sustancias y productos químicos básicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2012','Fabricación de abonos y compuestos inorgánicos nitrogenados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2013','Fabricación de plásticos en formas primarias.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2014','Fabricación de caucho sintético en formas primarias.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2021','Fabricación de plaguicidas y otros productos químicos de uso agropecuario.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2022','Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2023','Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2029','Fabricación de otros productos químicos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2030','Fabricación de fibras sintéticas y artificiales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2100','Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2211','Fabricación de llantas y neumáticos de caucho');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2212','Reencauche de llantas usadas');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2219','Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2221','Fabricación de formas básicas de plástico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2229','Fabricación de artículos de plástico n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2310','Fabricación de vidrio y productos de vidrio.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2391','Fabricación de productos refractarios.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2392','Fabricación de materiales de arcilla para la construcción.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2393','Fabricación de otros productos de cerámica y porcelana.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2394','Fabricación de cemento, cal y yeso.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2395','Fabricación de artículos de hormigón, cemento y yeso.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2396','Corte, tallado y acabado de la piedra.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2399','Fabricación de otros productos minerales no metálicos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2410','Industrias básicas de hierro y de acero.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2421','Industrias básicas de metales preciosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2429','Industrias básicas de otros metales no ferrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2431','Fundición de hierro y de acero.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2432','Fundición de metales no ferrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2511','Fabricación de productos metálicos para uso estructural.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2512','Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2513','Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2520','Fabricación de armas y municiones.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2591','Forja, prensado, estampado y laminado de metal; pulvimetalurgia.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2592','Tratamiento y revestimiento de metales; mecanizado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2593','Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2599','Fabricación de otros productos elaborados de metal n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2610','Fabricación de componentes y tableros electrónicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2620','Fabricación de computadoras y de equipo periférico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2630','Fabricación de equipos de comunicación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2640','Fabricación de aparatos electrónicos de consumo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2651','Fabricación de equipo de medición, prueba, navegación y control.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2652','Fabricación de relojes.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2660','Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2670','Fabricación de instrumentos ópticos y equipo fotográfico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2680','Fabricación de medios magnéticos y ópticos para almacenamiento de datos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2711','Fabricación de motores, generadores y transformadores eléctricos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2712','Fabricación de aparatos de distribución y control de la energía eléctrica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2720','Fabricación de pilas, baterías y acumuladores eléctricos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2731','Fabricación de hilos y cables eléctricos y de fibra óptica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2732','Fabricación de dispositivos de cableado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2740','Fabricación de equipos eléctricos de iluminación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2750','Fabricación de aparatos de uso doméstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2790','Fabricación de otros tipos de equipo eléctrico n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2811','Fabricación de motores, turbinas, y partes para motores de combustión interna.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2812','Fabricación de equipos de potencia hidráulica y neumática.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2813','Fabricación de otras bombas, compresores, grifos y válvulas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2814','Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2815','Fabricación de hornos, hogares y quemadores industriales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2816','Fabricación de equipo de elevación y manipulación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2817','Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2818','Fabricación de herramientas manuales con motor.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2819','Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2821','Fabricación de maquinaria agropecuaria y forestal.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2822','Fabricación de máquinas formadoras de metal y de máquinas herramienta.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2823','Fabricación de maquinaria para la metalurgia.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2824','Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2825','Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2826','Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2829','Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2910','Fabricación de vehículos automotores y sus motores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2920','Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('2930','Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3011','Construcción de barcos y de estructuras flotantes.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3012','Construcción de embarcaciones de recreo y deporte.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3020','Fabricación de locomotoras y de material rodante para ferrocarriles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3030','Fabricación de aeronaves, naves espaciales y de maquinaria conexa.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3040','Fabricación de vehículos militares de combate.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3091','Fabricación de motocicletas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3092','Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3099','Fabricación de otros tipos de equipo de transporte n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3110','Fabricación de muebles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3120','Fabricación de colchones y somieres.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3210','Fabricación de joyas, bisutería y artículos conexos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3220','Fabricación de instrumentos musicales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3230','Fabricación de artículos y equipo para la práctica del deporte.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3240','Fabricación de juegos, juguetes y rompecabezas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3250','Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3290','Otras industrias manufactureras n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3311','Mantenimiento y reparación especializado de productos elaborados en metal.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3312','Mantenimiento y reparación especializado de maquinaria y equipo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3313','Mantenimiento y reparación especializado de equipo electrónico y óptico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3314','Mantenimiento y reparación especializado de equipo eléctrico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3315','Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3319','Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3320','Instalación especializada de maquinaria y equipo industrial.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3511','Generación de energía eléctrica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3512','Transmisión de energía eléctrica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3513','Distribución de energía eléctrica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3514','Comercialización de energía eléctrica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3520','Producción de gas; distribución de combustibles gaseosos por tuberías.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3530','Suministro de vapor y aire acondicionado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3600','Captación, tratamiento y distribución de agua.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3700','Evacuación y tratamiento de aguas residuales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3811','Recolección de desechos no peligrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3812','Recolección de desechos peligrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3821','Tratamiento y disposición de desechos no peligrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3822','Tratamiento y disposición de desechos peligrosos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3830','Recuperación de materiales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('3900','Actividades de saneamiento ambiental y otros servicios de gestión de desechos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4111','Construcción de edificios residenciales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4112','Construcción de edificios no residenciales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4210','Construcción de carreteras y vías de ferrocarril.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4220','Construcción de proyectos de servicio público.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4290','Construcción de otras obras de ingeniería civil.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4311','Demolición.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4312','Preparación del terreno.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4321','Instalaciones eléctricas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4322','Instalaciones de fontanería, calefacción y aire acondicionado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4329','Otras instalaciones especializadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4330','Terminación y acabado de edificios y obras de ingeniería civil.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4390','Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4511','Comercio de vehículos automotores nuevos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4512','Comercio de vehículos automotores usados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4520','Mantenimiento y reparación de vehículos automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4530','Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4541','Comercio de motocicletas y de sus partes, piezas y accesorios.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4542','Mantenimiento y reparación de motocicletas y de sus partes y piezas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4610','Comercio al por mayor a cambio de una retribución o por contrata.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4620','Comercio al por mayor de materias primas agropecuarias; animales vivos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4631','Comercio al por mayor de productos alimenticios.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4632','Comercio al por mayor de bebidas y tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4641','Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4642','Comercio al por mayor de prendas de vestir.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4643','Comercio al por mayor de calzado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4644','Comercio al por mayor de aparatos y equipo de uso doméstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4645','Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4649','Comercio al por mayor de otros utensilios domésticos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4651','Comercio al por mayor de computadores, equipo periférico y programas de informática.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4652','Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4653','Comercio al por mayor de maquinaria y equipo agropecuarios.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4659','Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4661','Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4662','Comercio al por mayor de metales y productos metalíferos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4663','Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4664','Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4665','Comercio al por mayor de desperdicios, desechos y chatarra.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4669','Comercio al por mayor de otros productos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4690','Comercio al por mayor no especializado.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4711','Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4719','Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4721','Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4722','Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4723','Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4724','Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4729','Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4731','Comercio al por menor de combustible para automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4732','Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4741','Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4742','Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4751','Comercio al por menor de productos textiles en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4752','Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4753','Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4754','Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4755','Comercio al por menor de artículos y utensilios de uso doméstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4759','Comercio al por menor de otros artículos domésticos en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4761','Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4762','Comercio al por menor de artículos deportivos, en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4769','Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4771','Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4772','Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4773','Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4774','Comercio al por menor de otros productos nuevos en establecimientos especializados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4775','Comercio al por menor de artículos de segunda mano.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4781','Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4782','Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4789','Comercio al por menor de otros productos en puestos de venta móviles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4791','Comercio al por menor realizado a través de internet.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4792','Comercio al por menor realizado a través de casas de venta o por correo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4799','Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4911','Transporte férreo de pasajeros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4912','Transporte férreo de carga.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4921','Transporte de pasajeros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4922','Transporte mixto.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4923','Transporte de carga por carretera.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('4930','Transporte por tuberías.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5011','Transporte de pasajeros marítimo y de cabotaje.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5012','Transporte de carga marítimo y de cabotaje.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5021','Transporte fluvial de pasajeros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5022','Transporte fluvial de carga.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5111','Transporte aéreo nacional de pasajeros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5112','Transporte aéreo internacional de pasajeros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5121','Transporte aéreo nacional de carga.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5122','Transporte aéreo internacional de carga.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5210','Almacenamiento y depósito.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5221','Actividades de estaciones, vías y servicios complementarios para el transporte terrestre.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5222','Actividades de puertos y servicios complementarios para el transporte acuático.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5223','Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5224','Manipulación de carga.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5229','Otras actividades complementarias al transporte.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5310','Actividades postales nacionales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5320','Actividades de mensajería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5511','Alojamiento en hoteles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5512','Alojamiento en apartahoteles.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5513','Alojamiento en centros vacacionales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5514','Alojamiento rural.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5519','Otros tipos de alojamientos para visitantes.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5520','Actividades de zonas de camping y parques para vehículos recreacionales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5530','Servicio por horas');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5590','Otros tipos de alojamiento n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5611','Expendio a la mesa de comidas preparadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5612','Expendio por autoservicio de comidas preparadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5613','Expendio de comidas preparadas en cafeterías.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5619','Otros tipos de expendio de comidas preparadas n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5621','Catering para eventos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5629','Actividades de otros servicios de comidas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5630','Expendio de bebidas alcohólicas para el consumo dentro del establecimiento.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5811','Edición de libros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5812','Edición de directorios y listas de correo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5813','Edición de periódicos, revistas y otras publicaciones periódicas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5819','Otros trabajos de edición.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5820','Edición de programas de informática (software).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5911','Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5912','Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5913','Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5914','Actividades de exhibición de películas cinematográficas y videos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('5920','Actividades de grabación de sonido y edición de música.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6010','Actividades de programación y transmisión en el servicio de radiodifusión sonora.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6020','Actividades de programación y transmisión de televisión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6110','Actividades de telecomunicaciones alámbricas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6120','Actividades de telecomunicaciones inalámbricas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6130','Actividades de telecomunicación satelital.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6190','Otras actividades de telecomunicaciones.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6201','Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6202','Actividades de consultoría informática y actividades de administración de instalaciones informáticas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6209','Otras actividades de tecnologías de información y actividades de servicios informáticos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6311','Procesamiento de datos, alojamiento (hosting) y actividades relacionadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6312','Portales web.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6391','Actividades de agencias de noticias.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6399','Otras actividades de servicio de información n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6411','Banco Central.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6412','Bancos comerciales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6421','Actividades de las corporaciones financieras.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6422','Actividades de las compañías de financiamiento.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6423','Banca de segundo piso.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6424','Actividades de las cooperativas financieras.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6431','Fideicomisos, fondos y entidades financieras similares.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6432','Fondos de cesantías.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6491','Leasing financiero (arrendamiento financiero).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6492','Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6493','Actividades de compra de cartera o factoring.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6494','Otras actividades de distribución de fondos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6495','Instituciones especiales oficiales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6499','Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6511','Seguros generales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6512','Seguros de vida.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6513','Reaseguros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6514','Capitalización.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6521','Servicios de seguros sociales de salud.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6522','Servicios de seguros sociales de riesgos profesionales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6531','Régimen de prima media con prestación definida (RPM).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6532','Régimen de ahorro individual (RAI).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6611','Administración de mercados financieros.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6612','Corretaje de valores y de contratos de productos básicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6613','Otras actividades relacionadas con el mercado de valores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6614','Actividades de las casas de cambio.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6615','Actividades de los profesionales de compra y venta de divisas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6619','Otras actividades auxiliares de las actividades de servicios financieros n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6621','Actividades de agentes y corredores de seguros');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6629','Evaluación de riesgos y daños, y otras actividades de servicios auxiliares');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6630','Actividades de administración de fondos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6810','Actividades inmobiliarias realizadas con bienes propios o arrendados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6820','Actividades inmobiliarias realizadas a cambio de una retribución o por contrata.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6910','Actividades jurídicas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('6920','Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7010','Actividades de administración empresarial.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7020','Actividades de consultaría de gestión.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7110','Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7120','Ensayos y análisis técnicos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7210','Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7220','Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7310','Publicidad.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7320','Estudios de mercado y realización de encuestas de opinión pública.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7410','Actividades especializadas de diseño.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7420','Actividades de fotografía.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7490','Otras actividades profesionales, científicas y técnicas n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7500','Actividades veterinarias.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7710','Alquiler y arrendamiento de vehículos automotores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7721','Alquiler y arrendamiento de equipo recreativo y deportivo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7722','Alquiler de videos y discos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7729','Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7730','Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7740','Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7810','Actividades de agencias de empleo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7820','Actividades de agencias de empleo temporal.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7830','Otras actividades de suministro de recurso humano.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7911','Actividades de las agencias de viaje.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7912','Actividades de operadores turísticos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('7990','Otros servicios de reserva y actividades relacionadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8010','Actividades de seguridad privada.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8020','Actividades de servicios de sistemas de seguridad.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8030','Actividades de detectives e investigadores privados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8110','Actividades combinadas de apoyo a instalaciones.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8121','Limpieza general interior de edificios.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8129','Otras actividades de limpieza de edificios e instalaciones industriales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8130','Actividades de paisajismo y servicios de mantenimiento conexos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8211','Actividades combinadas de servicios administrativos de oficina.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8219','Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8220','Actividades de centros de llamadas (Call center).');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8230','Organización de convenciones y eventos comerciales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8291','Actividades de agencias de cobranza y oficinas de calificación crediticia.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8292','Actividades de envase y empaque.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8299','Otras actividades de servicio de apoyo a las empresas n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8411','Actividades legislativas de la administración pública.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8412','Actividades ejecutivas de la administración pública.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8413','Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8414','Actividades reguladoras y facilitadoras de la actividad económica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8415','Actividades de los otros órganos de control.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8421','Relaciones exteriores.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8422','Actividades de defensa.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8423','Orden público y actividades de seguridad.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8424','Administración de justicia.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8430','Actividades de planes de seguridad social de afiliación obligatoria.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8511','Educación de la primera infancia.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8512','Educación preescolar.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8513','Educación básica primaria.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8521','Educación básica secundaria.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8522','Educación media académica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8523','Educación media técnica y de formación laboral.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8530','Establecimientos que combinan diferentes niveles de educación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8541','Educación técnica profesional.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8542','Educación tecnológica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8543','Educación de instituciones universitarias o de escuelas tecnológicas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8544','Educación de universidades.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8551','Formación académica no formal.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8552','Enseñanza deportiva y recreativa.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8553','Enseñanza cultural.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8559','Otros tipos de educación n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8560','Actividades de apoyo a la educación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8610','Actividades de hospitales y clínicas, con internación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8621','Actividades de la práctica médica, sin internación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8622','Actividades de la práctica odontológica.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8691','Actividades de apoyo diagnóstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8692','Actividades de apoyo terapéutico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8699','Otras actividades de atención de la salud humana.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8710','Actividades de atención residencial medicalizada de tipo general.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8720','Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8730','Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8790','Otras actividades de atención en instituciones con alojamiento');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8810','Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('8890','Otras actividades de asistencia social sin alojamiento.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9001','Creación literaria.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9002','Creación musical.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9003','Creación teatral.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9004','Creación audiovisual.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9005','Artes plásticas y visuales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9006','Actividades teatrales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9007','Actividades de espectáculos musicales en vivo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9008','Otras actividades de espectáculos en vivo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9101','Actividades de bibliotecas y archivos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9102','Actividades y funcionamiento de museos, conservación de edificios y sitios históricos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9103','Actividades de jardines botánicos, zoológicos y reservas naturales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9200','Actividades de juegos de azar y apuestas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9311','Gestión de instalaciones deportivas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9312','Actividades de clubes deportivos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9319','Otras actividades deportivas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9321','Actividades de parques de atracciones y parques temáticos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9329','Otras actividades recreativas y de esparcimiento n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9411','Actividades de asociaciones empresariales y de empleadores');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9412','Actividades de asociaciones profesionales');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9420','Actividades de sindicatos de empleados.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9491','Actividades de asociaciones religiosas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9492','Actividades de asociaciones políticas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9499','Actividades de otras asociaciones n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9511','Mantenimiento y reparación de computadores y de equipo periférico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9512','Mantenimiento y reparación de equipos de comunicación.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9521','Mantenimiento y reparación de aparatos electrónicos de consumo.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9522','Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9523','Reparación de calzado y artículos de cuero.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9524','Reparación de muebles y accesorios para el hogar.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9529','Mantenimiento y reparación de otros efectos personales y enseres domésticos.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9601','Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9602','Peluquería y otros tratamientos de belleza.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9603','Pompas fúnebres y actividades relacionadas.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9609','Otras actividades de servicios personales n.c.p.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9700','Actividades de los hogares individuales como empleadores de personal doméstico.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9810','Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9820','Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('9900','Actividades de organizaciones y entidades extraterritoriales.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0010','Asalariados: Personas naturales cuyos ingresos provengan de la relación laboral, legal o reglamentaria o tenga su origen en ella.');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0081','Personas Naturales sin Actividad Económica');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0082','Personas Naturales Subsidiadas por Terceros');
INSERT CodigoCIIU (ciiCodigo, ciiDescripcion) VALUES ('0090','Rentistas de Capital, solo para personas naturales.');
GO