--liquibase formatted sql

--changeset Heinsohn:1 stripComments:true

-- Creación de las cajas de compensación disponibles (se utilizan para indicar de qué otras cajas provienen los afiliados)


-- Inserción de datos
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (1, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CALDAS'), 'GENERADA','CONFAMILIARES');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (1, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ANTIOQUIA'), 'GENERADA','CAMACOL');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (1, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ANTIOQUIA'), 'GENERADA','COMFENALCO ANTIOQUIA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (1, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ANTIOQUIA'), 'GENERADA','COMFAMA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ATLÁNTICO'), 'GENERADA','CAJACOPI ATLANTICO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ATLÁNTICO'), 'GENERADA','COMBARRANQUILLA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ATLÁNTICO'), 'GENERADA','COMFAMILIAR DEL ATLANTICO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'BOLÍVAR'), 'GENERADA','COMFENALCO CARTAGENA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'BOLÍVAR'), 'GENERADA','COMFAMILIAR CARTAGENA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'BOYACÁ'), 'GENERADA','COMFABOY');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CAQUETÁ'), 'GENERADA','COMFACA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CAUCA'), 'GENERADA','COMFACAUCA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CESAR'), 'GENERADA','COMFACESAR');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CÓRDOBA'), 'GENERADA','COMFACOR');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CUNDINAMARCA'), 'GENERADA','CAFAM');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CUNDINAMARCA'), 'GENERADA','COLSUBSIDIO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CUNDINAMARCA'), 'GENERADA','COMPENSAR');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CUNDINAMARCA'), 'GENERADA','COMFACUNDI');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CHOCÓ'), 'GENERADA','COMFACHOCO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'LA GUAJIRA'), 'GENERADA','COMFAMILIAR de la GUAJIRA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'HUILA'), 'GENERADA','COMFAMILIAR HUILA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'MAGDALENA'), 'GENERADA','CAJAMAG');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'META'), 'GENERADA','COFREM');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'NARIÑO'), 'GENERADA','COMFAMILIAR NARIÑO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'NORTE DE SANTANDER'), 'GENERADA','COMFAORIENTE');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'NORTE DE SANTANDER'), 'GENERADA','COMFANORTE');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'SANTANDER'), 'GENERADA','CAFABA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'SANTANDER'), 'GENERADA','CAJASAN');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'SANTANDER'), 'GENERADA','COMFENALCO SANTANDER');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'SUCRE'), 'GENERADA','COMFASUCRE');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'QUINDIO'), 'GENERADA','COMFENALCO QUINDIO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'RISARALDA'), 'GENERADA','COMFAMILIAR RISARALDA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'TOLIMA'), 'GENERADA','CAFASUR');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'TOLIMA'), 'GENERADA','COMFATOLIMA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'TOLIMA'), 'GENERADA','COMFENALCO TOLIMA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'VALLE DEL CAUCA'), 'GENERADA','COMFENALCO VALLE');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'VALLE DEL CAUCA'), 'GENERADA','COMFANDI');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'PUTUMAYO'), 'GENERADA','COMFAMILIAR PUTUMAYO');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'), 'GENERADA','CAJASAI');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'AMAZONAS'), 'GENERADA','CAFAMAZ');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'ARAUCA'), 'GENERADA','COMFIAR');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'VAUPÉS'), 'GENERADA','COMCAJA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'VICHADA'), 'GENERADA','COMCAJA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'GUAVIARE'), 'GENERADA','COMCAJA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'GUAINÍA'), 'GENERADA','COMCAJA');
INSERT CajaCompensacion  (ccfSocioAsopagos, ccfHabilitado, ccfDepartamento, ccfMetodoGeneracionEtiquetas, ccfNombre) VALUES (0, 1, (SELECT dpto.depId FROM [dbo].[Departamento] dpto WHERE dpto.depNombre = 'CASANARE'), 'GENERADA','COMFACASANARE');
GO