--liquibase formatted sql

--changeset Heinsohn:1 stripComments:true

-- Creación de relación entre tipoSolicitante y RequisitoDocumentales

-- Se ingresa datos transaccion nueva afilicion
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Acta de posesión del representante legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite condición de Ley 1429 de 2010'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite condición de Ley 1429 de 2010'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del documento que certifique la personería jurídica'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del documento de identidad del administrador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia acta Asamblea/Acto de nombramiento administrador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia resolución Ministerio con régimen compensaciones y trabajo asociado'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia de los Estatutos'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'La relación de los cooperados (y opcional: de sus beneficiarios)'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento acredita existencia/representación legal o Personería Jurídica'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de afiliación'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_NUEVA_AFILIACION'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
-- Se ingresa datos transaccion reintegro
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Acta de posesión del representante legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite condición de Ley 1429 de 2010'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona jurídica'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite condición de Ley 1429 de 2010'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Persona natural'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Empleador de servicio doméstico'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del documento que certifique la personería jurídica'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del documento de identidad del administrador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia acta Asamblea/Acto de nombramiento administrador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Propiedad horizontal'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia resolución Ministerio con régimen compensaciones y trabajo asociado'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia de los Estatutos'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'La relación de los cooperados (y opcional: de sus beneficiarios)'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Cooperativa o pre-cooperativa de trabajo asociado'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento acredita existencia/representación legal o Personería Jurídica'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Entidad sin ánimo de lucro'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia del RUT'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Copia documento identidad representante legal/empleador'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Documento que acredite la existencia y/o representación legal'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Información de nómina de los trabajadores a afiliar'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OPCIONAL',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Paz y salvo caja de compensación afiliación anterior'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));
INSERT INTO RequisitoTipoSolicitante(rtsEstado,rtsRequisito,rtsTipoSolicitante)VALUES('OBLIGATORIO',(SELECT req.reqId FROM Requisito req WHERE req.reqDescripcion = 'Formulario de solicitud de reintegro'AND req.reqTipoTransaccion ='AFILIACION_EMPLEADORES_PRESENCIAL_REINTEGRO'),(SELECT tipSol.tsoId FROM TipoSolicitante tipSol WHERE tipSol.tsoDescripcion = 'Organización religiosa o parroquia'));


GO