--liquibase formatted sql

--changeset clmarin:01
--comment: Actualizacion en la tabla PlantillaComunicado
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccion}</br>${telefono}</br>${tipoIdentificacionEmpleador}</br>${numeroIdentificacionEmpleador}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${tipoIdCcf}</br>${numeroIdCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${firmaResponsableCcf}</br>${responsableCcf}</br>${cargoResponsableCcf}</p>' WHERE pcoEtiqueta = 'NTF_INT_AFL';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombresYApellidosAfiliado}</br>${direccion}</br>${telefono}</br>${resultadoNovedad}</br>${solicitudDeNovedadad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${firmaResponsableCcf}</br>${responsableCcf}</br>${cargoResponsableCcf}</p>' WHERE pcoEtiqueta = 'NTF_NVD_PERS';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccion}</br>${telefono}</br>${resultadoNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${tipoIdCcf}</br>${numeroIdCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_NVD_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombresYApellidosAfiliado}</br>${direccion}</br>${telefono}</br>${solicitudDeNovedadad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${firmaResponsableCcf}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_RAD_NVD_PER';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccion}</br>${telefono}</br>${resultadoNovedad}</br>${nombreEmpresa}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${tipoIdCcf}</br>${numeroIdCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${firmaResponsableCcf}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_RAD_NVD_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccion}</br>${telefono}</br>${productoNoConformeNoSubsanado}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${tipoIdCcf}</br>${numeroIdCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'RCHZ_NVD_EMP_PROD_NSUBLE';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombresYApellidosAfiliado}</br>${direccion}</br>${telefono}</br>${resultadoNovedad}</br>${productoNoConformeNoSubsanado}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${tipoIdCcf}</br>${numeroIdCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'RCHZ_NVD_PERS_PROD_NSUBLE';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'CNFR_RET_APRT';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${novedadEmpleador}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'DSTMTO_NVD_RET_APRT';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${resultadoNovedad}</br>${solicitudDeNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_APRB_NVD_WEB_TRB_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${resultadoNovedad}</br>${solicitudDeNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'RCHZ_NVD_WEB_TRB_REP_POR_EMP_POR_PROD_NSUBLE';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${resultadoNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_PARA_SBC_NVD_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${resultadoNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_PARA_SBC_NVD_PERS';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${solicitudDeNovedad}</br>${resultadoNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_NVD_WEB_TRB_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${novedadEmpleador}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_PARA_SBC_NVD_WEB_TRB_EMP';
UPDATE PlantillaComunicado SET pcoCuerpo = '<p>${ciudadSolicitud}</br>${fechaDelSistema}</br>${nombreYApellidosRepresentanteLegal}</br>${razonSocial/Nombre}</br>${direccionEmpleador}</br>${telefonoEmpleador}</br>${solicitudDeNovedad}</br>${resultadoNovedad}</br>${nombreCcf}</br>${logoDeLaCcf}</br>${departamentoCcf}</br>${ciudadCcf}</br>${direccionCcf}</br>${telefonoCcf}</br>${webCcf}</br>${logoSuperservicios}</br>${responsableNovedadesCcf}</br>${cargoResponsableNovedadesCcf}</p>' WHERE pcoEtiqueta = 'NTF_RAD_NVD_WEB_TRB_EMP';

--changeset clmarin:02
--comment: Actualizacion en la tabla PlantillaComunicado
UPDATE PlantillaComunicado SET pcoPie='${responsableCcf}' WHERE pcoEtiqueta='CRT_ACP_IDPE'  
UPDATE PlantillaComunicado SET pcoPie='${responsableCcf}' WHERE pcoEtiqueta='CRT_BVD_IDPE' 
UPDATE PlantillaComunicado SET pcoPie='${responsableCcf}' WHERE pcoEtiqueta='CRT_ACP_PNS' 
UPDATE PlantillaComunicado SET pcoPie='${responsableCcf}' WHERE pcoEtiqueta='CRT_BVD_PNS' 

--changeset atoro:03
--comment: Eliminación en la tabla ValidacionProceso
DELETE ValidacionProceso WHERE vapbloque='NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_TRABAJADOR_INDEPENDIENTE';

--changeset atoro:04
--comment: Cambio de tamaño en campo de la tabla DetalleDatosRegistroValidacion
ALTER TABLE DetalleDatosRegistroValidacion ALTER COLUMN ddrValorDetalle varchar (150); 

