--liquibase formatted sql

--changeset abaquero:01
--comment: Eliminacion de campos en la tabla Aportante, AporteDetalladoSimulado y Cotizante
ALTER TABLE Aportante DROP COLUMN apoValorMoraAportante
ALTER TABLE AporteDetalladoSimulado DROP COLUMN adsValorTotalAporteObligatorio
ALTER TABLE Cotizante DROP COLUMN cotValorMoraCotizante

--changeset edelgado:02
--comment: Actualizacion del campo pcoCuerpo en PlantillaComunicado
UPDATE PlantillaComunicado SET pcoCuerpo = '<p style="text-align: justify;">${contenido}</p><p style="text-align: justify;">El suscrito <strong>${nombres}</strong> con <strong>${tipoIdentificacion}</strong> No. <strong>${numeroIdentificacion}</strong> &nbsp;en mi nombre propio como persona natural o en mi car&aacute;cter como representante legal de este empleador,solicito a <strong>${nombreCcf}</strong>,la afiliaci&oacute;n del empleador que represento y si fuera aceptado me comprometo a cumplir y respetar todas las normas,as&iacute; como las disposiciones legales que se refieren al subsidio familiar.</p><p style="text-align: justify;">Acepto &nbsp;de antemano que la violaci&oacute;n por parte del empleador de cualquiera de estas normas, dar&aacute; derecho a <strong>${nombreCcf}</strong> para ordenar la expulsi&oacute;n del empleador afiliado. La responsabilidad en cuanto al subsidio familiar,queda limitada para la caja desde el momento de la afiliaci&oacute;n y pago de aportes por parte del empleador,hasta que el empleador sea desafiliado por cualquier motivo. &nbsp;</p><p><strong>Declaraci&oacute;n:</strong></p><p style="text-align: justify;">En calidad de representante legal del empleador declaro que la Informaci&oacute;n registrada en este formulario es cierta y tiene por objeto solicitar la afiliaci&oacute;n a <strong>${nombreCcf}</strong>. En caso de ser aceptados como afiliados nos comprometemos a cumplir y a respetar la legislaci&oacute;n del Subsidio Familiar,al igual que los estatutos y reglamentos de <strong>${nombreCcf}</strong>.</p><p style="text-align: justify;">Cualquier falsedad u omisi&oacute;n voluntaria conlleva a la anulaci&oacute;n de esta solicitud.<input id="aceptacionDeclaracion" name="aceptacionDeclaracion" type="checkbox" /></p><p>&nbsp;</p><p>___________________________________</p><p><strong>${nombres}</strong><br />${tipoIdentificacion} ${numeroIdentificacion}</p><p>&nbsp;</p>' WHERE pcoEtiqueta = 'ACRDS_TRMS_CDNES_WEB'

--changeset jusanchez:03
--comment: Cambio de tipo de dato cecGradoAvance en ConsolaEstadoCargueMasivo
ALTER TABLE ConsolaEstadoCargueMasivo ALTER COLUMN cecGradoAvance numeric(3,3) NOT NULL

--changeset clmarin:04
--comment: Actualizacion en PlantillaComunicado
-- Actualización de los campos pcoMensaje y pcoCuerpo de la tabla PlantillaComunicado para la etiqueta CRT_BVD_IDPE
UPDATE PlantillaComunicado SET pcoMensaje='Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>', pcoCuerpo ='<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>' WHERE pcoEtiqueta = 'CRT_BVD_IDPE';
-- Actualización de los campos pcoMensaje y pcoCuerpo de la tabla PlantillaComunicado para la etiqueta CRT_BVD_PNS
UPDATE PlantillaComunicado SET pcoMensaje='Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>', pcoCuerpo = '<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>' WHERE pcoEtiqueta = 'CRT_BVD_PNS';
-- Actualización de los campos pcoMensaje y pcoCuerpo de la tabla PlantillaComunicado para la etiqueta CRT_ACP_IDPE
UPDATE PlantillaComunicado SET pcoMensaje='Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>', pcoCuerpo ='<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>' WHERE pcoEtiqueta = 'CRT_ACP_IDPE'
-- Actualización de los campos pcoMensaje y pcoEncabezado de la tabla PlantillaComunicado para la etiqueta CRT_ACP_PNS
UPDATE PlantillaComunicado SET pcoCuerpo='<p style="text-align: justify;">El suscrito <strong>${nombreYApellidosRepresentanteLegal}</strong>  &nbsp;en mi nombre propio como persona natural o en mi car&aacute;cter como representante legal de este empleador, solicito a <strong>${nombreCcf}</strong>, la afiliaci&oacute;n del empleador que represento y si fuera aceptado me comprometo a cumplir y respetar todas las normas, as&iacute; como las disposiciones legales que se refieren al subsidio familiar.</p><p><strong>Declaraci&oacute;n:</strong></p><p style="text-align: justify;">Cualquier falsedad u omisi&oacute;n voluntaria conlleva a la anulaci&oacute;n de esta solicitud.<input id="aceptacionDeclaracion" name="aceptacionDeclaracion" type="checkbox" /></p><p>&nbsp;</p><p>___________________________________</p><p><strong>${nombreYApellidosRepresentanteLegal}</strong></p><p>&nbsp;</p><br/>${direccionRepresentanteLegal}<br/>${telefonoRepresentanteLegal}<br/>${ciudadRepresentanteLegal}<br/>${sede}<br/>${direccionSede}<br/>${parametroValorCuotaMonetariaUrbano}<br/>${parametroValorCuotaMonetariaRural}<br/><br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>', pcoEncabezado ='<p>${ciudadSede}&nbsp;</p><p>${fechaDelSistema}</p>' WHERE pcoEtiqueta = 'CRT_ACP_PNS'
-- Actualización del campo pcoCuerpo de la tabla PlantillaComunicado para la etiqueta RCHZ_AFL_DPT_PROD_NSUB_TRB
UPDATE PlantillaComunicado SET pcoCuerpo = '${ciudadSolicitud}<br/>${fechaDelSistema}<br/>${nombresYApellidosDelAfiliadoPrincipal}<br/>${direccionDeResidencia}<br/>${telefono}<br/>${nombreCcf}<br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>' WHERE pcoEtiqueta = 'RCHZ_AFL_DPT_PROD_NSUB_TRB' 

--changeset clmarin:05
--comment: Actualizacion en CONSTANTE
UPDATE CONSTANTE SET cnsValor='libardo_ramirez' WHERE cnsNombre='RESPONSABLE_CCF';

