metadata:
  name: wildfly-swarm-topic-asopagos
data:
  wildfly-swarm-topic-asopagos.yaml: | 
    servicelocator.type: KUBERNETES
    gestor-cache: SERVICIO
    org.apache.activemq.SERIALIZABLE_PACKAGES: java.lang,javax.security,java.util,org.apache.activemq,org.fusesource.hawtbuf,com.thoughtworks.xstream.mapper,com.asopagos
    property.mdb.mails.queue.name: MailsQueue
    ccf.clientId: ${ccf.clientId}
    ccf.codigo: ${ccf.codigo}
    org.apache.coyote.http11.Http11Protocol.MAX_HEADER_SIZE: 32768
    com.arjuna.ats.arjuna.allowMultipleLastResources: true
    jboss.as.management.blocking.timeout: 900
    property.mdb.mails.maxsessions: 3
    swarm:
      transactions:
        socket-binding: txn-recovery-environment
        status-socket-binding: txn-status-manager
        default-timeout: 7200
      datasources:
        data-sources:
          asopagosDS:
            driver-name: sqlserver
            connection-url: ${url.core}
            user-name: ${user.core}
            password: ${password.core}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true

      deployment:
        org.apache.activemq:activemq-rar.rar:

      resource-adapters:
        resource-adapters:
          activemq-rar:
            # This is not the physical jar name, but the maven coordinates (without version!)
            archive: activemq-rar.rar
            transaction-support: LocalTransaction
            config-properties:
              ServerUrl:
                value: failover:tcp://${activemq.ip}:61616
              UserName:
                value: admin
              Password:
                value: admin
              UseInboundSession:
                value: false

            connection-definitions:
                ConnectionFactory:
                    jndi-name: ConnectionFactory
                    class-name: org.apache.activemq.ra.ActiveMQManagedConnectionFactory
                    enabled: true
                    min-pool-size: 1
                    max-pool-size: 20
                    pool-prefill: false
                    same-rm-override: false
                    use-java-context: true

            admin-objects:
                ReplicacionParametrosAsopagosTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionParametrosAsopagosTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionParametrosAsopagosTopic
                ReplicacionParametrosSubisidioTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionParametrosSubisidioTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionParametrosSubisidioTopic
                ReplicacionValoresAnualesTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionValoresAnualesTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionValoresAnualesTopic
                ReplicacionParametrosSubsidioCajaTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionParametrosSubsidioCajaTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionParametrosSubsidioCajaTopic
                ReplicacionCajasActualizarListaEspecialRevisionTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionCajasActualizarListaEspecialRevisionTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionCajasActualizarListaEspecialRevisionTopic
                ReplicacionCajasInsertarListaEspecialRevisionTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionCajasInsertarListaEspecialRevisionTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionCajasInsertarListaEspecialRevisionTopic
                ReplicacionInsercionListaEspecialRevisionTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionInsercionListaEspecialRevisionTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionInsercionListaEspecialRevisionTopic
                ReplicacionCambioEstadoListaEspecialRevisionTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionCambioEstadoListaEspecialRevisionTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionCambioEstadoListaEspecialRevisionTopic
                ReplicacionListaChequeoTopic:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ReplicacionListaChequeoTopic
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ReplicacionListaChequeoTopic
                ListaChequeoCreacionClasificacion:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ListaChequeoCreacionClasificacion
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ListaChequeoCreacionClasificacion
                ListaChequeoActualizacionClasificacion:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ListaChequeoActualizacionClasificacion
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ListaChequeoActualizacionClasificacion
                ListaChequeoCreacionClasificacionPorCaja:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ListaChequeoCreacionClasificacionPorCaja
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ListaChequeoCreacionClasificacionPorCaja
                ListaChequeoActualizacionClasificacionPorCaja:
                    class-name: org.apache.activemq.command.ActiveMQTopic
                    jndi-name: topic/ListaChequeoActualizacionClasificacionPorCaja
                    use-java-context: true
                    config-properties:
                      PhysicalName: 
                        value: ListaChequeoActualizacionClasificacionPorCaja

      ejb3:
        default-resource-adapter-name: activemq-rar.rar
        default-mdb-instance-pool: mdb-strict-max-pool

      ee:
        annotation-property-replacement: true
        default-bindings:
          jms-connection-factory: java:/ConnectionFactory

      messaging-activemq:
        servers:
          default:
            active: false
            connection-factories:
              InVmConnectionFactory:
                block-on-acknowledge: true
                entries:
                - "java:/ArtemisConnectionFactory"

      jca:
        archive-validation:
          enabled: false

      logging:
        loggers:
          com.asopagos:
            level: DEBUG