metadata:
  name: wildfly-swarm-solicitudes
data:
  wildfly-swarm-solicitudes.yaml: | 
    servicelocator.type: KUBERNETES
    gestor-cache: SERVICIO
    org.apache.coyote.http11.Http11Protocol.MAX_HEADER_SIZE: 32768
    com.arjuna.ats.arjuna.allowMultipleLastResources: true
    jboss.as.management.blocking.timeout: 900
    swarm:
      undertow:
        servers:
          default-server:
            http-listeners:
              default:
                max-post-size: 104857600
      transactions:
        socket-binding: txn-recovery-environment
        status-socket-binding: txn-status-manager
        default-timeout: 7200
      datasources:
        data-sources:
          asopagosDS:
            driver-name: sqlserver
            connection-url: ${url.core}
            user-name: ${user.core}
            password: ${password.core}
            min-pool-size: 5
            max-pool-size: 100
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
      ee:
        jboss.naming.context.java.jboss.ee.concurrency.executor.solicitudes:
          jndi-name: java:jboss/ee/concurrency/executor/solicitudes
          context-service: default
          hung-task-threshold: 0
          core-threads: 10
          max-threads: 200
          keepalive-time: 0
          queue-length: 100000
      logging:
        loggers:
          com.asopagos:
            level: INFO
      