metadata:
  name: wildfly-swarm-ee
data:
  wildfly-swarm-ee.yaml: | 
    servicelocator.type: KUBERNETES
    gestor-cache: SERVICIO
    org.apache.coyote.http11.Http11Protocol.MAX_HEADER_SIZE: 32768
    com.arjuna.ats.arjuna.allowMultipleLastResources: true
    jboss.as.management.blocking.timeout: 900    
    swarm:
      undertow:
        servers:
          default-server:
            http-listeners:
              default:
                max-post-size: 104857600
      transactions:
        socket-binding: txn-recovery-environment
        status-socket-binding: txn-status-manager
        default-timeout: 7200
      datasources:
        data-sources:
          asopagosDS:
            driver-name: sqlserver
            connection-url: ${url.core}
            user-name: ${user.core}
            password: ${password.core}
            min-pool-size: 5
            max-pool-size: 200
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          asopagosAudDS:
            driver-name: sqlserver
            connection-url: ${url.aud}
            user-name: ${user.aud}
            password: ${password.aud}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          asopagosSecurityDS:
            driver-name: sqlserver
            connection-url: ${url.security}
            user-name: ${user.security}
            password: ${password.security}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          pilaDS:
            driver-name: sqlserver
            connection-url: ${url.pila}
            user-name: ${user.pila}
            password: ${password.pila}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          subsidioDS:
            driver-name: sqlserver
            connection-url: ${url.subsidio}
            user-name: ${user.subsidio}
            password: ${password.subsidio}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          reportesDS:
            driver-name: sqlserver
            connection-url: ${url.reportes}
            user-name: ${user.reportes}
            password: ${password.reportes}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
          bpmsDS:
            driver-name: sqlserver
            connection-url: ${url.bpms}
            user-name: ${user.bpms}
            password: ${password.bpms}
            min-pool-size: 5
            max-pool-size: 10
            pool-prefill: false
            pool-use-strict-min: false
            flush-strategy: EntirePool
            use-fast-fail: false
            check-valid-connection-sql: select 1
            background-validation: true        
            validate-on-match: false
            background-validation-millis: 80000
            valid-connection-checker-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exception-sorter-class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            set-tx-query-timeout: false
            blocking-timeout-wait-millis: 10000
            idle-timeout-minutes: 2
            query-timeout: 0
            use-try-lock: 0
            allocation-retry: 3
            allocation-retry-wait-millis: 4000
            use-ccm: true
      ee:
        annotation-property-replacement: true
        context-services:
          default:
            jndi-name: java:jboss/ee/concurrency/context/default
        default-bindings-service:
          managed-thread-factory: java:jboss/ee/concurrency/factory/default
        managed-executor-services:
          jboss.naming.context.java.jboss.ee.concurrency.executor.validaciones:
            jndi-name: java:jboss/ee/concurrency/executor/validaciones
            context-service: default
            hung-task-threshold: 180000
            core-threads: 20
            max-threads: 200
            keepalive-time: 10000
            queue-length: 100000
        managed-scheduled-executor-services:
          default:
            jndi-name: java:jboss/ee/concurrency/scheduler/default
            context-service: default
            hung-task-threshold: 60000
            keepalive-time: 3000
        default-bindings:
          context-service: java:jboss/ee/concurrency/context/default
          datasource: java:jboss/datasources/ExampleDS
          managed-executor-service: java:jboss/ee/concurrency/executor/default
          managed-scheduled-executor-service: java:jboss/ee/concurrency/scheduler/default
          managed-thread-factory: java:jboss/ee/concurrency/factory/default
      logging:
        loggers:
          com.asopagos:
            level: INFO
