--liquibase formatted sql

--changeset jzambrano:01
--comment: Insercion de registros en la tabla ValidacionProceso
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-2','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-3','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-4','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-5','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-6','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-104-7','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('121-107-2','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('122-359-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_DEPENDIENTE_WEB','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('122-361-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_DEPENDIENTE_WEB','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('122-369-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('122-363-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_DEPENDIENTE_WEB','ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('123-379-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_INDEPENDIENTE_WEB','ACTIVO',1,'PENSIONADO',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('123-379-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_INDEPENDIENTE_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('123-374-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_INDEPENDIENTE_WEB','ACTIVO',1,'PENSIONADO',0);
INSERT ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES ('123-374-1','VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION','AFILIACION_INDEPENDIENTE_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0);