apiVersion: v1
data:
  api_gateway.conf: |-
    log_format roles  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" "$http_permissionsapp"';

    server {
        client_header_buffer_size 1k;
        large_client_header_buffers 4 16k;
        listen 443 ssl;
        server_name  nginxgatewaypruebas.asopagos.com;
        ssl_certificate     /etc/ssl/asp.crt;
        ssl_certificate_key /etc/ssl/asp.key;
        #server_name  genesys-api;
        # set client body size to 2M #
        client_max_body_size 400M;
        #charset koi8-r;
        error_log /usr/local/nginx/logs/api_gateway_error.log  debug;
        #access_log  logs/host.access.log  main;
        location /comfaboy/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxpluscomfaboy.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }

        location /asopagos/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://nginxplusasopagos.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }


        location /comfacauca/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxpluscomfacauca.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }

        location /comfasucre/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxpluscomfasucre.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }
        location /confa/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxplusconfa.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }
        location /cajasan/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxcajasanplus.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }
        location /comfenalcoantioquia/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxpluscomfenalcoantioquia.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }
        location /genesyspruebas/ {
            auth_jwt "Root";
            auth_jwt_key_file /etc/nginx/secret.json;
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,PermissionsApp' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Content-Length' '0';
                add_header 'Content-Type' 'text/plain';
                return 204;
            }
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://nginxplusgenesyspruebas.asopagos.com/;
            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE,PUT,OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization,Origin,cache-control,if-modified-since,pragma,Profile,real_ip_header,PermissionsApp' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Disposition,draw,totalrecords' always;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'real_ip_header' 'X-Originating-IP' always;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy.log;
            access_log /usr/local/nginx/logs/proxy-access-comfaboy-roles.log roles;
        }
        location /api/ {
            api write=on;
        }

        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }

        # Redirect requests made to the old dashboard
        location = / {
            return 301 /dashboard.html;
        }

        location = /status.html {
            return 301 /dashboard.html;
        }

    }
kind: ConfigMap
metadata:
  creationTimestamp: "2018-10-10T15:40:59Z"
  labels:
    app: nginx-plus-gateway
    group: com.asopagos.coreaas
    provider: fabric8
    version: 0.0.2-SNAPSHOT
  name: nginx-plus-gateway
  namespace: default
  resourceVersion: "724598499"
  uid: e2f6a81b-cca2-11e8-99fb-42010a800049
