--liquibase formatted sql

--changeset squintero:01
--comment: Se resuelve mantis #0224316
DELETE FROM ValidacionProceso WHERE vapBloque IN ('CONYUGE_LABORA_PRESENCIAL','CONYUGE_LABORA_WEB','CONYUGE_LABORA_DEPWEB') AND vapValidacion = 'VALIDACION_HIJO_2_GRUPOS_DISTINTOS_AFILIADOS';
DELETE FROM ValidacionProceso WHERE vapBloque IN ('CONYUGE_LABORA_PRESENCIAL','CONYUGE_LABORA_WEB','CONYUGE_LABORA_DEPWEB') AND vapValidacion = 'VALIDACION_TRABAJADOR_DEP_ASOCIADO_EMPLEADOR';

