--liquibase formatted sql

--changeset jocorrea:01
--comment: Se resuelve incidencia # 0225782
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion = 'CONYUGE';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_CONYUGE_WEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_WEB' AND vapObjetoValidacion = 'CONYUGE';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_DEPENDIENTE_WEB' AND vapObjetoValidacion = 'CONYUGE';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion = 'HIJO_BIOLOGICO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_WEB' AND vapObjetoValidacion = 'HIJO_BIOLOGICO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_DEPENDIENTE_WEB' AND vapObjetoValidacion = 'HIJO_BIOLOGICO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion = 'HIJASTRO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJASTRO_WEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_WEB' AND vapObjetoValidacion = 'HIJASTRO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_DEPENDIENTE_WEB' AND vapObjetoValidacion = 'HIJASTRO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HUERFANO_WEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_WEB' AND vapObjetoValidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_DEPENDIENTE_WEB' AND vapObjetoValidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion = 'HIJO_ADOPTIVO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_PERSONAS_WEB' AND vapObjetoValidacion = 'HIJO_ADOPTIVO';
DELETE FROM dbo.ValidacionProceso WHERE vapBloque = 'INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB' AND vapValidacion = 'VALIDACION_PERSONA_INCLUIDA_SOLICITUD' AND vapProceso = 'NOVEDADES_DEPENDIENTE_WEB' AND vapObjetoValidacion = 'HIJO_ADOPTIVO';
