--liquibase formatted sql

--changeset GLPI 50278
if not exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'RADICACIONES_PAGOS_BANCOS' and TABLE_SCHEMA = 'dbo')
begin
	CREATE TABLE [dbo].[RADICACIONES_PAGOS_BANCOS](
		[RADI_ID] [int] IDENTITY(1,1) NOT NULL,
		[RADI_ID_ARCH] [int] NULL,
		[RADI_RADI] [varchar](200) NULL,
		[RADI_FECH] [date] NULL,
		[RADI_BANC_ORIG] [int] NULL,
	PRIMARY KEY CLUSTERED 
	(
		[RADI_ID] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
