--liquibase formatted sql

--changeset amarin:01
--comment:
ALTER TABLE ParametrizacionCondicionesSubsidio ADD pcsSumarSalarioConyugeBenPadre BIT;
ALTER TABLE ParametrizacionCondicionesSubsidio ADD pcsSumarSalarioConyugeBenHijo BIT;
ALTER TABLE ParametrizacionCondicionesSubsidio ADD pcsSumarSalarioConyugeBenHermanoHuerfano BIT;
ALTER TABLE aud.ParametrizacionCondicionesSubsidio_aud ADD pcsSumarSalarioConyugeBenPadre BIT;
ALTER TABLE aud.ParametrizacionCondicionesSubsidio_aud ADD pcsSumarSalarioConyugeBenHijo BIT;
ALTER TABLE aud.ParametrizacionCondicionesSubsidio_aud ADD pcsSumarSalarioConyugeBenHermanoHuerfano BIT;