IF EXISTS (
select * from ValidacionProceso
where vapBloque = 'NOVEDAD_CAMBIOS_CIERRE_FINANCIERO'
AND VAPVALIDACION != 'VALIDACION_ESTADO_HOGAR_CIERRE_FINANCIERO')

BEGIN

UPDATE ValidacionProceso
SET VAPVALIDACION = 'VALIDACION_ESTADO_HOGAR_CIERRE_FINANCIERO'
WHERE VAPBLOQUE = 'NOVEDAD_CAMBIOS_CIERRE_FINANCIERO'

END