--liquibase formatted sql

--changeset squintero:01
--comment:
ALTER TABLE RegistroInconsistenciaTarjeta ADD ritResultadoGestion varchar(100);

--changeset mamonroy:02
--comment:CCP1OCT2019[63]
DELETE FROM ValidacionProceso
WHERE vapBloque IN ('RETIRO_TRABAJADOR_DEPENDIENTE','RETIRO_TRABAJADOR_INDEPENDIENTE','RETIRO_PENSIONADO_25ANIOS','RETIRO_PENSIONADO_MAYOR_1_5SM_0_6','RETIRO_PENSIONADO_MAYOR_1_5SM_2','RETIRO_PENSIONADO_MENOR_1_5SM_0','RETIRO_PENSIONADO_MENOR_1_5SM_0_6','RETIRO_PENSIONADO_MENOR_1_5SM_2','RETIRO_PENSIONADO_PENSION_FAMILIAR')
AND vapvalidacion = 'VALIDACION_ESTADO_CONYUGE';
