--liquibase formatted sql

--changeset flopez:01
--comment: CC Novedades
INSERT INTO GradoAcademico ( graNombre, graNivelEducativo ) VALUES ('NINGUNO','PRIMERA_INFANCIA'),
('PRIMERO', 'BASICA_PRIMARIA_INCOMPLETA_ADULTOS'),
('SEGUNDO', 'BASICA_PRIMARIA_INCOMPLETA_ADULTOS'),
('TERCERO', 'BASICA_PRIMARIA_INCOMPLETA_ADULTOS'),
('CUARTO', 'BASICA_PRIMARIA_INCOMPLETA_ADULTOS'),
('QUINTO', 'BASICA_PRIMARIA_COMPLETA_ADULTOS'),
('SEXTO', 'BASICA_SECUNDARIA_INCOMPLETA_ADULTOS'),
('SEPTIMO', 'BASICA_SECUNDARIA_INCOMPLETA_ADULTOS'),
('OCTAVO', 'BASICA_SECUNDARIA_INCOMPLETA_ADULTOS'),
('NOVENO', 'BASICA_SECUNDARIA_COMPLETA_ADULTOS'),
('DECIMO', 'MEDIA INCOMPLETA ADULTOS'),
('ONCE', 'MEDIA_COMPLETA_ADULTOS');

--changeset flopez:02
--comment: CC Novedades
IF EXISTS (SELECT graID FROM GradoAcademico WHERE graNombre = 'DECIMO' AND graNivelEducativo = 'MEDIA INCOMPLETA ADULTOS') DELETE FROM GradoAcademico WHERE graNombre = 'DECIMO' AND graNivelEducativo = 'MEDIA INCOMPLETA ADULTOS';
IF NOT EXISTS (SELECT graID FROM GradoAcademico WHERE graNombre = 'DECIMO' AND graNivelEducativo = 'MEDIA_INCOMPLETA_ADULTOS')INSERT INTO GradoAcademico ( graNombre, graNivelEducativo ) VALUES ('DECIMO', 'MEDIA_INCOMPLETA_ADULTOS');
