--Eliminar validacion VALIDACION_ESTADO_CIVIL_AFILIADO--
IF EXISTS (
    SELECT 1 
    FROM ValidacionProceso
    WHERE vapBloque = 'NOVEDAD_ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL'
    AND vapValidacion = 'VALIDACION_ESTADO_CIVIL_AFILIADO'
)
BEGIN
    DELETE FROM ValidacionProceso
    WHERE vapBloque = 'NOVEDAD_ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL'
    AND vapValidacion = 'VALIDACION_ESTADO_CIVIL_AFILIADO';
END
