IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'medioTransferencia' AND COLUMN_NAME = 'mdtId' AND TABLE_SCHEMA = 'dbo')
BEGIN
	ALTER TABLE dbo.medioTransferencia ADD mdtId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioEfectivo' AND COLUMN_NAME = 'mdeId' AND TABLE_SCHEMA = 'dbo')
BEGIN
	ALTER TABLE dbo.MedioEfectivo ADD mdeId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioCheque' AND COLUMN_NAME = 'mecId' AND TABLE_SCHEMA = 'dbo')
BEGIN
	ALTER TABLE dbo.MedioCheque ADD mecId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioConsignacion' AND COLUMN_NAME = 'mcoId' AND TABLE_SCHEMA = 'dbo')
BEGIN
	ALTER TABLE dbo.MedioConsignacion ADD mcoId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioTarjeta' AND COLUMN_NAME = 'mtrId' AND TABLE_SCHEMA = 'dbo')
BEGIN
	ALTER TABLE dbo.MedioTarjeta ADD mtrId BIGINT IDENTITY(1,1) NOT NULL
END
--================================================================ TABLAS AUD

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'medioTransferencia_aud' AND COLUMN_NAME = 'mdtId' AND TABLE_SCHEMA = 'aud')
BEGIN
	ALTER TABLE aud.medioTransferencia_aud ADD mdtId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioEfectivo_aud' AND COLUMN_NAME = 'mdeId' AND TABLE_SCHEMA = 'aud')
BEGIN
	ALTER TABLE aud.MedioEfectivo_aud ADD mdeId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioCheque_aud' AND COLUMN_NAME = 'mecId' AND TABLE_SCHEMA = 'aud')
BEGIN
	ALTER TABLE aud.MedioCheque_aud ADD mecId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioConsignacion_aud' AND COLUMN_NAME = 'mcoId' AND TABLE_SCHEMA = 'aud')
BEGIN
	ALTER TABLE aud.MedioConsignacion_aud ADD mcoId BIGINT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MedioTarjeta_aud' AND COLUMN_NAME = 'mtrId' AND TABLE_SCHEMA = 'aud')
BEGIN
	ALTER TABLE aud.MedioTarjeta_aud ADD mtrId BIGINT IDENTITY(1,1) NOT NULL
END