UPDATE ValidacionProceso 
SET vapEstadoProceso = 'INACTIVO'
WHERE vapValidacion = 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO'
AND (vapBloque = 'CAMBIO_ESTADO_CIVIL_PERSONAS' OR vapBloque = 'CAMBIO_ESTADO_CIVIL_PERSONAS_WEB' 
OR vapBloque = 'CAMBIO_GENERO_PERSONAS' OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS_DEPWEB' 
OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS' OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS')
AND vapEstadoProceso = 'ACTIVO';

--ROLLBACK 
-- UPDATE ValidacionProceso 
-- SET vapEstadoProceso = 'ACTIVO'
-- WHERE vapValidacion = 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO'
-- AND (vapBloque = 'CAMBIO_ESTADO_CIVIL_PERSONAS' OR vapBloque = 'CAMBIO_ESTADO_CIVIL_PERSONAS_WEB' 
-- OR vapBloque = 'CAMBIO_GENERO_PERSONAS' OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS_DEPWEB' 
-- OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS' OR vapBloque = 'ACTUALIZACION_GRADO_CURSADO_PERSONAS')
-- AND vapEstadoProceso = 'INACTIVO';