--liquibase formatted sql
--changeset amarin:01
--comment: CC Fovis 31/07/2020
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-020-3','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-020-4','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-020-6','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-023-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-023-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-026-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-026-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-027-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-027-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-037-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('321-037-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('322-039-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('322-039-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('322-041-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('322-041-2','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('322-044-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','JEFE_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','ABUELO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISABUELO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','BISNIETO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CONYUGE_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','CUNIADO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HERMANO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJASTRO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_ADOPTIVO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','HIJO_BIOLOGICO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','MADRE_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','NIETO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','PADRE_MADRE_ADOPTANTE_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SOBRINO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','SUEGRO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','TIO_HOGAR',0),
('323-045-1','VALIDACION_MODALIDAD_ADQUISICION_VIVIENDA_USADA','POSTULACION_FOVIS_PRESENCIAL','ACTIVO','1','YERNO_HOGAR',0);


-- Actualiza el campo vapValidacion con la nueva validacion afiliado activo

--HU-321-020
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%321-020%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-321-023
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%321-023%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-321-026
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%321-026%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-321-027
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%321-027%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-321-037
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%321-037%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-322-039
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%322-039%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-322-041
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%322-041%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-322-044
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%322-044%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO'

--HU-323-045
UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO_DOS_POR_CIENTO'
WHERE vapBloque LIKE '%323-045%' AND vapValidacion LIKE 'VALIDACION_AFILIADO_ACTIVO';

--comment: Insercion de registros en la tabla ValidacionProceso - PROCESO 321-020-6 FOVIS
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-020-6','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-020-4','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-020-1','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

--321-023-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-023-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

--321-026-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-026-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

--321-027-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-027-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

--321-037-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('321-037-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

--322-039-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('322-039-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_WEB','ACTIVO',1,'JEFE_HOGAR',0);

--322-041-2
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('322-041-2','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_WEB','ACTIVO',1,'JEFE_HOGAR',0);

--322-044-1
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('322-044-1','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_WEB','ACTIVO',1,'JEFE_HOGAR',0);

--323-045-1
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES ('323-045-1','VALIDACION_MODALIDAD_MEJORA_VIVIENDA_SALUDABLE_JEFE_HOGAR','POSTULACION_FOVIS_PRESENCIAL','ACTIVO',1,'JEFE_HOGAR',0);

