IF not exists
(
    SELECT *
    FROM requisito
    WHERE reqDescripcion = 'Certificación medica EPS-IPS'
    or reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'
)
BEGIN

insert into requisito (reqDescripcion, reqEstado)values('Certificación medica EPS-IPS', 'HABILITADO')
insert into requisito (reqDescripcion, reqEstado)values('Declaración juramentada de no trabajo no ingresos', 'HABILITADO')


(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID')


--HIJO_ADOPTIVO
			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','ACTIVAR_BENEFICIO_HIJO_ADOPTIVO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','ACTIVAR_BENEFICIO_HIJO_ADOPTIVO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_ADOPTIVO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')



--PADRE


			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','ACTIVAR_BENEFICIARIO_PADRE_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','ACTIVAR_BENEFICIARIO_PADRE_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'PADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'PADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')


--HIJO BIOLOGICO

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','ACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','ACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJO_BIOLOGICO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

--MADRE 


			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','ACTIVAR_BENEFICIARIO_MADRE_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','ACTIVAR_BENEFICIARIO_MADRE_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'MADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'MADRE','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

--HIJASRTO


			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','ACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','ACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HIJASTRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HIJASTRO','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

--HUERFANO


			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_PRESENCIAL_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','ACTIVAR_BENEFICIARIO_HERMANO_HUERFANO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','ACTIVAR_BENEFICIARIO_HERMANO_HUERFANO_PRESENCIAL',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','REPORTE_INVALIDEZ_PERSONAS',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','REPORTE_INVALIDEZ_PERSONAS_WEB',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_PRESENCIAL_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_WEB_DEPENDIENTE_NUEVA_AFILIACION',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Certificación medica EPS-IPS'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')

			insert into RequisitoCajaClasificacion (rtsestado, rtsrequisito, rtsclasificacion,rtsTipoTransaccion, rtscajacompensacion, rtstextoayuda, rtstiporequisito)
			values ('OPCIONAL',(select reqId from requisito where reqDescripcion = 'Declaración juramentada de no trabajo no ingresos'),'HERMANO_HUERFANO_DE_PADRES','AFILIACION_PERSONAS_WEB_DEPENDIENTE_REINTEGRO',(select cnsValor from Constante where cnsNombre = 'CAJA_COMPENSACION_ID'),'pEdad entre 0 y 6 años cumplidos: OPCIONAL<br />Edad entre 7 y 17 años cumplidos: Tarjeta de identidad (OBLIGATORIO)<br />Edad igual o mayor a 18 años: Cédula de ciudadanía o Cédula de extranjería (OBLIGATORIO)<br />Se revisa:<br />-No debe tener tachones o enmendaduras<br />-El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación<br />-Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación<br />-La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación','ESTANDAR')
end