--liquibase formatted sql

--changeset mamonroy:01
--comment:CCP1_OCT2019[52]

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque = 'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS'
AND vapValidacion = 'VALIDACION_ESTADO_AFILIADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_CAMBIO_NOMBRE_APELLIDOS_PERSONAS','NOVEDAD_CAMBIO_NOMBRE_APELLIDOS_PERSONAS_WEB','NOVEDAD_CAMBIO_NOMBRE_APELLIDOS_PERSONAS_DEPWEB')
AND vapValidacion = 'VALIDACION_ESTADO_AFILIADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_REPORTE_FALLECIMIENTO_PERSONAS','NOVEDAD_REPORTE_FALLECIMIENTO_PERSONAS_WEB','NOVEDAD_REPORTE_FALLECIMIENTO_PERSONAS_DEPWEB')
AND vapValidacion = 'VALIDACION_ESTADO_AFILIADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_ESTADO_CCF_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_LICENCIA_MATERNIDAD_PATERNIDAD_LMA_PERSONA_PRESENCIAL','NOVEDAD_LICENCIA_MATERNIDAD_PATERNIDAD_LMA_PERSONA_WEB','NOVEDAD_LICENCIA_MATERNIDAD_PATERNIDAD_LMA_PERSONA_DEPWEB')
AND vapValidacion = 'VALIDACION_AFILIADO_ESTADO_NO_FORMALIZADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_ESTADO_CCF_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_INCAPACIDAD_TEMPORAL_ENFERMEDAD_GENERAL_IGE_PERSONA_PRESENCIAL','NOVEDAD_INCAPACIDAD_TEMPORAL_ENFERMEDAD_GENERAL_IGE_PERSONA_WEB','NOVEDAD_INCAPACIDAD_TEMPORAL_ENFERMEDAD_GENERAL_IGE_PERSONA_DEPWEB')
AND vapValidacion = 'VALIDACION_AFILIADO_ESTADO_NO_FORMALIZADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_CAMBIO_FECHA_EXPEDICION_DOCUMENTO_IDENTIDAD_PERSONA_PRESENCIAL','NOVEDAD_CAMBIO_FECHA_EXPEDICION_DOCUMENTO_IDENTIDAD_PERSONA_WEB','NOVEDAD_CAMBIO_FECHA_EXPEDICION_DOCUMENTO_IDENTIDAD_PERSONA_DEPWEB')
AND vapValidacion = 'VALIDACION_ESTADO_AFILIADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_CAMBIO_FECHA_NACIMIENTO_PERSONA_PRESENCIAL','NOVEDAD_CAMBIO_FECHA_NACIMIENTO_PERSONA_WEB','NOVEDAD_CAMBIO_FECHA_NACIMIENTO_PERSONA_DEPWEB')
AND vapValidacion = 'VALIDACION_ESTADO_AFILIADO';

UPDATE ValidacionProceso
SET vapValidacion = 'VALIDACION_DISTINTOS_ESTADOS_AFILIADO'
WHERE vapBloque IN ('NOVEDAD_ACTUALIZAR_INFORMACION_PADRE_MADRE_BIOLOGICO_PERSONA_PRESENCIAL','NOVEDAD_ACTUALIZAR_INFORMACION_PADRE_MADRE_BIOLOGICO_PERSONA_WEB','NOVEDAD_ACTUALIZAR_INFORMACION_PADRE_MADRE_BIOLOGICO_PERSONA_DEPWEB')
AND vapValidacion IS NULL;
