--liquibase formatted sql
--changeset eprocess:01
--comment: Inserta registro para GLPI 57808
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUENTAS_BANCARIAS'))
BEGIN
  CREATE TABLE CUENTAS_BANCARIAS
  (
    ID INT NOT NULL IDENTITY(1,1), 
    BANCO VARCHAR(200),
    TIPO VARCHAR(200),
    NUMERO_CUENTA VARCHAR(200),
    TIPO_RECAUDO VARCHAR(200),
    PRIMARY KEY(ID)
  )
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'APORTEGENERAL' AND  COLUMN_NAME = 'apgCuentaBancariaRecaudo') ALTER TABLE dbo.APORTEGENERAL ADD apgCuentaBancariaRecaudo int null;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'solicitudaporte' AND  COLUMN_NAME = 'soaCuentaBancariaRecaudo') ALTER TABLE dbo.solicitudaporte ADD soaCuentaBancariaRecaudo int null;
