--liquibase formatted sql

--changeset flopez:01
--comment:  Ajustes validaciones Novedad Cambio de Admon Subsidio CC637
UPDATE ValidacionProceso SET vapValidacion = 'VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO' WHERE vapBloque in ('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE', 'NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB')
AND vapValidacion IN ('VALIDACION_AFILIADO_ACTIVO')

UPDATE ValidacionProceso SET vapValidacion = 'VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS' WHERE vapBloque in ('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE', 'NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB')
AND vapValidacion IN ('VALIDACION_BENEFICIARIO_ACTIVO_DIF_CONYUGE')

UPDATE ValidacionProceso SET vapValidacion = 'VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO' WHERE vapBloque in ('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO', 'NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB')
AND vapValidacion IN ('VALIDACION_AFILIADO_ACTIVO')

UPDATE ValidacionProceso SET vapValidacion = 'VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS' WHERE vapBloque in ('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO', 'NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB')
AND vapValidacion IN ('VALIDACION_BENEFICIARIO_ACTIVO_DIF_CONYUGE')

INSERT INTO ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES 
('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_EXISTENCIA_PERSONA','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_HIJO_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_PADRE_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_APORTES_3_PERIODOS','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_PRESENCIAL','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_TIENE_NOVEDAD_PERSONA_EN_CURSO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_EXISTENCIA_PERSONA','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_HIJO_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_PADRE_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_PRESENCIAL','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_TIENE_NOVEDAD_PERSONA_EN_CURSO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)

INSERT INTO ValidacionProceso (vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa) VALUES 
('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_EXISTENCIA_PERSONA','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_HIJO_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_PADRE_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_APORTES_3_PERIODOS','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_PRESENCIAL','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_TIENE_NOVEDAD_PERSONA_EN_CURSO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS','NOVEDADES_PERSONAS_PRESENCIAL','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_EXISTENCIA_PERSONA','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_HIJO_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_PADRE_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_APORTES_3_PERIODOS','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_PRESENCIAL','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_TIENE_NOVEDAD_PERSONA_EN_CURSO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0)
,('NOVEDAD_CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS','NOVEDADES_PERSONAS_WEB','ACTIVO',1,'PENSIONADO',0);

--changeset flopez:02
--comment:  Eliminar Validación VALIDACION_MAYOR_18 CC642
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_CAMBIO_GENERO_PERSONAS' AND vapValidacion = 'VALIDACION_MAYOR_18';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_GENERO_PERSONAS' AND vapValidacion IN ('VALIDACION_MAYOR_18','VALIDACION_PERSONA_NO_MAYOR_15','VALIDACION_PERSONA_NO_MAYOR_14');

--changeset flopez:03
--comment:  Modificar Validaciones Traslado de Beneficiarios CC638
UPDATE ValidacionProceso set vapValidacion = 'VALIDACION_TRABAJADOR_AFILIADO_CUALQUIER_ESTADO' WHERE vapBloque = 'NOVEDAD_TRASLADO_BENEFICIARIO_GRUPO_FAMILIAR_AFILIADO_PERSONAS' AND vapValidacion = 'VALIDACION_AFILIADO_ACTIVO';
UPDATE ValidacionProceso set vapValidacion = 'VALIDACION_AFILIADO_GRUPO_FAMILIAR_BENEFICIARIOS' WHERE vapBloque = 'NOVEDAD_TRASLADO_BENEFICIARIO_GRUPO_FAMILIAR_AFILIADO_PERSONAS' AND vapValidacion = 'VALIDACION_GRUPO_FAMILIAR_MAS_UN_BENEF_ACTIVO';

--changeset flopez:04
--comment:  Inserta Validaciones para Inactivación de Beneficiarios y fecha de retiro CC72,73,74
INSERT INTO core.dbo.ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES('INACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'CONYUGE', 0)
,('INACTIVAR_BENEFICIARIO_CONYUGE_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'CONYUGE', 0)
,('INACTIVAR_BENEFICIARIO_CONYUGE_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'CONYUGE', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'HIJO_BIOLOGICO', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'HIJO_BIOLOGICO', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'HIJO_BIOLOGICO', 0)
,('INACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'HIJASTRO', 0)
,('INACTIVAR_BENEFICIARIO_HIJASTRO_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'HIJASTRO', 0)
,('INACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'HIJASTRO', 0)
,('INACTIVAR_BENEFICIARIO_HUERFANO_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'HERMANO_HUERFANO_DE_PADRES', 0)
,('INACTIVAR_BENEFICIARIO_HUERFANO_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'HERMANO_HUERFANO_DE_PADRES', 0)
,('INACTIVAR_BENEFICIARIO_HUERFANO_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'HERMANO_HUERFANO_DE_PADRES', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'HIJO_ADOPTIVO', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'HIJO_ADOPTIVO', 0)
,('INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'HIJO_ADOPTIVO', 0)
,('INACTIVAR_BENEFICIO_EN_CUSTODIA_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'BENEFICIARIO_EN_CUSTODIA', 0)
,('INACTIVAR_BENEFICIO_EN_CUSTODIA_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'BENEFICIARIO_EN_CUSTODIA', 0)
,('INACTIVAR_BENEFICIO_EN_CUSTODIA_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'BENEFICIARIO_EN_CUSTODIA', 0)
,('INACTIVAR_BENEFICIOS_PADRE_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PADRE', 0)
,('INACTIVAR_BENEFICIOS_PADRE_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'PADRE', 0)
,('INACTIVAR_BENEFICIOS_PADRE_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'PADRE', 0)
,('INACTIVAR_BENEFICIOS_MADRE_PRESENCIAL', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MADRE', 0)
,('INACTIVAR_BENEFICIOS_MADRE_WEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', 1, 'MADRE', 0)
,('INACTIVAR_BENEFICIOS_MADRE_DEPWEB', 'VALIDACION_BENEFICIARIO_ACTIVO_FECHA_RETIRO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', 1, 'MADRE', 0);

INSERT INTO core.dbo.ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES('RETIRO_TRABAJADOR_DEPENDIENTE', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'TRABAJADOR_DEPENDIENTE', 0)
,('RETIRO_TRABAJADOR_INDEPENDIENTE', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'TRABAJADOR_INDEPENDIENTE', 0)
,('RETIRO_PENSIONADO_25ANIOS', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'FIDELIDAD_25_ANIOS', 0)
,('RETIRO_PENSIONADO_MAYOR_1_5SM_0_6', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MAS_1_5_SM_0_6_POR_CIENTO', 0)
,('RETIRO_PENSIONADO_MAYOR_1_5SM_2', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MAS_1_5_SM_2_POR_CIENTO', 0)
,('RETIRO_PENSIONADO_MENOR_1_5SM_0', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MENOS_1_5_SM_0_POR_CIENTO', 0)
,('RETIRO_PENSIONADO_MENOR_1_5SM_0_6', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MENOS_1_5_SM_0_6_POR_CIENTO', 0)
,('RETIRO_PENSIONADO_MENOR_1_5SM_2', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'MENOS_1_5_SM_2_POR_CIENTO', 0)
,('RETIRO_PENSIONADO_PENSION_FAMILIAR', 'VALIDACION_TRABAJADOR_ACTIVO_FECHA_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSION_FAMILIAR', 0);
