--liquibase formatted sql

--changeset rarboleda:01
--comment: Se agregam cmapos a tabla MedioTransferencia y MedioTransferencia_aud
ALTER TABLE MedioTransferencia ADD metCobroJudicial bit;
ALTER TABLE MedioTransferencia ADD metInfoRelacionadaCobroJudicial varchar(50);
ALTER TABLE aud.MedioTransferencia_aud ADD metCobroJudicial bit;
ALTER TABLE aud.MedioTransferencia_aud ADD metInfoRelacionadaCobroJudicial varchar(50);

--changeset jocorrea:02
--comment: Eliminaciones tabla ValidacionProceso
DELETE ValidacionProceso 
WHERE vapBloque IN ('NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FIDELIDAD_25ANIOS_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_MAYOR_1_5SM_0_6_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_MAYOR_1_5SM_2_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_MENOR_1_5SM_0_6_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_MENOR_1_5SM_0_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_MENOR_1_5SM_2_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_PENSIONADO_FAMILIAR_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_TRABAJADOR_DEPENDIENTE_WEB',
'NOVEDAD_ACTIVAR_DESACTIVAR_CABEZA_HOGAR_TRABAJADOR_INDEPENDIENTE_WEB'); 

DELETE ValidacionProceso 
WHERE vapBloque IN ('NOVEDAD_REPORTE_INVALIDEZ_BENEFICIARIO_CUSTODIA_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_CONYUGE_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_FIDELIDAD_25ANIOS_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_HERMANO_HUERFANO_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_HIJASTRO_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_HIJO_ADOPTIVO_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_HIJO_BIOLOGICO_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_MADRE_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_MAYOR_1_5SM_0_6_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_MAYOR_1_5SM_2_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_MENOR_1_5SM_0_6_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_MENOR_1_5SM_0_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_MENOR_1_5SM_2_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PADRE_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_PENSIONADO_PENSION_FAMILIAR_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_TRABAJADOR_DEPENDIENTE_WEB',
'NOVEDAD_REPORTE_INVALIDEZ_TRABAJADOR_INDEPENDIENTE_WEB');            
     
DELETE ValidacionProceso 
WHERE vapBloque IN ('NOVEDAD_CAMBIO_NIVEL_EDUCATIVO_OCUPACION_PROFESION_CONYUGE_DEPWEB',
'NOVEDAD_CAMBIO_NIVEL_EDUCATIVO_OCUPACION_PROFESION_TRABAJADOR_DEPENDIENTE_DEPWEB');

DELETE ValidacionProceso 
WHERE vapBloque IN ('NOVEDAD_ACTIVAR_INACTIVAR_ENVIO_CORREO_Y_DATOS_PERSONALES_PENSIONADO_MNOOR_1_5SM_0_WEB',
'NOVEDAD_ACTIVAR_INACTIVAR_ENVIO_CORREO_Y_DATOS_PERSONALES_PENSIONADO_MENOR_1_5SM_0_6_WEB',
'NOVEDAD_ACTIVAR_INACTIVAR_ENVIO_CORREO_Y_DATOS_PERSONALES_PENSIONADO_MENOR_1_5SM_2_WEB',
'NOVEDAD_ACTIVAR_INACTIVAR_ENVIO_CORREO_Y_DATOS_PERSONALES_PENSIONADO_PENSION_FAMILIAR_WEB');

--changeset arocha:03
--comment: insert tabla ReporteKPI
INSERT ReporteKPI (rekIdReporte,rekIdGrupo,rekNombreReporte,rekFrecuencia) VALUES
('210cf395-cbe9-4b68-8494-c5645351a24a','D2044B92-AF76-4BF7-BFCE-DB27AEDC3738','AFILIACIONES_PERSONA','MENSUAL'),
('a820ed1f-fb8c-4159-a191-06d75410ae5f','D2044B92-AF76-4BF7-BFCE-DB27AEDC3738','AFILIACIONES_PERSONA','BIMENSUAL'),
('6fdb5587-d133-4f5d-bdb0-d98701a122d1','D2044B92-AF76-4BF7-BFCE-DB27AEDC3738','AFILIACIONES_PERSONA','TRIMESTRAL'),
('850382c4-26c2-457f-9194-e787a007f30a','D2044B92-AF76-4BF7-BFCE-DB27AEDC3738','AFILIACIONES_PERSONA','SEMESTRAL'),
('f4ca5d9b-2809-4be3-a25c-8e5671af2903','D2044B92-AF76-4BF7-BFCE-DB27AEDC3738','AFILIACIONES_PERSONA','ANUAL');

