--liquibase formatted sql

--changeset mamonroy:01
--comment: CC Novedades - Certificado escolar
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'BENEFICIARIO_EN_CUSTODIA';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJASTRO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_ADOPTIVO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_BIOLOGICO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'BENEFICIARIO_EN_CUSTODIA';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJASTRO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_ADOPTIVO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_BIOLOGICO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'BENEFICIARIO_EN_CUSTODIA';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJASTRO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_ADOPTIVO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB' AND vapValidacion = 'VALIDACION_HIJO_ACTIVO' AND vapObjetovalidacion = 'HIJO_BIOLOGICO';