update VALIDACIONPROCESO
set vapEstadoProceso = 'INACTIVO'
WHERE (vapBloque LIKE 'ACTUALIZACION_ESCOLARIDAD%'
or vapBloque LIKE 'ACTUALIZACION_CERTIFICADO%')
AND vapValidacion in ('VALIDACION_PERSONA_BENEFICIARIO_HIJO',
'VALIDACION_PERSONA_CONDICION_INVALIDEZ',
'VALIDACION_HIJO_2_GRUPOS_DISTINTOS_AFILIADOS',
'VALIDACION_ESTADO_AFILIACION_ACTIVO',
'VALIDACION_AFILIADO_ACTIVO')