if not exists (select * from sys.objects as o where o.name ='EstadisticasGenesys')
begin
    CREATE TABLE [dbo].[EstadisticasGenesys](
    	[esgId] [bigint] IDENTITY(1,1) NOT NULL,
    	[esgFechaRegistro] [datetime2](7) NULL,
    	[esgCantidadEmpresas] [int] NULL,
    	[esgCantidadAfiliados] [int] NULL,
    	[esgCantidadBeneficiarios] [int] NULL,
    	[esgCantidadEmpresasMorosas] [int] NULL,
    	[esgLiquidacionMesUno] [varchar](100) NULL,
    	[esgLiquidacionConDerechoUno] [int] NULL,
    	[esgLiquidacionSinDerechoUno] [int] NULL,
    	[esgLiquidacionMesDos] [varchar](100) NULL,
    	[esgLiquidacionConDerechoDos] [int] NULL,
    	[esgLiquidacionSinDerechoDos] [int] NULL,
    	[esgLiquidacionMesTres] [varchar](100) NULL,
    	[esgLiquidacionConDerechoTres] [int] NULL,
    	[esgLiquidacionSinDerechoTres] [int] NULL,
    	[esgLiquidacionMesCuatro] [varchar](100) NULL,
    	[esgLiquidacionConDerechoCuatro] [int] NULL,
    	[esgLiquidacionSinDerechoCuatro] [int] NULL,
    	[esgLiquidacionMesCinco] [varchar](100) NULL,
    	[esgLiquidacionConDerechoCinco] [int] NULL,
    	[esgLiquidacionSinDerechoCinco] [int] NULL,
    	[esgLiquidacionMesSeis] [varchar](100) NULL,
    	[esgLiquidacionConDerechoSeis] [int] NULL,
    	[esgLiquidacionSinDerechoSeis] [int] NULL,
    	[esgLiquidacionesMasivas] [int] NULL,
    	[esgLiquidacionesPorFallecimiento] [int] NULL,
    	[esgLiquidacionesPorAjuste] [int] NULL,
    	[esgLiquidacionesPorReconocimiento] [int] NULL,
    	[esgPostulacionesAsignadas] [int] NULL,
    	[esgPostulacionesRecibidasEnElAnio] [int] NULL,
    	[esgPostulacionesPorAsignar] [int] NULL,
    	[esgPostulacionesLegalizadas] [int] NULL,
    	[esgValorAsignacionUltimoMes] [numeric](18, 0) NULL,
    	[esgAfiliacionesSinTerminarEnAnio] [int] NULL,
    	[esgAportesPlanillasNotificadas] [int] NULL,
    	[esgAportesManuales] [int] NULL,
    	[esgAportesCorreciones] [int] NULL,
    	[esgAportesDevoluciones] [int] NULL,
    	[esgAporteMesUno] [varchar](100) NULL,
    	[esgAportesRelacionadosUno] [int] NULL,
    	[esgAportesRegistradosUno] [int] NULL,
    	[esgAporteMesDos] [varchar](100) NULL,
    	[esgAportesRelacionadosDos] [int] NULL,
    	[esgAportesRegistradosDos] [int] NULL,
    	[esgAporteMesTres] [varchar](100) NULL,
    	[esgAportesRelacionadosTres] [int] NULL,
    	[esgAportesRegistradosTres] [int] NULL,
    	[esgAporteMesCuatro] [varchar](100) NULL,
    	[esgAportesRelacionadosCuatro] [int] NULL,
    	[esgAportesRegistradosCuatro] [int] NULL,
    	[esgAporteMesCinco] [varchar](100) NULL,
    	[esgAportesRelacionadosCinco] [int] NULL,
    	[esgAportesRegistradosCinco] [int] NULL,
    	[esgAporteMesSeis] [varchar](100) NULL,
    	[esgAportesRelacionadosSeis] [int] NULL,
    	[esgAportesRegistradosSeis] [int] NULL
    )
end