-- =============================================
-- Author:		Diego Suesca
-- Create date: 2018/05/29
-- Description:	
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[USP_SM_GET_InsertCuentaAdministradorSubsidios]	
	@idSolicitudLiquidacion bigint,
	@sUsuario VARCHAR(255)
with execute as owner
AS
BEGIN
BEGIN TRY
	DECLARE @iNumeroRegistros BIGINT,
			@iRevision BIGINT,@NumeroRadicacion VARCHAR(30) ;

	select @NumeroRadicacion = solNumeroRadicacion 
	from Solicitud
	join SolicitudLiquidacionSubsidio on solid = slsSolicitudGlobal  
	where slsId = @idSolicitudLiquidacion

	CREATE TABLE #TempCuentaAdminPagos (tmcDispersionMedioDePagoAdmin bigint,tmcFechaHoraCreacionRegistro datetime,tmcUsuarioCreacionRegistro varchar(200),tmcTipoTransaccionSubsidio varchar(40),tmcEstadoTransaccionSubsidio varchar(25),tmcEstadoLiquidacionSubsidio varchar(25),tmcOrigenTransaccion varchar(30),tmcMedioDePagoTransaccion varchar(13),tmcNumeroTarjetaAdmonSubsidio varchar(50),tmcCodigoBanco varchar(7),tmcNombreBanco varchar(255),tmcTipoCuentaAdmonSubsidio varchar(30),tmcNumeroCuentaAdmonSubsidio varchar(30),tmcTipoIdentificacionTitularCuentaAdmonSubsidio varchar(20),tmcNumeroIdentificacionTitularCuentaAdmonSubsidio varchar(20),tmcNombreTitularCuentaAdmonSubsidio varchar(200),tmcFechaHoraTransaccion datetime,tmcUsuarioTransaccion varchar(200),tmcValorOriginalTransaccion numeric(19,5),tmcValorRealTransaccion numeric(19,5),tmcTransaccionOriginal bigint,tmcRemisionDatosTerceroPagador varchar(200),tmcTransaccionTerceroPagador varchar(200),tmcNombreTerceroPagado varchar(200),tmcCuentaAdmonSubsidioRelacionado bigint,tmcFechaHoraUltimaModificacion datetime,tmcUsuarioUltimaModificacion varchar(200),tmcAdministradorSubsidio bigint,tmcSitioDePago bigint,tmcSitioDeCobro bigint,tmcMedioDePago bigint,tmcCondicionPersonaAdministradorSubsidio bigint,s1 varchar(500),s2 varchar(500), idSolicitud bigint);
	DECLARE @TempCuentaAdminPagosIns table(casId bigint,casFechaHoraCreacionRegistro datetime,casUsuarioCreacionRegistro varchar(200),casTipoTransaccionSubsidio varchar(40),casEstadoTransaccionSubsidio varchar(25),casEstadoLiquidacionSubsidio varchar(25),casOrigenTransaccion varchar(30),casMedioDePagoTransaccion varchar(13),casNumeroTarjetaAdmonSubsidio varchar(50),casCodigoBanco varchar(7),casNombreBanco varchar(255),casTipoCuentaAdmonSubsidio varchar(30),casNumeroCuentaAdmonSubsidio varchar(30),casTipoIdentificacionTitularCuentaAdmonSubsidio varchar(20),casNumeroIdentificacionTitularCuentaAdmonSubsidio varchar(20),casNombreTitularCuentaAdmonSubsidio varchar(200),casFechaHoraTransaccion datetime,casUsuarioTransaccion varchar(200),casValorOriginalTransaccion numeric(19,5),casValorRealTransaccion numeric(19,5),casIdTransaccionOriginal bigint,casIdRemisionDatosTerceroPagador varchar(200),casIdTransaccionTerceroPagador varchar(200),casNombreTerceroPagado varchar(200),casIdCuentaAdmonSubsidioRelacionado bigint,casFechaHoraUltimaModificacion datetime,casUsuarioUltimaModificacion varchar(200),casAdministradorSubsidio bigint,casSitioDePago bigint,casSitioDeCobro bigint,casMedioDePago bigint,casSolicitudLiquidacionSubsidio bigint,casCondicionPersonaAdmin bigint);
		
	INSERT #TempCuentaAdminPagos (tmcFechaHoraCreacionRegistro,tmcUsuarioCreacionRegistro,tmcTipoTransaccionSubsidio,tmcEstadoTransaccionSubsidio,tmcEstadoLiquidacionSubsidio,tmcOrigenTransaccion,tmcMedioDePagoTransaccion,tmcNumeroTarjetaAdmonSubsidio,tmcCodigoBanco,tmcNombreBanco,tmcTipoCuentaAdmonSubsidio,tmcNumeroCuentaAdmonSubsidio,tmcTipoIdentificacionTitularCuentaAdmonSubsidio,tmcNumeroIdentificacionTitularCuentaAdmonSubsidio,tmcNombreTitularCuentaAdmonSubsidio,tmcFechaHoraTransaccion,tmcUsuarioTransaccion,tmcValorOriginalTransaccion,tmcValorRealTransaccion,tmcTransaccionOriginal,tmcRemisionDatosTerceroPagador,tmcTransaccionTerceroPagador,tmcNombreTerceroPagado,tmcCuentaAdmonSubsidioRelacionado,tmcFechaHoraUltimaModificacion,tmcUsuarioUltimaModificacion,tmcAdministradorSubsidio,tmcSitioDePago,tmcSitioDeCobro,tmcMedioDePago,idSolicitud,tmcCondicionPersonaAdministradorSubsidio,s1)
	EXEC sp_execute_remote SubsidioReferenceData, 
	N'SELECT tmcFechaHoraCreacionRegistro,tmcUsuarioCreacionRegistro,tmcTipoTransaccionSubsidio,tmcEstadoTransaccionSubsidio,tmcEstadoLiquidacionSubsidio,tmcOrigenTransaccion,tmcMedioDePagoTransaccion,tmcNumeroTarjetaAdmonSubsidio,tmcCodigoBanco,tmcNombreBanco,tmcTipoCuentaAdmonSubsidio,tmcNumeroCuentaAdmonSubsidio,tmcTipoIdentificacionTitularCuentaAdmonSubsidio,tmcNumeroIdentificacionTitularCuentaAdmonSubsidio,tmcNombreTitularCuentaAdmonSubsidio,tmcFechaHoraTransaccion,tmcUsuarioTransaccion,tmcValorOriginalTransaccion,tmcValorRealTransaccion,tmcTransaccionOriginal,tmcRemisionDatosTerceroPagador,tmcTransaccionTerceroPagador,tmcNombreTerceroPagado,tmcCuentaAdmonSubsidioRelacionado,tmcFechaHoraUltimaModificacion,tmcUsuarioUltimaModificacion,tmcAdministradorSubsidio,tmcSitioDePago,tmcSitioDeCobro,tmcMedioDePago,@idSolicitudLiquidacion,tmcCondicionPersonaAdministradorSubsidio
	  FROM TempCuentaAdminPagos t
	  WHERE tmcNumeroradicado = @NumeroRadicacion',
	  	N'@idSolicitudLiquidacion bigint,@NumeroRadicacion varchar(30)',
 		@idSolicitudLiquidacion=@idSolicitudLiquidacion,@NumeroRadicacion=@NumeroRadicacion;	

	INSERT CuentaAdministradorSubsidio (casFechaHoraCreacionRegistro,casUsuarioCreacionRegistro,casTipoTransaccionSubsidio,casEstadoTransaccionSubsidio,casEstadoLiquidacionSubsidio,casOrigenTransaccion,casMedioDePagoTransaccion,casNumeroTarjetaAdmonSubsidio,casCodigoBanco, casNombreBanco,casTipoCuentaAdmonSubsidio,casNumeroCuentaAdmonSubsidio,casTipoIdentificacionTitularCuentaAdmonSubsidio,casNumeroIdentificacionTitularCuentaAdmonSubsidio,casNombreTitularCuentaAdmonSubsidio,casFechaHoraTransaccion,casUsuarioTransaccion,casValorOriginalTransaccion,casValorRealTransaccion,casIdTransaccionOriginal,casIdRemisionDatosTerceroPagador,casIdTransaccionTerceroPagador,casNombreTerceroPagado,casIdCuentaAdmonSubsidioRelacionado,casFechaHoraUltimaModificacion,casUsuarioUltimaModificacion,casAdministradorSubsidio,casSitioDePago,casSitioDeCobro,casMedioDePago,casSolicitudLiquidacionSubsidio,casCondicionPersonaAdmin)
	OUTPUT INSERTED.casId,INSERTED.casFechaHoraCreacionRegistro,INSERTED.casUsuarioCreacionRegistro,INSERTED.casTipoTransaccionSubsidio,INSERTED.casEstadoTransaccionSubsidio,INSERTED.casEstadoLiquidacionSubsidio,INSERTED.casOrigenTransaccion,INSERTED.casMedioDePagoTransaccion,INSERTED.casNumeroTarjetaAdmonSubsidio,INSERTED.casCodigoBanco, INSERTED.casNombreBanco,INSERTED.casTipoCuentaAdmonSubsidio,INSERTED.casNumeroCuentaAdmonSubsidio,INSERTED.casTipoIdentificacionTitularCuentaAdmonSubsidio,INSERTED.casNumeroIdentificacionTitularCuentaAdmonSubsidio,INSERTED.casNombreTitularCuentaAdmonSubsidio,INSERTED.casFechaHoraTransaccion,INSERTED.casUsuarioTransaccion,INSERTED.casValorOriginalTransaccion,INSERTED.casValorRealTransaccion,INSERTED.casIdTransaccionOriginal,INSERTED.casIdRemisionDatosTerceroPagador,INSERTED.casIdTransaccionTerceroPagador,INSERTED.casNombreTerceroPagado,INSERTED.casIdCuentaAdmonSubsidioRelacionado,INSERTED.casFechaHoraUltimaModificacion,INSERTED.casUsuarioUltimaModificacion,INSERTED.casAdministradorSubsidio,INSERTED.casSitioDePago,INSERTED.casSitioDeCobro,INSERTED.casMedioDePago,INSERTED.casSolicitudLiquidacionSubsidio,INSERTED.casCondicionPersonaAdmin
	INTO @TempCuentaAdminPagosIns
	--(casFechaHoraCreacionRegistro,casUsuarioCreacionRegistro,casTipoTransaccionSubsidio,casEstadoTransaccionSubsidio,casEstadoLiquidacionSubsidio,casOrigenTransaccion,casMedioDePagoTransaccion,casNumeroTarjetaAdmonSubsidio,casCodigoBanco, casNombreBanco,casTipoCuentaAdmonSubsidio,casNumeroCuentaAdmonSubsidio,casTipoIdentificacionTitularCuentaAdmonSubsidio,casNumeroIdentificacionTitularCuentaAdmonSubsidio,casNombreTitularCuentaAdmonSubsidio,casFechaHoraTransaccion,casUsuarioTransaccion,casValorOriginalTransaccion,casValorRealTransaccion,casIdTransaccionOriginal,casIdRemisionDatosTerceroPagador,casIdTransaccionTerceroPagador,casNombreTerceroPagado,casIdCuentaAdmonSubsidioRelacionado,casFechaHoraUltimaModificacion,casUsuarioUltimaModificacion,casAdministradorSubsidio,casSitioDePago,casSitioDeCobro,casMedioDePago,casSolicitudLiquidacionSubsidio,casCondicionPersonaAdmin)
	SELECT max(tmcFechaHoraCreacionRegistro),tmcUsuarioCreacionRegistro,tmcTipoTransaccionSubsidio,tmcEstadoTransaccionSubsidio,tmcEstadoLiquidacionSubsidio,tmcOrigenTransaccion,tmcMedioDePagoTransaccion,tmcNumeroTarjetaAdmonSubsidio,tmcCodigoBanco,tmcNombreBanco,tmcTipoCuentaAdmonSubsidio,tmcNumeroCuentaAdmonSubsidio,tmcTipoIdentificacionTitularCuentaAdmonSubsidio,tmcNumeroIdentificacionTitularCuentaAdmonSubsidio,tmcNombreTitularCuentaAdmonSubsidio,max(tmcFechaHoraTransaccion),tmcUsuarioTransaccion,sum(tmcValorOriginalTransaccion) tmcValorOriginalTransaccion,sum(tmcValorRealTransaccion) tmcValorRealTransaccion,tmcTransaccionOriginal,tmcRemisionDatosTerceroPagador,tmcTransaccionTerceroPagador,tmcNombreTerceroPagado,tmcCuentaAdmonSubsidioRelacionado,max(tmcFechaHoraUltimaModificacion),tmcUsuarioUltimaModificacion,tmcAdministradorSubsidio,max(tmcSitioDePago),tmcSitioDeCobro,max(tmcMedioDePago) tmcMedioDePago,idSolicitud,tmcCondicionPersonaAdministradorSubsidio
	FROM #TempCuentaAdminPagos
	GROUP BY tmcUsuarioCreacionRegistro,tmcTipoTransaccionSubsidio,tmcEstadoTransaccionSubsidio,tmcEstadoLiquidacionSubsidio,tmcOrigenTransaccion,tmcMedioDePagoTransaccion,tmcNumeroTarjetaAdmonSubsidio,tmcCodigoBanco,tmcNombreBanco,tmcTipoCuentaAdmonSubsidio,tmcNumeroCuentaAdmonSubsidio,tmcTipoIdentificacionTitularCuentaAdmonSubsidio,tmcNumeroIdentificacionTitularCuentaAdmonSubsidio,tmcNombreTitularCuentaAdmonSubsidio,tmcUsuarioTransaccion,tmcTransaccionOriginal,tmcRemisionDatosTerceroPagador,tmcTransaccionTerceroPagador,tmcNombreTerceroPagado,tmcCuentaAdmonSubsidioRelacionado,tmcUsuarioUltimaModificacion,tmcAdministradorSubsidio,tmcSitioDeCobro,idSolicitud,tmcCondicionPersonaAdministradorSubsidio


	SELECT @iNumeroRegistros = COUNT(*) FROM #TempCuentaAdminPagos

	IF @iNumeroRegistros > 0
	BEGIN
		EXEC [dbo].[USP_UTIL_GET_CrearRevision] 'com.asopagos.entidades.subsidiomonetario.pagos.CuentaAdministradorSubsidio',@iNumeroRegistros,'',@sUsuario,@iRevision OUTPUT

		INSERT INTO aud.CuentaAdministradorSubsidio_aud (casId,casFechaHoraCreacionRegistro,casUsuarioCreacionRegistro,casTipoTransaccionSubsidio,casEstadoTransaccionSubsidio,casEstadoLiquidacionSubsidio,casOrigenTransaccion,casMedioDePagoTransaccion,casNumeroTarjetaAdmonSubsidio,casCodigoBanco, casNombreBanco,casTipoCuentaAdmonSubsidio,casNumeroCuentaAdmonSubsidio,casTipoIdentificacionTitularCuentaAdmonSubsidio,casNumeroIdentificacionTitularCuentaAdmonSubsidio,casNombreTitularCuentaAdmonSubsidio,casFechaHoraTransaccion,casUsuarioTransaccion,casValorOriginalTransaccion,casValorRealTransaccion,casIdTransaccionOriginal,casIdRemisionDatosTerceroPagador,casIdTransaccionTerceroPagador,casNombreTerceroPagado,casIdCuentaAdmonSubsidioRelacionado,casFechaHoraUltimaModificacion,casUsuarioUltimaModificacion,casAdministradorSubsidio,casSitioDePago,casSitioDeCobro,casMedioDePago,casSolicitudLiquidacionSubsidio,casCondicionPersonaAdmin,REV,REVTYPE)
		SELECT casId,casFechaHoraCreacionRegistro,casUsuarioCreacionRegistro,casTipoTransaccionSubsidio,casEstadoTransaccionSubsidio,casEstadoLiquidacionSubsidio,casOrigenTransaccion,casMedioDePagoTransaccion,casNumeroTarjetaAdmonSubsidio,casCodigoBanco,casNombreBanco,casTipoCuentaAdmonSubsidio,casNumeroCuentaAdmonSubsidio,casTipoIdentificacionTitularCuentaAdmonSubsidio,casNumeroIdentificacionTitularCuentaAdmonSubsidio,casNombreTitularCuentaAdmonSubsidio,casFechaHoraTransaccion,casUsuarioTransaccion,casValorOriginalTransaccion,casValorRealTransaccion,casIdTransaccionOriginal,casIdRemisionDatosTerceroPagador,casIdTransaccionTerceroPagador,casNombreTerceroPagado,casIdCuentaAdmonSubsidioRelacionado,casFechaHoraUltimaModificacion,casUsuarioUltimaModificacion,casAdministradorSubsidio,casSitioDePago,casSitioDeCobro,casMedioDePago,casSolicitudLiquidacionSubsidio,casCondicionPersonaAdmin,@iRevision,0
		FROM @TempCuentaAdminPagosIns
	END

	EXEC sp_execute_remote SubsidioReferenceData, 
	N'UPDATE dmp
		SET dmpEnviadoAPagos = 1
		FROM dbo.DispersionMedioDePagoAdmin dmp
		JOIN TempCuentaAdminPagos t on t.tmcDispersionMedioDePagoAdmin =dmp.dmpId'	

END TRY
BEGIN CATCH
	INSERT RegistroLog (relFecha,relParametrosEjecucion,relErrorMessage)
	VALUES (dbo.GetLocalDate(),'[USP_SM_GET_InsertCuentaAdministradorSubsidios] ' ,ERROR_MESSAGE());
END CATCH
	print 'Finaliza USP_SM_GET_InsertCuentaAdministradorSubsidios'
END ;