--liquibase formatted sql

--changeset jusanchez:01
--comment: Insercion en las tablas DestinatarioComunicado, GrupoPrioridad y Destinatario

--DestinatarioComunicado
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','CRT_BVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','CRT_ACP_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','RCHZ_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_SBC_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_INC_VAL_TRAB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_INC_VAL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_PROD_NSUB_TRB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_PROD_NSUB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_EMP_AFL_MLT_TRBW');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_INVL_AFL_TRBW');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_SUB_AFL_TRB_DPT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_INVL_AFL_TRBW_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_REG_BNF_WEB_TRB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_REG_BNF_WEB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ENRL_AFL_IDPE_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ENRL_AFL_PNS_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ACPT_AFL_PNS_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RCHZ_AFL_PNS_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ACPT_AFL_IDPE_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RCHZ_AFL_IDPE_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_SBC_AFL_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_SBC_AFL_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RAD_AFL_IDPE_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RAD_AFL_PNS_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_BVD_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_BVD_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_ACP_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_ACP_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_RAD_AFL_EMP_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_ENRL_AFL_EMP_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_REG_BNF_WEB_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_REG_BNF_WEB_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_RAD_NVD_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_RAD_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','RCHZ_NVD_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','RCHZ_NVD_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','CNFR_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CNFR_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_APRB_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','RCHZ_NVD_WEB_TRB_REP_POR_EMP_POR_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_PARA_SBC_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_PARA_SBC_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_PARA_SBC_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_RAD_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','RCHZ_AFL_PER_POR_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','RCHZ_AFL_PER_POR_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PER_INC_VAL');

--GrupoPrioridad
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 1');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 2');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 3');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 4');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 5');

--Destinatario
INSERT Destinatario (desNombre,desRolContacto) VALUES ('ResponsableAfiliaciones','RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('RepresentanteLegal','REPRESENTANTE_LEGAL');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('OficinaPrincipal','OFICINA_PRINCIPAL');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('EnvioCorrespondencia','ENVIO_DE_CORRESPONDENCIA');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('NotificacionJudicial','NOTIFICACION_JUDICIAL');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('TrabajadorDependiente','TRABAJADOR_DEPENDIENTE');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('TrabajadorIndependiente','TRABAJADOR_INDEPENDIENTE');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('Pensionado','PENSIONADO');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('ResponsableSubsidios','RESPONSABLE_DE_SUBSIDIOS');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('ResponsableAportes','RESPONSABLE_DE_APORTES');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('InformacionContacto','INFORMACION_DE_CONTACTO');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('Aportante','APORTANTE');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('Solicitante','SOLICITANTE');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('IndependientePensionadoPagoTercero','INFORMACION_PESIONADO_INDEPENDIENTE_PAGO_APORTE_TERCERO');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('IndependientePensionadoPagoSiMismo','INFORMACION_PESIONADO_INDEPENDIENTE_PAGO_APORTE');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('AdministradorSubsidios','ADMINISTRADOR_DE_SUBSIDIO');
INSERT Destinatario (desNombre,desRolContacto) VALUES ('AutorizoPago','AUTORIZADO_PARA_PAGO');

--changeset jusanchez:02
--comment: Insercion en las tablas PrioridadDestinatario y DestinatarioGrupo

--PrioridadDestinatario
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (1,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (2,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (3,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (4,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (5,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (6,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (7,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (8,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (9,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (10,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (11,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (12,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (13,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (14,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (15,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (16,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (17,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (18,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (19,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (20,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (21,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (22,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (23,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (24,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (25,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (26,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (27,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (28,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (29,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (30,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (31,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (32,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (33,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (34,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (35,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (36,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (37,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (38,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (39,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (40,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (41,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (42,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (43,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (44,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (45,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (46,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (47,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (48,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (49,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (50,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (51,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (52,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (53,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (54,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (55,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (56,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (57,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (58,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (59,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (60,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (61,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (62,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (63,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (64,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (65,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (66,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (67,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (68,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (69,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (70,5,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (71,1,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (72,1,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (73,2,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (74,2,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (75,3,5);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (76,3,1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (77,4,2);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (78,4,3);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (79,5,4);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES (80,5,5);

--DestinatarioGrupo
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (1,1);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (2,2);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (3,3);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (4,4);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (5,5);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (6,1);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (7,2);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (8,3);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (9,4);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (10,5);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (11,1);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (12,2);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (13,3);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (14,4);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (15,5);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (16,1);
INSERT DestinatarioGrupo (dgrDestinatario,dgrGrupoPrioridad) VALUES (17,2);

