--liquibase formatted sql

--changeset jusanchez:01
--comment: Insercion en las tablas GrupoPrioridad, DestinatarioComunicado, DestinatarioGrupo y PrioridadDestinatario

-- GrupoPrioridad
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 1');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 2');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 3');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 4');
INSERT GrupoPrioridad (gprNombre) VALUES ('GRUPO 5');

-- DestinatarioComunicado
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','NTF_RAD_AFL_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_INT_AFL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','CRT_BVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','CRT_ACP_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_PRESENCIAL','RCHZ_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_SBC_AFL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','RCHZ_AFL_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_INC_VAL_TRAB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_INC_VAL_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_PROD_NSUB_TRB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','RCHZ_AFL_DPT_PROD_NSUB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_EMP_AFL_MLT_TRBW');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_INVL_AFL_TRBW');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_SUB_AFL_TRB_DPT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_INVL_AFL_TRBW_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_REG_BNF_WEB_TRB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_DEPENDIENTE_WEB','NTF_REG_BNF_WEB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ENRL_AFL_IDPE_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ENRL_AFL_PNS_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ACPT_AFL_PNS_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RCHZ_AFL_PNS_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_ACPT_AFL_IDPE_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RCHZ_AFL_IDPE_DSP_SUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_INC_VAL');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_SBC_AFL_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_SBC_AFL_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PNS_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_IDPE_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RAD_AFL_IDPE_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_RAD_AFL_PNS_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_BVD_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_BVD_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_ACP_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','CRT_ACP_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_RAD_AFL_EMP_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_EMPRESAS_WEB','NTF_ENRL_AFL_EMP_WEB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_REG_BNF_WEB_IDPE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','NTF_REG_BNF_WEB_PNS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','NTF_RAD_NVD_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','NTF_RAD_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','RCHZ_NVD_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','RCHZ_NVD_EMP_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','CNFR_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','CNFR_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_PRESENCIAL','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','DSTMTO_NVD_RET_APRT');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_APRB_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','RCHZ_NVD_WEB_TRB_REP_POR_EMP_POR_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_EMPRESAS_PRESENCIAL','NTF_PARA_SBC_NVD_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_PERSONAS_WEB','NTF_PARA_SBC_NVD_PERS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_PARA_SBC_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('NOVEDADES_DEPENDIENTE_WEB','NTF_RAD_NVD_WEB_TRB_EMP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','RCHZ_AFL_PER_POR_PROD_NSUBLE');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_PERSONAS_PRESENCIAL','RCHZ_AFL_PER_POR_PROD_NSUB');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('AFILIACION_INDEPENDIENTE_WEB','RCHZ_AFL_PER_INC_VAL');

-- DestinatarioGrupo
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),'TRABAJADOR_DEPENDIENTE');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),'TRABAJADOR_INDEPENDIENTE');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),'PENSIONADO');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'REPRESENTANTE_LEGAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'OFICINA_PRINCIPAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'ENVIO_DE_CORRESPONDENCIA');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'NOTIFICACION_JUDICIAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'TRABAJADOR_DEPENDIENTE');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'TRABAJADOR_INDEPENDIENTE');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),'PENSIONADO');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),'TRABAJADOR_INDEPENDIENTE');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),'PENSIONADO');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),'RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),'REPRESENTANTE_LEGAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),'OFICINA_PRINCIPAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),'ENVIO_DE_CORRESPONDENCIA');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),'NOTIFICACION_JUDICIAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'RESPONSABLE_DE_SUBSIDIOS');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'RESPONSABLE_DE_APORTES');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'REPRESENTANTE_LEGAL');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'INFORMACION_DE_CONTACTO');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'ENVIO_DE_CORRESPONDENCIA');
INSERT DestinatarioGrupo (dgrGrupoPrioridad,dgrRolContacto) VALUES ((SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),'NOTIFICACION_JUDICIAL');

-- PrioridadDestinatario
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CNFR_RET_APRT' AND dcoProceso = 'NOVEDADES_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CNFR_RET_APRT' AND dcoProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_ACP_EMP' AND dcoProceso = 'AFILIACION_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_ACP_IDPE' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_ACP_PNS' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_BVD_EMP' AND dcoProceso = 'AFILIACION_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_BVD_IDPE' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='CRT_BVD_PNS' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT' AND dcoProceso = 'NOVEDADES_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT' AND dcoProceso = 'NOVEDADES_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT' AND dcoProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT' AND dcoProceso = 'NOVEDADES_PERSONAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_ACPT_AFL_IDPE_DSP_SUB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_ACPT_AFL_PNS_DSP_SUB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_APRB_NVD_WEB_TRB_EMP' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_EMP_AFL_MLT_TRBW' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_ENRL_AFL_EMP_WEB' AND dcoProceso = 'AFILIACION_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_ENRL_AFL_IDPE_WEB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_ENRL_AFL_PNS_WEB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'AFILIACION_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'AFILIACION_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'AFILIACION_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'NOVEDADES_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'NOVEDADES_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INT_AFL' AND dcoProceso = 'NOVEDADES_PERSONAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INVL_AFL_TRBW' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_INVL_AFL_TRBW_EMP' AND dcoProceso = 'AFILIACION_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_EMP' AND dcoProceso = 'NOVEDADES_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_EMP' AND dcoProceso = 'NOVEDADES_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_EMP' AND dcoProceso = 'NOVEDADES_PERSONAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_PERS' AND dcoProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_PERS' AND dcoProceso = 'NOVEDADES_PERSONAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_NVD_WEB_TRB_EMP' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_PARA_SBC_NVD_EMP' AND dcoProceso = 'NOVEDADES_EMPRESAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_PARA_SBC_NVD_PERS' AND dcoProceso = 'NOVEDADES_PERSONAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_PARA_SBC_NVD_WEB_TRB_EMP' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_AFL_EMP_WEB' AND dcoProceso = 'AFILIACION_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_AFL_IDPE_WEB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_AFL_PER' AND dcoProceso = 'AFILIACION_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_AFL_PNS_WEB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_NVD_EMP' AND dcoProceso = 'NOVEDADES_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 4'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_NVD_PER' AND dcoProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RAD_NVD_WEB_TRB_EMP' AND dcoProceso = 'NOVEDADES_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RCHZ_AFL_IDPE_DSP_SUB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_RCHZ_AFL_PNS_DSP_SUB' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_EMP' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_IDPE' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_PNS' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 2'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_TRB' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_SBC_AFL_EMP' AND dcoProceso = 'AFILIACION_EMPRESAS_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_SBC_AFL_IDPE' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 1'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_SBC_AFL_PNS' AND dcoProceso = 'AFILIACION_INDEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='NTF_SUB_AFL_TRB_DPT' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='RCHZ_AFL_DPT_INC_VAL_EMP' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='RCHZ_AFL_DPT_INC_VAL_TRAB' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUB_EMP' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 5'),1);
INSERT PrioridadDestinatario (prdDestinatarioComunicado,prdGrupoPrioridad,prdPrioridad) VALUES ((SELECT dcoid FROM DestinatarioComunicado WHERE dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUB_TRB' AND dcoProceso = 'AFILIACION_DEPENDIENTE_WEB'),(SELECT gprid FROM GrupoPrioridad WHERE gprNombre='GRUPO 3'),1);
