--liquibase formatted sql

--changeSET heinsohn:01 context:integracion runOnChange:true
--comment: Configuracion del ambiente ambiente integración COMFABOY
UPDATE PARAMETRO SET prmValor='COMFABOY' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='TUNJA' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='BOYACA' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Carrera 10 # 16-81' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='18000918778' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='891800213-8' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='d528dcd6-ed22-4d7e-9cca-e0a33cecc507_1.0' WHERE prmNombre='LOGO_DE_LA_CCF'
UPDATE PARAMETRO SET prmValor='www.dianis.com.co' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='pruebaLogoSuperServicios' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='pruebaFirmaResponsableEnvioComunicadoCaja' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='libardo_ramirez' WHERE prmNombre='RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='zDgxdoNnBaLbivLqKjtnww==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.office365.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='587' WHERE prmNombre='mail.smtp.port';
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/subsidios/integracion' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';

--
UPDATE CONSTANTE SET cnsValor='CONFAHBT' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF10' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.77.187.38:8282/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='Admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='Asdf1234$' WHERE cnsNombre='ECM_PASSWORD';
UPDATE CONSTANTE SET cnsValor='http://10.77.187.51/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://50.23.54.143:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://50.23.54.143:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD';

--changeSET heinsohn:02 context:pruebas runAlways:true runOnChange:true
--comment: Configuracion del ambiente pruebas HBT COMFACAUCA 
UPDATE PARAMETRO SET prmValor='COMFACAUCA' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='POPAYAN' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='CAUCA' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Calle 2N No. 6A-54' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='(2) 8231868' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='891500182-0' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='9560bfc8-d503-49fb-8733-eeafc66d94ce_1.0' WHERE prmNombre='LOGO_DE_LA_CCF'
UPDATE PARAMETRO SET prmValor='www.ccfcaldas.com' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='pruebaLogoSuperServicios' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='pruebaFirmaResponsableEnvioComunicadoCaja' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='zDgxdoNnBaLbivLqKjtnww==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.office365.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='587' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/subsidios/pruebas' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';

--
UPDATE CONSTANTE SET cnsValor='CONFA' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF14' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.77.187.38:8282/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='Admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='Asdf1234$' WHERE cnsNombre='ECM_PASSWORD'
UPDATE CONSTANTE SET cnsValor='http://10.77.187.42/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT'
UPDATE CONSTANTE SET cnsValor='http://50.23.54.143:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://50.23.54.143:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD'

--changeSET heinsohn:03 context:pruebas-asopagos runOnChange:true
--comment: Configuracion del ambiente pruebas asopagos CONFA
UPDATE PARAMETRO SET prmValor='http://10.77.187.38:8282/alfresco' WHERE prmNombre='ECM_HOST';
UPDATE PARAMETRO SET prmValor='Admin' WHERE prmNombre='ECM_USERNAME';
UPDATE PARAMETRO SET prmValor='Asdf1234$' WHERE prmNombre='ECM_PASSWORD'
UPDATE PARAMETRO SET prmValor='http://10.77.187.3/business-central' WHERE prmNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE PARAMETRO SET prmValor='http://genesys.heinsohn.com.co:8082/auth/' WHERE prmNombre='IDM_SERVER_URL';
UPDATE PARAMETRO SET prmValor='http://genesys.heinsohn.com.co:8082/auth/realms/{realm}' WHERE prmNombre='KEYCLOAK_ENDPOINT'; 
UPDATE PARAMETRO SET prmValor='132e4816-0876-4711-add8-24da0215f663' WHERE prmNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE PARAMETRO SET prmValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE prmNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE PARAMETRO SET prmValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE prmNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE PARAMETRO SET prmValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE prmNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE PARAMETRO SET prmValor='8' WHERE prmNombre='SEC_INITIAL_CHARACTERS_PASSWORD'
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='RWU4DjifCrlC4vGGxj+FWw==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.gmail.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='25' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
--
UPDATE CONSTANTE SET cnsValor='CONFASOPAGOS' WHERE cnsNombre='CAJA_COMPENSACION_SITE';UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';

UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF11' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='TARJETA' WHERE cnsNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE CONSTANTE SET cnsValor='CONFA' WHERE cnsNombre='NOMBRE_CCF';
UPDATE CONSTANTE SET cnsValor='MANIZALES' WHERE cnsNombre='CIUDAD_CCF';
UPDATE CONSTANTE SET cnsValor='CALDAS' WHERE cnsNombre='DEPARTAMENTO_CCF';
UPDATE CONSTANTE SET cnsValor='MANIZALES' WHERE cnsNombre='CIUDAD_CCF';
UPDATE CONSTANTE SET cnsValor='Cra 25 Calle 50' WHERE cnsNombre='DIRECCION_CCF';
UPDATE CONSTANTE SET cnsValor='57(6)8783111' WHERE cnsNombre='TELEFONO_CCF';
UPDATE CONSTANTE SET cnsValor='NIT' WHERE cnsNombre='TIPO_ID_CCF';
UPDATE CONSTANTE SET cnsValor='890806490-5' WHERE cnsNombre='NUMERO_ID_CCF';
UPDATE CONSTANTE SET cnsValor='fc360d0a-165b-435b-940c-e3593c2d94dd' WHERE cnsNombre='LOGO_DE_LA_CCF';
UPDATE CONSTANTE SET cnsValor='www.asopagos.com' WHERE cnsNombre='WEB_CCF';
UPDATE CONSTANTE SET cnsValor='c4562d89-1f8a-414f-bbe7-e2bf90ed4cf0' WHERE cnsNombre='LOGO_SUPERSERVICIOS';
UPDATE CONSTANTE SET cnsValor='839e030f-d8f2-464a-8a95-0ff6e8c00b03' WHERE cnsNombre='FIRMA_RESPONSABLE_CCF';
UPDATE CONSTANTE SET cnsValor='GerenteGeneral' WHERE cnsNombre='CARGO_RESPONSABLE_CCF';

--changeSET heinsohn:04 context:integracion-asopagos  runAlways:true runOnChange:true
--comment: Configuracion del ambiente integracion asopagos integracionasopagos
UPDATE PARAMETRO SET prmValor='CONFA' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='MANIZALES' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='CALDAS' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='MANIZALES' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='Cra 25 Calle 50' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='57(6)8783111' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='890806490-5' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='fc360d0a-165b-435b-940c-e3593c2d94dd' WHERE prmNombre='LOGO_DE_LA_CCF';
UPDATE PARAMETRO SET prmValor='www.asopagos.com' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='c4562d89-1f8a-414f-bbe7-e2bf90ed4cf0' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='839e030f-d8f2-464a-8a95-0ff6e8c00b03' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='RWU4DjifCrlC4vGGxj+FWw==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.gmail.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='25' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/subsidios/espejo' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';

--
UPDATE CONSTANTE SET cnsValor='integracionasopagos' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF04' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.77.187.38:8282/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='Admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='Asdf1234$' WHERE cnsNombre='ECM_PASSWORD'
UPDATE CONSTANTE SET cnsValor='http://10.77.187.13/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://genesys.heinsohn.com.co:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://genesys.heinsohn.com.co:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT'; 
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD'

--changeSET heinsohn:05 context:asopagos_confa runOnChange:true
--comment: Configuracion del ambiente asopagos_confa
UPDATE PARAMETRO SET prmValor='CONFA' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='MANIZALES' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='CALDAS' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Cra 25 Calle 50' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='57(6)8783111' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='890806490-5' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='fc360d0a-165b-435b-940c-e3593c2d94dd' WHERE prmNombre='LOGO_DE_LA_CCF';
UPDATE PARAMETRO SET prmValor='www.asopagos.com' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='a25863d9-9d6e-414c-926e-7934cbd7e0b4' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='814d2376-5847-44da-a3ea-32c4751fe559' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='RWU4DjifCrlC4vGGxj+FWw==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.gmail.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='25' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/SFTP' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';
UPDATE PARAMETRO set prmValor='77ba84e2-769d-4cb4-add3-053cc042f370' where prmNombre='ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122'
--
UPDATE CONSTANTE SET cnsValor='CONFA' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF11' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.0.1.5:8080/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='SK-[:gq{1S' WHERE cnsNombre='ECM_PASSWORD'
UPDATE CONSTANTE SET cnsValor='http://10.0.1.4/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://pruebasconfa.eastus2.cloudapp.azure.com:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://pruebasconfa.eastus2.cloudapp.azure.com:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT'; 
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD';

--changeSET heinsohn:06 context:asopagos_funcional runOnChange:true
--comment: Configuracion del ambiente asopagos_funcional
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='CONFA' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='MANIZALES' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='CALDAS' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Cra 25 Calle 50' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='57(6)8783111' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='890806490-5' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='fc360d0a-165b-435b-940c-e3593c2d94dd' WHERE prmNombre='LOGO_DE_LA_CCF';
UPDATE PARAMETRO SET prmValor='www.asopagos.com' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='a25863d9-9d6e-414c-926e-7934cbd7e0b4' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='814d2376-5847-44da-a3ea-32c4751fe559' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='RWU4DjifCrlC4vGGxj+FWw==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.gmail.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='25' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/SFTP' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';
UPDATE PARAMETRO set prmValor='d52957da-c2d1-4a60-987c-f7196bce4a4f' where prmNombre='ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122'
--
UPDATE CONSTANTE SET cnsValor='FUNCIONALES' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF11' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.0.1.5:8080/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='SK-[:gq{1S' WHERE cnsNombre='ECM_PASSWORD'
UPDATE CONSTANTE SET cnsValor='http://10.0.1.8/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://comfa.eastus2.cloudapp.azure.com:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://comfa.eastus2.cloudapp.azure.com:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT'; 
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD';


--changeSET heinsohn:07 context:asopagosSubsidio runOnChange:true
--comment: Configuracion del ambiente ASOPAGOSSUBSIDIO
UPDATE PARAMETRO SET prmValor='ASOPAGOSSUBSIDIO' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='TUNJA' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='BOYACA' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Carrera 10 # 16-81' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='18000918778' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='891800213-8' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='d528dcd6-ed22-4d7e-9cca-e0a33cecc507_1.0' WHERE prmNombre='LOGO_DE_LA_CCF'
UPDATE PARAMETRO SET prmValor='www.dianis.com.co' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='pruebaLogoSuperServicios' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='pruebaFirmaResponsableEnvioComunicadoCaja' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='libardo_ramirez' WHERE prmNombre='RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='zDgxdoNnBaLbivLqKjtnww==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.office365.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='587' WHERE prmNombre='mail.smtp.port';
UPDATE PARAMETRO SET prmValor='asopagos-proyecto@heinsohn.com.co' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/subsidios/ambSubsidio/carga' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';

--
UPDATE CONSTANTE SET cnsValor='asopagos-subsidio' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF10' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.77.187.38:8282/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='Admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='Asdf1234$' WHERE cnsNombre='ECM_PASSWORD';
UPDATE CONSTANTE SET cnsValor='http://172.20.0.135/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://172.20.0.135:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://172.20.0.135:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD';


--changeSET heinsohn:08 context:asopagos_subsidio runOnChange:true
--comment: Configuracion del ambiente asopagos_subsidio
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='CONFA' WHERE prmNombre='NOMBRE_CCF';
UPDATE PARAMETRO SET prmValor='MANIZALES' WHERE prmNombre='CIUDAD_CCF';
UPDATE PARAMETRO SET prmValor='CALDAS' WHERE prmNombre='DEPARTAMENTO_CCF';
UPDATE PARAMETRO SET prmValor='Cra 25 Calle 50' WHERE prmNombre='DIRECCION_CCF';
UPDATE PARAMETRO SET prmValor='57(6)8783111' WHERE prmNombre='TELEFONO_CCF';
UPDATE PARAMETRO SET prmValor='NIT' WHERE prmNombre='TIPO_ID_CCF';
UPDATE PARAMETRO SET prmValor='890806490-5' WHERE prmNombre='NUMERO_ID_CCF';
UPDATE PARAMETRO SET prmValor='fc360d0a-165b-435b-940c-e3593c2d94dd' WHERE prmNombre='LOGO_DE_LA_CCF';
UPDATE PARAMETRO SET prmValor='www.asopagos.com' WHERE prmNombre='WEB_CCF';
UPDATE PARAMETRO SET prmValor='a25863d9-9d6e-414c-926e-7934cbd7e0b4' WHERE prmNombre='LOGO_SUPERSERVICIOS';
UPDATE PARAMETRO SET prmValor='814d2376-5847-44da-a3ea-32c4751fe559' WHERE prmNombre='FIRMA_RESPONSABLE_CCF';
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.user';
UPDATE PARAMETRO SET prmValor='RWU4DjifCrlC4vGGxj+FWw==' WHERE prmNombre='mail.smtp.password';
UPDATE PARAMETRO SET prmValor='smtp.gmail.com' WHERE prmNombre='mail.smtp.host';
UPDATE PARAMETRO SET prmValor='25' WHERE prmNombre='mail.smtp.port'
UPDATE PARAMETRO SET prmValor='soporte.ti@asopagos.com' WHERE prmNombre='mail.smtp.from';
UPDATE PARAMETRO SET prmValor='2592000000' WHERE prmNombre ='TIEMPO_REINTEGRO';
UPDATE PARAMETRO SET prmValor='TARJETA' WHERE prmNombre='CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE';
UPDATE PARAMETRO SET prmValor='/SFTP' WHERE prmNombre='FTP_ARCHIVOS_DESCUENTO_URL_ARCHIVOS';
UPDATE PARAMETRO set prmValor='d52957da-c2d1-4a60-987c-f7196bce4a4f' where prmNombre='ARCHIVO_PLANTILLA_EJEMPLO_EXCEL_CARGUE_MASIVO_122'
--
UPDATE CONSTANTE SET cnsValor='FUNCIONALES' WHERE cnsNombre='CAJA_COMPENSACION_SITE';
UPDATE CONSTANTE SET cnsValor='euNuWPuienBrq2t/lEnpCw3f3IpFuQRA' WHERE cnsNombre='KEY';
UPDATE CONSTANTE SET cnsValor='1' WHERE cnsNombre='CAJA_COMPENSACION_ID';
UPDATE CONSTANTE SET cnsValor='CCF11' WHERE cnsNombre='CAJA_COMPENSACION_CODIGO';
UPDATE CONSTANTE SET cnsValor='http://10.0.1.5:8080/alfresco' WHERE cnsNombre='ECM_HOST';
UPDATE CONSTANTE SET cnsValor='admin' WHERE cnsNombre='ECM_USERNAME';
UPDATE CONSTANTE SET cnsValor='SK-[:gq{1S' WHERE cnsNombre='ECM_PASSWORD'
UPDATE CONSTANTE SET cnsValor='http://10.0.1.10/business-central' WHERE cnsNombre='BPMS_BUSINESS_CENTRAL_ENDPOINT';
UPDATE CONSTANTE SET cnsValor='http://10.0.1.10:8082/auth/' WHERE cnsNombre='IDM_SERVER_URL';
UPDATE CONSTANTE SET cnsValor='http://10.0.1.10:8082/auth/realms/{realm}' WHERE cnsNombre='KEYCLOAK_ENDPOINT'; 
UPDATE CONSTANTE SET cnsValor='cd5f3ee7-39ad-4275-9e8c-cfeeae478280' WHERE cnsNombre='IDM_CLIENT_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='409e5a38-fc8c-475d-8f26-78d1fc1044b1' WHERE cnsNombre='IDM_INTEGRATION_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='a66e9334-fb15-4f7a-8858-3584d2c13588' WHERE cnsNombre='IDM_INTEGRATION_WEB_PUBLIC_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='b9b1493b-384a-42dd-a6b8-bf4b980427f4' WHERE cnsNombre='IDM_EMPLEADORES_WEB_CLIENT_SECRET';
UPDATE CONSTANTE SET cnsValor='8' WHERE cnsNombre='SEC_INITIAL_CHARACTERS_PASSWORD';
