--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de CajaCompensacion
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (1,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CALDAS'),'GENERADA','CONFAMILIARES','CCF11',9);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ANTIOQUIA'),'GENERADA','CAMACOL','CCF02',19);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ANTIOQUIA'),'GENERADA','COMFENALCO ANTIOQUIA','CCF03',7);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ANTIOQUIA'),'GENERADA','COMFAMA','CCF04', NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ATLÁNTICO'),'GENERADA','CAJACOPI ATLANTICO','CCF05',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ATLÁNTICO'),'GENERADA','COMBARRANQUILLA','CCF06',14);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ATLÁNTICO'),'GENERADA','COMFAMILIAR DEL ATLANTICO','CCF07',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'BOLÍVAR'),'GENERADA','COMFENALCO CARTAGENA','CCF08',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'BOLÍVAR'),'GENERADA','COMFAMILIAR CARTAGENA','CCF09',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'BOYACÁ'),'GENERADA','COMFABOY','CCF10',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CAQUETÁ'),'GENERADA','COMFACA','CCF13',10);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CAUCA'),'GENERADA','COMFACAUCA','CCF14',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CESAR'),'GENERADA','COMFACESAR','CCF15',16);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CÓRDOBA'),'GENERADA','COMFACOR','CCF16',13);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CUNDINAMARCA'),'GENERADA','CAFAM','CCF21',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CUNDINAMARCA'),'GENERADA','COLSUBSIDIO','CCF22',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CUNDINAMARCA'),'GENERADA','COMPENSAR','CCF24',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CUNDINAMARCA'),'GENERADA','COMFACUNDI', 'CCF26',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CHOCÓ'),'GENERADA','COMFACHOCO','CCF29',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'LA GUAJIRA'),'GENERADA','COMFAMILIAR DE LA GUAJIRA','CCF30',12);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'HUILA'),'GENERADA','COMFAMILIAR HUILA','CCF32',6);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'MAGDALENA'),'GENERADA','CAJAMAG','CCF33',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'META'),'GENERADA','COFREM','CCF34',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'NARIÑO'),'GENERADA','COMFAMILIAR NARIÑO','CCF35',15);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'NORTE DE SANTANDER'),'GENERADA','COMFAORIENTE','CCF36',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'NORTE DE SANTANDER'),'GENERADA','COMFANORTE','CCF37',1);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'SANTANDER'),'GENERADA','CAFABA','CCF38',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'SANTANDER'),'GENERADA','CAJASAN','CCF39',20);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'SANTANDER'),'GENERADA','COMFENALCO SANTANDER','CCF40',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'SUCRE'),'GENERADA','COMFASUCRE','CCF41',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'QUINDIO'),'GENERADA','COMFENALCO QUINDIO','CCF43',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'RISARALDA'),'GENERADA','COMFAMILIAR RISARALDA','CCF44',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'TOLIMA'),'GENERADA','CAFASUR','CCF46',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'TOLIMA'),'GENERADA','COMFATOLIMA','CCF48',17);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'TOLIMA'),'GENERADA','COMFENALCO TOLIMA','CCF50',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'VALLE DEL CAUCA'),'GENERADA','COMFENALCO VALLE','CCF56',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'VALLE DEL CAUCA'),'GENERADA','COMFANDI','CCF57',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'PUTUMAYO'),'GENERADA','COMFAMILIAR PUTUMAYO','CCF63',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),'GENERADA','CAJASAI','CCF64',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'AMAZONAS'),'GENERADA','CAFAMAZ','CCF65',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'ARAUCA'),'GENERADA','COMFIAR','CCF67',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'VAUPÉS'),'GENERADA','COMCAJA','CCF68',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'VICHADA'),'GENERADA','COMCAJA','CCF68',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'GUAVIARE'),'GENERADA','COMCAJA','CCF68',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'GUAINÍA'),'GENERADA','COMCAJA','CCF68',NULL);
INSERT CajaCompensacion (ccfSocioAsopagos,ccfHabilitado,ccfDepartamento,ccfMetodoGeneracionEtiquetas,ccfNombre,ccfCodigo,ccfCodigoRedeban) VALUES (0,1,(SELECT dpto.depId FROM Departamento dpto WHERE dpto.depNombre = 'CASANARE'),'GENERADA','COMFACASANARE','CCF69',NULL);


