--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de PilaDiasFestivos
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Año Nuevo','2014-01-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de los Reyes Magos','2014-01-13');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San José','2014-03-24');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Ramos','2014-04-13');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Jueves Santo','2014-04-17');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Viernes Santo','2014-04-18');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Pascua o Resurrección','2014-04-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día del trabajo','2014-05-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Ascensión','2014-06-02');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de Corpus Christi','2014-06-23');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San Pedro y San Pablo','2014-06-30');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día del Sagrado Corazón de Jesús','2014-06-30');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día de la independencia','2014-07-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Batalla de Boyacá','2014-08-07');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Asunción de la Virgen','2014-08-18');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Raza','2014-10-13');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de todos los Santos','2014-11-03');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Independencia de Cartagena','2014-11-17');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Inmaculada Concepción','2014-12-08');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Navidad','2014-12-25');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Año Nuevo','2015-01-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de los Reyes Magos','2015-01-12');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San José','2015-03-23');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Ramos','2015-03-29');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Jueves Santo','2015-04-02');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Viernes Santo','2015-04-03');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Pascua o Resurrección','2015-04-05');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día del trabajo','2015-05-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Ascensión','2015-05-18');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de Corpus Christi','2015-06-08');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día del Sagrado Corazón de Jesús','2015-06-15');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San Pedro y San Pablo','2015-06-29');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día de la independencia','2015-07-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Batalla de Boyacá','2015-08-07');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Asunción de la Virgen','2015-08-17');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Raza','2015-10-12');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de todos los Santos','2015-11-02');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Independencia de Cartagena','2015-11-16');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Inmaculada Concepción','2015-12-08');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Navidad','2015-12-25');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Año Nuevo','2016-01-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de los Reyes Magos','2016-01-11');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Ramos','2016-03-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San José','2016-03-21');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Jueves Santo','2016-03-24');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Viernes Santo','2016-03-25');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Domingo de Pascua o Resurrección','2016-03-27');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día del trabajo','2016-05-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Ascensión','2016-05-09');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de Corpus Christi','2016-05-30');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día del Sagrado Corazón de Jesús','2016-06-06');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San Pedro y San Pablo','2016-07-04');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día de la independencia','2016-07-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Batalla de Boyacá','2016-08-07');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Asunción de la Virgen','2016-08-15');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Raza','2016-10-17');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de todos los Santos','2016-11-07');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Independencia de Cartagena','2016-11-14');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Inmaculada Concepción','2016-12-08');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Navidad','2016-12-25');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Año Nuevo','2017-01-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de los Reyes Magos','2017-09-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San José','2017-03-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Jueves Santo','2017-04-13');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Viernes Santo','2017-04-14');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día del trabajo','2017-05-01');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Ascensión','2017-05-29');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de Corpus Christi','2017-06-19');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día del Sagrado Corazón de Jesús','2017-06-26');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de San Pedro y San Pablo','2017-07-03');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Día de la independencia','2017-07-20');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Batalla de Boyacá','2017-08-07');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Asunción de la Virgen','2017-08-21');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el Día de la Raza','2017-10-16');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por el día de todos los Santos','2017-11-06');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Festivo por la Independencia de Cartagena','2017-11-13');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Inmaculada Concepción','2017-12-08');
INSERT DiasFestivos (pifConcepto,pifFecha) VALUES ('Navidad','2017-12-25');