--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de ElementoDireccion
INSERT ElementoDireccion VALUES ('Apartamento');
INSERT ElementoDireccion VALUES ('Administración');
INSERT ElementoDireccion VALUES ('Aeropuerto');
INSERT ElementoDireccion VALUES ('Agrupación');
INSERT ElementoDireccion VALUES ('Altillo');
INSERT ElementoDireccion VALUES ('Bloque');
INSERT ElementoDireccion VALUES ('Bodega');
INSERT ElementoDireccion VALUES ('Camino');
INSERT ElementoDireccion VALUES ('Carretera');
INSERT ElementoDireccion VALUES ('Casa');
INSERT ElementoDireccion VALUES ('Célula');
INSERT ElementoDireccion VALUES ('Centro comercial');
INSERT ElementoDireccion VALUES ('Ciudadela');
INSERT ElementoDireccion VALUES ('Conjunto');
INSERT ElementoDireccion VALUES ('Conjunto residencial');
INSERT ElementoDireccion VALUES ('Comuna');
INSERT ElementoDireccion VALUES ('Consultorio');
INSERT ElementoDireccion VALUES ('Depósito');
INSERT ElementoDireccion VALUES ('Edificio');
INSERT ElementoDireccion VALUES ('Entrada');
INSERT ElementoDireccion VALUES ('Esquina');
INSERT ElementoDireccion VALUES ('Estación');
INSERT ElementoDireccion VALUES ('Etapa');
INSERT ElementoDireccion VALUES ('Exterior');
INSERT ElementoDireccion VALUES ('Finca');
INSERT ElementoDireccion VALUES ('Garaje');
INSERT ElementoDireccion VALUES ('Garaje sótano');
INSERT ElementoDireccion VALUES ('Glorieta');
INSERT ElementoDireccion VALUES ('Indicación');
INSERT ElementoDireccion VALUES ('Interior');
INSERT ElementoDireccion VALUES ('Kilómetro');
INSERT ElementoDireccion VALUES ('Local');
INSERT ElementoDireccion VALUES ('Local mezanine');
INSERT ElementoDireccion VALUES ('Lote');
INSERT ElementoDireccion VALUES ('Manzana');
INSERT ElementoDireccion VALUES ('Mezanine');
INSERT ElementoDireccion VALUES ('Módulo');
INSERT ElementoDireccion VALUES ('Oficina');
INSERT ElementoDireccion VALUES ('Parcela');
INSERT ElementoDireccion VALUES ('Parque');
INSERT ElementoDireccion VALUES ('Parqueadero');
INSERT ElementoDireccion VALUES ('Paseo');
INSERT ElementoDireccion VALUES ('Penthhouse');
INSERT ElementoDireccion VALUES ('Piso');
INSERT ElementoDireccion VALUES ('Planta');
INSERT ElementoDireccion VALUES ('Portería');
INSERT ElementoDireccion VALUES ('Predio');
INSERT ElementoDireccion VALUES ('Puente');
INSERT ElementoDireccion VALUES ('Puesto');
INSERT ElementoDireccion VALUES ('Salón Comunal');
INSERT ElementoDireccion VALUES ('Sector');
INSERT ElementoDireccion VALUES ('Semi sótano');
INSERT ElementoDireccion VALUES ('Solar');
INSERT ElementoDireccion VALUES ('Sótano');
INSERT ElementoDireccion VALUES ('Suite');
INSERT ElementoDireccion VALUES ('Súper manzana');
INSERT ElementoDireccion VALUES ('Terraza');
INSERT ElementoDireccion VALUES ('Torre');
INSERT ElementoDireccion VALUES ('Unidad');
INSERT ElementoDireccion VALUES ('Unidad residencial');
INSERT ElementoDireccion VALUES ('Urbanización');
INSERT ElementoDireccion VALUES ('Vereda');
INSERT ElementoDireccion VALUES ('Vacío');
INSERT ElementoDireccion VALUES ('Zona');