--liquibase formatted sql

--changeset clmarin:01
--comment:Actualizacion de registros de la tabla VariableComunicado
UPDATE VariableComunicado SET vcoTipoVariableComunicado='REPORTE_VARIABLE' WHERE vcoClave='${totalLiquidacion}' AND vcoPlantillaComunicado IN (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR');

--changeset squintero:02
--comment:Se adiciona campo en la tabla Empresa
ALTER TABLE Empresa ADD empFechaFiscalizacion DATE NULL;

--changeset atoro:03
--comment:Insercion de registros de la tabla ParametrizacionMetodoAsignacion
INSERT ParametrizacionMetodoAsignacion (pmaSedeCajaCompensacion,pmaProceso,pmaMetodoAsignacion,pmaUsuario,pmaGrupo,pmaSedeCajaDestino) VALUES (1,'GESTION_COBRO_MANUAL','CONSECUTIVO_TURNOS',NULL,'AnaCarApo',NULL);

--changeset jocorrea:04
--comment:Insercion de registros en la tabla Requisito
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Comunicado formal de desistimiento de postulación','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Certificado de movilización del ahorro previo emitido por entidad bancaria reconocida','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Documento que certifique el rechazo de la postulación','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Formulario solicitud de reintegro','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Comunicado formal de renuncia a subsidio asignado','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Comunicado formal por parte del hogar beneficario solicitando la prórroga del subsidio','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Comunicado de restitución de susbsidio por incumplimiento','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Comunicado formal de reembolso voluntario del subsidio','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Documento de enajenación de vivienda subsidiada','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Documento que permite la movilización del ahorro programado y/o las cesantías que le entega al solicitante','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Documento formal que certifique el ajuste y actuliazación valor SFV','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Autorización para levantar inhabilidad o sanción','HABILITADO');
INSERT Requisito (reqDescripcion,reqEstado) VALUES ('Documento de inhabilidad para recibir el subsidio de vivienda','HABILITADO');

--changeset jocorrea:05
--comment:Insercion de registros en la tabla RequisitoCajaClasificacion
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CONYUGE_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CONYUGE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_BIOLOGICO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BIOLOGICO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJASTRO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HIJASTRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_ADOPTIVO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ADOPTIVO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HERMANO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HERMANO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'MADRE_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_MADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'ABUELO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'NIETO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_NIETO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'TIO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_TIO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SOBRINO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SOBRINO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'BISABUELO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BISABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_MADRE_ADOPTANTE_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE_ADOPTANTE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'YERNO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_YERNO_NUERA',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SUEGRO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SUEGRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CUNIADO_HOGAR','CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CUNIADO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CONYUGE_HOGAR','CAMBIO_NOMBRES_APELLIDOS_CONYUGE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_BIOLOGICO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_BIOLOGICO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJASTRO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_HIJASTRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_ADOPTIVO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_ADOPTIVO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HERMANO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_HERMANO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_HOGAR','CAMBIO_NOMBRES_APELLIDOS_PADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'MADRE_HOGAR','CAMBIO_NOMBRES_APELLIDOS_MADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'ABUELO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_ABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'NIETO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_NIETO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'TIO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_TIO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SOBRINO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_SOBRINO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'BISABUELO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_BISABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_MADRE_ADOPTANTE_HOGAR','CAMBIO_NOMBRES_APELLIDOS_PADRE_ADOPTANTE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'YERNO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_YERNO_NUERA',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SUEGRO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_SUEGRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CUNIADO_HOGAR','CAMBIO_NOMBRES_APELLIDOS_CUNIADO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Comunicado formal de desistimiento de postulación'),'HOGAR','DESISTIMIENTO_POSTULACION',1,'Documento firmado por el solicitante en donde mencione explicitamente el desistimiento voluntario de la postulación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Certificado de movilización del ahorro previo emitido por entidad bancaria reconocida'),'HOGAR','MOVILIZACION_AHORRO_PREVIO_HOGAR_NO_ASIGNADO',1,'Se revisa: - Monto: Debe coincidir con la información suministrada en el formulario - Fecha de apertura: Debe coincidir con la información suministrada en el formulario - Debe ser emitida por la entidad donde se realice el Ahorro Programado para vivienda - La fecha de expedición debe ser menor a 30 días. Nota: Se exceptúan para efectos del requisito del ahorro,los hogares con ingresos hasta de dos (2) salarios mínimos legales mensuales vigentes que tengan garantizada la totalidad de la financiación de la vivienda; igualmente las familias reubicadas en el continente como solución del problema de población del departamento de San Andrés,Providencia y Santa Catalina.');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento que certifique el rechazo de la postulación'),'HOGAR','RECHAZO_DE_POSTULACION',1,'Documento firmado por el solicitante en donde mencione explicitamente el motivo del rechazo de la postulación.');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Formulario solicitud de reintegro'),'HOGAR','HABILITACION_POSTULACION_RECHAZADA',1,'Se revisa: -Formulario completamente diligenciado sin enmendaduras ni tachones -Firma del jefe de hogar');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Comunicado formal de renuncia a subsidio asignado'),'HOGAR','RENUNCIO_SUBISIDIO_ASIGNADO',1,'Documento firmado por el solicitante en donde mencione explicitamente la renuncia al subsidio asignado');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Comunicado formal por parte del hogar beneficario solicitando la prórroga del subsidio'),'HOGAR','PRORROGA_FOVIS',1,'Esta prórroga puede darse por un plazo no superior a doce (12) meses,prorrogable máximo por doce (12) meses más,es decir,que un subsidio podrá tener una vigencia máxima de 36 meses.');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Comunicado de restitución de susbsidio por incumplimiento'),'HOGAR','RESTITUCION_SUBSIDIO_INCUMPLIMIENTO',1,'Documento firmado por el solicitante en donde mencione explicitamente la restitución  al subsidio por incumplimiento');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Comunicado formal de reembolso voluntario del subsidio'),'HOGAR','REEMBOLSO_VOLUNTARIO_SUBSIDIO',1,'Documento  certifique el reembolso voluntario del subsidio');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de enajenación de vivienda subsidiada'),'HOGAR','AUTORIZACION_ENAJENACION_VIVIENDA_SUBSIDIADA',1,'Documento firmado donde certifque la enajenación de vivienda subsidiada');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'JEFE_HOGAR','CONFORMACION_NUEVO_HOGAR_JEFE_HOGAR',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CONYUGE_HOGAR','CONFORMACION_NUEVO_HOGAR_CONYUGE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_BIOLOGICO_HOGAR','CONFORMACION_NUEVO_HOGAR_BIOLOGICO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJASTRO_HOGAR','CONFORMACION_NUEVO_HOGAR_HIJASTRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HIJO_ADOPTIVO_HOGAR','CONFORMACION_NUEVO_HOGAR_ADOPTIVO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'HERMANO_HOGAR','CONFORMACION_NUEVO_HOGAR_HERMANO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_HOGAR','CONFORMACION_NUEVO_HOGAR_PADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'MADRE_HOGAR','CONFORMACION_NUEVO_HOGAR_MADRE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'ABUELO_HOGAR','CONFORMACION_NUEVO_HOGAR_ABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'NIETO_HOGAR','CONFORMACION_NUEVO_HOGAR_NIETO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'TIO_HOGAR','CONFORMACION_NUEVO_HOGAR_TIO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SOBRINO_HOGAR','CONFORMACION_NUEVO_HOGAR_SOBRINO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'BISABUELO_HOGAR','CONFORMACION_NUEVO_HOGAR_BISABUELO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'PADRE_MADRE_ADOPTANTE_HOGAR','CONFORMACION_NUEVO_HOGAR_PADRE_ADOPTANTE',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'YERNO_HOGAR','CONFORMACION_NUEVO_HOGAR_YERNO_NUERA',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'SUEGRO_HOGAR','CONFORMACION_NUEVO_HOGAR_SUEGRO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Copia del documento de identidad'),'CUNIADO_HOGAR','CONFORMACION_NUEVO_HOGAR_CUNIADO',1,'Tarjeta de identidad para menores de 18 años de edad,cédula de ciudadanía o cédula de extranjería para mayores de 18 años de edad. Se revisa: -No debe tener tachones o enmendaduras -El tipo y número de documento de identidad deben coincidir con el registrado en el formulario de afiliación -Los nombres y apellidos deben corresponder a los registrados en el formulario de afiliación -La fecha de nacimiento debe corresponder a la registrada en el formulario de afiliación');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento que permite la movilización del ahorro programado y/o las cesantías que le entega al solicitante'),'HOGAR','MOVILIZACION_AHORRO_PREVIO_PAGO_OFERENTE',1,'Documento emitido por entidad bancaria en el que certifique: - Nombre completo del titular de la cuenta - Tipo y número de documento de identificación - Fecha de movilización - Tipo de cuenta - Número de cuenta - Fecha de expedición del certificado');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento formal que certifique el ajuste y actuliazación valor SFV'),'HOGAR','AJUSTE_ACTUALIZACION_VALOR_SFV',1,'Cuando se presente la novedad se deben cosiderar los siguientes campos para hacer el cálculo del Valor SFV: - Fecha de desembolso del subsidio - Valor del IPC de los años que han transcurrido - Monto desembolsado - Fecha de la solicitud (de la novedad)');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'JEFE_HOGAR','LEVANTAR_INHABILIDAD_SANCION_JEFE_HOGAR',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'CONYUGE_HOGAR','LEVANTAR_INHABILIDAD_SANCION_CONYUGE',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'HIJO_BIOLOGICO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_BIOLOGICO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'HIJASTRO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_HIJASTRO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'HIJO_ADOPTIVO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_ADOPTIVO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'HERMANO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_HERMANO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'PADRE_HOGAR','LEVANTAR_INHABILIDAD_SANCION_PADRE',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'MADRE_HOGAR','LEVANTAR_INHABILIDAD_SANCION_MADRE',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'ABUELO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_ABUELO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'NIETO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_NIETO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'TIO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_TIO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'SOBRINO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_SOBRINO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'BISABUELO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_BISABUELO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'PADRE_MADRE_ADOPTANTE_HOGAR','LEVANTAR_INHABILIDAD_SANCION_PADRE_ADOPTANTE',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'YERNO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_YERNO_NUERA',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'SUEGRO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_SUEGRO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Autorización para levantar inhabilidad o sanción'),'CUNIADO_HOGAR','LEVANTAR_INHABILIDAD_SANCION_CUNIADO',1,'Documento formal donde ceritifique el levantamiento de la inhabilidad o sanción');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_HOGAR',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'JEFE_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_JEFE_HOGAR',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'CONYUGE_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_CONYUGE',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'HIJO_BIOLOGICO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_BIOLOGICO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'HIJASTRO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_HIJASTRO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'HIJO_ADOPTIVO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_ADOPTIVO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'HERMANO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_HERMANO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'PADRE_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_PADRE',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'MADRE_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_MADRE',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'ABUELO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_ABUELO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'NIETO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_NIETO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'TIO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_TIO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'SOBRINO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_SOBRINO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'BISABUELO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_BISABUELO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'PADRE_MADRE_ADOPTANTE_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_PADRE_ADOPTANTE',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'YERNO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_YERNO_NUERA',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'SUEGRO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_SUEGRO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');
INSERT RequisitoCajaClasificacion (rtsEstado,rtsRequisito,rtsClasificacion,rtsTipoTransaccion,rtsCajaCompensacion,rtsTextoAyuda) VALUES ('OBLIGATORIO',(SELECT reqId FROM Requisito WHERE reqDescripcion = 'Documento de inhabilidad para recibir el subsidio de vivienda'),'CUNIADO_HOGAR','REGISTRAR_INHABILIDAD_SUBSIDIO_CUNIADO',1,'Documento firmado por el solicitante en donde mencione explicitamente la inhabilidad para recibir el subsidio de vivienda');

--changeset hhernandez:06
--comment:Se eliminan llaves foraneas y primarias de las tablas
ALTER TABLE TransaccionFallidaOperacionSubsidio DROP CONSTRAINT PK_TransaccionFallidaOperacionSubsidio_tfoId;
ALTER TABLE TransaccionFallidaOperacionSubsidio DROP CONSTRAINT FK_TransaccionFallidaOperacionSubsidio_tfoRegistroOperacionesSubsidio;
ALTER TABLE TransaccionFallidaOperacionSubsidio DROP CONSTRAINT FK_TransaccionFallidaOperacionSubsidio_tfoTransaccionesFallidas;
ALTER TABLE RegistroOperacionesSubsidio DROP CONSTRAINT PK_RegistroOperacionesSubsidio_rosId;
ALTER TABLE RegistroOperacionesSubsidio DROP CONSTRAINT FK_RegistroOperacionesSubsidio_rosAdministradorSubsidio;

--changeset hhernandez:07
--comment:Se cambia de nombre de la tabla RegistroOperacionesSubsidio a RegistroOperacionTransaccionSubsidio
EXEC sp_rename 'RegistroOperacionesSubsidio', 'RegistroOperacionTransaccionSubsidio';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosId', 'rotId', 'COLUMN';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosAdministradorSubsidio', 'rotAdministradorSubsidio', 'COLUMN';
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CK_RegistroOperacionesSubsidio_rosTipoOperacion')) ALTER TABLE dbo.RegistroOperacionTransaccionSubsidio DROP CONSTRAINT CK_RegistroOperacionesSubsidio_rosTipoOperacion;
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosTipoOperacion', 'rotTipoOperacion', 'COLUMN';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosFechaHoraOperacion', 'rotFechaHoraOperacionTransaccion', 'COLUMN';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosUsuarioOperacion', 'rotUsuarioOperacionTransaccion', 'COLUMN';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosParametrosIn', 'rotParametrosIn', 'COLUMN';
EXEC sp_rename 'RegistroOperacionTransaccionSubsidio.rosParametrosOut', 'rotParametrosOut', 'COLUMN';
ALTER TABLE RegistroOperacionTransaccionSubsidio ALTER COLUMN rotTipoOperacion VARCHAR(65) NULL;
ALTER TABLE RegistroOperacionTransaccionSubsidio ADD rotTipoTransaccion VARCHAR(60);
ALTER TABLE RegistroOperacionTransaccionSubsidio ADD CONSTRAINT PK_RegistroOperacionTransaccionSubsidio_rotId PRIMARY KEY (rotId);
ALTER TABLE RegistroOperacionTransaccionSubsidio ADD CONSTRAINT FK_RegistroOperacionTransaccionSubsidio_rotAdministradorSubsidio FOREIGN KEY (rotAdministradorSubsidio) REFERENCES AdministradorSubsidio(asuId);

--changeset hhernandez:08
--comment:Se cambia de nombre de la tabla TransaccionFallidaOperacionSubsidio a TransaccionFallidaOperacTransacSubsidio
EXEC sp_rename 'TransaccionFallidaOperacionSubsidio', 'TransaccionFallidaOperacTransacSubsidio';
EXEC sp_rename 'TransaccionFallidaOperacTransacSubsidio.tfoRegistroOperacionesSubsidio', 'tfoRegistroOperacionTransaccionSubsidio', 'COLUMN';
ALTER TABLE TransaccionFallidaOperacTransacSubsidio ADD CONSTRAINT PK_TransaccionFallidaOperacTransacSubsidio_tfoId PRIMARY KEY  (tfoId);
ALTER TABLE TransaccionFallidaOperacTransacSubsidio ADD CONSTRAINT FK_TransaccionFallidaOperacTransacSubsidio_tfoRegistroOperacionTransaccionSubsidio FOREIGN KEY (tfoRegistroOperacionTransaccionSubsidio) REFERENCES RegistroOperacionTransaccionSubsidio(rotId);
ALTER TABLE TransaccionFallidaOperacTransacSubsidio ADD CONSTRAINT FK_TransaccionFallidaOperacTransacSubsidio_tfoTransaccionesFallidasSubsidio FOREIGN KEY (tfoTransaccionesFallidasSubsidio) REFERENCES TransaccionesFallidasSubsidio(tfsId);

--changeset rlopez:09
--comment:Se adiciona campos en la tabla SolicitudLiquidacionSubsidio
ALTER TABLE SolicitudLiquidacionSubsidio ADD slsConsideracionAporteDesembolso BIT NULL; 
ALTER TABLE SolicitudLiquidacionSubsidio ADD slsTipoDesembolso VARCHAR(40) NULL;

--changeset hhernandez:10
--comment:Se modifica campo en la tabla RegistroOperacionTransaccionSubsidio
ALTER TABLE RegistroOperacionTransaccionSubsidio ALTER COLUMN rotUsuarioOperacionTransaccion VARCHAR(255) NOT NULL; 
