--liquibase formatted sql

--changeset borozco:01
--comment:Se adicionan campos en las tablas Empleador y RolAfiliado
ALTER TABLE Empleador ADD empMarcaExpulsion VARCHAR (22) NULL;
ALTER TABLE RolAfiliado ADD roaMarcaExpulsion VARCHAR (22) NULL;

--changeset clmarin:02
--comment: Se eliminan registros en las tablas VariableComunicado y PlantillaComunicado
DELETE FROM VariableComunicado WHERE vcoPlantillaComunicado IN (SELECT pcoId FROM PlantillaComunicado WHERE pcoEtiqueta='NTF_NO_REC_APO_CNS');
DELETE FROM VariableComunicado WHERE vcoPlantillaComunicado IN (SELECT pcoId FROM PlantillaComunicado WHERE pcoEtiqueta='SUS_NTF_NO_PAG_CNS');
DELETE FROM PlantillaComunicado WHERE pcoEtiqueta='NTF_NO_REC_APO_CNS';
DELETE FROM PlantillaComunicado WHERE pcoEtiqueta='SUS_NTF_NO_PAG_CNS';

--changeset clmarin:03
--comment: Insercion en la tabla PlantillaComunicado
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES('Consolidado','Cuerpo','Encabezado','Mensaje','Consolidado','Pie','CONSOLIDADO') ;
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES('Carta persona expulsada','Cuerpo','Encabezado','Mensaje','Carta persona expulsada','Pie','CAR_PER_EXP') ;
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES('Notificación por cancelación de publicación en edicto para gestión de cobro de aportantes','Cuerpo','Encabezado','Mensaje','Notificación por cancelación de publicación en edicto para gestión de cobro de aportantes','Pie','NTF_CCL_PUB_EDC') ;

--changeset clmarin:04
--comment: Insercion y actualizacion de las tablas VariableComunicado y PlantillaComunicado - Variables 
--CONSOLIDADO
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${consolidado}','0','Consolidado','Comunicado que se genera de forma consolidada ','REPORTE_VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CONSOLIDADO') ) ;
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${consolidado}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${consolidado}') WHERE pcoEtiqueta = 'CONSOLIDADO';

--changeset clmarin:05
--comment: Insercion y actualizacion de las tablas VariableComunicado y PlantillaComunicado - Variables 
--CAR_PER_EXP
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','0','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreYApellidosAfiliadoPrincipal}','0','Nombre y Apellidos Afiliado Principal','Nombres y apellidos del afiliado principal asociado a la solicitud','VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccion}','0','Dirección','Dirección de la empresa relacionada al representante legal','VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefono}','0','Teléfono','Teléfono fijo o Celular capturado en Información de representante legal','VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudad}','0','Ciudad','Ciudad donde se encuentra el representante legal','VARIABLE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP') ) ;
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${fechaDelSistema}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${fechaDelSistema}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${nombreYApellidosAfiliadoPrincipal}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${nombreYApellidosAfiliadoPrincipal}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${direccion}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${direccion}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${telefono}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${telefono}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${ciudad}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${ciudad}') WHERE pcoEtiqueta = 'CAR_PER_EXP';

--changeset clmarin:06
--comment: Insercion y actualizacion de las tablas VariableComunicado y PlantillaComunicado - Constantes 
--CAR_PER_EXP
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','responsable caja de compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo del responsable del envío del comunicado en la caja','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP')) ;
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${nombreCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${nombreCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${logoDeLaCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${logoDeLaCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${departamentoCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${departamentoCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${ciudadCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${ciudadCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${direccionCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${direccionCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${telefonoCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${telefonoCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${webCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${webCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${logoSuperservicios}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${logoSuperservicios}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${responsableCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${responsableCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo ,'<br  /> <p>${cargoResponsableCcf}</p>'),pcoMensaje = CONCAT(pcoMensaje,'<br /> ${cargoResponsableCcf}') WHERE pcoEtiqueta = 'CAR_PER_EXP';

--changeset clmarin:07
--comment: Insercion y actualizacion de las tablas VariableComunicado y PlantillaComunicado - Variables 
--NTF_CCL_PUB_EDC
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','0','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreUsuarioNotificacion}','0','Nombre Usuario Notificación','Nombre del usuario que realizó la tarea de notificación por edicto','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC') ) ;
INSERT VariableComunicado (vcoClave,vcoOrden,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${tabla}','0','Tabla','Tabla con los aportante a los cuales no se les aplicará publicación en el edicto','REPORTE_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC') ) ;
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${fechaDelSistema}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${fechaDelSistema}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${nombreUsuarioNotificacion}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${nombreUsuarioNotificacion}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${tabla}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${tabla}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';

--changeset clmarin:08
--comment: Insercion y actualizacion de las tablas VariableComunicado y PlantillaComunicado - Constantes 
--NTF_CCL_PUB_EDC
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','responsable caja de compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo del responsable del envío del comunicado en la caja','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC')) ;
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${nombreCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${nombreCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${logoDeLaCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${logoDeLaCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${departamentoCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${departamentoCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${ciudadCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${ciudadCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${direccionCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${direccionCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${telefonoCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${telefonoCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${webCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${webCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${logoSuperservicios}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${logoSuperservicios}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${responsableCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${responsableCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${cargoResponsableCcf}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${cargoResponsableCcf}') WHERE pcoEtiqueta = 'NTF_CCL_PUB_EDC';

--changeset jocorrea:09
--comment: Actualizacion de registro en la tabla Constante
UPDATE Constante SET cnsValor = 'com.asopagos.coreaas.bpm.analisis_postulacion_fovis_novedad:analisis_postulacion_fovis_novedad:0.0.2-SNAPSHOT' WHERE cnsNombre = 'BPMS_PROCESS_ANALISIS_NOVEDADES_PERSONAS_FOVIS_DEPLOYMENTID';

--changeset fvasquez:10
--comment:Se adiciona campo en la tabla DocumentoCartera
ALTER TABLE DocumentoCartera ADD dcaConsecutivoLiquidacion VARCHAR(10) NULL;

--changeset fvasquez:11
--comment:Insercion de registros en la tabla ParametrizacionEjecucionProgramada
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2A','00','05','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2B','00','10','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2C','00','15','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2D','00','20','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2E','00','25','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2F','00','30','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2G','00','35','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_2H','00','40','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_LC2A','00','45','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_LC3A','00','50','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_LC4A','00','55','00','DIARIO','ACTIVO');
INSERT ParametrizacionEjecucionProgramada (pepProceso,pepHoras,pepMinutos,pepSegundos,pepFrecuencia,pepEstado) VALUES ('ASIGNACION_ACCION_LC5A','00','00','00','DIARIO','ACTIVO');

--changeset jocorrea:12
--comment:Insercion de registros en la tabla ParametrizacionNovedad
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CONYUGE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BIOLOGICO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HIJASTRO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ADOPTIVO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HERMANO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_MADRE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_NIETO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_TIO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SOBRINO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BISABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BISNIETO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE_ADOPTANTE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_YERNO_NUERA','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SUEGRO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CUNIADO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_CONYUGE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_BIOLOGICO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_HIJASTRO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_ADOPTIVO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_HERMANO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_PADRE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_MADRE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_ABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_NIETO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_TIO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_SOBRINO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_BISABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_BISNIETO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_PADRE_ADOPTANTE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_YERNO_NUERA','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_SUEGRO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NOMBRES_APELLIDOS_CUNIADO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarIntegranteHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('DESISTIMIENTO_POSTULACION','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarHogarMovilizacionAhorrosNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('MOVILIZACION_AHORRO_PREVIO_HOGAR_NO_ASIGNADO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarHogarMovilizacionAhorrosNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('RECHAZO_DE_POSTULACION','BACK','com.asopagos.novedades.fovis.convertidores.RechazarPostulacionNovedadFovis ','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('HABILITACION_POSTULACION_RECHAZADA','BACK','com.asopagos.novedades.fovis.convertidores.HabilitarPostulacionRechazadaNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('RENUNCIO_SUBISIDIO_ASIGNADO','BACK','com.asopagos.novedades.fovis.convertidores.RenunciarSubsidioAsignadoNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('PRORROGA_FOVIS','BACK','com.asopagos.novedades.fovis.convertidores.RechazarPostulacionNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('RESTITUCION_SUBSIDIO_INCUMPLIMIENTO','BACK','com.asopagos.novedades.fovis.convertidores.RestitucionSubsidioIncumplimientoNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REEMBOLSO_VOLUNTARIO_SUBSIDIO','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarHogarPorReembolsoVoluntarioSubsidio','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('AUTORIZACION_ENAJENACION_VIVIENDA_SUBSIDIADA','BACK','com.asopagos.novedades.fovis.convertidores.AutorizacionEnajenacionViviendaSubsidiadaNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_JEFE_HOGAR','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_CONYUGE','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_BIOLOGICO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_HIJASTRO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_ADOPTIVO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_HERMANO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_PADRE','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_MADRE','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_ABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_NIETO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_TIO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_SOBRINO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_BISABUELO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_BISNIETO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_PADRE_ADOPTANTE','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_YERNO_NUERA','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_SUEGRO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CONFORMACION_NUEVO_HOGAR_CUNIADO','BACK','com.asopagos.novedades.fovis.convertidores.ConformacionNuevoHogarNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('MOVILIZACION_AHORRO_PREVIO_PAGO_OFERENTE','BACK','com.asopagos.novedades.fovis.convertidores.ActualizarHogarMovilizacionAhorrosNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('AJUSTE_ACTUALIZACION_VALOR_SFV','BACK','com.asopagos.novedades.fovis.convertidores.AjusteActualizacionValorSFVNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_JEFE_HOGAR','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_CONYUGE','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_BIOLOGICO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_HIJASTRO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_ADOPTIVO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_HERMANO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_PADRE','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_MADRE','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_ABUELO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_NIETO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_TIO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_SOBRINO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_BISABUELO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_BISNIETO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_PADRE_ADOPTANTE','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_YERNO_NUERA','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_SUEGRO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('LEVANTAR_INHABILIDAD_SANCION_CUNIADO','BACK','com.asopagos.novedades.fovis.convertidores.LevantarInhabilidadSancionNovedadFovis ','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_HOGAR','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','GENERAL','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_JEFE_HOGAR','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_CONYUGE','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_BIOLOGICO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_HIJASTRO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_ADOPTIVO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_HERMANO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_PADRE','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_MADRE','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_ABUELO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_NIETO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_TIO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_SOBRINO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_BISABUELO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_BISNIETO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_PADRE_ADOPTANTE','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_YERNO_NUERA','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_SUEGRO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');
INSERT ParametrizacionNovedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('REGISTRAR_INHABILIDAD_SUBSIDIO_CUNIADO','BACK','com.asopagos.novedades.fovis.convertidores.RegistrarInhabilidadSancionNovedadFovis','INTEGRANTE_HOGAR','NOVEDADES_FOVIS_REGULAR');

--changeset clmarin:13
--comment:Insercion de registros en la tabla DestinatarioComunicado
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','NTF_NO_REC_APO');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','SUS_NTF_NO_PAG');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','AVI_INC');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','LIQ_APO_MOR');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','CIT_NTF_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','PRI_AVI_COB_PRS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','NTF_AVI');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','SEG_AVI_COB_PRS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','NTF_NO_REC_APO_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','SUS_NTF_NO_PAG_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','CAR_EMP_EXP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','CAR_PER_EXP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_CARTERA_FISICA_GENERAL','NTF_CCL_PUB_EDC');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','AVI_INC');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','LIQ_APO_MOR');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','CIT_NTF_PER');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','PRI_AVI_COB_PRS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','NTF_AVI');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','SEG_AVI_COB_PRS');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','CAR_EMP_EXP');
INSERT DestinatarioComunicado (dcoProceso,dcoEtiquetaPlantilla) VALUES ('GESTION_COBRO_ELECTRONICO','CAR_PER_EXP');
