--liquibase formatted sql

--changeset ogiral:01 
ALTER TABLE ValidacionProceso
ADD CONSTRAINT CK_ValidacionProceso_vapObjetoValidacion  CHECK   (
vapObjetoValidacion IN('PERSONA_JURIDICA','PERSONA_NATURAL','EMPLEADOR_DE_SERVICIO_DOMESTICO','PROPIEDAD_HORIZONTAL','COOPERATIVA_O_PRECOOPERATIVA_DE_TRABAJO_ASOCIADO','ENTIDAD_SIN_ANIMO_DE_LUCRO','ORGANIZACION_RELIGIOSA_O_PARROQUIA','TRABAJADOR_INDEPENDIENTE_2_POR_CIENTO','TRABAJADOR_INDEPENDIENTE_0_6_POR_CIENTO','TRABAJADOR_DEPENDIENTE','FIDELIDAD_25_ANIOS','MENOS_1_5_SM_0_POR_CIENTO','MENOS_1_5_SM_0_6_POR_CIENTO','MENOS_1_5_SM_2_POR_CIENTO','MAS_1_5_SM_0_6_POR_CIENTO','MAS_1_5_SM_2_POR_CIENTO','PENSION_FAMILIAR','CONYUGE','PADRE','MADRE','HIJO_BIOLOGICO','HIJO_ADOPTIVO','HIJASTRO','HERMANO_HUERFANO_DE_PADRES','BENEFICIARIO_EN_CUSTODIA','PADRES','HIJO','TRABAJADOR_DEPENDIENTE','TRABAJADOR_INDEPENDIENTE','PENSIONADO','EMPLEADOR'));
