apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
spec:
  type: LoadBalancer
  ports:
  - port: 61616
    targetPort: 61616
    protocol: TCP
    name: tcp
  - port: 8161
    targetPort: 8161
    protocol: TCP
    name: ui
  selector:
    app: ${project.artifactId}