--liquibase formatted sql

--changeset  ogiral:01
--comment:  Actualización nombres de check constraints
update PlantillaComunicado set pcoEtiqueta = 'ACRDS_TRMS_CDNES_PERS' where pcoEtiqueta = 'ACUERDOS_TERMINOS_Y_CONDICIONES_PERSONAS'
update PlantillaComunicado set pcoEtiqueta = 'ACRDS_TRMS_CDNES_WEB' where pcoEtiqueta = 'ACUERDOS_TERMINOS_Y_CONDICIONES_WEB'
update PlantillaComunicado set pcoEtiqueta = 'CRT_ACP_EMP' where pcoEtiqueta = 'CARTA_ACEPTACION_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'CRT_ACP_IDPE' where pcoEtiqueta = 'CARTA_ACEPTACION_INDEPENDIENTE'
update PlantillaComunicado set pcoEtiqueta = 'CRT_ACP_PNS' where pcoEtiqueta = 'CARTA_ACEPTACION_PENSIONADO'
update PlantillaComunicado set pcoEtiqueta = 'CRT_BVD_EMP' where pcoEtiqueta = 'CARTA_BIENVENIDA_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'CRT_BVD_IDPE' where pcoEtiqueta = 'CARTA_BIENVENIDA_INDEPENDIENTE'
update PlantillaComunicado set pcoEtiqueta = 'CRT_BVD_PNS' where pcoEtiqueta = 'CARTA_BIENVENIDA_PENSIONADO'
update PlantillaComunicado set pcoEtiqueta = 'CRT_ENT_PAG' where pcoEtiqueta = 'CARTA_ENTIDAD_PAGADORA'
update PlantillaComunicado set pcoEtiqueta = 'NTF_ACPT_AFL_IDPE_DSP_SUB' where pcoEtiqueta = 'NOTIFICACION_ACEPTACION_AFILIACION_INDEPENDIENTE_DESPUES_SUBSANACION'
update PlantillaComunicado set pcoEtiqueta = 'NTF_ACPT_AFL_PNS_DSP_SUB' where pcoEtiqueta = 'NOTIFICACION_ACEPTACION_AFILIACION_PENSIONADO_DESPUES_SUBSANACION'
update PlantillaComunicado set pcoEtiqueta = 'NTF_CRCN_USR_EXT' where pcoEtiqueta = 'NOTIFICACION_CREACION_USUARIO_EXITOSA'
update PlantillaComunicado set pcoEtiqueta = 'NTF_EMP_AFL_MLT_TRBW' where pcoEtiqueta = 'NOTIFICACION_EMPLEADOR_RESULTADOS_AFILIACION_MULTIPLE_TRABAJADORES_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_ENRL_AFL_EMP_WEB' where pcoEtiqueta = 'NOTIFICACION_ENROLAMIENTO_AFILIACION_EMPLEADOR_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_ENRL_AFL_IDPE_WEB' where pcoEtiqueta = 'NOTIFICACION_ENROLAMIENTO_AFILIACION_INDEPENDIENTE_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_ENRL_AFL_PNS_WEB' where pcoEtiqueta = 'NOTIFICACION_ENROLAMIENTO_AFILIACION_PENSIONADO_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_INVL_AFL_TRBW' where pcoEtiqueta = 'NOTIFICACION_INDIVIDUAL_RESULTADO_AFILIACION_TRABAJADOR_WEB_TRABAJADOR'
update PlantillaComunicado set pcoEtiqueta = 'NTF_INVL_AFL_TRBW_EMP' where pcoEtiqueta = 'NOTIFICACION_INDIVIDUAL_RESULTADOS_AFILIACION_TRABAJADORES_WEB_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'NTF_INT_AFL' where pcoEtiqueta = 'NOTIFICACION_INTENTO_AFILIACION'
update PlantillaComunicado set pcoEtiqueta = 'NTF_SBC_AFL_EMP' where pcoEtiqueta = 'NOTIFICACION_PARA_REQUERIR_SUBSANACION_SOLICITUD_AFILIACION_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RAD_AFL_EMP_WEB' where pcoEtiqueta = 'NOTIFICACION_RADICACION_SOLICITUD_AFILIACION_EMPLEADOR_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RAD_AFL_IDPE_WEB' where pcoEtiqueta = 'NOTIFICACION_RADICACION_SOLICITUD_AFILIACION_INDEPENDIENTE_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RAD_AFL_PNS_WEB' where pcoEtiqueta = 'NOTIFICACION_RADICACION_SOLICITUD_AFILIACION_PENSIONADO_WEB'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RAD_AFL_PER' where pcoEtiqueta = 'NOTIFICACION_RADICACION_SOLICITUD_AFILIACION_PERSONA'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RCHZ_AFL_IDPE_DSP_SUB' where pcoEtiqueta = 'NOTIFICACION_RECHAZO_AFILIACION_INDEPENDIENTE_DESPUES_SUBSANACION'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RCHZ_AFL_PNS_DSP_SUB' where pcoEtiqueta = 'NOTIFICACION_RECHAZO_AFILIACION_PENSIONADO_DESPUES_SUBSANACION'
update PlantillaComunicado set pcoEtiqueta = 'NTF_RECU_CNTRS_EXT' where pcoEtiqueta = 'NOTIFICACION_RECUPERACION_CONTRASENA_EXITOSA'
update PlantillaComunicado set pcoEtiqueta = 'NTF_SBC_AFL_IDPE' where pcoEtiqueta = 'NOTIFICACION_REQUERIR_SUBSANACION_SOLICITUD_AFILIACION_INDEPENDIENTE'
update PlantillaComunicado set pcoEtiqueta = 'NTF_SBC_AFL_PNS' where pcoEtiqueta = 'NOTIFICACION_REQUERIR_SUBSANACION_SOLICITUD_AFILIACION_PENSIONADO'
update PlantillaComunicado set pcoEtiqueta = 'NTF_SUB_AFL_TRB_DPT' where pcoEtiqueta = 'NOTIFICACION_REQUERIR_SUBSANACION_SOLICITUD_AFILIACION_TRABAJADOR_DEPENDIENTE'
update PlantillaComunicado set pcoEtiqueta = 'NTF_REG_BNF_WEB_IDPE' where pcoEtiqueta = 'NOTIFICACION_RESULTADOS_REGISTRO_BENEFICIARIOS_SOLICITUD_WEB_INDEPENDIENTE'
update PlantillaComunicado set pcoEtiqueta = 'NTF_REG_BNF_WEB_PNS' where pcoEtiqueta = 'NOTIFICACION_RESULTADOS_REGISTRO_BENEFICIARIOS_SOLICITUD_WEB_PENSIONADO'
update PlantillaComunicado set pcoEtiqueta = 'NTF_REG_BNF_WEB_EMP' where pcoEtiqueta = 'NOTIFICACION_RESULTADOS_REGISTRO_BENEFICIARIOS_SOLICITUD_WEB_UNA_TRABAJADOR_DIRIGIDA_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'NTF_REG_BNF_WEB_TRB' where pcoEtiqueta = 'NOTIFICACION_RESULTADOS_REGISTRO_BENEFICIARIOS_SOLICITUD_WEB_UNA_TRABAJADOR_DIRIGIDA_TRABAJADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_PROD_NSUBLE_TRB' where pcoEtiqueta = 'RECHAZO_SOLICI_AFILIAC_TRABAJADOR_DEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANABLE_DIRIGIDA_TRABAJADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_PROD_NSUBLE_EMP' where pcoEtiqueta = 'RECHAZO_SOLICI_AFILIACI_TRABAJADOR_DEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANABLE_DIRIGIDA_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_PROD_NSUB_EMP' where pcoEtiqueta = 'RECHAZO_SOLICI_AFILIACI_TRABAJADOR_DEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANADO_DIRIGIDA_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_PROD_NSUB_TRB' where pcoEtiqueta = 'RECHAZO_SOLICI_AFILIACI_TRABAJADOR_DEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANADO_DIRIGIDA_TRABAJADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_EMP_INC_VAL' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_EMPLEADOR_INCONSITENCIA_VALIDACION'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_EMP_PROD_NSUBLE' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_EMPLEADOR_POR_PRODUCTO_NO_CONFORME_NO_SUBSANABLE'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_EMP_PROD_NSUB' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_EMPLEADOR_POR_PRODUCTO_NO_CONFORME_NO_SUBSANADO'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_EMP' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_EMPRESA'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_IDPE_INC_VAL' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_INDEPENDIENTE_INCONSISTENCIA_VALIDACION'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_IDPE_PROD_NSUBLE' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_INDEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANABLE'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_IDPE_PROD_NSUB' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_INDEPENDIENTE_PRODUCTO_NO_CONFORME_NO_SUBSANADO'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_PNS_INC_VAL' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_PENSIONADO_INCONSISTENCIA_VALIDACION'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_PNS_PROD_NSUBLE' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_PENSIONADO_PRODUCTO_NO_CONFORME_NO_SUBSANABLE'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_PNS_PROD_NSUB' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_PENSIONADO_PRODUCTO_NO_CONFORME_NO_SUBSANADO'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_PER_POR_PROD_NSUBLE' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_PERSONA_POR_PRODUCTO_NO_CONFORME_NO_SUBSANABLE'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_PER_POR_PROD_NSUB' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_PERSONA_POR_PRODUCTO_NO_CONFORME_NO_SUBSANADO'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_INC_VAL_EMP' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_TRABAJADOR_DEPENDIENTE_INCONSISTENCIA_VALIDACION_CASO_EMPLEADOR'
update PlantillaComunicado set pcoEtiqueta = 'RCHZ_AFL_DPT_INC_VAL_TRAB' where pcoEtiqueta = 'RECHAZO_SOLICITUD_AFILIACION_TRABAJADOR_DEPENDIENTE_INCONSISTENCIA_VALIDACION_CASO_TRABAJADOR'


--changeset  juagonzalez:02
--comment:  Actualización RequisitoCajaClasificacion
update RequisitoCajaClasificacion set rtsTipoTransaccion = 'CAMBIO_DATOS_SUCURSAL_PRESENCIAL' where rtsTipoTransaccion='CAMBIO_DATOS_SUCURSAL_PRESENCIA'