--liquibase formatted sql

--changeset halzate-mgiraldo:01 
--comment: Actualización de tipotransaccion por enumeración
SET ANSI_PADDING ON
UPDATE CargueAfiliacionMultiple SET camTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION'
WHERE camTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_PENSIONADO_NUEVA_AFILIACION', 'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_NUEVA_AFILIACION');

UPDATE IntentoAfiliacion SET iafTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION'
WHERE iafTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_PENSIONADO_NUEVA_AFILIACION', 'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_NUEVA_AFILIACION');

UPDATE RequisitoCajaClasificacion SET rtsTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION'
WHERE rtsTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_PENSIONADO_NUEVA_AFILIACION', 'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_NUEVA_AFILIACION');

UPDATE Solicitud SET solTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_NUEVA_AFILIACION'
WHERE solTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_PENSIONADO_NUEVA_AFILIACION', 'AFILIACION_PERSONAS_WEB_INDEPENDIENTE_NUEVA_AFILIACION');


UPDATE CargueAfiliacionMultiple SET camTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'
WHERE camTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_INDEPENDIENTE_REINTEGRO', 'AFILIACION_PERSONAS_WEB_PENSIONADO_REINTEGRO');

UPDATE IntentoAfiliacion SET iafTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'
WHERE iafTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_INDEPENDIENTE_REINTEGRO', 'AFILIACION_PERSONAS_WEB_PENSIONADO_REINTEGRO');

UPDATE RequisitoCajaClasificacion SET rtsTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'
WHERE rtsTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_INDEPENDIENTE_REINTEGRO', 'AFILIACION_PERSONAS_WEB_PENSIONADO_REINTEGRO');

UPDATE Solicitud SET solTipoTransaccion='AFILIACION_PERSONAS_WEB_INDEPENDIENTE_PENSIONADO_REINTEGRO'
WHERE solTipoTransaccion IN ('AFILIACION_PERSONAS_WEB_INDEPENDIENTE_REINTEGRO', 'AFILIACION_PERSONAS_WEB_PENSIONADO_REINTEGRO');

SET ANSI_PADDING OFF

--changeset mgiraldo:03 
--comment: Creación de la tabla Catalogo
CREATE TABLE Catalogo
(
  catNombreTabla varchar(50),
  catAgrupacion varchar (30),
  catPrefijo varchar(3),
  catParametrica varchar(10)
);

--changeset ogiral:05
--comment: Creación del campo ccfCodigo en la tabla CajaCompensacion
alter table CajaCompensacion add ccfCodigo varchar(5);