--liquibase formatted sql

--changeset hhernandez:01
--comment: Se adicionan campos a la taba
ALTER TABLE dbo.AporteDetallado ADD apdCodSucursal VARCHAR(10);
ALTER TABLE dbo.AporteDetallado ADD apdNomSucursal VARCHAR(100);

--changeset jocorrea:02
--comment: Se modifican registros de la tabla ValidacionProceso
UPDATE ValidacionProceso SET vapInversa = 0 WHERE vapValidacion = 'VALIDACION_PERSONA_HIJO_ACTIVO' AND vapBloque IN ('ACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_PRESENCIAL','ACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_WEB','ACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO_DEPWEB','ACTIVAR_BENEFICIARIO_HIJASTRO_PRESENCIAL','ACTIVAR_BENEFICIARIO_HIJASTRO_WEB','ACTIVAR_BENEFICIARIO_HIJASTRO_DEPWEB','ACTIVAR_BENEFICIARIO_HERMANO_HUERFANO_PRESENCIAL','ACTIVAR_BENEFICIARIO_HERMANO_HUERFANO_WEB','ACTIVAR_BENEFICIARIO_HERMANO_HUERFANO_DEPWEB','ACTIVAR_BENEFICIO_HIJO_ADOPTIVO_PRESENCIAL','ACTIVAR_BENEFICIO_HIJO_ADOPTIVO_WEB','ACTIVAR_BENEFICIO_HIJO_ADOPTIVO_DEPWEB','ACTIVA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL','ACTIVA_BENEFICIARIO_EN_CUSTODIA_WEB','ACTIVA_BENEFICIARIO_EN_CUSTODIA_DEPWEB');

--changeset abaquero:03
--comment: Se eliminan registros de las tablas ValidatorParamValue, ValidatorParameter, ValidatorDefinition y ValidatorCatalog
DELETE FROM ValidatorParamValue WHERE id BETWEEN 2110000 AND 2119999;
DELETE FROM ValidatorParameter WHERE id BETWEEN 211000 AND 211999;
DELETE FROM ValidatorDefinition WHERE id BETWEEN 2110000 AND 2119999;
DELETE FROM ValidatorCatalog WHERE id BETWEEN 211000 AND 211999;