--liquibase formatted sql

--changeset jvelandia:01
--comment: Configuracion plantilla comunicado
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_APORTES_PILA','NTF_PAG_APT_DEP_APTE_CTZ');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_APORTES_PILA','NTF_PAG_APT_DEP_APTE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_APORTES_PILA','NTF_PAG_APT_TRC');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_APORTES_PILA','NTF_PAG_PAG_SIM');

INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 2);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 3);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 4);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 5);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 0);

INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 2);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 3);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 4);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 5);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 0);

INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 2);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 3);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 4);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 5);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 0);

INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 2);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 3);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 4);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 5);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='RECAUDO_APORTES_PILA' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 0);
