--liquibase formatted sql

--changeset jocorrea:01
--comment: Actualizacion tabla ValidacionProceso
UPDATE ValidacionProceso
SET vapInversa = '1'
WHERE vapValidacion = 'VALIDACION_PERSONA_INHABILITADA_SUBSIDIO_FOVIS'
AND vapProceso = 'NOVEDADES_FOVIS_REGULAR'
AND vapBloque IN ('LEVANTAR_INHABILIDAD_SANCION_JEFE_HOGAR',
'LEVANTAR_INHABILIDAD_SANCION_CONYUGE',
'LEVANTAR_INHABILIDAD_SANCION_BIOLOGICO',
'LEVANTAR_INHABILIDAD_SANCION_HIJASTRO',
'LEVANTAR_INHABILIDAD_SANCION_ADOPTIVO',
'LEVANTAR_INHABILIDAD_SANCION_HERMANO',
'LEVANTAR_INHABILIDAD_SANCION_PADRE',
'LEVANTAR_INHABILIDAD_SANCION_MADRE',
'LEVANTAR_INHABILIDAD_SANCION_ABUELO',
'LEVANTAR_INHABILIDAD_SANCION_NIETO',
'LEVANTAR_INHABILIDAD_SANCION_TIO',
'LEVANTAR_INHABILIDAD_SANCION_SOBRINO',
'LEVANTAR_INHABILIDAD_SANCION_BISABUELO',
'LEVANTAR_INHABILIDAD_SANCION_BISNIETO',
'LEVANTAR_INHABILIDAD_SANCION_PADRE_ADOPTANTE',
'LEVANTAR_INHABILIDAD_SANCION_YERNO_NUERA',
'LEVANTAR_INHABILIDAD_SANCION_SUEGRO',
'LEVANTAR_INHABILIDAD_SANCION_CUNIADO',
'LEVANTAR_INHABILIDAD_SANCION_HOGAR');

--changeset jocorrea:02
--comment: Actualizacion tabla ValidacionProceso
UPDATE ValidacionProceso
SET vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'
WHERE vapBloque IN ('NOVEDAD_SOLICITUD_SERVICIOS_SIN_AFILIACION_TRABAJADOR_DEPENDIENTE',
'SOLICITUD_SERVICIOS_SIN_AFILIACION_TRABAJADOR_DEPENDIENTE');

INSERT INTO ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES
('SOLICITUD_SERVICIOS_SIN_AFILIACION_TRABAJADOR_DEPENDIENTE', 'VALIDACION_TIEMPO_TRANSC_DESDE_RETIRO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'TRABAJADOR_DEPENDIENTE', 0);
