--liquibase formatted sql

--changeset jvelandia:01
--comment: Eliminacion de registros tabla PrioridadDestinatario
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL');