--liquibase formatted sql

--changeset jocampo:01
--comment: se eliminan los constraint para las tablas CarteraAgrupadora
ALTER TABLE CarteraAgrupadora DROP CONSTRAINT PK_CarteraAgrupadora_cagId

--changeset jocampo:02
--comment: Se agrega una columna temporal para la copia de los valores actuales de la llave a la que se le quitar? el IDENTITY
ALTER TABLE CarteraAgrupadora ADD cagId_new BIGINT

--changeset jocampo:03
--comment: Se copian los valores de las llaves a la columna temporal
UPDATE CarteraAgrupadora SET cagId_new = cagId

--changeset jocampo:04
--comment: Se elimina la columna de llave con IDENTITY
ALTER TABLE CarteraAgrupadora DROP COLUMN cagId

--changeset jocampo:05
--comment: Se renombra la columna
EXEC sp_rename 'dbo.CarteraAgrupadora.cagId_new', 'cagId', 'COLUMN';

--changeset jocampo:06
--comment: Se agrega la restricción de NOT NULL a los campos de llave
ALTER TABLE CarteraAgrupadora ALTER COLUMN cagId BIGINT NOT NULL

--changeset jocampo:07
--comment: Se creas de nuevo los constraint
ALTER TABLE CarteraAgrupadora ADD CONSTRAINT PK_CarteraAgrupadora_cagId PRIMARY KEY (cagId)

--changeset jocampo:08
--comment: Se crea la secuencia para el manejo de los valores de PK y de numero de operación
DECLARE @inicioSeq BIGINT
SELECT @inicioSeq = max(cagId) + 1 FROM CarteraAgrupadora
SELECT @inicioSeq = ISNULL(@inicioSeq, 1)
EXEC('CREATE SEQUENCE Sec_CarteraAgrupadora AS BIGINT START WITH ' + @inicioSeq + ' INCREMENT BY 1')
SELECT @inicioSeq = max(cagNumeroOperacion) + 1 FROM CarteraAgrupadora
SELECT @inicioSeq = ISNULL(@inicioSeq, 1)
EXEC('CREATE SEQUENCE Sec_CarteraAgrupadora_NumeroOperacion AS BIGINT START WITH ' + @inicioSeq + ' INCREMENT BY 1')

--changeset abaquero:01
--comment: Se crea la tabla de bitacora de ejecución de SPs
CREATE TABLE BitacoraEjecucionSp(
	besId bigint IDENTITY NOT NULL,
	besNombreStoredProcedure varchar(500) NOT NULL,
	besUltimoInicio datetime NOT NULL,
	besUltimoExito datetime NULL,
	besUltimoFallo datetime NULL,
	besRegistrosAfectados bigint NULL
)

--changeset jocorrea:01
--comment: Se crea la tabla de bitacora de ejecución de SPs
INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_BENEFICIARIO_EN_CUSTODIA_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HERMANO_HUERFANO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJASTRO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_ADOPTIVO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_ESCOLARIDAD_ESTUDIANTE_EDUCACION_BASICA_MEDIA_HIJO_BIOLOGICO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0);

INSERT ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_DEPWEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_DEPENDIENTE_WEB', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_PRESENCIAL', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_BENEFICIARIO_EN_CUSTODIA_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'BENEFICIARIO_EN_CUSTODIA', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HERMANO_HUERFANO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HERMANO_HUERFANO_DE_PADRES', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJASTRO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJASTRO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_ADOTIVO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJO_ADOPTIVO', 0),
('NOVEDAD_ACTUALIZACION_CERTIFICADO_ESTUDIOS_HIJO_BIOLOGICO_WEB', 'VALIDACION_HIJO_ACTIVO', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO', '1', 'HIJO_BIOLOGICO', 0);

