
--SE RETIRA VALIDACION EN PROCESO DE RETIRO, SEGUN FUNCIONAL NO VA ESTA VALIDACION 64739
delete ValidacionProceso where vapBloque='INACTIVAR_BENEFICIOS_PADRE_PRESENCIAL' and vapValidacion='VALIDACION_ESTADO_PADRE' 
AND vapProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND vapObjetoValidacion='PADRE'