--liquibase formatted sql

--changeset dsuesca:01
--comment: 
IF NOT EXISTS (SELECT * FROM sys.types WHERE is_table_type = 1 AND name = 'TY_GrupoFamiliar')
		CREATE TYPE dbo.TY_GrupoFamiliar AS table(grfId BIGINT);
		
--changeset mosorio:02
--comment: Actualizaciones PlantillaComunicado
UPDATE PlantillaComunicado 
SET pcoCuerpo = 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />',
pcoMensaje = 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />'
WHERE pcoId = (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB');

UPDATE PlantillaComunicado 
SET pcoCuerpo = 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />',
pcoMensaje = 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />'
WHERE pcoId = (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB');

--changeset mosorio:03
--comment: Actualizaciones PlantillaComunicado
UPDATE PlantillaComunicado 
SET pcoCuerpo = 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />',
pcoMensaje = 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br />'
WHERE pcoId = (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB');