--liquibase formatted sql

--changeset abaquero:01
--comment: Ampliación de los campos de la BitacoraCartera
ALTER TABLE BitacoraCartera ALTER COLUMN bcaActividad VARCHAR(50)
ALTER TABLE BitacoraCartera ALTER COLUMN bcaResultado VARCHAR(40)
ALTER TABLE BitacoraCartera ALTER COLUMN bcaMedio VARCHAR(20)
ALTER TABLE BitacoraCartera ALTER COLUMN bcaTipoSolicitante VARCHAR(20)

--changeset abaquero:02
--comment: Ampliación de los campos de la BitacoraCartera en buffer auditoría
ALTER TABLE aud.BitacoraCartera_aud ALTER COLUMN bcaActividad VARCHAR(50)
ALTER TABLE aud.BitacoraCartera_aud ALTER COLUMN bcaResultado VARCHAR(40)
ALTER TABLE aud.BitacoraCartera_aud ALTER COLUMN bcaMedio VARCHAR(20)
ALTER TABLE aud.BitacoraCartera_aud ALTER COLUMN bcaTipoSolicitante VARCHAR(20)

--changeset squintero:03
--comment: 
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAepTiempoProcesoSolicitud}','bpm aep tiempo proceso solicitud','afiliación empleador presencial tiempo de proceso de solicitud','BPM_AEP_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAepTiempoSolPendienteDocumentos}','bpm aep tiempo sol pendiente documentos','afiliación empleador tiempo solicitud pendiente documentos físicos','BPM_AEP_TIEMPO_SOL_PENDIENTE_DOCUMENTOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAepTiempoAsignacionBack}','bpm aep tiempo asignacion back','afiliación empleador presencial tiempo de proceso de solicitud back','BPM_AEP_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAewTiempoProcesoSolicitud}','bpm aew tiempo proceso solicitud','bpm afiliación empresa web tiempo proceso solicitud','BPM_AEW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AEW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAewTiempoAsignacionBack}','bpm aew tiempo asignacion back','afiliación empleador web tiempo asignación back','BPM_AEW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AEW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAppTiempoProcesoSolicitud}','bpm app tiempo proceso solicitud','afiliación persona presencial tiempo proceso solicitud','BPM_APP_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAppTiempoSolPendienteDocumentos}','bpm app tiempo sol pendiente documentos','afiliación personas presencial solicitud pendiente documentos','BPM_APP_TIEMPO_SOL_PENDIENTE_DOCUMENTOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_ASE')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAppTiempoAsignacionBack}','bpm app tiempo asignacion back','Afiliación persona presencial tiempo asignación back','BPM_APP_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAdwTiempoProcesoSolicitud}','bpm adw tiempo proceso solicitud','afiliación dependiente web tiempo proceso solicitud','BPM_ADW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_ADW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAdwTiempoAsignacionBack}','bpm adw tiempo asignacion back','Afiliación dependiente web tiempo asignación back','BPM_ADW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_ADW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAipwTiempoProcesoSolicitud}','bpm aipw tiempo proceso solicitud','afiliación independiente web tiempo proceso solicitud','BPM_AIPW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AIPW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAipwTiempoAsignacionBack}','bpm aipw tiempo asignacion back','afiliación independiente web tiempo asignación back','BPM_AIPW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AIPW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNepTiempoProcesoSolicitud}','bpm nep tiempo proceso solicitud','novedad empresa presencial tiempo proceso solicitud','BPM_NEP_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNepTiempoSolPendienteDocumentos}','bpm nep tiempo sol pendiente documentos','novedad empresa presencial tiempo solicitud pendiente documentos','BPM_NEP_TIEMPO_SOL_PENDIENTE_DOCUMENTOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_ASE')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNepTiempoAsignacionBack}','bpm nep tiempo asignacion back','novedad empresa presencial tiempo asignación back','BPM_NEP_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNewTiempoProcesoSolicitud}','bpm new tiempo proceso solicitud','novedad empleador web tiempo proceso solicitud','BPM_NEW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NEW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNewTiempoAsignacionBack}','bpm new tiempo asignacion back','novedad empleador web tiempo asignación back','BPM_NEW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NEW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNppTiempoProcesoSolicitud}','bpm npp tiempo proceso solicitud','novedad persona presencial tiempo proceso solicitud','BPM_NPP_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNppTiempoSolPendienteDocumentos}','bpm npp tiempo sol pendiente documentos','novedad persona presencial tiempo sollicitud pendiente documentos','BPM_NPP_TIEMPO_SOL_PENDIENTE_DOCUMENTOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_ASE')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNppTiempoAsignacionBack}','bpm npp tiempo asignacion back','novedad persona presencial tiempo asignación back','BPM_NPP_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNdwTiempoProcesoSolicitud}','bpm ndw tiempo proceso solicitud','novedad dependiente web tiempo proceso solicitud','BPM_NDW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NDW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNdwTiempoAsignacionBack}','bpm ndw tiempo asignacion back','novedad dependiente web tiempo asignación back','BPM_NDW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NDW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNpwTiempoProcesoSolicitud}','bpm npw tiempo proceso solicitud','novedad persona web tiempo proceso solicitud','BPM_NPW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NPW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmNpwTiempoAsignacionBack}','bpm npw tiempo asignacion back','novedad persona web tiempo asignación back','BPM_NPW_TIEMPO_ASIGNACION_BACK','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_NPW_TIM_GSB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAmTiempoProcesoSolicitud}','bpm am tiempo proceso solicitud','aporte manual tiempo proceso solicitud','BPM_AM_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AM_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmAmTiempoPendienteInformacion}','bpm am tiempo pendiente informacion','aporte manual tiempo pendiente información','BPM_AM_TIEMPO_PENDIENTE_INFORMACION','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_AM_TIM_PI')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmDaTiempoProcesoSolicitud}','bpm da tiempo proceso solicitud','devolución aporte tiempo proceso solicitud','BPM_DA_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_DA_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmDaTiempoPendienteInformacion}','bpm da tiempo pendiente informacion','devolución aporte tiempo pendiente información','BPM_DA_TIEMPO_PENDIENTE_INFORMACION','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_DA_TIM_PI')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmCaTiempoProcesoSolicitud}','bpm ca tiempo proceso solicitud','corrección aporte tiempo proceso solicitud','BPM_CA_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_CA_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmCraycoTiempoProcesoSolicitud}','bpm crayco tiempo proceso solicitud','cierre recaudo aporte tiempo proceso solicitud','BPM_CRAYCO_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_CRAYCO_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmPfpTiempoProcesoSolicitud}','bpm pfp tiempo proceso solicitud','postulación fovis presencial tiempo proceso solicitud','BPM_PFP_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_PFP_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmPfpTiempoPendGestionCruces}','bpm pfp tiempo pend gestion cruces','postulación fovis presencial tiempo pendiente gestión cruces','BPM_PFP_TIEMPO_PEND_GESTION_CRUCES','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_PFP_TIM_PGC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmPfwTiempoProcesoSolicitud}','bpm pfw tiempo proceso solicitud','postulación fovis web tiempo proceso solicitud','BPM_PFW_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_PFW_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmPfwTiempoPendGestionCruces}','bpm pfw tiempo pend gestion cruces','postulación fovis web tiempo pendiente gestión cruces','BPM_PFW_TIEMPO_PEND_GESTION_CRUCES','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_PFW_TIM_PGC')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmLmsmTiempoProcesoSolicitud}','bpm lmsm tiempo proceso solicitud','liquidación masiva subsidio monetario tiempo proceso solicitud','BPM_LMSM_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_LMSM_TIM_PS')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${bpmLpesmTiempoProcesoSolicitud}','bpm lpesm tiempo proceso solicitud','liquidación y pago específico de subsidio monetario tiempo proceso solicitud','BPM_LPESM_TIEMPO_PROCESO_SOLICITUD','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_AVI_LPESM_TIM_PS')) ;

UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAepTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAepTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_AEP_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAepTiempoSolPendienteDocumentos}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAepTiempoSolPendienteDocumentos}') WHERE pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAepTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAepTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAewTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAewTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_AEW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAewTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAewTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_AEW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAppTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAppTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_APP_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAppTiempoSolPendienteDocumentos}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAppTiempoSolPendienteDocumentos}') WHERE pcoEtiqueta = 'COM_AVI_APP_TIM_ASE';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAppTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAppTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_APP_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAdwTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAdwTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_ADW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAdwTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAdwTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_ADW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAipwTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAipwTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_AIPW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAipwTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAipwTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_AIPW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNepTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNepTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_NEP_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNepTiempoSolPendienteDocumentos}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNepTiempoSolPendienteDocumentos}') WHERE pcoEtiqueta = 'COM_AVI_NEP_TIM_ASE';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNepTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNepTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_NEP_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNewTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNewTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_NEW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNewTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNewTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_NEW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNppTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNppTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_NPP_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNppTiempoSolPendienteDocumentos}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNppTiempoSolPendienteDocumentos}') WHERE pcoEtiqueta = 'COM_AVI_NPP_TIM_ASE';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNppTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNppTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_NPP_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNdwTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNdwTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_NDW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNdwTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNdwTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_NDW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNpwTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNpwTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_NPW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmNpwTiempoAsignacionBack}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmNpwTiempoAsignacionBack}') WHERE pcoEtiqueta = 'COM_AVI_NPW_TIM_GSB';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAmTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAmTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_AM_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmAmTiempoPendienteInformacion}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmAmTiempoPendienteInformacion}') WHERE pcoEtiqueta = 'COM_AVI_AM_TIM_PI';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmDaTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmDaTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_DA_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmDaTiempoPendienteInformacion}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmDaTiempoPendienteInformacion}') WHERE pcoEtiqueta = 'COM_AVI_DA_TIM_PI';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmCaTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmCaTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_CA_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmCraycoTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmCraycoTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_CRAYCO_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmPfpTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmPfpTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_PFP_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmPfpTiempoPendGestionCruces}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmPfpTiempoPendGestionCruces}') WHERE pcoEtiqueta = 'COM_AVI_PFP_TIM_PGC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmPfwTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmPfwTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_PFW_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmPfwTiempoPendGestionCruces}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmPfwTiempoPendGestionCruces}') WHERE pcoEtiqueta = 'COM_AVI_PFW_TIM_PGC';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmLmsmTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmLmsmTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_LMSM_TIM_PS';
UPDATE PlantillaComunicado SET pcoCuerpo  =  CONCAT(pcoCuerpo , '<br  /> <p>${bpmLpesmTiempoProcesoSolicitud}</p>'), pcoMensaje = CONCAT(pcoMensaje, '<br /> ${bpmLpesmTiempoProcesoSolicitud}') WHERE pcoEtiqueta = 'COM_AVI_LPESM_TIM_PS';
























