
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_FECHA_NACIMIENTO_MAYOR_FECHA_AFILIACION' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_FECHA_NACIMIENTO_MAYOR_FECHA_AFILIACION', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_PERSONA_BENEFICIARIO_HIJO' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_PERSONA_BENEFICIARIO_HIJO', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_PERSONA_BENEFICIARIO_PADRE' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_PERSONA_FALLECIDA' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_PERSONA_FALLECIDA', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_PERSONA_RETIRADA_CON_SUBSANACION', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_SOLICITUD_PERSONA' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_SOLICITUD_PERSONA', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
if not exists (select 1 from ValidacionProceso where vapBloque = '25LEY' and vapValidacion = 'VALIDACION_TIEMPO_REINTEGRO_AFILIADO' and vapProceso = 'AFILIACION_PERSONAS_PRESENCIAL' and vapObjetoValidacion = 'PENSIONADO') INSERT ValidacionProceso(vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa)
VALUES ('25LEY', 'VALIDACION_TIEMPO_REINTEGRO_AFILIADO', 'AFILIACION_PERSONAS_PRESENCIAL', 'ACTIVO', 1, 'PENSIONADO', 0);
