--liquibase formatted sql

--changeset jvelandia:01
--comment: Inserts en tabla PrioridadDestinatario y delete en tablas PrioridadDestinatario y DestinatarioComunicado
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES');
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL');
DELETE DestinatarioComunicado WHERE dcoProceso='GESTION_PREVENTIVA_CARTERA' AND  dcoEtiquetaPlantilla = 'REC_PLZ_LMT_PAG_PER';
DELETE PrioridadDestinatario WHERE prdDestinatarioComunicado = (SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG') AND prdGrupoPrioridad = (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL');
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 2);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 3);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 4);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 5);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 0);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 0);