--liquibase formatted sql

--changeset mamonroy:01
--comment: 
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'BENEFICIARIO_EN_CUSTODIA';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'CONYUGE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'FIDELIDAD_25_ANIOS';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'HERMANO_HUERFANO_DE_PADRES';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'HIJASTRO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'HIJO_ADOPTIVO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'HIJO_BIOLOGICO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MADRE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MAS_1_5_SM_0_6_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MAS_1_5_SM_2_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MENOS_1_5_SM_0_6_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MENOS_1_5_SM_0_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'MENOS_1_5_SM_2_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'PADRE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'PENSION_FAMILIAR';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'PERSONA';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'TRABAJADOR_INDEPENDIENTE_0_6_POR_CIENTO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'CAMBIO_TIPO_NUMERO_DOCUMENTO_PERSONAS' AND vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD' AND vapObjetovalidacion = 'TRABAJADOR_INDEPENDIENTE_2_POR_CIENTO';