--liquibase formatted sql

--changeset squintero:01
--comment: Correcion Plantillas
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE')
and vcoClave = '${responsableCarteraCcf}';
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB')
and vcoClave = '${responsableCarteraCcf}';
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_PS')
and vcoClave = '${responsableCarteraCcf}';
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE')
and vcoClave = '${cargoResponsableCarteraCcf}';
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB')
and vcoClave = '${cargoResponsableCarteraCcf}';
DELETE from variableComunicado where vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_PS')
and vcoClave = '${cargoResponsableCarteraCcf}';

update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_ADW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_ADW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEP_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AEW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AIPW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AIPW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_APP_TIM_ASE');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AM_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_AM_TIM_PI');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_CRAYCO_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_CA_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_DA_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_DA_TIM_PI');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_LMSM_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_LPESM_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NDW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NDW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NEP_TIM_ASE');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NEW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NEW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NPP_TIM_ASE');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NPW_TIM_GSB');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_NPW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_PFP_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_PFP_TIM_PGC');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_PFW_TIM_PS');
update variableComunicado set vcoClave = '${numeroDeRadicacion}', vcoDescripcion = 'Número de radicado de la solicitud', vcoNombre = 'Número de radicación' where vcoClave = '${solicitudDeNovedad}' and vcoPlantillaComunicado = (select pcoId from plantillaComunicado where pcoEtiqueta = 'COM_AVI_PFW_TIM_PGC');

update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_ADW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_ADW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AEP_TIM_ASE';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AEP_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AEP_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AEW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AEW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AIPW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AIPW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_APP_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_APP_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_APP_TIM_ASE';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AM_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_AM_TIM_PI';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_CRAYCO_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_CA_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_DA_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_DA_TIM_PI';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_LMSM_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_LPESM_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NDW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NDW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NEP_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NEP_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NEP_TIM_ASE';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NEW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NEW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NPP_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NPP_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NPP_TIM_ASE';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NPW_TIM_GSB';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_NPW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_PFP_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_PFP_TIM_PGC';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_PFW_TIM_PS';
update plantillaComunicado set pcoCuerpo = REPLACE(pcoCuerpo, '${solicitudDeNovedad}', '${numeroDeRadicacion}'), pcoMensaje = REPLACE(pcoMensaje, '${solicitudDeNovedad}', '${numeroDeRadicacion}') where pcoEtiqueta = 'COM_AVI_PFW_TIM_PGC';

--changeset clmarin:02
--comment:
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)
VALUES(
(select dcoid from destinatariocomunicado where dcoProceso='CORRECCION_APORTES' and dcoetiquetaPlantilla='NTF_APR_COR_APT'),
(Select gprid from grupoprioridad where gprNombre = 'RESPONSABLE_DE_APORTES'), 5);