insert into ValidacionProceso(vapBloque,vapValidacion,vapProceso,vapEstadoProceso,vapOrden,vapObjetoValidacion,vapInversa)
values
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'HIJO_BIOLOGICO',0),
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'PADRE',0),
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'HERMANO_HUERFANO_DE_PADRES',0),
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'HIJASTRO',0),
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'CONYUGE',0),
('TRASLADOS','VALIDACION_PERSONA_FALLECIDA','AFILIACION_PERSONAS_PRESENCIAL','ACTIVO',1,'BENEFICIARIO_EN_CUSTODIA',0)