--liquibase formatted sql

--changeset jocorrea:01
--comment: Actualizaciones tabla ValidacionProceso
--------------------------------------------------------------------
--- 3 - Cambios en ingresos
--------------------------------------------------------------------
UPDATE ValidacionProceso 
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO'
WHERE vapValidacion = 'VALIDACION_JEFE_HOGAR_ACTIVO_6_FOVIS'
AND vapBloque IN ('NOVEDAD_CAMBIOS_INGRESOS_ABUELO',
'NOVEDAD_CAMBIOS_INGRESOS_ADOPTIVO',
'NOVEDAD_CAMBIOS_INGRESOS_BIOLOGICO',
'NOVEDAD_CAMBIOS_INGRESOS_BISABUELO',
'NOVEDAD_CAMBIOS_INGRESOS_BISNIETO',
'NOVEDAD_CAMBIOS_INGRESOS_CONYUGE',
'NOVEDAD_CAMBIOS_INGRESOS_CUNIADO',
'NOVEDAD_CAMBIOS_INGRESOS_HERMANO',
'NOVEDAD_CAMBIOS_INGRESOS_HIJASTRO',
'NOVEDAD_CAMBIOS_INGRESOS_MADRE',
'NOVEDAD_CAMBIOS_INGRESOS_NIETO',
'NOVEDAD_CAMBIOS_INGRESOS_PADRE',
'NOVEDAD_CAMBIOS_INGRESOS_PADRE_ADOPTANTE',
'NOVEDAD_CAMBIOS_INGRESOS_SOBRINO',
'NOVEDAD_CAMBIOS_INGRESOS_SUEGRO',
'NOVEDAD_CAMBIOS_INGRESOS_TIO',
'NOVEDAD_CAMBIOS_INGRESOS_YERNO_NUERA');
--------------------------------------------------------------------
-- 4 - Cambio tipo y número documento identidad
--------------------------------------------------------------------
UPDATE ValidacionProceso 
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO',
vapInversa = '1'
WHERE vapValidacion = 'VALIDACION_JEFE_HOGAR_ACTIVO_6_FOVIS'
AND vapBloque IN ('NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ABUELO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_ADOPTIVO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BIOLOGICO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BISABUELO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_BISNIETO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CONYUGE',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_CUNIADO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HERMANO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_HIJASTRO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_MADRE',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_NIETO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_PADRE_ADOPTANTE',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SOBRINO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_SUEGRO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_TIO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTOS_IDENTIDAD_YERNO_NUERA');
--------------------------------------------------------------------
-- 9 - Cambio tipo y número documento identidad
--------------------------------------------------------------------
UPDATE ValidacionProceso 
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO',
vapInversa = '1'
WHERE vapValidacion = 'VALIDACION_JEFE_HOGAR_ACTIVO_6_FOVIS'
AND vapBloque IN ('NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_ABUELO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_ADOPTIVO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_BIOLOGICO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_BISABUELO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_BISNIETO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_CONYUGE',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_CUNIADO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_HERMANO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_HIJASTRO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_MADRE',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_NIETO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_PADRE',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_PADRE_ADOPTANTE',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_SOBRINO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_SUEGRO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_TIO',
'NOVEDAD_CAMBIO_NOMBRES_APELLIDOS_YERNO_NUERA');
--------------------------------------------------------------------
-- 6 - Cambio en otros datos
--------------------------------------------------------------------
UPDATE ValidacionProceso 
SET vapValidacion = 'VALIDACION_AFILIADO_ACTIVO',
vapInversa = '1'
WHERE vapValidacion = 'VALIDACION_JEFE_HOGAR_ACTIVO_6_FOVIS'
AND vapBloque IN ('NOVEDAD_CAMBIO_OTROS_DATOS_ABUELO',
'NOVEDAD_CAMBIO_OTROS_DATOS_ADOPTIVO',
'NOVEDAD_CAMBIO_OTROS_DATOS_BIOLOGICO',
'NOVEDAD_CAMBIO_OTROS_DATOS_BISABUELO',
'NOVEDAD_CAMBIO_OTROS_DATOS_BISNIETO',
'NOVEDAD_CAMBIO_OTROS_DATOS_CONYUGE',
'NOVEDAD_CAMBIO_OTROS_DATOS_CUNIADO',
'NOVEDAD_CAMBIO_OTROS_DATOS_HERMANO',
'NOVEDAD_CAMBIO_OTROS_DATOS_HIJASTRO',
'NOVEDAD_CAMBIO_OTROS_DATOS_MADRE',
'NOVEDAD_CAMBIO_OTROS_DATOS_NIETO',
'NOVEDAD_CAMBIO_OTROS_DATOS_PADRE',
'NOVEDAD_CAMBIO_OTROS_DATOS_PADRE_ADOPTANTE',
'NOVEDAD_CAMBIO_OTROS_DATOS_SOBRINO',
'NOVEDAD_CAMBIO_OTROS_DATOS_SUEGRO',
'NOVEDAD_CAMBIO_OTROS_DATOS_TIO',
'NOVEDAD_CAMBIO_OTROS_DATOS_YERNO_NUERA');

DELETE 
FROM ValidacionProceso
WHERE vapValidacion = 'VALIDACION_JEFE_HOGAR_ACTIVO_6_FOVIS'
AND vapBloque = 'NOVEDAD_CAMBIO_OTROS_DATOS_JEFE_HOGAR';
--------------------------------------------------------------------
-- 2 - Actualización datos de contacto
--------------------------------------------------------------------
INSERT INTO ValidacionProceso (vapBloque, vapValidacion, vapProceso, vapEstadoProceso, vapOrden, vapObjetoValidacion, vapInversa) VALUES
('NOVEDAD_ACTUALIZACION_DATOS_CONTACTO_JEFE_HOGAR',NULL,'NOVEDADES_FOVIS_ESPECIAL', 'ACTIVO', '1', 'JEFE_HOGAR', '0');

--changeset jocorrea:02
--comment: se crea campo epsProcesoCancelado
ALTER TABLE EjecucionProcesoAsincrono ADD epsProcesoCancelado BIT;
ALTER TABLE aud.EjecucionProcesoAsincrono_aud ADD epsProcesoCancelado BIT;