-- Update for MAS_1_5_SM_0_6_POR_CIENTO, MAS_1_5_SM_2_POR_CIENTO, MENOS_1_5_SM_0_POR_CIENTO, MENOS_1_5_SM_0_6_POR_CIENTO, MENOS_1_5_SM_2_POR_CIENTO
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion IN ('MAS_1_5_SM_0_6_POR_CIENTO', 'MAS_1_5_SM_2_POR_CIENTO', 'MENOS_1_5_SM_0_POR_CIENTO', 'MENOS_1_5_SM_0_6_POR_CIENTO', 'MENOS_1_5_SM_2_POR_CIENTO')
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','VALIDACION_EXISTENCIA_PERSONA', 'VALIDACION_ESTADO_AFILIACION', 'VALIDACION_PERSONA_FALLECIDA_PRESENCIAL', 'VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_ES_EMPLEADOR','VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_HIJO','VALIDACION_PERSONA_HIJO_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE','VALIDACION_PERSONA_PADRE_ACTIVO', 'VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%CAMBIO_TIPO_PENSIONADO_PENSIONADO%';

-- Update for TRABAJADOR_INDEPENDIENTE
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'TRABAJADOR_INDEPENDIENTE'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','VALIDACION_PERSONA_TIENE_NOVEDAD_PERSONA_EN_CURSO','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','VALIDACION_ESTADO_AFILIACION', 'VALIDACION_PERSONA_FALLECIDA_PRESENCIAL', 'VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_ES_EMPLEADOR','VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_HIJO','VALIDACION_PERSONA_HIJO_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE','VALIDACION_PERSONA_PADRE_ACTIVO', 'VALIDACION_PERSONA_CONDICION_INVALIDEZ', 'VALIDACION_REPRESENTANTES_NO_FALLECIDOS')
AND vapBloque LIKE '%CAMBIO_TIPO_INDEPENDIENTE_SEGUN_VALOR_APORTES%';

-- Update for CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE (vapObjetoValidacion = 'TRABAJADOR_DEPENDIENTE' OR vapObjetoValidacion = 'TRABAJADOR_INDEPENDIENTE' OR vapObjetoValidacion = 'PENSIONADO')
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_ESTADO_AFILIADO_ACTIVO_INACTIVO','VALIDACION_ESTADO_AFILIACION','VALIDACION_PERSONA_EMPLEADOR','VALIDACION_PERSONA_ES_EMPLEADOR','VALIDACION_PERSONA_EMPLEADOR_ACTIVO','VALIDACION_PERSONA_BENEFICIARIO_HIJO','VALIDACION_PERSONA_HIJO_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE','VALIDACION_PERSONA_PADRE_ACTIVO','VALIDACION_PERSONA_APORTES_3_PERIODOS')
AND vapBloque LIKE '%CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO%';
---------------------------- se agregan las validaciones para la novedad de cambio admin subsidio ------------------------------------------

insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)


insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_PERSONA_FALLECIDA_ENTIDADES_EXTERNAS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)


insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_DEPENDIENTE',0)


insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_ADMINISTRADOR_SUBSIDIO_WEB','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_PRESENCIAL', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)
insert into validacionProceso values ('CAMBIO_ADMINISTRADOR_DEL_SUBSIDIO_MONETARIO_TRABAJADOR_DEPENDIENTE_WEB','VALIDACION_REPRESENTANTES_NO_FALLECIDOS', 'NOVEDADES_PERSONAS_WEB', 'ACTIVO',1,'TRABAJADOR_INDEPENDIENTE',0)

