
-- Update for CONYUGE
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'CONYUGE'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_MISMO_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_HIJO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE', 'VALIDACION_PERSONA_CONDICION_INVALIDEZ','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIARIO_CONYUGE%';

-- Update for HIJO_BIOLOGICO
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'HIJO_BIOLOGICO'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_MISMO_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIARIO_HIJO_BIOLOGICO%';

-- Update for HIJASTRO
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'HIJASTRO'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIARIO_HIJASTRO%';

-- Update for HERMANO_HUERFANO_DE_PADRES
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'HERMANO_HUERFANO_DE_PADRES'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIARIO_HUERFANO%';

-- Update for HIJO_ADOPTIVO
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'HIJO_ADOPTIVO'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIARIO_HIJO_ADOPTIVO%';

-- Update for BENEFICIARIO_EN_CUSTODIA
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'BENEFICIARIO_EN_CUSTODIA'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_PADRE', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIO_EN_CUSTODIA%';

-- Update for PADRE
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'PADRE'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIOS_PADRE%';

-- Update for MADRE
UPDATE validacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapObjetoValidacion = 'MADRE'
AND vapEstadoProceso = 'ACTIVO'
AND vapValidacion IN ('VALIDACION_PERSONA_EMPLEADOR', 'VALIDACION_PERSONA_EMPLEADOR_ACTIVO', 'VALIDACION_PERSONA_BENEFICIARIO_CONYUGE', 'VALIDACION_PERSONA_PENSIONADO', 'VALIDACION_PERSONA_INDEPENDIENTE', 'VALIDACION_PERSONA_DEPENDIENTE','VALIDACION_PERSONA_FALLECIDA_NO_PRESENCIAL')
AND vapBloque LIKE '%INACTIVAR_BENEFICIOS_MADRE%';


