--liquibase formatted sql

--changeset dsuesca:03
--comment: Se crean tablas para categorias
CREATE TABLE ParametrizacionCategoria
(
       pctId BIGINT IDENTITY NOT NULL,
       pctTipoAfiliado VARCHAR(30) NOT NULL,
       pctClasificacion VARCHAR(48),
       pctSMMLVDesde INT,
       pctSMMLVHasta INT,
       pctCategoria VARCHAR(50) NOT NULL,
       CONSTRAINT PK_ParametrizacionCategoria_pctId PRIMARY KEY (pctId)
);

INSERT INTO ParametrizacionCategoria (pctTipoAfiliado,pctClasificacion,pctSMMLVDesde,pctSMMLVHasta,pctCategoria)
VALUES
('TRABAJADOR_DEPENDIENTE',NULL,0,2,'A'),
('TRABAJADOR_DEPENDIENTE',NULL,2,4,'B'),
('TRABAJADOR_DEPENDIENTE',NULL,4,NULL,'C'),
('TRABAJADOR_DEPENDIENTE',NULL,0,2,'A'),
('PENSIONADO','FIDELIDAD_25_ANIOS',NULL,NULL,'A'),
('PENSIONADO','MENOS_1_5_SM_0_POR_CIENTO',NULL,NULL,'A'),
('PENSIONADO','MENOS_1_5_SM_2_POR_CIENTO',NULL,NULL,'A'),
('PENSIONADO','MENOS_1_5_SM_0_6_POR_CIENTO',NULL,NULL,'A'),
('PENSIONADO','MENOS_1_5_SM_0_POR_CIENTO',NULL,NULL,'A'),
('PENSIONADO','MAS_1_5_SM_0_6_POR_CIENTO',0,2,'A'),
('PENSIONADO','MAS_1_5_SM_0_6_POR_CIENTO',2,4,'B'),
('PENSIONADO','MAS_1_5_SM_0_6_POR_CIENTO',4,NULL,'C'),
('PENSIONADO','MAS_1_5_SM_2_POR_CIENTO',0,2,'A'),
('PENSIONADO','MAS_1_5_SM_2_POR_CIENTO',2,4,'B'),
('PENSIONADO','MAS_1_5_SM_2_POR_CIENTO',4,NULL,'C'),
('TRABAJADOR_INDEPENDIENTE','TRABAJADOR_INDEPENDIENTE_2_POR_CIENTO',0,4,'B'),
('TRABAJADOR_INDEPENDIENTE','TRABAJADOR_INDEPENDIENTE_2_POR_CIENTO',4,NULL,'C'),
('TRABAJADOR_INDEPENDIENTE','TRABAJADOR_INDEPENDIENTE_0_6_POR_CIENTO',0,4,'B'),
('TRABAJADOR_INDEPENDIENTE','TRABAJADOR_INDEPENDIENTE_0_6_POR_CIENTO',4,NULL,'C');
 