--liquibase formatted sql

--changeset jocampo:01
--comment: Plantillas etiqueta COM_SUB_DIS_FAL_PRO_TRA

INSERT INTO PlantillaComunicado (pcoNombre, pcoAsunto, pcoEncabezado, pcoPie, pcoCuerpo, pcoMensaje, pcoEtiqueta) VALUES('Notificación de dispersión de pagos subsidio fallecimineto programados al trabajador ó conyuge', 'Notificación de dispersión de pagos subsidio fallecimineto programados al trabajador', 'Encabezado', 'Pie', 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelTrabajador/Conyuge}</p><br /> <p>${tipoIdentificacionTrabajador/Conyuge}</p><br /> <p>${numeroIdentificacionTrabajador/Conyuge}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelTrabajador/Conyuge}</p><br /> <p>${tipoIdentificacionTrabajador/Conyuge}</p><br /> <p>${numeroIdentificacionTrabajador/Conyuge}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'COM_SUB_DIS_FAL_PRO_TRA');
-- variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreDelTrabajador/Conyuge}','Nombre del trabajador ó conyuge','Nombre del trabajador ó conyuge por el cual liquidó el subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${tipoIdentificacionTrabajador/Conyuge}','Tipo identificación trabajador ó conyuge','Tipo de identificación del trabajador ó conyuge que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroIdentificacionTrabajador/Conyuge}','Número identificación trabajador ó conyuge','Número de identificación del trabajador ó conyuge que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${municipio}','Municipio','Municipio capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamento}','Departamento','Departamento capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${periodosLiquidados}','Periodos liquidados','Periodos presentes en la liquidación','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${montoLiquidado}','Monto liquidado','Monto liquidado por el trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroDeBeneficiarios}','Número de beneficiarios','Número de beneficiarios en los periodos liquidados','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${reporteDeBeneficiarios}','Reporte de beneficiarios','Lista de beneficiarios en los periodos liquidados','REPORTE_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreFallecido}','Nombre de la persona fallecida','Nombre de la persona fallecida','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA') ) ;
-- constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_TRA')) ;

--changeset jocampo:02
--comment: Plantillas etiqueta COM_SUB_DIS_FAL_PAG_TRA

INSERT INTO PlantillaComunicado (pcoNombre, pcoAsunto, pcoEncabezado, pcoPie, pcoCuerpo, pcoMensaje, pcoEtiqueta) VALUES('Notificación de dispersión de pagos subsidio fallecimineto al trabajador ó conyuge', 'Notificación de dispersión de pagos subsidio fallecimineto al trabajador', 'Encabezado', 'Pie', 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelTrabajador/Conyuge}</p><br /> <p>${tipoIdentificacionTrabajador/Conyuge}</p><br /> <p>${numeroIdentificacionTrabajador/Conyuge}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelTrabajador/Conyuge}</p><br /> <p>${tipoIdentificacionTrabajador/Conyuge}</p><br /> <p>${numeroIdentificacionTrabajador/Conyuge}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'COM_SUB_DIS_FAL_PAG_TRA');
-- variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreDelTrabajador/Conyuge}','Nombre del trabajador ó conyuge','Nombre del trabajador ó conyuge por el cual liquidó el subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${tipoIdentificacionTrabajador/Conyuge}','Tipo identificación trabajador ó conyuge','Tipo de identificación del trabajador ó conyuge que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroIdentificacionTrabajador/Conyuge}','Número identificación trabajador ó conyuge','Número de identificación del trabajador ó conyuge que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${municipio}','Municipio','Municipio capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamento}','Departamento','Departamento capturada en Información de ubicación y correspondencia del trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos)','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${periodosLiquidados}','Periodos liquidados','Periodos presentes en la liquidación','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${montoLiquidado}','Monto liquidado','Monto liquidado por el trabajador','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroDeBeneficiarios}','Número de beneficiarios','Número de beneficiarios en los periodos liquidados','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreFallecido}','Nombre de la persona fallecida','Nombre de la persona fallecida','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA') ) ;

-- constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_TRA')) ;

--changeset jocampo:03
--comment: Plantillas etiqueta COM_SUB_DIS_FAL_PRO_ADM_SUB

INSERT INTO PlantillaComunicado (pcoNombre, pcoAsunto, pcoEncabezado, pcoPie, pcoCuerpo, pcoMensaje, pcoEtiqueta) VALUES('Notificación de dispersión de pagos subsidio fallecimineto programados al admin subsidio', 'Notificación de dispersión de pagos subsidio fallecimineto  programados al admin subsidio', 'Encabezado', 'Pie', 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios} <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios} <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'COM_SUB_DIS_FAL_PRO_ADM_SUB');
-- variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreDelAdministradorDelSubsidio}','Nombre del admin del subsidio','Nombre del admin del admin del subsidio','USUARIO_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${tipoIdentificacionAdmin}','Tipo identificación del admin del subsidio','Tipo de identificación del admin del subsidio que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroIdentificacionAdmin}','Número identificación del admin del subsidio','Número de identificación del admin del subsidio que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${municipio}','Municipio','Municipio capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamento}','Departamento','Departamento capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos) del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${periodosLiquidados}','Periodos liquidados','Periodos presentes en la liquidación','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${montoLiquidado}','Monto liquidado','Monto liquidado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroDeBeneficiarios}','Número de beneficiarios','Número de beneficiarios en los periodos liquidados','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${reporteDeBeneficiarios}','Reporte de beneficiarios','Lista de beneficiarios en los periodos liquidados','REPORTE_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreFallecido}','Nombre de la persona fallecida','Nombre de la persona fallecida','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB') ) ;
-- constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PRO_ADM_SUB')) ;

--changeset jocampo:04
--comment: Plantillas etiqueta -- COM_SUB_DIS_FAL_PAG_ADM_SUB

INSERT INTO PlantillaComunicado (pcoNombre, pcoAsunto, pcoEncabezado, pcoPie, pcoCuerpo, pcoMensaje, pcoEtiqueta) VALUES('Notificación de dispersión de pagos subsidio fallecimineto al admin subsidio', 'Notificación de dispersión de pagos subsidio fallecimineto  al admin subsidio', 'Encabezado', 'Pie', 'Cuerpo<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios} <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'Mensaje<br /> <p>${ciudadSolicitud}</p><br /> <p>${fechaDelSistema}</p><br /> <p>${nombreDelAdministradorDelSubsidio}</p><br /> <p>${tipoIdentificacionAdmin}</p><br /> <p>${numeroIdentificacionAdmin}</p><br /> <p>${direccion}</p><br /> <p>${municipio}</p><br /> <p>${departamento}</p><br /> <p>${telefono}</p><br /> <p>${periodosLiquidados}</p><br /> <p>${montoLiquidado}</p><br /> <p>${numeroDeBeneficiarios}</p><br /> <p>${reporteDeBeneficiarios} <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${departamentoCcf}</p><br /> <p>${ciudadCcf}</p><br /> <p>${direccionCcf}</p><br /> <p>${telefonoCcf}</p><br /> <p>${webCcf}</p><br /> <p>${logoSuperservicios}</p><br /> <p>${firmaResponsableCcf}</p><br /> <p>${responsableCcf}</p><br /> <p>${cargoResponsableCcf}</p><br /> <p>${nombreFallecido}</p><br /> ', 'COM_SUB_DIS_FAL_PAG_ADM_SUB');
-- variables
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadSolicitud}','Ciudad solicitud','Ciudad de la sede donde se realiza la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${fechaDelSistema}','Fecha del sistema','dd/mm/aaaa proporcionado por el sistema al generar el comunicado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreDelAdministradorDelSubsidio}','Nombre del admin del subsidio','Nombre del admin del admin del subsidio','USUARIO_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${tipoIdentificacionAdmin}','Tipo identificación del admin del subsidio','Tipo de identificación del admin del subsidio que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroIdentificacionAdmin}','Número identificación del admin del subsidio','Número de identificación del admin del subsidio que realizó la solicitud','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccion}','Dirección','Dirección capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${municipio}','Municipio','Municipio capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamento}','Departamento','Departamento capturada en Información de ubicación y correspondencia del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefono}','Teléfono','Teléfono fijo o Celular capturado en Información de ubicación y correspondencia (uno de los dos) del admin del subsidio','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${periodosLiquidados}','Periodos liquidados','Periodos presentes en la liquidación','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${montoLiquidado}','Monto liquidado','Monto liquidado','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${numeroDeBeneficiarios}','Número de beneficiarios','Número de beneficiarios en los periodos liquidados','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${reporteDeBeneficiarios}','Reporte de beneficiarios','Lista de beneficiarios en los periodos liquidados','REPORTE_VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreFallecido}','Nombre de la persona fallecida','Nombre de la persona fallecida','VARIABLE', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB') ) ;
-- constantes
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${nombreCcf}','Nombre CCF','Nombre de la caja de Compensación','NOMBRE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoDeLaCcf}','Logo de la CCF','Logotipo de la Caja de Compensación','LOGO_DE_LA_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${departamentoCcf}','Departamento CCF','Departamento de la caja de Compensación','DEPARTAMENTO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${ciudadCcf}','Ciudad CCF','Ciudad de la caja de Compensación','CIUDAD_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${direccionCcf}','Dirección CCF','Dirección de la caja de Compensación','DIRECCION_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${telefonoCcf}','Teléfono CCF','Teléfono de la caja de Compensación','TELEFONO_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${webCcf}','Web CCF','Web de la caja de Compensación','WEB_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${logoSuperservicios}','Logo SuperServicios','Logo de la caja de Compensación','LOGO_SUPERSERVICIOS','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${firmaResponsableCcf}','Firma Responsable CCF','Firma de la caja de Compensación','FIRMA_RESPONSABLE_CCF','CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${responsableCcf}','Responsable CCF','Responsable de la caja de Compensación','RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;
INSERT VariableComunicado (vcoClave,vcoNombre,vcoDescripcion,vcoNombreConstante,vcoTipoVariableComunicado,vcoPlantillaComunicado) VALUES ('${cargoResponsableCcf}','Cargo responsable CCF','Cargo de la caja de Compensación','CARGO_RESPONSABLE_CCF','USUARIO_CONSTANTE',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'COM_SUB_DIS_FAL_PAG_ADM_SUB')) ;


INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('SUBSIDIO_MONETARIO_ESPECIFICO', 'COM_SUB_DIS_PAG_EMP');
INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('SUBSIDIO_MONETARIO_ESPECIFICO', 'COM_SUB_DIS_PAG_TRA');
INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('SUBSIDIO_MONETARIO_ESPECIFICO', 'COM_SUB_DIS_PAG_ADM_SUB');

INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('LIQUIDACION_SUBSIDIO_FALLECIMIENTO', 'COM_SUB_DIS_FAL_PRO_TRA');
INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('LIQUIDACION_SUBSIDIO_FALLECIMIENTO', 'COM_SUB_DIS_FAL_PRO_ADM_SUB');

INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('LIQUIDACION_SUBSIDIO_FALLECIMIENTO', 'COM_SUB_DIS_FAL_PAG_TRA');
INSERT DestinatarioComunicado (dcoProceso, dcoEtiquetaPlantilla) VALUES ('LIQUIDACION_SUBSIDIO_FALLECIMIENTO', 'COM_SUB_DIS_FAL_PAG_ADM_SUB');
