--- GAP 89667--- NO SE EVIDENCIA EL CAMBIO DE MEDIO DE PAGO

UPDATE ValidacionProceso
SET vapEstadoProceso = 'INACTIVO'
WHERE vapValidacion ='VALIDACION_PERSONA_EMPLEADOR_ACTIVO' 
AND vapBloque in ('CAMBIAR_MEDIO_DE_PAGO_DEPENDIENTE_PRESENCIAL', 'CAMBIAR_MEDIO_DE_PAGO_ADMINISTRADOR_DE_SUBSIDIO_PRESENCIAL')