--liquibase formatted sql

--changeset fhoyos:01
--comment: Se agregan claves, constantes y parametro para los comunicados de cartera
INSERT INTO Parametro(prmNombre,prmValor,prmCargaInicio,prmSubCategoriaParametro,prmDescripcion,prmTipoDato)
VALUES('FIRMA_RESPONSABLE_CARTERA_CCF','',0,'CAJA_COMPENSACION','Corresponde a la firma del responsable de proceso de cartera','FILE');

INSERT INTO VariableComunicado(vcoClave,vcoDescripcion,vcoNombre,vcoPlantillaComunicado,vcoTipoVariableComunicado,vcoOrden,vcoNombreConstante)
VALUES
-- Carta persona expulsada - GESTION_CARTERA_FISICA_GENERAL, Carta persona expulsada (CAR_PER_EXP)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionAfiliado}', 'Número de identificación del afiliado', 'Número de identificación del afiliado', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'VARIABLE', '', ''),
('${periodos}', 'Periodos para los cuales esta en mora', 'Periodos', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'REPORTE_VARIABLE', '', ''),
('${tipoIdentificacionAfiliado}', 'Tipo de identificación del afiliado', 'Tipo de identificación del afiliado', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_PER_EXP'), 'VARIABLE', '', ''),
--Suspensión automática de servicios por mora y notificación de no recaudo, Suspensión automática de servicios por mora y notificación de no recaudo - GESTION_CARTERA_FISICA_GENERAL (SUS_NTF_NO_PAG)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${consecutivoLiquidacion}', 'Número consecutivo de la liquidación','Consecutivo Liquidación',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador','Número de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal','Número de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE','',''),
--Suspensión automática de servicios por mora y notificación de no recaudo personas, Suspensión automática de servicios por mora y notificación de no recaudo personas - GESTION_CARTERA_FISICA_GENERAL (SUS_NTF_NO_PAG_PER)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${consecutivoLiquidacion}', 'Número consecutivo de la liquidación','Consecutivo Liquidación',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'VARIABLE','',''),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${numeroIdentificacionAfiliado}', 'Número de identificación del afiliado','Número de identificación del afiliado',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'VARIABLE','',''),
('${tipoIdentificacionAfiliado}', 'Tipo de identificación del afiliado', 'Tipo de identificación del afiliado',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'VARIABLE','',''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG_PER'), 'VARIABLE','',''),
--Notificación de no recaudo de aportes personas, Notificación de no recaudo de aportes personas -  GESTION_CARTERA_FISICA_GENERAL (NTF_NO_REC_APO_PER)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${fechaVencimientoPago}', 'Fecha vencimiento del pago','Fecha de vencimiento del pago',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'VARIABLE','',''),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${numeroIdentificacionAfiliado}', 'Número de identificación del afiliado','Número de identificación del afiliado',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'VARIABLE','',''),
('${tipoIdentificacionAfiliado}', 'Tipo de identificación del afiliado', 'Tipo de identificación del afiliado',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'VARIABLE','',''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO_PER'), 'VARIABLE','',''),
--Notificación de no recaudo de aportes - GESTION_CARTERA_FISICA_GENERAL, Notificación de no recaudo de aportes (NTF_NO_REC_APO)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${fechaVencimientoPago}', 'Fecha vencimiento del pago','Fecha de vencimiento del pago',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador','Número de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal','Número de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_NO_REC_APO'), 'VARIABLE','',''),
----Liquidación de aportes en mora manual (LIQ_APO_MAN)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${celularAportante}', 'Celular en datos para envío de correspondencia (caso empleador)', 'Celular del apotante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${direccionAportante}', 'Datos para envío de correspondencia (caso empleador)', 'Dirección del aportante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${fechaLimitePago}', 'Fecha Límite de pago', 'Fecha Límite de pago', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${nombreYApellidosRepresentanteLegal}', 'Nombres y Apellidos del representante legal de la empresa', 'Nombre y Apellidos Representante Legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${telefonoAportante}', 'Teléfono fijo en datos para envío de correspondencia (caso empleador)', 'Teléfono del aportante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MAN'), 'VARIABLE', '', ''),
--Segundo aviso cobro persuasivo, Segundo aviso cobro persuasivo - GESTION_CARTERA_FISICA_GENERAL (SEG_AVI_COB_PRS)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${consecutivoLiquidacion}', 'Número consecutivo de la liquidación', 'Consecutivo Liquidación ', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE', '', ''),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador', 'Número de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SUS_NTF_NO_PAG'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor de la deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${ValorDeudaPresuntaEnLetras}', 'El valor de la deuda en letras para el aportante', 'Valor deuda presunta en letras', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'SEG_AVI_COB_PRS'), 'VARIABLE', '', ''),
--Primer aviso cobro persuasivo, Primer aviso cobro persuasivo - GESTION_CARTERA_FISICA_GENERAL (PRI_AVI_COB_PRS)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${consecutivoLiquidacion}', 'Número consecutivo de la liquidación', 'Consecutivo Liquidación ', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${fechaExpedicionActaLiquidacionAportes}', 'Fecha de expedición del Acta del Liquidación de Aportes', 'Fecha de expedición del Acta del Liquidación de Aportes', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador', 'Número de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor de la deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
('${ValorDeudaPresuntaEnLetras}', 'El valor de la deuda en letras para el aportante', 'Valor deuda presunta en letras', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'PRI_AVI_COB_PRS'), 'VARIABLE', '', ''),
--Notificación por cancelación de publicación en edicto para gestión de cobro de aportantes (NTF_CCL_PUB_EDC)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${cargoResponsableCarteraCcf}', 'Cargo responsable del proceso de cartera', 'Cargo responsable del proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','CARGO_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${responsableCarteraCcf}', 'Responsable del proceso de cartera', 'Responsable del proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_CCL_PUB_EDC'), 'CONSTANTE','','RESPONSABLE_CARTERA_CCF'),
--Liquidación de aportes en mora, Liquidación de aportes en mora GESTION_CARTERA_FISICA_GENERAL (LIQ_APO_MOR)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${celularAportante}', 'Celular en datos para envío de correspondencia (caso empleador)', 'Celular del apotante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${direccionAportante}', 'Datos para envío de correspondencia (caso empleador)', 'Dirección del aportante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${fechaLimitePago}', 'Fecha Límite de pago', 'Fecha Límite de pago', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${nombreYApellidosRepresentanteLegal}', 'Nombres y Apellidos del representante legal de la empresa', 'Nombre y Apellidos Representante Legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${telefonoAportante}', 'Teléfono fijo en datos para envío de correspondencia (caso empleador)', 'Teléfono del aportante', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'LIQ_APO_MOR'), 'VARIABLE', '', ''),
--Cierre satisfactorio convenio de pago (CRR_STC_CNV_PAG)
('${departamentoCcf}', 'Departamento de Ubicación de la Caja de Compensación', 'Departamento CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','DEPARTAMENTO_CCF'),
('${direccionCcf}', 'Dirección de la Caja de Compensación', 'Dirección CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','DIRECCION_CCF'),
('${telefonoCcf}', 'Número telefónico de la Caja de Compensación', 'Teléfono CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','TELEFONO_CCF'),
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${logoSupersubsidio}', 'Logo de la Superintendencia del Subsidio Familiar', 'Logo Supersubsidio',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'CONSTANTE','','LOGO_SUPERSUBSIDIO'),
('${numeroConvenio}', 'Número de convenio', 'Número de convenio', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número identificación representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CRR_STC_CNV_PAG'), 'VARIABLE', '', ''),
--Citación para notificación personal - GESTION_CARTERA_FISICA_GENERAL, Citación para notificación personal (CIT_NTF_PER)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador', 'Número de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'VARIABLE', '', ''),
('${periodos}', 'Periodos para los cuales esta en mora', 'Periodos', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'REPORTE_VARIABLE', '', ''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CIT_NTF_PER'), 'VARIABLE', '', ''),
--Carta a empresa expulsada, Carta a empresa expulsada - GESTION_CARTERA_FISICA_GENERAL (CAR_EMP_EXP)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${consecutivoLiquidacion}', 'Número consecutivo de la liquidación', 'Consecutivo Liquidación ', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador', 'Número de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
('${periodos}', 'Periodos para los cuales esta en mora', 'Periodos', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'REPORTE_VARIABLE', '', ''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'CAR_EMP_EXP'), 'VARIABLE', '', ''),
--Aviso de incumplimiento - GESTION_CARTERA_FISICA_GENERAL, Aviso de incumplimiento (AVI_INC)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${correoCcf}', 'Correo electronico de la caja de Compensación', 'Correo CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'CONSTANTE','','CORREO_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador', 'Número de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'VARIABLE', '', ''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal', 'Número de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'VARIABLE', '', ''),
('${periodos}', 'Periodo-año / Monto adeudado (en miles sin decimales)', 'Periodos', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'REPORTE_VARIABLE', '', ''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'VARIABLE', '', ''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC'), 'VARIABLE', '', ''),
--Aviso de incumplimiento persona- GESTION_CARTERA_FISICA_GENERAL, Aviso de incumplimiento persona (AVI_INC_PER)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${correoCcf}', 'Correo electronico de la caja de Compensación', 'Correo CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'CONSTANTE','','CORREO_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'CONSTANTE', '', 'FIRMA_RESPONSABLE_CARTERA_CCF'),
('${numeroIdentificacionAfiliado}', 'Número de identificación del afiliado', 'Número de identificación del afiliado', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'VARIABLE', '', ''),
('${periodos}', 'Periodo-año / Monto adeudado (en miles sin decimales)', 'Periodos', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'REPORTE_VARIABLE', '', ''),
('${tipoIdentificacionAfiliado}', 'Tipo de identificación del afiliado', 'Tipo de identificación del afiliado', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'VARIABLE', '', ''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta', (SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'AVI_INC_PER'), 'VARIABLE', '', '')
;
--changeset fhoyos:02
--comment: Se agregan claves para el comunicado NTF_AVI
INSERT INTO VariableComunicado(vcoClave,vcoDescripcion,vcoNombre,vcoPlantillaComunicado,vcoTipoVariableComunicado,vcoOrden,vcoNombreConstante)
VALUES
--Notificación por aviso - GESTION_CARTERA_FISICA_GENERAL, Notificación por aviso (NTF_AVI)
('${tipoIdCcf}', 'Tipo documento de la Caja de Compensación', 'Tipo ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'CONSTANTE','','TIPO_ID_CCF'),
('${numeroIdCcf}', 'Número de documento de la Caja de Compensación', 'Número ID CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'CONSTANTE','','NUMERO_ID_CCF'),
('${firmaResponsableProcesoCartera}', 'Firma del responsable de proceso de cartera', 'Firma del responsable de proceso de cartera',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'CONSTANTE','','FIRMA_RESPONSABLE_CARTERA_CCF'),
('${firmaResponsableCcf}', 'Imagen de la firma del responsable del envío del comunicado en la caja', 'Firma Responsable CCF',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'CONSTANTE','','FIRMA_RESPONSABLE_CCF'),
('${numeroIdentificacionEmpleador}', 'Número de identificación del empleador','Número de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'VARIABLE','',''),
('${numeroIdentificacionRepresentanteLegal}', 'Número de identificación del representante legal','Número de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'VARIABLE','',''),
('${periodos}', 'Periodos para los cuales esta en mora', 'Periodos',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'REPORTE_VARIABLE','',''),
('${tipoIdentificacionEmpleador}', 'Tipo de identificación del empleador', 'Tipo de identificación del empleador',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'VARIABLE','',''),
('${tipoIdentificacionRepresentanteLegal}', 'Tipo de identificación del representante legal', 'Tipo de identificación del representante legal',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'VARIABLE','',''),
('${valorDeudaPresunta}', 'Valor deuda presunta', 'Valor deuda presunta',(SELECT pcoId FROM PlantillaComunicado where pcoEtiqueta = 'NTF_AVI'), 'VARIABLE','','')
;
