update ValidacionProceso
set vapEstadoProceso = 'INACTIVO'
WHERE vapValidacion ='VALIDACION_PERSONA_EMPLEADOR_ACTIVO' 
and vapBloque in ('CAMBIAR_MEDIO_DE_PAGO_ADMINISTRADOR_DE_SUBSIDIO_DEPWEB', 'CAMBIAR_MEDIO_DE_PAGO_DEPENDIENTE_DEPWEB','CAMBIAR_MEDIO_DE_PAGO_ADMINISTRADOR_DE_SUBSIDIO_WEB','CAMBIAR_MEDIO_DE_PAGO_DEPENDIENTE_WEB')
