--liquibase formatted sql

--changeset jvelandia:01
--comment: Actualizacion tabla PlantillaComunicado
UPDATE PlantillaComunicado set pcoCuerpo='<p style=''text-align:justify;line-height:normal''>S - AP</p>  <p style=''text-align:justify;line-height:normal''>FU - SUB</p>  <p>&nbsp;</p>  <p style=''text-align:justify;line-height:normal''>(<i style=''mso-bidi-font-style:normal''>Ciudad</i>), ${fechaGeneracion}</p>  <p>&nbsp;</p>  <p style=''text-align:justify;line-height:normal''>Señor (a)</p>  <p style=''text-align:justify;line-height:normal''><b style=''mso-bidi-font-weight:normal''>${nombreCompleto}</b></p><p style=''text-align:justify;line-height:normal''><b style=''mso-bidi-font-weight:normal''>${tipoSolicitante}</b></p><p style=''text-align:justify;line-height:normal''><b style=''mso-bidi-font-weight:normal''><span style=''mso-spacerun:yes''> </span>${direccionPrincipal} – ${municipio} ${departamento}</b></p>  <p style=''text-align:justify;line-height:normal''><b style=''mso-bidi-font-weight:normal''>${telefono}</b></p>  <p>&nbsp;</p>  <p style=''text-align:justify;line-height:normal''>Ref.: ${tipoCertificado} </p>  <p>&nbsp;</p>  <p style=''text-align:center''><b style=''mso-bidi-font-weight:normal''>${nombreCcf}</b></p>  <p style=''text-align:center''><b style=''mso-bidi-font-weight:normal''>Sección de afiliación ${seccionAfiliacion}</b></p>  <p style=''text-align:center''><b style=''mso-bidi-font-weight:normal''>Certifica</b></p>  <p>&nbsp;</p>  <p>&nbsp;</p>  <p style=''text-align:justify;line-height:normal''>Que ${tipoTrabajador} <b style=''mso-bidi-font-weight:normal''>${nombreCompleto} ${tipoIdentificacion} número ${numeroIdentificacion}   a la fecha ${fechaGeneracion} se encuentra afiliada a esta CAJA DE COMPENSACION FAMILIAR${trabajador}${nombreRazonSocialEmpleador}.</b></p>  <p>&nbsp;</p>  <p><span style=''color:black;mso-themecolor:text1''>${parrafoNoValidez}</span></p>  <p>&nbsp;</p>  <p><span style=''color:black;mso-themecolor:text1''>Se expide a solicitud del interesado.</span></p>  <p><span style=''color:black;mso-themecolor:text1''>&nbsp;</span></p>  <p><span style=''color:black;mso-themecolor:text1''>NOS RESERVAMOS EL DERECHO DE REALZAR AUDITORIA POSTERIOR.</span></p>  <p style=''text-align:justify''>&nbsp;</p>  <p style=''text-align:justify;line-height:normal''>${contenido}</p>  <p>&nbsp;</p>' WHERE pcoEtiqueta='COM_GEN_CER_AFI';

--changeset jvelandia:02
--comment: Actualizacion tabla PlantillaComunicado
UPDATE PlantillaComunicado SET pcoMensaje = 'Mensaje<br />  <p>${nombreCcf}</p><br /> <p>${logoDeLaCcf}</p><br /> <p>${responsableCcf}</p> <br /> <p>${nombreCompleto}</p><br /> ' WHERE pcoEtiqueta IN ('COM_GEN_CER_AFI','COM_GEN_CER_HIS_AFI','COM_GEN_CER_APO','COM_GEN_CER_PYS_EMP','COM_GEN_CER_PYS');
