--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de LINEDEFINITIONLOAD
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,REQUIREDINGROUP,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (1222,'1',null,1,null,1,1221,1222);