--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de VALIDATORDEFINITION
INSERT VALIDATORDEFINITION (ID,EXCLUDELINE,STOPPROCESS,VALIDATORORDER,FIELDDEFINITION_ID,FILEDEFINITIONLOAD_ID,LINEDEFINITION_ID,VALIDATORCATALOG_ID) VALUES (1222,1,0,1,null,null,1222,1222);