--liquibase formatted sql

--changeset Heinsohn:01
--comment: Insercion inicial CONSTANTE
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CAJA_COMPENSACION_SITE','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('KEY','<ENVIRONMENT>');

INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CAJA_COMPENSACION_ID','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CAJA_COMPENSACION_CODIGO','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CAJA_COMPENSACION_MEDIO_PAGO_PREFERENTE','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('NOMBRE_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CIUDAD_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('DEPARTAMENTO_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CIUDAD_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('DIRECCION_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('TELEFONO_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('TIPO_ID_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('NUMERO_ID_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('LOGO_DE_LA_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('WEB_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('LOGO_SUPERSERVICIOS','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('FIRMA_RESPONSABLE_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('RESPONSABLE_CCF','<ENVIRONMENT>');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('CARGO_RESPONSABLE_CCF','<ENVIRONMENT>');


INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('FECHA_INICIO_LEY_1429','1293580800000');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('FECHA_FIN_LEY_1429','1419984000000');
INSERT CONSTANTE (cnsNombre,cnsValor) VALUES ('FECHA_FIN_LEY_590','963187200000');


