--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de FILEDEFINITIONLOAD
INSERT FILEDEFINITIONLOAD (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,EXCLUDELINES,REGISTERSREAD,SHEETNUMBERXLS,USECHARACTERS,FILEDEFINITIONTYPE_ID) VALUES (1,'.','Definición Archivo Información Aportante Dependiente o Independiente',null,null,0,null,null,0,1);
INSERT FILEDEFINITIONLOAD (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,EXCLUDELINES,REGISTERSREAD,SHEETNUMBERXLS,USECHARACTERS,FILEDEFINITIONTYPE_ID) VALUES (2,'.','Definición Archivo Información Aportante Pensionado',null,null,0,null,null,0,2);
INSERT FILEDEFINITIONLOAD (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,EXCLUDELINES,REGISTERSREAD,SHEETNUMBERXLS,USECHARACTERS,FILEDEFINITIONTYPE_ID) VALUES (3,'.','Definición Archivo Detalle Dependiente o Independiente',null,null,0,null,null,1,3);
INSERT FILEDEFINITIONLOAD (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,EXCLUDELINES,REGISTERSREAD,SHEETNUMBERXLS,USECHARACTERS,FILEDEFINITIONTYPE_ID) VALUES (4,'.','Definición Archivo Detalle Pensionado',null,null,0,null,null,1,4);
INSERT FILEDEFINITIONLOAD (ID,DECIMALSEPARATOR,NOMBRE,TENANTID,THOUSANDSSEPARATOR,EXCLUDELINES,REGISTERSREAD,SHEETNUMBERXLS,USECHARACTERS,FILEDEFINITIONTYPE_ID) VALUES (5,'.','Definición Archivo Operador Financiero',null,null,0,null,null,1,5);
