--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de LINEDEFINITIONLOAD
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (1,'',null,1,1,1,1);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (2,'',null,1,1,2,2);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (3,'1',1,1,1,3,3);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (4,'2',2,1,1,3,4);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (5,'00031',3,1,1,3,5);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (6,'00036',4,1,1,3,6);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (7,'00039',5,1,1,3,7);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (8,'1',6,1,1,4,8);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (9,'2',7,1,1,4,9);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (10,'3',8,1,1,4,10);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (11,'1',9,1,1,5,11);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (12,'5',10,1,1,5,12);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (13,'6',11,1,1,5,13);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (14,'8',12,1,1,5,14);
INSERT LINEDEFINITIONLOAD (ID,IDENTIFIER,NUMBERGROUP,REQUIRED,ROLLBACKORDER,FILEDEFINITION_ID,LINELOADCATALOG_ID) VALUES (15,'9',13,1,1,5,15);
