--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de LINELOADCATALOG
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (1,'com.asopagos.pila.persistencia.PersistirArchivoARegistro1','Catalogo de línea para la información de aportante dependiente o independiente','Información Aportante Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (2,'com.asopagos.pila.persistencia.PersistirArchivoAPRegistro1','Catalogo de línea para la información de aportante pensionado','Información Aportante Pensionado',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (3,'com.asopagos.pila.persistencia.PersistirArchivoIRegistro1','Catalogo de línea para el detalle de aportante dependiente o independiente','Detalle de Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (4,'com.asopagos.pila.persistencia.PersistirArchivoIRegistro2','Catalogo de línea para el detalle de aportante dependiente o independiente','Detalle de Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (5,'com.asopagos.pila.persistencia.PersistirArchivoIRegistro3','Catalogo de línea para el detalle de aportante dependiente o independiente','Detalle de Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (6,'com.asopagos.pila.persistencia.PersistirArchivoIRegistro3','Catalogo de línea para el detalle de aportante dependiente o independiente','Detalle de Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (7,'com.asopagos.pila.persistencia.PersistirArchivoIRegistro3','Catalogo de línea para el detalle de aportante dependiente o independiente','Detalle de Dependiente o Independiente',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (8,'com.asopagos.pila.persistencia.PersistirArchivoIPRegistro1','Catalogo de línea para el detalle de aportante pensionado','Detalle de Pensionado',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (9,'com.asopagos.pila.persistencia.PersistirArchivoIPRegistro2','Catalogo de línea para el detalle de aportante pensionado','Detalle de Pensionado',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (10,'com.asopagos.pila.persistencia.PersistirArchivoIPRegistro3','Catalogo de línea para el detalle de aportante pensionado','Detalle de Pensionado',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (11,'com.asopagos.pila.persistencia.PersistirArchivoFRegistro1','Catalogo de línea para el registro de encabezado de archivo','Registro de encabezado de archivo',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (12,'com.asopagos.pila.persistencia.PersistirArchivoFRegistro5','Catalogo de línea para el registro de encabezado de lote','Registro de encabezado de lote',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (13,'com.asopagos.pila.persistencia.PersistirArchivoFRegistro6','Catalogo de línea para el registro de detalle de planillas','Registro de detalle de planillas',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (14,'com.asopagos.pila.persistencia.PersistirArchivoFRegistro8','Catalogo de línea para el registro de control de lote','Registro de control de lote',null,1,'|',null);
INSERT LINELOADCATALOG (ID,CLASSNAME,DESCRIPTION,NAME,TENANTID,LINEORDER,LINESEPARATOR,TARGETENTITY) VALUES (15,'com.asopagos.pila.persistencia.PersistirArchivoFRegistro9','Catalogo de línea para el registro de control de archivo','Registro de control de archivo',null,1,'|',null);
