--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de ValidatorParameter
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (1,'STRING','Nombre del campo a validar',null,'nombreCampo',1);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (2,'STRING','Expresión regular',null,'expresionRegular',1);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (3,'STRING','Nombre del campo a validar',null,'nombreCampo',2);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (4,'STRING','Valor único a validar',null,'valorUnico',2);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (5,'STRING','Convertir a número',null,'convertirNumero',2);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (6,'STRING','Nombre del campo a validar',null,'nombreCampo',3);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (7,'STRING','Rango de valores',null,'rangoValor',3);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (8,'STRING','Nombre del campo a validar',null,'nombreCampo',4);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (9,'STRING','Llave lista contexto',null,'llaveListaContexto',4);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (10,'STRING','Nombre del campo a validar',null,'nombreCampo',5);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (11,'STRING','Campo Departamento',null,'campoDepartamento',5);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (12,'STRING','Campo Municipio',null,'campoMunicipio',5);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (13,'STRING','Nombre del campo a validar',null,'nombreCampo',6);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (14,'STRING','Campo Tipo de Documento',null,'campoTipoDocumento',6);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (15,'STRING','Campo Dígito Verificación',null,'campoDigito',6);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (16,'STRING','Nombre del campo a validar',null,'nombreCampo',7);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (17,'STRING','Expresión regular',null,'expresionRegular',7);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (18,'STRING','Nombre del campo a validar',null,'nombreCampo',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (19,'STRING','Nombre campo planilla asociada',null,'campoPlanillaAsociada',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (20,'STRING','Nombre del campo de tipo planilla',null,'campoTipoPlanilla',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (21,'STRING','Tipos para planilla asociada no vacia',null,'tiposNoVacios',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (22,'STRING','Nombre del campo a validar',null,'nombreCampo',9);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (23,'STRING','Campo Clase Aportante',null,'campoClaseAportante',9);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (24,'STRING','Campo Tipo Aportante',null,'campoTipoAportante',9);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (25,'STRING','Nombre del campo a validar',null,'nombreCampo',10);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (26,'STRING','Llave de variable en contexto',null,'llaveVariable',10);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (27,'STRING','Comparación',null,'comparacion',10);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (28,'STRING','Nombre del campo a validar',null,'nombreCampo',11);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (29,'STRING','Campo número ID',null,'campoId',11);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (30,'STRING','Campo tipo ID',null,'campoTipoId',11);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (31,'STRING','Nombre del campo a validar',null,'nombreCampo',12);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (32,'STRING','Campo Tipo Aportante',null,'campoTipoAportante',12);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (33,'STRING','Campo Tipo Planilla',null,'campoTipoPlanilla',12);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (34,'STRING','Nombre del campo a validar',null,'nombreCampo',13);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (35,'STRING','Campo fecha de pago planilla asociada',null,'campofechaPagoPlanillaAsociada',13);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (36,'STRING','Campo Tipo Planilla',null,'campoTipoPlanilla',13);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (37,'STRING','Nombre del campo a validar',null,'nombreCampo',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (38,'STRING','Llave de variable en contexto',null,'llaveVariable',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (39,'STRING','Campo Tipo Planilla',null,'campoTipoPlanilla',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (40,'STRING','Campo Cantidad de Registros Tipo 2',null,'campoCantidadRegistrosTipo2',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (41,'STRING','Llave de variable en contexto',null,'llaveVariable',15);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (42,'STRING','Nombre del campo a validar',null,'nombreCampo',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (43,'STRING','Campo fecha de pago',null,'campoFechaPago',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (44,'STRING','Campo periodo de pago',null,'campoPeriodoPago',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (45,'STRING','Campo días de mora',null,'campoDiasMora',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (46,'STRING','Campo Tipo Planilla',null,'campoTipoPlanilla',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (47,'STRING','Campo número ID',null,'campoId',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (48,'STRING','Campo Cantidad Afiliados',null,'campoCantidadAfiliados',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (49,'STRING','Campo Clase Aportante',null,'campoClaseAportante',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (50,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (51,'STRING','Nombre del campo a validar',null,'nombreCampo',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (52,'STRING','Llave de la fecha de vencimiento',null,'llaveFechaVencimiento',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (53,'STRING','Llave de la fecha de pago',null,'llaveFechaPago',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (54,'STRING','Llave del valor del aporte',null,'llaveValorAporte',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (55,'STRING','Campo del valor de mora',null,'campoValorMora',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (56,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (57,'STRING','Nombre del campo a validar',null,'nombreCampo',18);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (58,'STRING','Campo Fecha Matricula',null,'campoMatricula',18);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (59,'STRING','Campo Clase Aportante',null,'campoClaseAportante',18);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (60,'STRING','Nombre del campo a validar',null,'nombreCampo',19);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (61,'STRING','Campo Tipo Aportante',null,'campoTipoAportante',19);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (62,'STRING','Campo Naturaleza Aportante',null,'campoNaturalezaAportante',19);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (63,'STRING','Nombre del campo a validar',null,'nombreCampo',20);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (64,'STRING','Campo Tipo Aportante',null,'campoTipoAportante',20);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (65,'STRING','Campo Tipo Persona',null,'campoTipoPersona',20);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (66,'STRING','Nombre del campo a validar',null,'nombreCampo',21);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (67,'STRING','Valor numérico mínimo',null,'valorMinimo',21);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (68,'STRING','Valor numérico máximo',null,'valorMaximo',21);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (69,'STRING','Nombre del campo a validar',null,'nombreCampo',22);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (70,'STRING','Llave de variable en contexto',null,'llaveVariable',22);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (71,'STRING','Nombre del campo a validar',null,'nombreCampo',23);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (72,'STRING','Llave de variable en contexto',null,'llaveVariable',23);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (73,'STRING','Nombre del campo a validar',null,'nombreCampo',24);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (74,'STRING','Llave de variable en contexto',null,'llaveVariable',24);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (75,'STRING','Nombre del campo a validar',null,'nombreCampo',25);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (76,'STRING','Nombre del campo a validar',null,'nombreCampo',26);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (77,'STRING','Campo Subtipo Cotizante',null,'campoSubtipoCotizante',26);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (78,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',26);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (79,'STRING','Nombre del campo a validar',null,'nombreCampo',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (80,'STRING','Campo Tipo Documento',null,'campoTipoDocumento',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (81,'STRING','Campo Extranjero',null,'campoExtranjero',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (82,'STRING','Valores Válidos',null,'valoresValidos',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (83,'STRING','Nombre del campo a validar',null,'nombreCampo',28);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (84,'STRING','Campo Extranjero',null,'campoExtranjero',28);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (85,'STRING','Campo Departamento / Municipio',null,'campoLocalidad',28);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (86,'STRING','Nombre del campo a validar',null,'nombreCampo',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (87,'STRING','Tipo Novedad',null,'tipoNovedad',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (88,'STRING','Campo Leído',null,'campoLeido',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (89,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (90,'STRING','Llave periodo de pago',null,'llavePeriodoPago',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (91,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (92,'STRING','Nombre del campo a validar',null,'nombreCampo',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (93,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (94,'STRING','Campo Días Cotizados',null,'campoDiasCotizados',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (95,'STRING','Campos Novedades',null,'camposNovedades',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (96,'STRING','Validar 0 días',null,'validarCeroDias',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (97,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (98,'STRING','Nombre del campo a validar',null,'nombreCampo',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (99,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (100,'STRING','Campo IBC',null,'campoIBC',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (101,'STRING','Redondeo',null,'redondeo',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (102,'STRING','Nombre del campo a validar',null,'nombreCampo',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (103,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (104,'STRING','Llave de la fecha de matrícula',null,'llaveFechaMatricula',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (105,'STRING','Llave de la clase de aportante',null,'llaveClaseAportante',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (106,'STRING','Llave del período de pago',null,'llavePeriodoPago',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (107,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (108,'STRING','Campo Tarifa',null,'campoTarifa',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (109,'STRING','Campo Novedad SLN',null,'campoNovedadSLN',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (110,'STRING','Campo Salario o Mesada Pensional',null,'campoSalarioMesada',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (111,'STRING','Nombre del campo a validar',null,'nombreCampo',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (112,'STRING','Campo Tipo Cotizante',null,'campoTipoCotizante',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (113,'STRING','Campo Horas Laboradas',null,'campoHorasLaboradas',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (114,'STRING','Tipos de cotizante con horas',null,'tipoCotizanteHoras',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (115,'STRING','Nombre del campo a validar',null,'nombreCampo',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (116,'STRING','Campo IBC',null,'campoIBC',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (117,'STRING','Campo Tarifa',null,'campoTarifa',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (118,'STRING','Campo Aporte Obligatorio',null,'campoAporteObligatorio',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (119,'STRING','Redondeo',null,'redondeo',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (120,'STRING','Nombre del campo a validar',null,'nombreCampo',35);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (121,'STRING','Llave del tipo de planilla',null,'llaveTipoPlanilla',35);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (122,'STRING','Nombre del campo a validar',null,'nombreCampo',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (123,'STRING','Campo Número Secuencia',null,'campoSecuencia',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (124,'STRING','Campo Correcciones',null,'campoCorrecciones',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (125,'STRING','Campo número ID',null,'campoId',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (126,'STRING','Llave corrección anterior',null,'llaveCorrecionAnterior',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (127,'STRING','Llave ID anterior',null,'llaveIdAnterior',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (128,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',37);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (129,'STRING','Nombre del campo a validar',null,'nombreCampo',38);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (130,'STRING','Llave corrección anterior',null,'llaveCorrecionAnterior',38);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (131,'STRING','Nombre del campo a validar',null,'nombreCampo',39);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (132,'STRING','Llave de la cantidad de resgistros tipo 2',null,'llaveCantidadRegistrosTipo2',39);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (133,'STRING','Nombre del campo a validar',null,'nombreCampo',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (134,'STRING','Llave de la clase de aportante',null,'llaveClaseAportante',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (135,'STRING','Llave del período de pago',null,'llavePeriodoPago',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (136,'STRING','Llave de la fecha de matrícula',null,'llaveFechaMatricula',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (137,'STRING','Nombre del campo a validar',null,'nombreCampo',41);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (138,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',41);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (139,'STRING','Llave del tipo de planilla',null,'llaveTipoPlanilla',41);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (140,'STRING','Nombre del campo a validar',null,'nombreCampo',42);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (141,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',42);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (142,'STRING','Llave del tipo de planilla',null,'llaveTipoPlanilla',42);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (143,'STRING','Nombre del campo a validar',null,'nombreCampo',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (144,'STRING','Campo Tipo de Documento',null,'campoTipoDocumento',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (145,'STRING','Campo número ID',null,'campoId',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (146,'STRING','Llave número ID',null,'llaveId',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (147,'STRING','Llave tipo de documento',null,'llaveTipoId',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (148,'STRING','Nombre del campo a validar',null,'nombreCampoA',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (149,'STRING','Nombre del campo de referencia',null,'nombreCampoB',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (150,'STRING','Campo a validar para comparar',null,'campoA',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (151,'STRING','Campo de referencia',null,'campoB',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (152,'STRING','Valor de referencia',null,'valorB',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (153,'STRING','Caso de comparación',null,'caso',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (154,'STRING','Nombre del campo a validar',null,'nombreCampo',45);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (155,'STRING','Llave de la Secuencia en el Contexto',null,'llaveSecuenciaContexto',45);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (156,'STRING','Nombre del campo a validar',null,'nombreCampo',46);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (157,'STRING','Llave del valor total de las mesadas',null,'llaveTotalMesadas',46);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (158,'STRING','Llave de la sumatoria de las mesadas',null,'llaveSumatoriaMesadas',46);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (159,'STRING','Nombre del campo a validar',null,'nombreCampo',47);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (160,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (161,'STRING','Nombre de Campos',null,'nombresCampos',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (162,'STRING','Llaves Campos Traslados',null,'llavesCamposTranspaso',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (163,'STRING','Llave del número de planilla',null,'llaveNumeroPlanilla',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (164,'STRING','Nombre del campo a validar',null,'nombreCampo',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (165,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (166,'STRING','Llave del valor del aporte',null,'llaveValorAporte',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (167,'STRING','Llave del valor de la mora',null,'llaveValorMora',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (168,'STRING','Campo del valor total a pagar',null,'campoValorTotal',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (169,'STRING','Nombre del campo a validar',null,'nombreCampo',50);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (170,'STRING','Nombre del campo a validar',null,'nombreCampo',51);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (171,'STRING','Campo número ID',null,'campoId',51);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (172,'STRING','Campo Dígito Verificación',null,'campoDigito',51);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (173,'STRING','Período Mínimo',null,'periodoMinimo',53);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (174,'STRING','Llave del período de pago',null,'llavePeriodoPago',53);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (175,'STRING','Nombre del campo a validar',null,'nombreCampo',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (176,'STRING','Campo evaluado',null,'campoEvaluado',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (177,'STRING','Campo con la fecha de referencia',null,'campoFechaReferencia',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (178,'STRING','Llave de la fecha de pago',null,'llaveFechaPago',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (179,'STRING','Nombre del campo a validar',null,'nombreCampo',55);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (180,'STRING','Campo tipo ID',null,'campoTipoId',55);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (181,'STRING','Campo Tipo Persona',null,'campoTipoPersona',55);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (182,'STRING','Nombre del campo a validar',null,'nombreCampo',56);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (183,'STRING','Modificador de fecha actual',null,'modificadorFecha',56);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (184,'STRING','Nombre del campo a validar',null,'nombreCampo',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (185,'STRING','Campo Salario o Mesada Pensional',null,'campoSalarioMesada',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (186,'STRING','Campo tipo de Cotizante',null,'campoTipoCotizante',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (187,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (188,'STRING','Nombre del campo a validar',null,'nombreCampo',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (189,'STRING','Campo IBC',null,'campoIBC',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (190,'STRING','Campos Novedades',null,'camposNovedades',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (191,'STRING','Campo Salario o Mesada Pensional',null,'campoSalarioMesada',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (192,'STRING','Campo Salario Integral',null,'campoSalarioIntegral',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (193,'STRING','Llave del tipo de archivo',null,'llaveTipoArchivo',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (194,'STRING','Campo tipo de Cotizante',null,'campoTipoCotizante',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (195,'STRING','Campo Días Cotizados',null,'campoDiasCotizados',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (196,'STRING','Redondeo',null,'redondeo',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (197,'STRING','Nombre del campo a validar',null,'nombreCampo',59);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (198,'STRING','Campo Salario Integral',null,'campoSalarioIntegral',59);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (199,'STRING','Campo Salario o Mesada Pensional',null,'campoSalarioMesada',59);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (200,'STRING','Nombre del campo a validar',null,'nombreCampo',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (201,'STRING','Campo Marca Novedad',null,'campoNovedad',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (202,'STRING','Campo Fecha Inicio Novedad',null,'campoFechaInicio',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (203,'STRING','Campo Fecha Fin Novedad',null,'campoFechaFin',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (204,'STRING','La novedad tiene fecha fin',null,'tieneFechaFin',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (205,'STRING','Nombre del campo a validar',null,'nombreCampo',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (206,'STRING','Campo Fecha de Pago',null,'campoFechaPago',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (207,'STRING','Modificador fecha actual mínimo',null,'fechaActualMenos',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (208,'STRING','Modificador fecha actual máximo',null,'fechaActualMax',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (209,'STRING','Nombre del campo a validar',null,'nombreCampo',63);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (210,'STRING','Nombre del campo a validar',null,'nombreCampo',64);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (211,'STRING','Nombre del campo a validar',null,'nombreCampo',65);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (212,'STRING','Llave del Contador o Sumatoria',null,'llaveContadorSumatoria',65);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (213,'STRING','Nombre del campo a validar',null,'nombreCampo',66);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (214,'STRING','Expresión regular',null,'expresionRegular',66);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (215,'STRING','Tipo Error',null,'tipoError',1);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (216,'STRING','Tipo Error',null,'tipoError',2);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (217,'STRING','Tipo Error',null,'tipoError',3);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (218,'STRING','Tipo Error',null,'tipoError',4);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (219,'STRING','Tipo Error',null,'tipoError',5);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (220,'STRING','Tipo Error',null,'tipoError',6);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (221,'STRING','Tipo Error',null,'tipoError',7);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (222,'STRING','Tipo Error',null,'tipoError',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (223,'STRING','Tipo Error',null,'tipoError',9);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (224,'STRING','Tipo Error',null,'tipoError',10);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (225,'STRING','Tipo Error',null,'tipoError',11);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (226,'STRING','Tipo Error',null,'tipoError',12);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (227,'STRING','Tipo Error',null,'tipoError',13);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (228,'STRING','Tipo Error',null,'tipoError',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (229,'STRING','Tipo Error',null,'tipoError',15);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (230,'STRING','Tipo Error',null,'tipoError',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (231,'STRING','Tipo Error',null,'tipoError',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (232,'STRING','Tipo Error',null,'tipoError',18);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (233,'STRING','Tipo Error',null,'tipoError',19);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (234,'STRING','Tipo Error',null,'tipoError',20);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (235,'STRING','Tipo Error',null,'tipoError',21);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (236,'STRING','Tipo Error',null,'tipoError',22);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (237,'STRING','Tipo Error',null,'tipoError',23);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (238,'STRING','Tipo Error',null,'tipoError',24);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (239,'STRING','Tipo Error',null,'tipoError',25);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (240,'STRING','Tipo Error',null,'tipoError',26);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (241,'STRING','Tipo Error',null,'tipoError',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (242,'STRING','Tipo Error',null,'tipoError',28);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (243,'STRING','Tipo Error',null,'tipoError',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (244,'STRING','Tipo Error',null,'tipoError',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (245,'STRING','Tipo Error',null,'tipoError',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (246,'STRING','Tipo Error',null,'tipoError',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (247,'STRING','Tipo Error',null,'tipoError',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (248,'STRING','Tipo Error',null,'tipoError',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (249,'STRING','Tipo Error',null,'tipoError',35);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (250,'STRING','Tipo Error',null,'tipoError',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (251,'STRING','Tipo Error',null,'tipoError',37);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (252,'STRING','Tipo Error',null,'tipoError',38);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (253,'STRING','Tipo Error',null,'tipoError',39);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (254,'STRING','Tipo Error',null,'tipoError',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (255,'STRING','Tipo Error',null,'tipoError',41);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (256,'STRING','Tipo Error',null,'tipoError',42);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (257,'STRING','Tipo Error',null,'tipoError',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (258,'STRING','Tipo Error',null,'tipoError',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (259,'STRING','Tipo Error',null,'tipoError',45);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (260,'STRING','Tipo Error',null,'tipoError',46);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (261,'STRING','Tipo Error',null,'tipoError',47);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (262,'STRING','Tipo Error',null,'tipoError',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (263,'STRING','Tipo Error',null,'tipoError',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (264,'STRING','Tipo Error',null,'tipoError',50);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (265,'STRING','Tipo Error',null,'tipoError',51);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (266,'STRING','Tipo Error',null,'tipoError',52);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (267,'STRING','Tipo Error',null,'tipoError',53);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (268,'STRING','Tipo Error',null,'tipoError',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (269,'STRING','Tipo Error',null,'tipoError',55);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (270,'STRING','Tipo Error',null,'tipoError',56);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (271,'STRING','Tipo Error',null,'tipoError',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (272,'STRING','Tipo Error',null,'tipoError',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (273,'STRING','Tipo Error',null,'tipoError',59);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (274,'STRING','Tipo Error',null,'tipoError',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (275,'STRING','Tipo Error',null,'tipoError',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (276,'STRING','Tipo Error',null,'tipoError',62);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (277,'STRING','Tipo Error',null,'tipoError',63);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (278,'STRING','Tipo Error',null,'tipoError',64);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (279,'STRING','Tipo Error',null,'tipoError',65);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (280,'STRING','Tipo Error',null,'tipoError',66);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (281,'STRING','Código del Campo',null,'codigoCampo',1);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (282,'STRING','Código del Campo',null,'codigoCampo',2);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (283,'STRING','Código del Campo',null,'codigoCampo',3);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (284,'STRING','Código del Campo',null,'codigoCampo',4);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (285,'STRING','Código del Campo',null,'codigoCampo',5);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (286,'STRING','Código del Campo',null,'codigoCampo',6);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (287,'STRING','Código del Campo',null,'codigoCampo',7);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (288,'STRING','Código del Campo',null,'codigoCampo',8);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (289,'STRING','Código del Campo',null,'codigoCampo',9);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (290,'STRING','Código del Campo',null,'codigoCampo',10);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (291,'STRING','Código del Campo',null,'codigoCampo',11);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (292,'STRING','Código del Campo',null,'codigoCampo',12);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (293,'STRING','Código del Campo',null,'codigoCampo',13);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (294,'STRING','Código del Campo',null,'codigoCampo',14);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (295,'STRING','Código del Campo',null,'codigoCampo',15);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (296,'STRING','Código del Campo',null,'codigoCampo',16);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (297,'STRING','Código del Campo',null,'codigoCampo',17);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (298,'STRING','Código del Campo',null,'codigoCampo',18);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (299,'STRING','Código del Campo',null,'codigoCampo',19);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (300,'STRING','Código del Campo',null,'codigoCampo',20);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (301,'STRING','Código del Campo',null,'codigoCampo',21);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (302,'STRING','Código del Campo',null,'codigoCampo',22);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (303,'STRING','Código del Campo',null,'codigoCampo',23);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (304,'STRING','Código del Campo',null,'codigoCampo',24);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (305,'STRING','Código del Campo',null,'codigoCampo',25);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (306,'STRING','Código del Campo',null,'codigoCampo',26);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (307,'STRING','Código del Campo',null,'codigoCampo',27);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (308,'STRING','Código del Campo',null,'codigoCampo',28);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (309,'STRING','Código del Campo',null,'codigoCampo',29);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (310,'STRING','Código del Campo',null,'codigoCampo',30);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (311,'STRING','Código del Campo',null,'codigoCampo',31);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (312,'STRING','Código del Campo',null,'codigoCampo',32);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (313,'STRING','Código del Campo',null,'codigoCampo',33);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (314,'STRING','Código del Campo',null,'codigoCampo',34);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (315,'STRING','Código del Campo',null,'codigoCampo',35);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (316,'STRING','Código del Campo',null,'codigoCampo',36);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (317,'STRING','Código del Campo',null,'codigoCampo',37);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (318,'STRING','Código del Campo',null,'codigoCampo',38);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (319,'STRING','Código del Campo',null,'codigoCampo',39);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (320,'STRING','Código del Campo',null,'codigoCampo',40);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (321,'STRING','Código del Campo',null,'codigoCampo',41);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (322,'STRING','Código del Campo',null,'codigoCampo',42);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (323,'STRING','Código del Campo',null,'codigoCampo',43);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (324,'STRING','Código del Campo',null,'codigoCampo',44);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (325,'STRING','Código del Campo',null,'codigoCampo',45);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (326,'STRING','Código del Campo',null,'codigoCampo',46);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (327,'STRING','Código del Campo',null,'codigoCampo',47);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (328,'STRING','Código del Campo',null,'codigoCampo',48);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (329,'STRING','Código del Campo',null,'codigoCampo',49);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (330,'STRING','Código del Campo',null,'codigoCampo',50);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (331,'STRING','Código del Campo',null,'codigoCampo',51);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (332,'STRING','Código del Campo',null,'codigoCampo',52);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (333,'STRING','Código del Campo',null,'codigoCampo',53);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (334,'STRING','Código del Campo',null,'codigoCampo',54);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (335,'STRING','Código del Campo',null,'codigoCampo',55);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (336,'STRING','Código del Campo',null,'codigoCampo',56);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (337,'STRING','Código del Campo',null,'codigoCampo',57);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (338,'STRING','Código del Campo',null,'codigoCampo',58);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (339,'STRING','Código del Campo',null,'codigoCampo',59);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (340,'STRING','Código del Campo',null,'codigoCampo',60);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (341,'STRING','Código del Campo',null,'codigoCampo',61);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (342,'STRING','Código del Campo',null,'codigoCampo',62);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (343,'STRING','Código del Campo',null,'codigoCampo',63);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (344,'STRING','Código del Campo',null,'codigoCampo',64);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (345,'STRING','Código del Campo',null,'codigoCampo',65);
INSERT ValidatorParameter (id,dataType,description,mask,name,validatorCatalog_id) VALUES (346,'STRING','Código del Campo',null,'codigoCampo',66);
