apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https-alt

  selector:
    name: ${project.artifactId}