--liquibase formatted sql

--changeset jocorrea:01
--comment:Se elimina valores vapValidacion de la tabla ValidacionProceso para solución mantis 0224283 
DELETE FROM ValidacionProceso
WHERE vapValidacion = 'VALIDACION_CAMBIO_TIPO_DOC_IDENTIDAD'
AND vapBloque IN ('NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_BENEFICIARIO_CONYUGE',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_BENEFICIARIO_EN_CUSTODIA',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_HERMANO_HUERFANO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_HIJASTRO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_HIJO_ADOPTIVO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_HIJO_BIOLOGICO',
'NOVEDAD_CAMBIO_TIPO_NUMERO_DOCUMENTO_TRABAJADOR_DEPENDIENTE')