--liquibase formatted sql

--changeset jvelandia:01
--comment:Se actualizan registros en las tablas DestinatarioGrupo, PrioridadDestinatario, GrupoPrioridad y Parametro
DELETE FROM DestinatarioGrupo;
DELETE FROM PrioridadDestinatario;
DELETE FROM DestinatarioComunicado;
DELETE FROM GrupoPrioridad;

INSERT GrupoPrioridad (gprNombre) VALUES('RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT GrupoPrioridad (gprNombre) VALUES('REPRESENTANTE_LEGAL');
INSERT GrupoPrioridad (gprNombre) VALUES('OFICINA_PRINCIPAL');
INSERT GrupoPrioridad (gprNombre) VALUES('ENVIO_DE_CORRESPONDENCIA');
INSERT GrupoPrioridad (gprNombre) VALUES('NOTIFICACION_JUDICIAL');
INSERT GrupoPrioridad (gprNombre) VALUES('TRABAJADOR_DEPENDIENTE');
INSERT GrupoPrioridad (gprNombre) VALUES('TRABAJADOR_INDEPENDIENTE');
INSERT GrupoPrioridad (gprNombre) VALUES('PENSIONADO');
INSERT GrupoPrioridad (gprNombre) VALUES('RESPONSABLE_DE_SUBSIDIOS');
INSERT GrupoPrioridad (gprNombre) VALUES('RESPONSABLE_DE_APORTES');
INSERT GrupoPrioridad (gprNombre) VALUES('INFORMACION_DE_CONTACTO');
INSERT GrupoPrioridad (gprNombre) VALUES('APORTANTE');
INSERT GrupoPrioridad (gprNombre) VALUES('SOLICITANTE');
INSERT GrupoPrioridad (gprNombre) VALUES('INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE_TERCERO');
INSERT GrupoPrioridad (gprNombre) VALUES('INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE');
INSERT GrupoPrioridad (gprNombre) VALUES('AUTORIZADO_PARA_PAGO');
INSERT GrupoPrioridad (gprNombre) VALUES('AFILIADO_PRINCIPAL');
INSERT GrupoPrioridad (gprNombre) VALUES('ENTIDAD_PAGADORA_ROL');
INSERT GrupoPrioridad (gprNombre) VALUES('REPRESENTANTE_LEGAL_SUPLENTE');
INSERT GrupoPrioridad (gprNombre) VALUES('RESPOSABLE_CAJA_UNO');
INSERT GrupoPrioridad (gprNombre) VALUES('RESPOSABLE_CAJA_DOS');
INSERT GrupoPrioridad (gprNombre) VALUES('SOCIOS');
INSERT GrupoPrioridad (gprNombre) VALUES('RESPONSABLE_JEFE_HOGAR');

INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_EMP_AFL_MLT_TRBW');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_INVL_AFL_TRBW');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_INVL_AFL_TRBW_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_REG_BNF_WEB_TRB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_REG_BNF_WEB_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_INC_VAL_TRAB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_INC_VAL_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_PROD_NSUBLE_TRB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_PROD_NSUBLE_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'NTF_SUB_AFL_TRB_DPT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_PROD_NSUB_TRB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_DEPENDIENTE_WEB', 'RCHZ_AFL_DPT_PROD_NSUB_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'NTF_INT_AFL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'NTF_INT_AFL_DEP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'CRT_BVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'CRT_ACP_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'NTF_CRCN_USR_EXT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'RCHZ_AFL_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_PRESENCIAL', 'RCHZ_AFL_EMP_PRE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'NTF_ENRL_AFL_EMP_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'NTF_RAD_AFL_EMP_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'RCHZ_AFL_EMP_INC_VAL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'CRT_BVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'CRT_ACP_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'NTF_CRCN_USR_EXT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_EMPRESAS_WEB', 'NTF_SBC_AFL_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_ENRL_AFL_IDPE_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_ENRL_AFL_PNS_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_RAD_AFL_IDPE_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_RAD_AFL_PNS_WEB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'RCHZ_AFL_IDPE_INC_VAL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'RCHZ_AFL_PNS_INC_VAL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'CRT_ACP_IDPE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'CRT_ACP_PNS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'CRT_BVD_IDPE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'CRT_BVD_PNS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_SBC_AFL_IDPE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_SBC_AFL_PNS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_REG_BNF_WEB_IDPE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_REG_BNF_WEB_PNS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_RCHZ_AFL_IDPE_DSP_SUB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_INDEPENDIENTE_WEB', 'NTF_RCHZ_AFL_PNS_DSP_SUB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'NTF_INT_AFL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'NTF_INT_AFL_IDPE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'NTF_INT_AFL_PNS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'NTF_RAD_AFL_PER');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'RCHZ_AFL_PER_POR_PROD_NSUB');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'RCHZ_AFL_PER_INC_VAL');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('AFILIACION_PERSONAS_PRESENCIAL', 'RCHZ_AFL_PER_POR_PROD_NSUBLE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_DEPENDIENTE_WEB', 'RCHZ_NVD_WEB_TRB_REP_POR_EMP_POR_PROD_NSUBLE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_DEPENDIENTE_WEB', 'NTF_NVD_WEB_TRB_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_DEPENDIENTE_WEB', 'NTF_RAD_NVD_WEB_TRB_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_DEPENDIENTE_WEB', 'NTF_APRB_NVD_WEB_TRB_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_PRESENCIAL', 'NTF_RAD_NVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_PRESENCIAL', 'NTF_NVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_PRESENCIAL', 'CNFR_RET_APRT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_WEB', 'NTF_RAD_NVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_WEB', 'NTF_NVD_EMP');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_EMPRESAS_WEB', 'CNFR_RET_APRT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_WEB', 'NTF_NVD_PERS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_WEB', 'NTF_RAD_NVD_PER');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_WEB', 'RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_WEB', 'NTF_PARA_SBC_NVD_PERS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_PRESENCIAL', 'NTF_NVD_PERS');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_PRESENCIAL', 'NTF_RAD_NVD_PER');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_PRESENCIAL', 'RCHZ_NVD_PERS_PROD_NSUBLE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_PRESENCIAL', 'CNFR_RET_APRT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('NOVEDADES_PERSONAS_PRESENCIAL', 'DSTMTO_NVD_RET_APRT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('CORRECCION_APORTES', 'NTF_APR_COR_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('CORRECCION_APORTES', 'NTF_RCHZ_COR_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('DEVOLUCION_APORTES', 'NTF_GST_INF_FLT_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('DEVOLUCION_APORTES', 'NTF_RCHZ_DVL_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('DEVOLUCION_APORTES', 'NTF_APR_DVL_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('DEVOLUCION_APORTES', 'NTF_PAG_DVL_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('PAGO_APORTES_MANUAL', 'NTF_PAG_APT_DEP_APTE_CTZ');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('PAGO_APORTES_MANUAL', 'NTF_PAG_APT_DEP_APTE');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('PAGO_APORTES_MANUAL', 'NTF_PAG_APT_TRC');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('PAGO_APORTES_MANUAL', 'NTF_PAG_PAG_SIM');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('PAGO_APORTES_MANUAL', 'NTF_GST_INF_PAG_APT');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('GESTION_PREVENTIVA_CARTERA','REC_PLZ_LMT_PAG');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('GESTION_PREVENTIVA_CARTERA','REC_PLZ_LMT_PAG_PER');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP1');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP2');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP3');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP4');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP5');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP6');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP7');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP8');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP9');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP10');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP11');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP12');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP13');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP14');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP15');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP16');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP17');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP18');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP19');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP20');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP21');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP22');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP23');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP24');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP25');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP26');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP27');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP28');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP29');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP30');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP31');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_DEP32');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE1');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE2');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE3');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE4');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE5');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE6');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE7');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE8');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_IDPE9');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS1');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS2');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS3');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS4');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS5');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS6');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS7');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS8');
INSERT INTO DestinatarioComunicado(dcoProceso, dcoEtiquetaPlantilla)VALUES('RECAUDO_PILA','NTF_REC_APT_PLA_PNS9');

INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_EMP_AFL_MLT_TRBW'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_INVL_AFL_TRBW'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_INVL_AFL_TRBW_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_TRB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_INC_VAL_TRAB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_INC_VAL_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUBLE_TRB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUBLE_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_SUB_AFL_TRB_DPT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUB_TRB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_DPT_PROD_NSUB_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_AFL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_AFL_DEP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='CRT_BVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='CRT_ACP_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_CRCN_USR_EXT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_EMP_PRE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_ENRL_AFL_EMP_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_AFL_EMP_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_EMP_INC_VAL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='CRT_BVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='CRT_ACP_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_CRCN_USR_EXT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_SBC_AFL_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_ENRL_AFL_IDPE_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_ENRL_AFL_PNS_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_AFL_IDPE_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_AFL_PNS_WEB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_IDPE_INC_VAL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_PNS_INC_VAL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='CRT_ACP_IDPE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='CRT_ACP_PNS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='CRT_BVD_IDPE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='CRT_BVD_PNS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_SBC_AFL_IDPE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_SBC_AFL_PNS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_IDPE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_REG_BNF_WEB_PNS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_RCHZ_AFL_IDPE_DSP_SUB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_INDEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_RCHZ_AFL_PNS_DSP_SUB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_AFL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_AFL_IDPE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_INT_AFL_PNS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_RAD_AFL_PER'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_PER_POR_PROD_NSUB'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_PER_INC_VAL'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='AFILIACION_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_AFL_PER_POR_PROD_NSUBLE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_NVD_WEB_TRB_REP_POR_EMP_POR_PROD_NSUBLE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_NVD_WEB_TRB_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_NVD_WEB_TRB_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_DEPENDIENTE_WEB' AND des.dcoEtiquetaPlantilla='NTF_APRB_NVD_WEB_TRB_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_RAD_NVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_NVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='CNFR_RET_APRT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_NVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_NVD_EMP'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_EMPRESAS_WEB' AND des.dcoEtiquetaPlantilla='CNFR_RET_APRT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_NVD_PERS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_RAD_NVD_PER'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_WEB' AND des.dcoEtiquetaPlantilla='RCHZ_NVD_PERS_PROD_NSUBLE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_WEB' AND des.dcoEtiquetaPlantilla='NTF_PARA_SBC_NVD_PERS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_NVD_PERS'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='NTF_RAD_NVD_PER'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='RCHZ_NVD_PERS_PROD_NSUBLE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='CNFR_RET_APRT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='NOVEDADES_PERSONAS_PRESENCIAL' AND des.dcoEtiquetaPlantilla='DSTMTO_NVD_RET_APRT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='CORRECCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_APR_COR_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='CORRECCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_RCHZ_COR_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='DEVOLUCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_GST_INF_FLT_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='DEVOLUCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_RCHZ_DVL_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='DEVOLUCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_APR_DVL_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='DEVOLUCION_APORTES' AND des.dcoEtiquetaPlantilla='NTF_PAG_DVL_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='PAGO_APORTES_MANUAL' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE_CTZ'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='APORTANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='PAGO_APORTES_MANUAL' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_DEP_APTE'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='APORTANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='PAGO_APORTES_MANUAL' AND des.dcoEtiquetaPlantilla='NTF_PAG_APT_TRC'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='PAGO_APORTES_MANUAL' AND des.dcoEtiquetaPlantilla='NTF_PAG_PAG_SIM'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='PAGO_APORTES_MANUAL' AND des.dcoEtiquetaPlantilla='NTF_GST_INF_PAG_APT'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES'), 1);
INSERT INTO PrioridadDestinatario(prdDestinatarioComunicado, prdGrupoPrioridad, prdPrioridad)VALUES((SELECT des.dcoId FROM DestinatarioComunicado des WHERE des.dcoProceso='GESTION_PREVENTIVA_CARTERA' AND des.dcoEtiquetaPlantilla='REC_PLZ_LMT_PAG_PER'), (SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES'), 1);

INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_LAS_AFILIACIONES'), 'RESPONSABLE_DE_LAS_AFILIACIONES');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL'), 'REPRESENTANTE_LEGAL');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='OFICINA_PRINCIPAL'), 'OFICINA_PRINCIPAL');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENVIO_DE_CORRESPONDENCIA'), 'ENVIO_DE_CORRESPONDENCIA');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='NOTIFICACION_JUDICIAL'), 'NOTIFICACION_JUDICIAL');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_DEPENDIENTE'), 'TRABAJADOR_DEPENDIENTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='TRABAJADOR_INDEPENDIENTE'), 'TRABAJADOR_INDEPENDIENTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='PENSIONADO'), 'PENSIONADO');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_SUBSIDIOS'), 'RESPONSABLE_DE_SUBSIDIOS');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_DE_APORTES'), 'RESPONSABLE_DE_APORTES');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='INFORMACION_DE_CONTACTO'), 'INFORMACION_DE_CONTACTO');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='APORTANTE'), 'APORTANTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOLICITANTE'), 'SOLICITANTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE_TERCERO'), 'INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE_TERCERO');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE'), 'INFORMACION_PENSIONADO_INDEPENDIENTE_PAGO_APORTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AUTORIZADO_PARA_PAGO'), 'AUTORIZADO_PARA_PAGO');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='AFILIADO_PRINCIPAL'), 'AFILIADO_PRINCIPAL');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='ENTIDAD_PAGADORA_ROL'), 'ENTIDAD_PAGADORA_ROL');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='REPRESENTANTE_LEGAL_SUPLENTE'), 'REPRESENTANTE_LEGAL_SUPLENTE');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPOSABLE_CAJA_UNO'), 'RESPOSABLE_CAJA_UNO');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPOSABLE_CAJA_DOS'), 'RESPOSABLE_CAJA_DOS');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='SOCIOS'), 'SOCIOS');
INSERT INTO DestinatarioGrupo(dgrGrupoPrioridad, dgrRolContacto)VALUES((SELECT grp.gprId FROM GrupoPrioridad grp WHERE grp.gprNombre='RESPONSABLE_JEFE_HOGAR'), 'RESPONSABLE_JEFE_HOGAR');

update parametro set prmDescripcion = 'URL del servidor que provee el servicio SMTP a través del cuál se enviarán los correos electrónicos' where prmNombre = 'mail.smtp.host';
update parametro set prmDescripcion = 'Puerto por el que atiende el servidor de correo SMTP' where prmNombre = 'mail.smtp.port';
update parametro set prmDescripcion = 'Algunos servidores SMPT  requieren autenticación de un usuario con permisos de envío.Esta propiedad debe ponerse TRUE si el servidor requiere autenticación' where prmNombre = 'mail.smtp.auth';
update parametro set prmDescripcion = 'Usuario que se autentica en el servidor de correo SMTP.Debe tener permiso de envío de correos en el servidor configurado' where prmNombre = 'mail.smtp.user';
update parametro set prmDescripcion = 'Constraseña del usuario que se autentica en el servidor de correo SMTP y que tiene permisos de envío de correo en dicho servidor. Propiedad cifrada ' where prmNombre = 'mail.smtp.password';
update parametro set prmDescripcion = 'Dirección de correo electrónico que aparecerá como remitente en los correos enviados por la solución, debe ser un formato de correo electrónico válido' where prmNombre = 'mail.smtp.from';
update parametro set prmDescripcion = 'Nombre de persona, corporación o empresa que aparecerá como remitente en los correos enviados por la solución' where prmNombre = 'mail.smtp.fromName';
update parametro set prmDescripcion = 'Indica si en un envío de un mensaje a una lista de varias direcciones, debe continuar a pesar de que se encuentren direcciones inválidas. (TRUE continuar, FALSE para detenerse)' where prmNombre = 'mail.smtp.sendpartial';
update parametro set prmDescripcion = 'Indica si el transporte de los mensajes de correo electrónico requiere ser transmitido a través de protocolo seguro' where prmNombre = 'mail.smtp.starttls.enable';

--changeset abaquero:02 
--comment: Adicion tablas de modelo de subsidios para liquidacion especifica
ALTER TABLE dbo.SolicitudLiquidacionSubsidio ADD slsCodigoReclamo varchar(50);
ALTER TABLE dbo.SolicitudLiquidacionSubsidio ADD slsComentarioReclamo varchar(250);

CREATE TABLE dbo.PersonaLiquidacionEspecifica (
	pleId BIGINT NOT NULL IDENTITY, 
	pleSolicitudLiquidacionSubsidio BIGINT NOT NULL, 
	pleEmpleador BIGINT NOT NULL, 
	pleAfiliadoPrincipal BIGINT, 
	pleBeneficiarioDetalle BIGINT, 
	pleGrupoFamiliar BIGINT, 
	CONSTRAINT PK_PersonaLiquidacionEspecifica_pleId PRIMARY KEY (pleId)
);

ALTER TABLE dbo.PersonaLiquidacionEspecifica ADD CONSTRAINT FK_PersonaLiquidacionEspecifica_pleSolicitudLiquidacionSubsidio FOREIGN KEY (pleSolicitudLiquidacionSubsidio) REFERENCES dbo.SolicitudLiquidacionSubsidio;
ALTER TABLE dbo.PersonaLiquidacionEspecifica ADD CONSTRAINT FK_PersonaLiquidacionEspecifica_pleEmpleador FOREIGN KEY (pleEmpleador) REFERENCES dbo.Empleador;
ALTER TABLE dbo.PersonaLiquidacionEspecifica ADD CONSTRAINT FK_PersonaLiquidacionEspecifica_pleAfiliadoPrincipal FOREIGN KEY (pleAfiliadoPrincipal) REFERENCES dbo.Afiliado;
ALTER TABLE dbo.PersonaLiquidacionEspecifica ADD CONSTRAINT FK_PersonaLiquidacionEspecifica_pleBeneficiarioDetalle FOREIGN KEY (pleBeneficiarioDetalle) REFERENCES dbo.BeneficiarioDetalle;
ALTER TABLE dbo.PersonaLiquidacionEspecifica ADD CONSTRAINT FK_PersonaLiquidacionEspecifica_pleGrupoFamiliar FOREIGN KEY (pleGrupoFamiliar) REFERENCES dbo.GrupoFamiliar;

CREATE TABLE dbo.ParametrizacionSubsidioAjuste (
	psaId BIGINT NOT NULL IDENTITY, 
	psaPeriodoLiquidacion BIGINT NOT NULL, 
	psaValorCuotaAjuste NUMERIC(19,5) NOT NULL, 
	psaValorCuotaAgrariaAjuste NUMERIC(19,5) NOT NULL, 
	CONSTRAINT PK_ParametrizacionSubsidioAjuste_psaId PRIMARY KEY (psaId)
);

ALTER TABLE dbo.ParametrizacionSubsidioAjuste ADD CONSTRAINT FK_ParametrizacionSubsidioAjuste_psaPeriodoLiquidacion FOREIGN KEY (psaPeriodoLiquidacion) REFERENCES dbo.PeriodoLiquidacion;