--liquibase formatted sql

--changeset borozco:01 
--comment: Se eliminan registros de la tabla ValidacionProceso
DELETE FROM ValidacionProceso WHERE vapBloque IN ('ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_GRUPO_FAMILIAR_PRESENCIAL',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MAYOR_1_5SM_0_6_PRESENCIAL',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MAYOR_1_5SM_2_PRESENCIAL',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MENOR_1_5SM_0_6_PRESENCIAL',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MENOR_1_5SM_2_PRESENCIAL',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_GRUPO_FAMILIAR_WEB',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MAYOR_1_5SM_0_6_WEB',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MAYOR_1_5SM_2_WEB',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MENOR_1_5SM_0_6_WEB',
'ACTUALIZAR_VALOR_MESADA_PENSIONAL_PENSIONADO_MENOR_1_5SM_2_WEB')
AND vapValidacion IN ('VALIDACION_PERSONA_INDEPENDIENTE_ACTIVO', 'VALIDACION_PERSONA_DEPENDIENTE_ACTIVO' );

--changeset jocorrea:02
--comment: Se eliminan registros de la tabla ValidacionProceso
DELETE FROM ValidacionProceso
WHERE vapBloque IN ('NOVEDAD_RETIRO_CONYUGE',
'NOVEDAD_RETIRO_HJO_BIOLOGICO',
'NOVEDAD_RETIRO_HIJASTRO',
'NOVEDAD_RETIRO_HERMANO_HUERFANO',
'NOVEDAD_RETIRO_HIJO_ADOPTIVO',
'NOVEDAD_RETIRO_BENEFICIARIO_CUSTODIA',
'NOVEDAD_RETIRO_PADRE',
'NOVEDAD_RETIRO_MADRE');

--changeset jocampo:03
--comment: Se adiciona registro de la tabla parametro
INSERT INTO [Parametro] ([prmNombre],[prmValor],[prmCargaInicio],[prmSubCategoriaParametro],[prmDescripcion]) VALUES('mail.smtp.fromName', 'Caja Compensación', 0, 'MAIL_SMTP', 'Se refiere al nombre del remitente en los envíos de correo de la solución');

--changeset fvasquez:04
--comment: Se adiciona campos en aporte general y se eliminan de aportedetallado
ALTER TABLE AporteGeneral ADD apgFechaReconocimiento DATETIME NULL;
ALTER TABLE AporteGeneral ADD apgFormaReconocimientoAporte VARCHAR(75) NULL;