--comment: Eliminación de la Validaciones del conyuge para el ambiente SUCRE - GLPI 60949

delete from ValidacionProceso WHERE  vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'  AND  vapBloque
like 'ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_HIJO_BIOLOGICO';

delete from ValidacionProceso WHERE  vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'  AND  vapBloque
like 'ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_HIJO_ACTIVO';

delete from ValidacionProceso WHERE  vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'  AND  vapBloque
like 'ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_HIJASTRO_OTRO_GRUPO_FAMILIAR';

delete from ValidacionProceso WHERE  vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'  AND  vapBloque
like 'ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_HIJO_2_GRUPO_AFILIADO_GENERO';

delete from ValidacionProceso WHERE  vapProceso = 'NOVEDADES_PERSONAS_PRESENCIAL'  AND  vapBloque
like 'ACTIVAR_BENEFICIARIO_CONYUGE_PRESENCIAL' AND vapValidacion = 'VALIDACION_PERSONA_SIN_COINCIDENCIA_APELLIDOS';