--liquibase formatted sql

--changeset Heinsohn:01
--comment: Inserción de PlantillaComunicado

--Comunicado No. 1 Carta entidad pagadora (HU-121-109)
INSERT PlantillaComunicado (pcoNombre,pcoEtiqueta) VALUES ('Carta entidad pagadora','CRT_ENT_PAG');

--Comunicado No. 2 Notificación de radicación de solicitud de afiliación de persona (HU-121-107)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificacion de radicacion de solicitud afiliacion persona','<p>Le informamos que su solicitud de afiliación fue recibida satisfactoriamente,sus documentos serán verificados y posteriormente le será notificada la evaluación del resultado.</p><p>Si tienen dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificacion de radicacion solicitud de afiliacion de persona','Notificación de radicación solicitud afiliación de persona','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_RAD_AFL_PER')

--Comunicado No. 3 Notificación de intento de afiliación (Proceso Transversal) 
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de incumplimiento de requisitos en solicitud de afiliación','<p>La solicitud de afiliación que intentó realizar no pudo ser completada por exceder el límite de tiempo estimado para ingresar los datos de afiliación. Le sugerimos lo intente nuevamente procurando completar el proceso para procesar su afiliación. Si tienen dudas al respecto comuníquese a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}</p>','<p>${ciudadCcf},${fechaDelSistema} </p><p>Señores</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificación de intento de afiliación','Notificación de intento de afiliación','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_INT_AFL') 

--Comunicado No. 4 Carta de bienvenida para empleador (HU-111-066)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Bienvenido a su caja de compensación','<p>En ${nombreCcf} buscamos cada día ser la Caja que ayuda a los trabajadores a alcanzar sus sueños de bienestar, es por ello que le agradecemos que nos abra las puertas de su empresa para ser su aliado en el mejoramiento de la calidad de vida de sus trabajadores y su familia. </p><p>Bienvenido a ${nombreCcf}, su Caja de Compensación. En unos días le estaremos comunicando el estado de su solicitud, una vez realizaremos el proceso de verificación de la información. </p><p>No dude en comunicarse con nosotros si tiene alguna inquietud Oficina de Aportes, teléfono ${telefonoCcf}</p>','<p>${ciudadSolicitud}, ${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccionRepresentanteLegal}</p><p>${telefonoRepresentanteLegal}</p><p>Ciudad</p>',NULL,'<p>Se&ntilde;ores&nbsp;</p><br/><p>${razonSocial/Nombre}<br/><br/><br/>Reciban un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a comenzar a gozar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}</p><br/>${direccionRepresentanteLegal}<br/>${responsableAfiliacionCcf}<br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>','Carta de bienvenida para empleador','<p>Cordialmente,</p><p>${responsableAfiliacionCcf}</p>','CRT_BVD_EMP')

--Comunicado No. 5 Carta de aceptación de empleador (HU-111-066)
INSERT PlantillaComunicado (pcoCuerpo,pcoEncabezado,pcoNombre,pcoEtiqueta) VALUES ('<p style="text-align: justify;">El suscrito <strong>${nombreYApellidosRepresentanteLegal}</strong>  &nbsp;en mi nombre propio como persona natural o en mi car&aacute;cter como representante legal de este empleador, solicito a <strong>${nombreCcf}</strong>, la afiliaci&oacute;n del empleador que represento y si fuera aceptado me comprometo a cumplir y respetar todas las normas, as&iacute; como las disposiciones legales que se refieren al subsidio familiar.</p><p><strong>Declaraci&oacute;n:</strong></p><p style="text-align: justify;">Cualquier falsedad u omisi&oacute;n voluntaria conlleva a la anulaci&oacute;n de esta solicitud.<input id="aceptacionDeclaracion" name="aceptacionDeclaracion" type="checkbox" /></p><p>&nbsp;</p><p>___________________________________</p><p><strong>${nombreYApellidosRepresentanteLegal}</strong></p><p>&nbsp;</p><br/>${direccionRepresentanteLegal}<br/>${telefonoRepresentanteLegal}<br/>${ciudadRepresentanteLegal}<br/>${sede}<br/>${direccionSede}<br/>${parametroValorCuotaMonetariaUrbano}<br/>${parametroValorCuotaMonetariaRural}<br/><br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>','<p>${ciudadSede}&nbsp;</p><p>${fechaDelSistema}</p>','Carta de aceptación de empleador','CRT_ACP_EMP');

--Comunicado No. 6 Rechazo de solicitud de afiliación de empresa (HU-111-070, HU-112-137)
INSERT PlantillaComunicado (pcoNombre,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de empresa','RCHZ_AFL_EMP');

--Comunicado No. 7 Rechazo de solicitud de afiliación de empleador inconsistencia validación (HU-112-126) 
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud por inconsistencia de validacion','<p>Le informamos que su solicitud de afiliación no pudo ser procesada por inconsistencias en la documentación,si tienen dudas al respecto le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}</p>','<p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'A continuacion se adjunta documento el cual explica el porque se rechazo la solicitud.','Rechazo de solicitud de afiliación de empleador inconsistencia validación','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_EMP_INC_VAL') 

--Comunicado No. 8 Notificación para requerir subsanación de solicitud de afiliación de empleador (HU-112-126)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificacion de subsanacion solicitud de afiliacion de empleador','<p>Deseamos agradecer el interés al efectuar su solicitud de afiliación a la Caja. Para dar continuidad al trámite de su solicitud debe adjuntar la siguiente documentación:</p><p>${contenido}</p>','<p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para Requerir subsanacion de solicitud afiliacion de empleador','Notificación para requerir subsanación de solicitud de afiliación de empleador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_SBC_AFL_EMP')

--Comunicado No. 9 Rechazo de solicitud de afiliación de empleador por producto no conforme no subsanado (HU-112-358)
INSERT PlantillaComunicado (pcoNombre,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de empleador por producto no conforme no subsanado','RCHZ_AFL_EMP_PROD_NSUB');

--Comunicado No. 10 Rechazo de solicitud de afiliación de empleador por producto no conforme no subsanable (HU-112-126)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud por producto no confomre no subsanable','<p>Luego de verificar la documentación adjuntada para completar el proceso de afiliación,se determinó que no es posible realizar la afiliación,por favor verifique la documentación y le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación si tienen dudas al respecto o acérquese a la sede de la caja de compensación dirección ${direccionCcf}</p>','<p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'A continuacion se adjunta documento el cual explica el porque se rechazo la solicitud de afiliacion.','Rechazo de solicitud de afiliación de empleador por producto no conforme no subsanable','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_EMP_PROD_NSUBLE')

--Comunicado No. 11 Rechazo de solicitud de afiliación de trabajador dependiente inconsistencia validación caso trabajador (HU-122-369)
INSERT PlantillaComunicado (pcoNombre,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de trabajador dependiente INconsistencia validación caso trabajador','RCHZ_AFL_DPT_INC_VAL_TRAB');

--Comunicado No. 12 Rechazo de solicitud de afiliación de trabajador dependiente inconsistencia validación caso empleador (HU-122-369)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliacion trabajador dependiente','<p>Le informamos que su solicitud de afiliación por los colaboradores reportados,no pudo ser procesada por inconsistencias en la documentación,si tienen dudas al respecto le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de trabajador dependiente inconsistencia validación caso empleador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_DPT_INC_VAL_EMP')

--Comunicado No. 13 Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanado dirigida a trabajador (HU-122-369) 
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliacion trabajador dependiente','<p>Le informamos que debido a la no obtención de respuesta por parte suya para completar la documentación requerida y dar continuidad al proceso de afiliación su solicitud fue rechazada,si tienen dudas al respecto le invitamos a comunicarse a los teléfonos ${telefonoCcf}  área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionDeResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanado dirigida a trabajador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_DPT_PROD_NSUB_TRB')

--Comunicado No. 14 Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanado dirigida a empleador (HU-122-369)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliacion por producto no conforme no subsanado','<p>Le informamos que debido a no obtener de respuesta por parte suya para completar la documentación requerida y dar continuidad al proceso de afiliación de sus colaboradores,su solicitud fue rechazada,si tienen dudas al respecto le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanado dirigida a empleador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_DPT_PROD_NSUB_EMP')

--Comunicado No. 15 Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanable dirigida a trabajador (HU-122-369)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliacion por producto no conforme no subsanable','<p>Luego de verificar la documentación adjuntada para completar el proceso de afiliación,se determinó que no es posible realizar la afiliación,por favor verifique la documentación y le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionDeResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanable dirigida a trabajador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_DPT_PROD_NSUBLE_TRB')

--Comunicado No. 16 Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanable dirigida a empleador (HU-122-369)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliacion por producto no conforme no subsanable','<p>Luego de verificar la documentación adjuntada para completar el proceso de afiliación,se determinó que no es posible realizar la afiliación de sus colaboradores,por favor verifique la documentación y le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de trabajador dependiente por producto no conforme no subsanable dirigida a empleador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_DPT_PROD_NSUBLE_EMP')

--Comunicado No. 17 Notificación para empleador de resultados de afiliación múltiple trabajadores web (HU-122-360)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación para empleador de resultados de afiliación múltiple trabajadores web','<p>Le informamos de la solicitud de múltiple afiliación por los colaboradores relacionados fue recibida satisfactoriamente,todos sus documentos serán verificados y posteriormente le será notificada la evaluación del resultado.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Sr Usuario</p><p>Le informamos que su solicitud de afiliación por los colaboradores reportados fue recibida con éxito,sus documentos serán verificados por el área encargada y le notificaremos la evaluación del resultado.</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación para empleador de resultados de afiliación múltiple trabajadores web','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_EMP_AFL_MLT_TRBW')

--Comunicado No. 18 Notificación individual de resultado de afiliación trabajador web (trabajador) (HU-122-360 y 361)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación individual de resultado de afiliación trabajador web (trabajador).','<p>Le informamos que se encuentra en proceso de verificación la documentación entregada por ${razonSocial/Nombre} </p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}<p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Sr Usuario</p><p>Le informamos que su solicitud de afiliación por los colaboradores reportados fue recibida con éxito,sus documentos serán verificados por el área encargada y le notificaremos la evaluación del resultado.</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación individual de resultado de afiliación trabajador web (trabajador)','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_INVL_AFL_TRBW')

--Comunicado No. 19 Notificación para requerir subsanación de solicitud de afiliación de trabajador dependiente (HU-122-369)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación para requerir subsanación de solicitud afiliación trabajador dependiente empleador','<p>Deseamos agradecer el interés de incluir a su colaborador ${nombresYApellidosDelAfiliadoPrincipal} a su caja de compensación familiar ${nombreCcf}. ). No obstante,después de verificar la documentación y para dar continuidad al trámite de afiliación debe adjuntar los siguientes documentos:</p><p>${contenido}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación para requerir subsanación de solicitud afiliación</p>','Notificación para requerir subsanación de solicitud afiliación de trabajador dependiente','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_SUB_AFL_TRB_DPT')

--Comunicado No. 20 Notificación individual de resultados de afiliación de trabajadores web (empleador) (HU-112-361)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación individual de resultado de afiliación de trabajadores web. (Empleador)','<p>Le informamos que la solicitud de afiliación por su colaborador ${nombresYApellidosDelAfiliadoPrincipal} fue recibida satisfactoriamente,todos sus documentos serán verificados y posteriormente le notificaremos la evaluación del resultado.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación para requerir subsanación de solicitud afiliación</p>','Notificación individual de resultados de afiliación de trabajadores web (empleador)','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_INVL_AFL_TRBW_EMP')

--Comunicado No. 21 Notificación de resultados del registro de beneficiarios en la solicitud web de una trabajador dirigida al trabajador (HU-122-361)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de resultados del registro de beneficiarios solicitud web trabajador (Trabajador)','<p>Le informamos que se encuentra en proceso de verificación la documentación entregada por ${razonSocial/Nombre} para afiliarle con nosotros como su caja de compensación familiar </p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación de resultados del registro de beneficiarios en la solicitud web de un trabajador (Trabajador)</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación de resultados del registro de beneficiarios en la solicitud web de una trabajador dirigida al trabajador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_REG_BNF_WEB_TRB')

--Comunicado No. 22 Notificación de resultados del registro de beneficiarios en la solicitud web de una trabajador dirigida al empleador (HU-122-365)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de resultados del registro de beneficiarios solicitud web trabajador (Empleador)','<p>Le informamos que la solicitud de afiliación por su colaborador ${nombresYApellidosDelAfiliadoPrincipal} fue recibida satisfactoriamente </p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación de resultados del registro de beneficiarios en la solicitud web de un trabajador (Trabajador)</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación de resultados del registro de beneficiarios en la solicitud web de una trabajador dirigida al empleador','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_REG_BNF_WEB_EMP')

--Comunicado No. 23 Notificación de enrolamiento afiliación independiente web (HU-123-374)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Solicitud de afiliación CCF ${nombreCcf}','<p>Para continuar con el proceso de afiliación haga clic en el enlace,recuerde que el enlace será bloqueado de no ser completado el proceso”</p><p>Si el enlace está bloqueado,le sugerimos reinciar el proceso de afiliación</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p>',NULL,'Señor(a)<br/>${nombresYApellidosDelAfiliadoPrincipal}<br/> Para continuar con el proceso de afiliación por favor aga clic en el enlace: ${enlaceDeEnrolamiento} recuerde que el enlace será bloqueado de no ser completado el proceso en la últimas ${tiempoexpiracionenlace} desde el momento de envio del presente correo.<br/> Si el enlace está bloqueado,le sugerimos reinciar el proceso de afiliación en el siguiente enlace ${enlacePortalPublicoCcf}<br/>Cordial saludo <br/>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”<br/><br/>AVISO LEGAL: El contenido de este mensaje y de los archivos adjuntos están dirigidos exclusivamente a sus destinatarios y puede contener información privilegiada o confidencial. Si usted no es el destinatario real,por favor informe de ello al remitente y elimine el mensaje de inmediato. Cualquier uso,distribución o reproducción de este correo sin autorización previa de ${nombreCcf},se considerará una vulneración al derecho de protección de los datos personales o de Hábeas Data.','Notificación de enrolamiento afiliación independiente web','<p>Cordial saludo </p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','NTF_ENRL_AFL_IDPE_WEB')

--Comunicado No. 24 Notificación de enrolamiento afiliación pensionado web (HU-123-374)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Solicitud de afiliación CCF ${nombreCcf}','<p>Para continuar con el proceso de afiliación haga clic en el enlace,recuerde que el enlace será bloqueado de no ser completado el proceso”</p><p>Si el enlace está bloqueado,le sugerimos reinciar el proceso de afiliación</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p>',NULL,'Señor(a)<br/>${nombresYApellidosDelAfiliadoPrincipal}<br/> Para continuar con el proceso de afiliación por favor aga clic en el enlace: ${enlaceDeEnrolamiento} recuerde que el enlace será bloqueado de no ser completado el proceso en la últimas ${tiempoexpiracionenlace} desde el momento de envio del presente correo.<br/> Si el enlace está bloqueado,le sugerimos reinciar el proceso de afiliación en el siguiente enlace ${enlacePortalPublicoCcf}<br/>Cordial saludo <br/>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”<br/><br/>AVISO LEGAL: El contenido de este mensaje y de los archivos adjuntos están dirigidos exclusivamente a sus destinatarios y puede contener información privilegiada o confidencial. Si usted no es el destinatario real,por favor informe de ello al remitente y elimine el mensaje de inmediato. Cualquier uso,distribución o reproducción de este correo sin autorización previa de ${nombreCcf},se considerará una vulneración al derecho de protección de los datos personales o de Hábeas Data.','Notificación de enrolamiento afiliación independiente web','<p>Cordial saludo </p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','NTF_ENRL_AFL_PNS_WEB')

--Comunicado No. 25 Notificacion de aceptación de afiliacion pensionado despues de subsanacion (HU-123-384)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificacion de aceptación de afiliación pensionado','<p>Le informamos que su solicitud de afiliación fue aceptada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificacion de aceptación de afiliacion pensionado despues de subsanacion','Notificacion de aceptación de afiliacion pensionado despues de subsanacion','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_ACPT_AFL_PNS_DSP_SUB')

--Comunicado No. 26 Notificacion de rechazo de afiliacion pensionado despues de subsanacion (HU-123-384)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de rechazo de afiliación pensionado despues de subsanacion','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificación de rechazo de afiliación pensionado despues de subsanacion','Notificación de rechazo de afiliación pensionado despues de subsanacion','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_RCHZ_AFL_PNS_DSP_SUB')

--Comunicado No. 27 Notificacion de aceptación de afiliacion de independiente despues de subsanacion (HU-123-384)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificacion de aceptación de afiliación independiente','<p>Le informamos que su solicitud de afiliación fue aceptada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificacion de aceptación de afiliacion de independiente despues de subsanación','Notificacion de aceptación de afiliacion de independiente despues de subsanacion','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_ACPT_AFL_IDPE_DSP_SUB')

--Comunicado No. 28 Notificacion de rechazo de afiliacion de independiente despues de subsanacion (HU-123-384)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de rechazo de afiliación independiente despues de subsanacion','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificacion de rechazo de afiliacion de independiente despues de subsanacion','Notificacion de rechazo de afiliacion de independiente despues de subsanacion','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_RCHZ_AFL_IDPE_DSP_SUB')

--Comunicado No. 29 Rechazo de solicitud de afiliación de independiente inconsistencia validación (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de pensionado inconsistencia validación','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de pensionado inconsistencia validación','Rechazo de solicitud de afiliación de pensionado inconsistencia validación','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_PNS_INC_VAL')

--Comunicado No. 30 Rechazo de solicitud de afiliación de pensionado inconsistencia validación (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de independiente inconsistencia validación','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de independiente inconsistencia validación','Rechazo de solicitud de afiliación de independiente inconsistencia validación','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_IDPE_INC_VAL')

--Comunicado No. 31 Rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanable (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de pensionado producto no conforme','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanable','Rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanable','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_PNS_PROD_NSUBLE')

--Comunicado No. 32 Rechazo de solicitud de afiliación de independiente por producto no conforme no subsanable (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de indeoendiente producto no conforme','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanable','Rechazo de solicitud de afiliación de independiente por producto no conforme no subsanable','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_IDPE_PROD_NSUBLE')

--Comunicado No. 33 Notificación para requerir subsanación de solicitud de afiliación de pensionado (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Solicitud afiliación requiere subsanación','<p>Deseamos agradecer el interés de incluir a su caja de compensación familiar ${nombreCcf} teléfono ${telefonoCcf}. No obstante,después de verificar la documentación y para dar continuidad al trámite de afiliación debe adjuntar los siguientes documentos:</p><p>${contenido}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de notificación para requerir subsanación de solicitud de afiliación de pensionado','Notificación para requerir subsanación de solicitud de afiliación de pensionado','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_SBC_AFL_PNS')

--Comunicado No. 34 Notificación para requerir subsanación de solicitud de afiliación de independiente (HU-123-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Solicitud afiliación requiere subsanación','<p>Deseamos agradecer el interés de incluir a su caja de compensación familiar ${nombreCcf} teléfono ${telefonoCcf}. No obstante,después de verificar la documentación y para dar continuidad al trámite de afiliación debe adjuntar los siguientes documentos:</p><p>${contenido}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de notificación para requerir subsanación de solicitud de afiliación de independiente','Notificación para requerir subsanación de solicitud de afiliación de independiente','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_SBC_AFL_IDPE')

--Comunicado No. 35 Rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanado (HU-123-382)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de independiente inconsistencia validación','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanado','Rechazo de solicitud de afiliación de pensionado por producto no conforme no subsanado','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_PNS_PROD_NSUB')

--Comunicado No. 36 Rechazo de solicitud de afiliación de independiente por producto no conforme no subsanado (HU-123-382) 
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de independiente producto no conforme','<p>Le informamos que su solicitud de afiliación fue rechazada.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de rechazo de solicitud de afiliación de independiente por producto no conforme no subsanado','Rechazo de solicitud de afiliación de independiente por producto no conforme no subsanado','<p>Cordial saludo</p><p>${responsableCcf}</p>','RCHZ_AFL_IDPE_PROD_NSUB')

--Comunicado No. 37 Notificación de radicación solicitud de afiliación independiente web (HU-123-378)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación solicitud de afiliación independiente web','<p>solicitud radicación solicitud afiliación independiente web.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} direccion ${direccionCcf}</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de notificación de radicación solicitud de afiliación independiente web','Notificación de radicación solicitud de afiliación independiente web','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_RAD_AFL_IDPE_WEB')

--Comunicado No. 38 Notificación de radicación solicitud de afiliación pensionado web (HU-123-378)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación solicitud de afiliación pensionado web','<p>solicitud radicación solicitud afiliación pensionado web.</p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su ${nombreCcf} </p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje de notificación de radicación solicitud de afiliación pensionado web','Notificación de radicación solicitud de afiliación pensionado web','<p>Cordial saludo</p><p>${responsableCcf}</p>','NTF_RAD_AFL_PNS_WEB')

--Comunicado No. 39 Carta de bienvenida para independiente (HU-123-379)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Carta de bienvenida para independiente','<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>','Carta de bienvenida para independiente','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','CRT_BVD_IDPE')

--Comunicado No. 40 Carta de bienvenida para pensionado (HU-123-379)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Carta de bienvenida para pensionado','<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>','Carta de bienvenida para pensionado','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','CRT_BVD_PNS')

--Comunicado No. 41 Carta de aceptación de independiente (HU-123-379)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Carta de aceptación de independiente','<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>','Carta de aceptación de independiente','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','CRT_ACP_IDPE')

--Comunicado No. 42 Carta de aceptación de pensionado (HU-123-379)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Carta de aceptación de pensionado','<br/>${logoDeLaCcf}<br/><br/>${departamentoCcf}<br/><br/>${ciudadCcf}<br/><br/>${direccionCcf}<br/><br/>${telefonoCcf}<br/><br/>${tipoIdCcf}<br/><br/>${numeroIdCcf}<br/><br/>${logoSuperservicios}<br/><br/>${webCcf}<br/><br/>${firmaResponsableCcf}<br/><br/>${responsableCcf}<br/><br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Señor(a) <br/>${nombresYApellidosDelAfiliadoPrincipal}<br/><br/><br/>Reciba un cordial saludo.<br/><br/>En nombre de la ${nombreCcf} le damos la bienvenida. Lo invitamos a disfrutar de los distintos servicios que le ofrecemos.<br/><br/><br/>Cordialmente,<br/><br/>${nombreCcf}. <br/>${ciudadSolicitud}<br/><br/>${direccionResidencia}<br/><br/>${telefono}<br/><br/>${fechaDelSistema}<br/>','Carta de aceptación de pensionado','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','CRT_ACP_PNS')

--Comunicado No. 43 Notificación de radicación solicitud de afiliación empleador web (HU-112-121 /127)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación de solicitud','<p>Le informamos que su solicitud de afiliación fue recibida satisfactoriamente,todos sus documentos serán verificados y posteriormente le será notificada la evaluación del resultado.</p><p>Si presenta alguna duda al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar</p>','<p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificcion de radicacion solicitud de afiliacion empleador web','Notificación de radicación solicitud de afiliación empleador web','<p>Cordial saludo,</p><p>${responsableCcf}</p>','NTF_RAD_AFL_EMP_WEB')

--Comunicado No. 44 Notificación de enrolamiento afiliación empleador web (HU-112-110)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Continuación proceso de afiliación  de empleador','<p>Para continuar con el proceso de afiliación haga clic en el enlace</p><p>recuerde que el enlace será bloqueado de no ser completado el proceso </p>','<p>${logoDeLaCcf}</p><p>Señor(a)</p><p>&nbsp;</p>',NULL,'Señores <br/>[razonSocialEmpleador]<br/>Las validaciones preliminares han sido exitosas. Para continuar con el proceso de afiliación por favor seguir el siguiente vínculo:<br/><br/><a href="[linkRegistro]">[linkRegistro]</a><br/><br/>Cordialmente,<br/><br/>[nombreSedeCCF]','Notificación de enrolamiento afiliación empleador web','<p>Cordial saludo,</p>','NTF_ENRL_AFL_EMP_WEB')

--Comunicado No. 45  Notificación de resultados del registro de beneficiarios en la solicitud web para independiente (HU-122-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación resultado de registro beneficiarios','<p>Le informamos que la solicitud de afiliación por su colaborador ${nombresYApellidosDelAfiliadoPrincipal} fue recibida satisfactoriamente </p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación de resultados del registro de beneficiarios en la solicitud web para independiente</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación de resultados del registro de beneficiarios en la solicitud web para independiente','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','NTF_REG_BNF_WEB_IDPE')

--Comunicado No. 46 Notificación de resultados del registro de beneficiarios en la solicitud web para pensionado (HU-122-380)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación resultado de registro beneficiarios','<p>Le informamos que la solicitud de afiliación por su colaborador ${nombresYApellidosDelAfiliadoPrincipal} fue recibida satisfactoriamente </p><p>Si presenta dudas al respecto,por favor comuníquese con los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>Notificación de resultados del registro de beneficiarios en la solicitud web para pensionado</p><p>Importante: Este correo es informativo,favor no responder a esta dirección de correo. Si requiere mayor información sobre el contenido de este correo,contactar los teléfonos ${telefonoCcf} área de afiliación de su “caja de compensación familiar”</p>','Notificación de resultados del registro de beneficiarios en la solicitud web para pensionado','<p>Cordial saludo</p><p>${responsableAfiliacionCcf}</p>','NTF_REG_BNF_WEB_PNS')

--Comunicado No. 48 Notificación de novedad de empleador (131-421, 131-463, 131-423, 13-417, 13-418, 133-458, 133-459, 133-461)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de resultados de solicitud de novedad empleador','<p>solicitud de novedad empleador. Resultado de la novedad ${resultadoNovedad}.</p><p>Si tienen dudas al respecto comuníquese a los teléfonos ${telefonoCcf} área de novedades o acérquese a la sede de la caja de compensación dirección ${direccionCcf}</p>','<p>${nombreCcf}</p><p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema} </p><p>Señores</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificación de resultados de solicitud de novedad empleador','Notificación de resultados de solicitud de novedad empleador','<p>Cordial saludo,</p><p>${responsableAfiliacionCcf}</p>','NTF_NVD_EMP')

--Comunicado No. 50 Notificación de radicación de novedad de empleador (HU-13-421, HU-133-458)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación de solicitud de novedad de empleador','<p>solicitud de novedad empleador. Resultado de la novedad ${resultadoNovedad}.</p><p>Si tienen dudas al respecto comuníquese a los teléfonos ${telefonoCcf} área de novedades o acérquese a la sede de la caja de compensación dirección ${direccionCcf}</p>','<p>${nombreCcf}</p><p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema} </p><p>Señores</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para notificación de radicación de solicitud de novedad de empleador','Notificación de radicación de solicitud de novedad de empleador','<p>Cordial saludo,</p><p>${responsableAfiliacionCcf}</p>','NTF_RAD_NVD_EMP')

--Comunicado No. 51 Nofificación de rechazo de novedad de empleador por producto no conforme no subsanable (131-423, 133-461)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de resultados de solicitud de novedad empleador','${ciudadSolicitud}<br/>${fechaDelSistema}<br/>${nombreYApellidosRepresentanteLegal}<br/>${razonSocial/Nombre}<br/>${direccion}<br/>${telefono}<br/>${productoNoConformeNoSubsanado}<br/>${responsableAfiliacionCcf}<br/>${nombreCcf}<br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p><p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema} </p><p>Señores</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para Rechazo solicitud novedad empleador producto no conforme no subsanable','Rechazo de solicitud de novedad de empleador por producto no conforme no subsanable','<p>Cordial saludo,</p><p>${responsableAfiliacionCcf}</p>','RCHZ_NVD_EMP_PROD_NSUBLE')

--Comunicado No. 53 Solicitud confirmacion retiro aportante (131-463, 131-423, 134-445, 134-447)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de retiro aportante','${ciudadSolicitud}<br/>${fechaDelSistema}<br/>${responsableAportes}<br/>${razonSocial/Nombre}<br/>${nombreYApellidosRepresentanteLegal}<br/>${responsableAfiliacionCcf}<br/>${nombreCcf}<br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p><p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema} </p><p>Señor(a)</p><p>${responsableAportes}</p><p>Ciudad</p>',NULL,'Mensaje de Solicitud de confirmación retiro de aportante','Solicitud de confirmación retiro de aportante','<p>Cordial saludo,</p><p>${responsableAfiliacionCcf}</p>','CNFR_RET_APRT')

--Comunicado No. 54 Desistimiento novedad de retiro de aportante (13-418)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Notificación de radicación de solicitud de novedad de empleador', '${ciudadSolicitud}<br/>${fechaDelSistema}<br/>${nombreYApellidosRepresentanteLegal}<br/>${razonSocial/Nombre}<br/>${direccion}<br/>${telefono}<br/>${novedadEmpleador}<br/>${nombreCcf}<br/>${logoDeLaCcf}<br/>${departamentoCcf}<br/>${ciudadCcf}<br/>${direccionCcf}<br/>${telefonoCcf}<br/>${tipoIdCcf}<br/>${numeroIdCcf}<br/>${webCcf}<br/>${logoSuperservicios}<br/>${firmaResponsableCcf}<br/>${responsableCcf}<br/>${cargoResponsableCcf}<br/>','<p>${nombreCcf}</p><p>${logoDeLaCcf}</p><p>${ciudadCcf},${fechaDelSistema} </p><p>Señores</p><p>${nombreYApellidosRepresentanteLegal}</p><p>Representante Legal</p><p>${razonSocial/Nombre}</p><p>${direccion}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'Mensaje para desistimiento novedad de retiro de aportante','Desistimiento novedad de retiro de aportante','<p>Cordial saludo,</p><p>${responsableAfiliacionCcf}</p>','DSTMTO_NVD_RET_APRT')

--Comunicado No. 71 Rechazo de solicitud de afiliación de persona por producto no conforme no subsanable (HU-121-122)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de persona por producto no conforme no subsanable','<p>Luego de verificar la documentación adjuntada para completar el proceso de afiliación,se determinó que no es posible realizar la afiliación,por favor verifique la documentación y le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación si tienen dudas al respecto o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento el cual explica el porque se rechazo la solicitud de afiliacion.</p>','Rechazo de solicitud de afiliación de persona por producto no conforme no subsanable','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_PER_POR_PROD_NSUBLE')

--Comunicado No. 72 Rechazo de solicitud de afiliación de persona por producto no conforme no subsanado (HU-121-116)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de persona por producto no conforme no subsanado','<p>Le informamos que debido a que no obtuvimos respuesta por parte suya para completar la documentación requerida y dar continuidad al proceso de afiliación su solicitud fue rechazada,si tienen dudas al respecto le invitamos a comunicarse a los teléfonos ${telefonoCcf}  área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud},${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de persona por producto no conforme no subsanado','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_PER_POR_PROD_NSUB')

--Comunicado No. 82 Rechazo de solicitud de afiliación de persona inconsistencia validación (HU-123-381)
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Rechazo de solicitud de afiliación de persona inconsistencia validación','<p>Luego de verificar la documentación adjuntada para completar el proceso de afiliación, se determinó que no es posible realizar la afiliación, por favor le invitamos a comunicarse a los teléfonos ${telefonoCcf} área de afiliación o acérquese a la sede de la caja de compensación dirección ${direccionCcf}"</p>','<p>${nombreCcf}</p>${logoDeLaCcf}</p><p>${ciudadSolicitud}, ${fechaDelSistema}</p><p>Señor(a)</p><p>${nombresYApellidosDelAfiliadoPrincipal}</p><p>${direccionResidencia}</p><p>${telefono}</p><p>Ciudad</p>',NULL,'<p>A continuacion se adjunta documento e cual explica el porque se rechazo la solicitud</p>','Rechazo de solicitud de afiliación de personas inconsistencia validación','<p>Cordial saludo,</p><p>${responsableCcf}</p>','RCHZ_AFL_PER_INC_VAL')

--Comunicado Acuerdos de términos y condiciones WEB
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Acuerdo términos y condiciones web','<table style="width: 100%;"><tbody><tr style="width: 100%;"><th style="width: 20%; text-align: left;">&nbsp;LOGO</th><th style="width: 60%;"><strong>SOLICITUD DE AFILIACI&Oacute;N DE EMPLEADORES</strong>&nbsp;</th><th style="width: 20%; text-align: right;">N&uacute;mero de solicitud<br />${numeroRadicacion}&nbsp;</th></tr></tbody></table>',NULL,'Mensaje','<p style="text-align:justify;">El suscrito <strong>${nombres}</strong> con <strong>${tipoIdentificacion}</strong> No. <strong>${numeroIdentificacion}</strong> &nbsp;en mi nombre propio como persona natural o en mi car&aacute;cter como representante legal de este empleador,solicito a <strong>${nombreCcf}</strong>,la afiliaci&oacute;n del empleador que represento y si fuera aceptado me comprometo a cumplir y respetar todas las normas,as&iacute; como las disposiciones legales que se refieren al subsidio familiar. </p><p style="text-align:justify;">Acepto &nbsp;de antemano que la violaci&oacute;n por parte del empleador de cualquiera de estas normas, dar&aacute; derecho a <strong>${nombreCcf}</strong> para ordenar la expulsi&oacute;n del empleador afiliado. La responsabilidad en cuanto al subsidio familiar,queda limitada para la caja desde el momento de la afiliaci&oacute;n y pago de aportes por parte del empleador,hasta  que el empleador sea desafiliado por cualquier motivo. &nbsp;</p><p><strong>Declaraci&oacute;n:</strong></p><p style="text-align:justify;">En calidad de representante legal del empleador declaro que la INformaci&oacute;n registrada en este formulario es cierta y tiene por objeto solicitar la afiliaci&oacute;n a <strong>${nombreCcf}</strong>. En caso de ser aceptados como afiliados nos comprometemos a cumplir y a respetar la legislaci&oacute;n del Subsidio Familiar,al igual que los estatutos y reglamentos de <strong>${nombreCcf}</strong>.</p> <p style="text-align:justify;">Cualquier falsedad u omisi&oacute;n voluntaria conlleva a la anulaci&oacute;n de esta solicitud.<INput id="aceptacionDeclaracion" name="aceptacionDeclaracion" type="checkbox"></p><p>&nbsp;</p><p>___________________________________</p><p><strong>${nombres}</strong><br/>${tipoIdentificacion} ${numeroIdentificacion}</p><p>&nbsp;</p>','Acuerdo de términos y condiciones web','v<p style="text-align: center;">&nbsp;</p><p style="text-align: center;">________________________________________________<br />Firma del representante legal y sello empleador</p>','ACRDS_TRMS_CDNES_WEB');

--Comunicado Acuerdo de términos y condiciones personas
INSERT PlantillaComunicado (pcoAsunto,pcoCuerpo,pcoEncabezado,pcoIdentificadorImagenPie,pcoMensaje,pcoNombre,pcoPie,pcoEtiqueta) VALUES ('Acuerdo de términos y condiciones personas','<p style="text-align:justify;">El suscrito <strong>${nombres}</strong> con <strong>${tipoIdentificacion}</strong> No. <strong>${numeroIdentificacion}</strong> &nbsp;en mi nombre propio como persona natural o en mi car&aacute;cter como representante legal de este empleador,solicito a <strong>${nombreCcf}</strong>,la afiliaci&oacute;n del empleador que represento y si fuera aceptado me comprometo a cumplir y respetar todas las normas,as&iacute; como las disposiciones legales que se refieren al subsidio familiar.</p><p style="text-align:justify;">Acepto &nbsp;de antemano que la violaci&oacute;n por parte del empleador de cualquiera de estas normas,dar&aacute; derecho a <strong>${nombreCcf}</strong> para ordenar la expulsi&oacute;n del empleador afiliado. La responsabilidad en cuanto al subsidio familiar,queda limitada para la caja desde el momento de la afiliaci&oacute;n y pago de aportes por parte del empleador,hasta que el empleador sea desafiliado por cualquier motivo. &nbsp;</p><p><strong>Declaraci&oacute;n:</strong></p><p style="text-align:justify;">En calidad de representante legal del empleador declaro que la INformaci&oacute;n registrada en este formulario es cierta y tiene por objeto solicitar la afiliaci&oacute;n a <strong>${nombreCcf}</strong>. En caso de ser aceptados como afiliados nos comprometemos a cumplir y a respetar la legislaci&oacute;n del Subsidio Familiar,al igual que los estatutos y reglamentos de <strong>${nombreCcf}</strong>.</p><p style="text-align:justify;">Cualquier falsedad u omisi&oacute;n voluntaria conlleva a la anulaci&oacute;n de esta solicitud.<INput id="aceptacionDeclaracion" name="aceptacionDeclaracion" type="checkbox"></p><p>&nbsp;</p><p>___________________________________</p><p><strong>${nombres}</strong><br/>${tipoIdentificacion} ${numeroIdentificacion}</p><p>&nbsp;</p>','<table style="width: 858px; height: 32px;"><tbody><tr style="width: 100%;"><th style="width: 20%; font-weight: normal;"><strong>&nbsp; LOGO &nbsp;</strong></th><th style="width: 60%; font-weight: normal;"><strong>SOLICITUD DE AFILIACI&Oacute;N DE &nbsp;${tipoAfiliado}&nbsp;</strong></th><th style="width: 20%; font-weight: normal;"><strong>&nbsp;N&uacute;mero de solicitud ${numeroRadicacion} &nbsp;</strong></th></tr></tbody></table>',NULL,'<p>Mensaje</p>','Acuerdo de términos y condiciones personas','<p style="text-align: center;">&nbsp;</p><p style="text-align: center;">________________________________________________<br />Firma de solicitante</p>','ACRDS_TRMS_CDNES_PERS');

--Comunicado Notificación de creación de usuario exitosa
INSERT PlantillaComunicado (pcoEtiqueta,pcoAsunto,pcoMensaje) VALUES ('NTF_CRCN_USR_EXT','Creación de usuario exitosa','Señor (a) <br/> [nombreUsuario] <br/><br/><br/> El usuario solicitado en el portal de GENESYS ha sido creado exitosamente. <br/><br/>Para autenticarse debe hacer uso de las siguientes credenciales:<br/><br/>Usuario:[usuario]<br/>Password:[Password]<br/><br/><br/>Cordialmente,<br/><br/><br/><br/>AdmINistrador GENESYS');

--Comunicado Notificación de recuperación de contraseña exitosa
INSERT PlantillaComunicado (pcoAsunto,pcoMensaje,pcoEtiqueta) VALUES ('Recuperación de contraseña sistema GENESYS','Señor(a)<br/>[nombreUsuario]<br/><br/><br/>Cordial Saludo<br/><br/>Se ha recuperado satisfactoriamente su contraseña. Por favor utilice las siguientes credenciales para autenticarse en el portal:<br/><br/>Usuario: [usuario]<br/>Password: [password]<br/><br/><br/>Cordialmente,<br/><br/><br/>AdmINistrador GENESYS','NTF_RECU_CNTRS_EXT');


