--changeset rlopez:01
--comment: Creacion tabla DetalleSubsidioAsignadoProgramado_aud
CREATE TABLE [DetalleSubsidioAsignadoProgramado_aud](
	[dprId] [bigint] IDENTITY(1,1) NOT NULL,
	REV bigint NOT NULL,
	REVTYPE smallint,
	[dprUsuarioCreador] [varchar](200) NOT NULL,
	[dprFechaHoraCreacion] [datetime] NOT NULL,
	[dprEstado] [varchar](20) NOT NULL,
	[dprMotivoAnulacion] [varchar](40) NULL,
	[dprDetalleAnulacion] [varchar](250) NULL,
	[dprOrigenRegistroSubsidio] [varchar](30) NOT NULL,
	[dprTipoliquidacionSubsidio] [varchar](60) NOT NULL,
	[dprTipoCuotaSubsidio] [varchar](80) NOT NULL,
	[dprValorSubsidioMonetario] [numeric](19, 5) NOT NULL,
	[dprValorDescuento] [numeric](19, 5) NOT NULL,
	[dprValorOriginalAbonado] [numeric](19, 5) NOT NULL,
	[dprValorTotal] [numeric](19, 5) NOT NULL,
	[dprFechaTransaccionRetiro] [date] NULL,
	[dprUsuarioTransaccionRetiro] [varchar](200) NULL,
	[dprFechaTransaccionAnulacion] [date] NULL,
	[dprUsuarioTransaccionAnulacion] [varchar](200) NULL,
	[dprFechaHoraUltimaModificacion] [datetime] NULL,
	[dprUsuarioUltimaModificacion] [varchar](200) NULL,
	[dprSolicitudLiquidacionSubsidio] [bigint] NOT NULL,
	[dprEmpleador] [bigint] NOT NULL,
	[dprAfiliadoPrincipal] [bigint] NOT NULL,
	[dprGrupoFamiliar] [bigint] NOT NULL,
	[dprAdministradorSubsidio] [bigint] NOT NULL,
	[dprIdRegistroOriginalRelacionado] [bigint] NULL,
	[dprCuentaAdministradorSubsidio] [bigint] NOT NULL,
	[dprBeneficiarioDetalle] [bigint] NOT NULL,
	[dprPeriodoLiquidado] [date] NOT NULL,
	[dprResultadoValidacionLiquidacion] [bigint] NOT NULL,
	[dprCondicionPersonaBeneficiario] [bigint] NULL,
	[dprCondicionPersonaAfiliado] [bigint] NULL,
	[dprCondicionPersonaEmpleador] [bigint] NULL,
 	CONSTRAINT FK_DetalleSubsidioAsignadoProgramado_aud_REV FOREIGN KEY (REV) REFERENCES Revision(revId)
)