--liquibase formatted sql

--changeset dasanchez:01
--comment:Se modifican campos en diferentes tablas
ALTER TABLE AFP ALTER COLUMN afpNombre VARCHAR(150) NOT NULL;

ALTER TABLE ARL ALTER COLUMN arlNombre VARCHAR(25) NOT NULL;

ALTER TABLE Beneficio ALTER COLUMN befVigenciaFiscal BIT NOT NULL;

ALTER TABLE CajaCompensacion ALTER COLUMN ccfHabilitado BIT NOT NULL;
ALTER TABLE CajaCompensacion ALTER COLUMN ccfMetodoGeneracionEtiquetas VARCHAR(150) NOT NULL;
ALTER TABLE CajaCompensacion ALTER COLUMN ccfNombre VARCHAR(100) NOT NULL;
ALTER TABLE CajaCompensacion ALTER COLUMN ccfSocioAsopagos BIT NOT NULL;
ALTER TABLE CajaCompensacion ALTER COLUMN ccfDepartamento SMALLINT NOT NULL;
ALTER TABLE CajaCompensacion ALTER COLUMN ccfCodigo VARCHAR(5) NOT NULL;

ALTER TABLE CodigoCIIU ALTER COLUMN ciiCodigo VARCHAR(4) NOT NULL;
ALTER TABLE CodigoCIIU ALTER COLUMN ciiDescripcion VARCHAR(255) NOT NULL;

ALTER TABLE Departamento ALTER COLUMN depCodigo VARCHAR(2) NOT NULL;
ALTER TABLE Departamento ALTER COLUMN depIndicativoTelefoniaFija VARCHAR(2) NOT NULL;
ALTER TABLE Departamento ALTER COLUMN depNombre VARCHAR(100) NOT NULL;

ALTER TABLE DiasFestivos ALTER COLUMN pifConcepto VARCHAR(150) NOT NULL;
ALTER TABLE DiasFestivos ALTER COLUMN pifFecha DATE NOT NULL;

ALTER TABLE ElementoDireccion ALTER COLUMN eldNombre VARCHAR(20) NOT NULL;

ALTER TABLE GradoAcademico ALTER COLUMN graNombre VARCHAR(20) NOT NULL;
ALTER TABLE GradoAcademico ALTER COLUMN graNivelEducativo VARCHAR(43) NOT NULL;

ALTER TABLE Municipio ALTER COLUMN munCodigo VARCHAR(6) NOT NULL;
ALTER TABLE Municipio ALTER COLUMN munNombre VARCHAR(50) NOT NULL;
ALTER TABLE Municipio ALTER COLUMN munDepartamento SMALLINT NOT NULL;

ALTER TABLE OcupacionProfesion ALTER COLUMN ocuNombre VARCHAR(100) NOT NULL;

ALTER TABLE Requisito ALTER COLUMN reqEstado VARCHAR(20) NOT NULL;

ALTER TABLE TipoVia ALTER COLUMN tviNombreVia VARCHAR(20) NOT NULL;