apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: archivos-service
  name: archivos-service
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: archivos-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: ${timestamp}
      creationTimestamp: null
      labels:
        app: archivos-service
      name: archivos-service
    spec:
      containers:
      - image: ${docker.registry.name}/${project.artifactId}
        imagePullPolicy: Always
        name: ${project.artifactId}
        ports:
        - containerPort: 8100
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}