metadata:
  name: archivos-service
  labels:
    app: archivos-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8100
      targetPort: 8100
  selector:
    name: archivos-service