--liquibase formatted sql

--changeset dasanchez:01
--comment: Eliminacion de identity para las campos primarios de las tablas de auditoria
ALTER TABLE AdministradorSubsidio_aud DROP COLUMN asuId;
ALTER TABLE AdministradorSubsidio_aud ADD asuId BIGINT NOT NULL;
ALTER TABLE AdminSubsidioGrupo_aud DROP COLUMN asgId;
ALTER TABLE AdminSubsidioGrupo_aud ADD asgId BIGINT NOT NULL;
ALTER TABLE AhorroPrevio_aud DROP COLUMN ahpId;
ALTER TABLE AhorroPrevio_aud ADD ahp BIGINT NOT NULL;
ALTER TABLE Banco_aud DROP COLUMN banId;
ALTER TABLE Banco_aud ADD banId BIGINT NOT NULL;
ALTER TABLE Beneficio_aud DROP COLUMN befId;
ALTER TABLE Beneficio_aud ADD befId BIGINT NOT NULL;
ALTER TABLE CargueArchivoActualizacion_aud DROP COLUMN caaId;
ALTER TABLE CargueArchivoActualizacion_aud ADD caaId BIGINT NOT NULL;
ALTER TABLE CicloAsignacion_aud DROP COLUMN ciaId;
ALTER TABLE CicloAsignacion_aud ADD ciaId BIGINT NOT NULL;
ALTER TABLE CicloModalidad_aud DROP COLUMN cmoId;
ALTER TABLE CicloModalidad_aud ADD cmoId BIGINT NOT NULL;
ALTER TABLE CondicionEspecial_aud DROP COLUMN coeId;
ALTER TABLE CondicionEspecial_aud ADD coeId BIGINT NOT NULL;
ALTER TABLE CondicionEspecialPersona_aud DROP CONSTRAINT PK_CondicionEspecialPersona_cepId;
ALTER TABLE CondicionEspecialPersona_aud DROP COLUMN cepId;
ALTER TABLE CondicionEspecialPersona_aud ADD cepId BIGINT NOT NULL;
ALTER TABLE Correccion_aud DROP COLUMN corId;
ALTER TABLE Correccion_aud ADD corId BIGINT NOT NULL;
ALTER TABLE DatoTemporalComunicado_aud DROP COLUMN dtcId;
ALTER TABLE DatoTemporalComunicado_aud ADD dtcId BIGINT NOT NULL;
ALTER TABLE DestinatarioComunicado_aud DROP COLUMN dcoId;
ALTER TABLE DestinatarioComunicado_aud ADD dcoId BIGINT NOT NULL;
ALTER TABLE DestinatarioGrupo_aud DROP COLUMN dgrId;
ALTER TABLE DestinatarioGrupo_aud ADD dgrId BIGINT NOT NULL;
ALTER TABLE DevolucionAporte_aud DROP COLUMN dapId;
ALTER TABLE DevolucionAporte_aud ADD dapId BIGINT NOT NULL;
ALTER TABLE DevolucionAporteDetalle_aud DROP CONSTRAINT PK_DevolucionAporteDetalle_dadId;
ALTER TABLE DevolucionAporteDetalle_aud DROP COLUMN dadId;
ALTER TABLE DevolucionAporteDetalle_aud ADD dadId BIGINT NOT NULL;
ALTER TABLE DiferenciasCargueActualizacion_aud DROP COLUMN dicId;
ALTER TABLE DiferenciasCargueActualizacion_aud ADD dicId BIGINT NOT NULL;
ALTER TABLE EntidadDescuento_aud DROP COLUMN endId;
ALTER TABLE EntidadDescuento_aud ADD endId BIGINT NOT NULL;
ALTER TABLE ExpulsionSubsanada_aud DROP COLUMN exsId;
ALTER TABLE ExpulsionSubsanada_aud ADD exsId BIGINT NOT NULL;
ALTER TABLE FormaPagoModalidad_aud DROP COLUMN fpmId;
ALTER TABLE FormaPagoModalidad_aud ADD fpmId BIGINT NOT NULL;
ALTER TABLE GestionNotiNoEnviadas_aud DROP COLUMN gneId;
ALTER TABLE GestionNotiNoEnviadas_aud ADD gneId BIGINT NOT NULL;
ALTER TABLE GrupoPrioridad_aud DROP COLUMN gprId;
ALTER TABLE GrupoPrioridad_aud ADD gprId BIGINT NOT NULL;
ALTER TABLE GrupoRequisito_aud DROP COLUMN grqId;
ALTER TABLE GrupoRequisito_aud ADD grqId BIGINT NOT NULL;
ALTER TABLE InformacionFaltanteAportante_aud DROP COLUMN ifaId;
ALTER TABLE InformacionFaltanteAportante_aud ADD ifaId BIGINT NOT NULL;
ALTER TABLE Infraestructura_aud DROP COLUMN infId;
ALTER TABLE Infraestructura_aud ADD infId BIGINT NOT NULL;
ALTER TABLE IntegranteHogar_aud DROP COLUMN inhId;
ALTER TABLE IntegranteHogar_aud ADD inhId BIGINT NOT NULL;
ALTER TABLE IntentoPostulacion_aud DROP COLUMN ipoId;
ALTER TABLE IntentoPostulacion_aud ADD ipoId BIGINT NOT NULL;
ALTER TABLE IntentoPostulacionRequisito_aud DROP COLUMN iprId;
ALTER TABLE IntentoPostulacionRequisito_aud ADD iprId BIGINT NOT NULL;
ALTER TABLE JefeHogar_aud DROP COLUMN jehId;
ALTER TABLE JefeHogar_aud ADD jehId BIGINT NOT NULL;
ALTER TABLE Licencia_aud DROP COLUMN licId;
ALTER TABLE Licencia_aud ADD licId BIGINT NOT NULL;
ALTER TABLE LicenciaDetalle_aud DROP COLUMN lidId;
ALTER TABLE LicenciaDetalle_aud ADD lidId BIGINT NOT NULL;
ALTER TABLE MedioDePago_aud DROP COLUMN mdpId;
ALTER TABLE MedioDePago_aud ADD mdpId BIGINT NOT NULL;
ALTER TABLE MedioPagoPersona_aud DROP COLUMN mppId;
ALTER TABLE MedioPagoPersona_aud ADD mppId BIGINT NOT NULL;
ALTER TABLE MediosPagoCCF_aud DROP COLUMN mpcId;
ALTER TABLE MediosPagoCCF_aud ADD mpcId BIGINT NOT NULL;
ALTER TABLE MovimientoAporte_aud DROP COLUMN moaId;
ALTER TABLE MovimientoAporte_aud ADD moaId BIGINT NOT NULL;
ALTER TABLE Oferente_aud DROP COLUMN ofeId;
ALTER TABLE Oferente_aud ADD ofeId BIGINT NOT NULL;
ALTER TABLE ParametrizacionCartera_aud DROP COLUMN pacId;
ALTER TABLE ParametrizacionCartera_aud ADD pacId BIGINT NOT NULL;
ALTER TABLE ParametrizacionCondicionesSubsidio_aud DROP COLUMN pcsId;
ALTER TABLE ParametrizacionCondicionesSubsidio_aud ADD pcsId BIGINT NOT NULL;
ALTER TABLE ParametrizacionFOVIS_aud DROP COLUMN pafId;
ALTER TABLE ParametrizacionFOVIS_aud ADD pafId BIGINT NOT NULL;
ALTER TABLE ParametrizacionLiquidacionSubsidio_aud DROP COLUMN plsId;
ALTER TABLE ParametrizacionLiquidacionSubsidio_aud ADD plsId BIGINT NOT NULL;
ALTER TABLE ParametrizacionModalidad_aud DROP COLUMN pmoId;
ALTER TABLE ParametrizacionModalidad_aud ADD pmoId BIGINT NOT NULL;
ALTER TABLE ParametrizacionTablaAuditable DROP CONSTRAINT PK_ParametrizacionTablaAuditable_ptaId;
ALTER TABLE ParametrizacionTablaAuditable DROP COLUMN ptaId;
ALTER TABLE ParametrizacionTablaAuditable ADD ptaId BIGINT NOT NULL;
ALTER TABLE Periodo_aud DROP COLUMN priId;
ALTER TABLE Periodo_aud ADD priId BIGINT NOT NULL;
ALTER TABLE PeriodoBeneficio_aud DROP COLUMN pbeId;
ALTER TABLE PeriodoBeneficio_aud ADD pbeId BIGINT NOT NULL;
ALTER TABLE PeriodoLiquidacion_aud DROP COLUMN pelId;
ALTER TABLE PeriodoLiquidacion_aud ADD pelId BIGINT NOT NULL;
ALTER TABLE PostulacionFOVIS_aud DROP COLUMN pofId;
ALTER TABLE PostulacionFOVIS_aud ADD pofId BIGINT NOT NULL;
ALTER TABLE PrioridadDestinatario_aud DROP COLUMN prdId;
ALTER TABLE PrioridadDestinatario_aud ADD prdId BIGINT NOT NULL;
ALTER TABLE ProyectoSolucionVivienda_aud DROP COLUMN psvId;
ALTER TABLE ProyectoSolucionVivienda_aud ADD psvId BIGINT NOT NULL;
ALTER TABLE RangoTopeValorSFV_aud DROP COLUMN rtvId;
ALTER TABLE RangoTopeValorSFV_aud ADD rtvId BIGINT NOT NULL;
ALTER TABLE RecursoComplementario_aud DROP COLUMN recId;
ALTER TABLE RecursoComplementario_aud ADD recId BIGINT NOT NULL;
ALTER TABLE RegistroEstadoAporte_aud DROP COLUMN reaId;
ALTER TABLE RegistroEstadoAporte_aud ADD reaId BIGINT NOT NULL;
ALTER TABLE RegistroNovedadFutura_aud DROP COLUMN rnfId;
ALTER TABLE RegistroNovedadFutura_aud ADD rnfId BIGINT NOT NULL;
ALTER TABLE SitioPago_aud DROP COLUMN sipId;
ALTER TABLE SitioPago_aud ADD sipId BIGINT NOT NULL;
ALTER TABLE SolicitudAporte_aud DROP COLUMN soaId;
ALTER TABLE SolicitudAporte_aud ADD soaId BIGINT NOT NULL;
ALTER TABLE SolicitudCorreccionAporte_aud DROP COLUMN scaId;
ALTER TABLE SolicitudCorreccionAporte_aud ADD scaId BIGINT NOT NULL;
ALTER TABLE SolicitudDevolucionAporte_aud DROP COLUMN sdaId;
ALTER TABLE SolicitudDevolucionAporte_aud ADD sdaId BIGINT NOT NULL;
ALTER TABLE SolicitudLiquidacionSubsidio_aud DROP COLUMN slsId;
ALTER TABLE SolicitudLiquidacionSubsidio_aud ADD slsId BIGINT NOT NULL;
ALTER TABLE SolicitudNovedadPila_aud DROP COLUMN spiId;
ALTER TABLE SolicitudNovedadPila_aud ADD spiId BIGINT NOT NULL;
ALTER TABLE SolicitudPostulacion_aud DROP COLUMN spoId;
ALTER TABLE SolicitudPostulacion_aud ADD spoId BIGINT NOT NULL;
ALTER TABLE SolicitudPreventiva_aud DROP COLUMN sprId;
ALTER TABLE SolicitudPreventiva_aud ADD sprId BIGINT NOT NULL;
ALTER TABLE TasasInteresMora_aud DROP COLUMN timId;
ALTER TABLE TasasInteresMora_aud ADD timId BIGINT NOT NULL;
ALTER TABLE TipoInfraestructura_aud DROP COLUMN tifId;
ALTER TABLE TipoInfraestructura_aud ADD tifId BIGINT NOT NULL;
ALTER TABLE TipoTenencia_aud DROP COLUMN tenId;
ALTER TABLE TipoTenencia_aud ADD tenId BIGINT NOT NULL;