/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asopagos.sat.constantes;

/**
 *
 * @author Sergio Reyes
 */
public enum EnumParametros {
    CORREO_NOTIFICACION_SAT("CORREO_NOTIFICACION_SAT"),
    USUARIO_SAT("USUARIO_SAT"),
    PASSWORD_SAT("PASSWORD_SAT"),
    CLIENT_ID_AFIL_PRIM_SAT("CLIENT_ID_AFIL_PRIM_SAT"),
    CLIENT_ID_NO_AFIL_PRIM_SAT("CLIENT_ID_NO_AFIL_PRIM_SAT"),
    CLIENT_ID_DESAFILIACION_SAT("CLIENT_ID_DESAFILIACION_SAT"),
    CLIENT_ID_INICIO_RELACION_LABORAL_SAT("CLIENT_ID_INICIO_RELACION_LABORAL_SAT"),
    CLIENT_ID_TERMINACION_RELACION_LABORAL_SAT("CLIENT_ID_TERMINACION_RELACION_LABORAL_SAT"),
    CLIENT_ID_PERDIDA_CAUSA_GRAVE_SAT("CLIENT_ID_PERDIDA_CAUSA_GRAVE_SAT"),
    CLIENT_ID_ESTADO_PAGO_EMPLEADOR_SAT("CLIENT_ID_ESTADO_PAGO_EMPLEADOR_SAT"),
    URL_TOKEN_SAT("URL_TOKEN_SAT"),
    URL_AFIL_PRIM_SAT("URL_AFIL_PRIM_SAT"),
    URL_AFIL_NO_PRIM_SAT("URL_AFIL_NO_PRIM_SAT"),
    URL_DESAFILIACION_SAT("URL_DESAFILIACION_SAT"),
    URL_INICIO_RELACION_LABORAL_SAT("URL_INICIO_RELACION_LABORAL_SAT"),
    URL_TERMINACION_RELACION_LABORAL_SAT("URL_TERMINACION_RELACION_LABORAL_SAT"),
    URL_PERDIDA_CAUSA_GRAVE_SAT("URL_PERDIDA_CAUSA_GRAVE_SAT"),
    URL_ESTADO_PAGO_EMPLEADOR_SAT("URL_ESTADO_PAGO_EMPLEADOR_SAT"),
    USUARIO_SAT_WS_F2("USUARIO_SAT_WS_F2"),
    PASSWORD_SAT_WS_F2("PASSWORD_SAT_WS_F2"),
    CLIENT_ID_NO_AFIL_PRIM_SAT_WS_F2("CLIENT_ID_NO_AFIL_PRIM_SAT_WS_F2"),
    CLIENTID_SAT_RES_AFI_PRIMER_VEZ_WS_F2("CLIENTID_SAT_RES_AFI_PRIMER_VEZ_WS_F2"),
    CLIENTID_SAT_RES_AFI_PRIMER_VEZ("CLIENTID_SAT_RES_AFI_PRIMER_VEZ"),
    URL_TOKEN_SAT_WS_F2("URL_TOKEN_SAT_WS_F2");
 
    ;
    
    private String nombre;
    
    private EnumParametros(String nombre){
        this.nombre = nombre;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
}
