--- Tabla de control para las planillas N
if not exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'RegistroDetalladoPlanillaN' and TABLE_SCHEMA = 'staging')
begin
CREATE TABLE [staging].[RegistroDetalladoPlanillaN](
	[redId] [bigint] NOT NULL,
	[redRegistroGeneral] [bigint] NOT NULL,
	[redTipoIdentificacionCotizante] [varchar](20) NOT NULL,
	[redNumeroIdentificacionCotizante] [varchar](16) NULL,
	[redTipoCotizante] [smallint] NULL,
	[redCodDepartamento] [varchar](2) NULL,
	[redCodMunicipio] [varchar](6) NULL,
	[redPrimerApellido] [varchar](50) NULL,
	[redSegundoApellido] [varchar](50) NULL,
	[redPrimerNombre] [varchar](50) NULL,
	[redSegundoNombre] [varchar](50) NULL,
	[redNovIngreso] [varchar](1) NULL,
	[redNovRetiro] [varchar](1) NULL,
	[redNovVSP] [varchar](1) NULL,
	[redNovVST] [varchar](1) NULL,
	[redNovSLN] [varchar](1) NULL,
	[redNovIGE] [varchar](1) NULL,
	[redNovLMA] [varchar](1) NULL,
	[redNovVACLR] [varchar](1) NULL,
	[redNovSUS] [varchar](1) NULL,
	[redDiasIRL] [varchar](2) NULL,
	[redDiasCotizados] [smallint] NULL,
	[redSalarioBasico] [numeric](19, 5) NULL,
	[redValorIBC] [numeric](19, 5) NULL,
	[redTarifa] [numeric](5, 5) NULL,
	[redAporteObligatorio] [numeric](19, 5) NULL,
	[redCorrecciones] [varchar](1) NULL,
	[redSalarioIntegral] [varchar](1) NULL,
	[redFechaIngreso] [date] NULL,
	[redFechaRetiro] [date] NULL,
	[redFechaInicioVSP] [date] NULL,
	[redFechaInicioSLN] [date] NULL,
	[redFechaFinSLN] [date] NULL,
	[redFechaInicioIGE] [date] NULL,
	[redFechaFinIGE] [date] NULL,
	[redFechaInicioLMA] [date] NULL,
	[redFechaFinLMA] [date] NULL,
	[redFechaInicioVACLR] [date] NULL,
	[redFechaFinVACLR] [date] NULL,
	[redFechaInicioVCT] [date] NULL,
	[redFechaFinVCT] [date] NULL,
	[redFechaInicioIRL] [date] NULL,
	[redFechaFinIRL] [date] NULL,
	[redFechaInicioSuspension] [date] NULL,
	[redFechaFinSuspension] [date] NULL,
	[redHorasLaboradas] [smallint] NULL,
	[redRegistroControl] [bigint] NULL,
	[redOUTMarcaValRegistroAporte] [varchar](50) NULL,
	[redOUTEstadoRegistroAporte] [varchar](60) NULL,
	[redOUTAnalisisIntegral] [bit] NULL,
	[redOUTFechaProcesamientoValidRegAporte] [datetime] NULL,
	[redOUTEstadoValidacionV0] [varchar](30) NULL,
	[redOUTEstadoValidacionV1] [varchar](30) NULL,
	[redOUTEstadoValidacionV2] [varchar](30) NULL,
	[redOUTEstadoValidacionV3] [varchar](30) NULL,
	[redOUTClaseTrabajador] [varchar](50) NULL,
	[redOUTPorcentajePagoAportes] [numeric](5, 5) NULL,
	[redOUTEstadoSolicitante] [varchar](50) NULL,
	[redOUTEsTrabajadorReintegrable] [bit] NULL,
	[redOUTFechaIngresoCotizante] [date] NULL,
	[redOUTFechaUltimaNovedad] [date] NULL,
	[redOUTFechaFallecimiento] [date] NULL,
	[redUsuarioAprobadorAporte] [varchar](50) NOT NULL,
	[redNumeroOperacionAprobacion] [varchar](12) NULL,
	[redEstadoEvaluacion] [varchar](22) NOT NULL,
	[redEstadoRegistroCorreccion] [varchar](40) NULL,
	[redOUTCodSucursal] [varchar](10) NULL,
	[redOUTNomSucursal] [varchar](100) NULL,
	[redOUTDiasCotizadosPlanillas] [smallint] NULL,
	[redOUTDiasCotizadosBD] [smallint] NULL,
	[redOUTDiasCotizadosNovedades] [smallint] NULL,
	[redOUTTipoAfiliado] [varchar](50) NULL,
	[redOUTRegistrado] [bit] NULL,
	[redOUTValorMoraCotizante] [numeric](19, 5) NULL,
	[redOUTAporteObligatorioMod] [numeric](19, 5) NULL,
	[redOUTDiasCotizadosMod] [smallint] NULL,
	[redOUTRegistradoAporte] [bit] NULL,
	[redOUTRegistradoNovedad] [bit] NULL,
	[redOUTTipoNovedadSituacionPrimaria] [varchar](15) NULL,
	[redOUTFechaInicioNovedadSituacionPrimaria] [date] NULL,
	[redOUTFechaFinNovedadSituacionPrimaria] [date] NULL,
	[redOUTRegDetOriginal] [bigint] NULL,
	[redOUTEstadoRegistroRelacionAporte] [varchar](50) NULL,
	[redOUTEstadoEvaluacionAporte] [varchar](22) NULL,
	[redOUTFechaRetiroCotizante] [date] NULL,
	[redOUTValorIBCMod] [numeric](19, 5) NULL,
	[redOUTValorMoraCotizanteMod] [numeric](19, 5) NULL,
	[redFechaInicioVST] [date] NULL,
	[redFechaFinVST] [date] NULL,
	[redOUTDiasCotizadosNovedadesBD] [smallint] NULL,
	[redOUTGrupoFamiliarReintegrable] [bit] NULL,
	[redIdRegistro2pila] [bigint] NULL,
	[redOUTEnviadoAFiscalizacionInd] [bit] NULL,
	[redOUTMotivoFiscalizacionInd] [varchar](30) NULL,
	[redOUTRegistroActual] [bit] NULL,
	[redOUTRegInicial] [bigint] NULL,
	[redOUTGrupoAC] [int] NULL,
	[redOUTTarifaMod] [numeric](5, 5) NULL,
	[redDateTimeInsert] [datetime] NULL,
	[redDateTimeUpdate] [datetime] NULL,
	[redOUTPeriodicidad] [varchar](11) NULL,
	[redUsuarioAccion] [varchar](100) NULL,
	[redFechaAccion] [datetime] NULL,
	[redRegistroDetalladoAnterior] [bigint] NULL)

end