--liquibase formatted sql

--changeSET Heinsohn:01
--comment: Inserción de Novedad
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_TIPO_NUMERO_DOCUMENTO','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarPersonaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_RAZON_SOCIAL_NOMBRE','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarPersonaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_NATURALEZA_JURIDICA','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpresaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpresaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_ACTIVIDAD_ECONOMICA_PRINCIPAL_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpresaNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIOS_OTROS_DATOS_IDENTIFICACION_EMPLEADOR','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarEmpresaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_PRESENCIAL','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DATOS_OFICINA_PRINCIPAL_WEB','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_PRESENCIAL','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DATOS_ENVIO_CORRESPONDENCIA_WEB','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTUALIZACION_DIRECCION_NOTIFICACION_JUDICIAL_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarRepresentantesNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIOS_REPRESENTANTE_LEGAL_SUPLENTE_O_SOCIOS_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarRepresentantesNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_MEDIO_PAGO_EMPLEADOR_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_MEDIO_PAGO_EMPLEADOR_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_CODIGO_NOMBRE_SUCURSAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_CODIGO_NOMBRE_SUCURSAL_WEB','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','SUCURSAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_DATOS_SUCURSAL_PRESENCIAL','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_DATOS_SUCURSAL_WEB','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizarUbicacionNovedad','SUCURSAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_ACTIVIDAD_ECONOMICA_SUCURSAL_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_MEDIO_PAGO_SUCURSAL_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_MEDIO_PAGO_SUCURSAL_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTIVAR_INACTIVAR_CODIGO_SUCURSAL_DEBE_COINCIDIR_CON_PILA','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('AGREGAR_SUCURSAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_SUCURSAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarSucursalNovedad','SUCURSAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIOS_ROLES_CONTACTO_PRESENCIAL','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizaRolesContactoNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIOS_ROLES_CONTACTO_WEB','FRONT','com.asopagos.novedades.convertidores.empleador.ActualizaRolesContactoNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('CAMBIO_RESPONSABLE_CONTACTOS_CFF','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarResponsablesCajaNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTIVAR_BENEFICIOS_LEY_1429_2010_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_BENEFICIOS_LEY_1429_2010_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_BENEFICIOS_LEY_1429_2010_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('ACTIVAR_BENEFICIOS_LEY_590_2000_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_BENEFICIOS_LEY_590_2000_PRESENCIAL','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_BENEFICIOS_LEY_590_2000_WEB','BACK','com.asopagos.novedades.convertidores.empleador.ActualizarEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_WEB');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('TRASLADO_TRABAJADORES_ENTRE_SUCURSALES','BACK','com.asopagos.novedades.convertidores.empleador.TrasladarTrabajadoresNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('SUSTITUCION_PATRONAL','BACK','com.asopagos.novedades.convertidores.empleador.TrasladarTrabajadoresNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('DESAFILIACION','BACK','com.asopagos.novedades.convertidores.empleador.SustituirEmpleadorNovedad','GENERAL','NOVEDADES_EMPRESAS_PRESENCIAL');
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_AUTOMATICAMENTE_BENEFICIO_LEY_1429_2010','SISTEMA_AUTOMATICO','com.asopagos.novedades.convertidores.empleador.ActualizarInactivarBeneficiosLey1429','AUTOMATICA',NULL)
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_AUTOMATICAMENTE_BENEFICIOS_LEY_590_2000','SISTEMA_AUTOMATICO','com.asopagos.novedades.convertidores.empleador.ActualizarInactivarBeneficiosLey590','AUTOMATICA',NULL)
INSERT Novedad (novTipoTransaccion,novPuntoResolucion,novRutaCualificada,novTipoNovedad,novProceso) VALUES ('INACTIVAR_AUTOMATICAMENTE_CUENTA_WEB_EMPLEADOR','SISTEMA_AUTOMATICO','com.asopagos.novedades.convertidores.empleador.ActualizarInactivarCuentaWeb','AUTOMATICA',NULL)
