--liquibase formatted sql

--changeset flopez:01
--comment: Se elimina registro de la tabla Parametro
DELETE FROM Parametro WHERE prmNombre = '112_ABRIR_LINK_TIMER';

--changeset jocorrea:02
--comment: Se eliminan registros de las tablas
DELETE FROM ParametrizacionNovedad WHERE novTipoTransaccion = 'REPORTE_LICENCIA_REMUNERADA_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'REPORTE_LICENCIA_REMUNERADA_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_REPORTE_LICENCIA_REMUNERADA_TRABAJADOR_DEPENDIENTE';
DELETE FROM ParametrizacionNovedad WHERE novTipoTransaccion = 'INCAPACIDAD_POR_ACCIDENTE_TRABAJO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'INCAPACIDAD_POR_ACCIDENTE_TRABAJO';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_INCAPACIDAD_POR_ACCIDENTE_TRABAJO';
DELETE FROM ParametrizacionNovedad WHERE novTipoTransaccion = 'LICENCIA_NO_REMUNERADA_SUSPENSION_CONTRATO_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'LICENCIA_NO_REMUNERADA_SUSPENSION_CONTRATO_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_LICENCIA_NO_REMUNERADA_SUSPENSION_CONTRATO_TRABAJADOR_DEPENDIENTE'
DELETE FROM ParametrizacionNovedad WHERE novTipoTransaccion = 'VARIACION_SALARIO_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'VARIACION_SALARIO_TRABAJADOR_DEPENDIENTE';
DELETE FROM ValidacionProceso WHERE vapBloque = 'NOVEDAD_VARIACION_SALARIO_TRABAJADOR_DEPENDIENTE';
